= Getting Started with Testing

By default, every Jmix project already contains the directory structure for automated tests and two test classes in the `src/test/java/<base-package>/user` directory:

. `UserTest.java` - an integration test for the `User` entity.
. `UserUiTest.java` - a UI integration test for the user management views.

The `UserTest` saves a `User` entity through the Jmix xref:data-access:data-manager.adoc[DataManager] API.
Then the test verifies that when loading the user by its username, the user is found and matches the originally saved user.

[source, java]
.UserTest.java
----
include::example$testing-ex1/src/test/java/com/company/demo/user/UserTest.java[]
----

<1> The `@SpringBootTest` annotation indicates that the Spring context is started during the test execution.
<2> `AuthenticatedAsAdmin` allows the test to interact with the system and the database as the `admin` user.
<3> Dependencies are injected into the test code using the `@Autowired` Spring dependency injection annotation.
<4> Each test case is marked with the JUnit's `@Test` annotation.
<5> To perform verifications, the assertion library https://assertj.github.io/doc/[AssertJ^] is automatically available in Jmix projects.
<6> Operations like database cleanup are performed in tear down methods annotated with JUnit's `@AfterEach` annotation.

The test itself is a regular Spring Boot integration test. It starts the complete Spring context and interacts with a real database.

NOTE: By default, the tests use the same database as the application when running locally.

Jmix Studio uses IntelliJ IDEA's capabilities to execute tests. When you open the `UserTest.java` class in Jmix Studio, you can run the test cases by clicking the play button on the line of the test class. The IDE will show the result of the test execution and whether the test was successful.

See more information on how to run tests in the https://www.jetbrains.com/help/idea/performing-tests.html[IntelliJ documentation^].

The following sections will explain different types of tests in more detail.