= UI Integration Tests

Jmix allows you to write tests for the UI layer. In these tests, you can open views, load data, verify the contents of UI components, make modifications, and simulate user actions such as button clicks.

TIP: Use the *New → Advanced → UI Integration Test* action in the *Jmix* tool window to quickly create a UI integration test using Studio.

Jmix UI tests start the complete Spring context and can interact with the database like the xref:integration-tests.adoc[integration tests] of the business logic. They are close to the browser-based end-to-end tests in the sense that they can check a wide range of application functionality, but at the same time they are easy to set up and are executed much faster than browser-based tests.

Every new Jmix project includes an example of a UI integration test: the `UserUiTest` class that verifies the user management views. Let's take a look at the configuration and logic of the UI tests using this example.

To execute UI tests, your project should contain the dependency on the `jmix-flowui-test-assist` module:

.build.gradle
[source,java,indent=0]
----
include::example$/testing-ex1/build.gradle[tag=dependency]
----

The example test class is shown below.

.UserUiTest.java
[source,java,indent=0]
----
include::example$/testing-ex1/src/test/java/com/company/demo/user/UserUiTest.java[]
----
<1> The `@UiTest` annotation defines a JUnit extension to start Vaadin, configure application views and set up authentication.
<2> The `@SpringBootTest` annotation should declare the application and the `jmix-flowui-test-assist` module configurations.
<3> You can inject any Spring beans using the `@Autowired` annotation.
<4> The test case method.
<5> `UiTestUtils.getCurrentView()` method returns the view currently opened by navigation.
<6> The `findComponent()` method returns a UI component by its id.
<7> The method executed after each test case can be used for test data cleanup.