= Quartz

This add-on allows you to manage https://www.quartz-scheduler.org/[Quartz^] jobs via the user interface:

* Create new Quartz jobs from the existing implementation of `org.quartz.Job` interface.
* Pause and resume job execution.
* Trigger immediate execution of inactive jobs.
* Edit job triggers and parameters.
* Delete jobs.

The Quartz management user interface can be accessed through the *Quartz -> Quartz jobs* main menu item.

The add-on also provides Liquibase changelogs for automatic creation of the database schema required by Quartz.

[[installation]]
== Installation

For automatic installation through Jmix Marketplace, follow instructions in the xref:ROOT:add-ons.adoc#installation[Add-ons] section.

For manual installation, add the following dependencies to your `build.gradle`:

[source,groovy,indent=0]
----
include::example$quartz-ex1/build.gradle[tags=dependencies]
----

[NOTE]
====
If the URL of your main database is set as a variable that replaces the whole URL (for example, `main.datasource.url=$\{DB_URL\}`),
you may need to explicitly set the proper driver delegate class with the `spring.quartz.properties.org.quartz.jobStore.driverDelegateClass` application property.

Value depends on your database:

* *PostgreSQL*: `org.quartz.impl.jdbcjobstore.PostgreSQLDelegate`
* *Oracle*: `org.quartz.impl.jdbcjobstore.oracle.OracleDelegate`
* *MS SQL*: `org.quartz.impl.jdbcjobstore.MSSQLDelegate`
* Other databases: skip this step, the default value will be used.

If the database prefix is specified explicitly (for example, `main.datasource.url=jdbc:postgresql://$\{DB_HOST\}/$\{DB_NAME\}`),
or variables are not used at all, the driver delegate class is resolved automatically and this step can be skipped.
====

include::ROOT:single-menu-note.adoc[]

[[usage]]
== Usage

To create and schedule a job for execution, do the following:

. Create a class implementing the `org.quartz.Job` interface. Its `execute()` method is invoked by the scheduler. For example:
+
[source,java,indent=0]
----
include::example$/quartz-ex1/src/main/java/com/company/demo/quartz/SampleJob.java[]
----
+
In the job class, you can inject Spring beans with `@Autowired`.

. Run the application, open *Quartz -> Quartz jobs* view and click *Create*.
+
--
** Enter an arbitrary unique name in the *Name* field and select your job class in the *Class* field.
+
The *Group* field is optional but can be used to group jobs in the UI.

** Create at least one trigger for the job on the *Triggers* tab. You can select either *Cron expression* or *Simple* schedule type. In the former case, enter a http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html[Cron expression^] like `0/5 * * ? * * *` (every 5 seconds). In the latter case, enter a repeat interval in milliseconds.
--
+
After you save the trigger and the job, it is immediately scheduled for execution according to the trigger settings.
+
To edit the job settings, first pause it by selecting and clicking *Pause*. After saving changes, you can resume the scheduling by clicking *Resume*.
+
You can also execute any registered job immediately by clicking *Execute now*, even if the job has no triggers. This is useful for testing.

[[configure-jobs-programmatically]]
=== Configuring Jobs and Triggers Programmatically

Instead of creating Quartz jobs and triggers in the *Quartz jobs* view, you can register them as Spring beans. This approach is useful when the schedule must be defined together with the application code.

Declare these beans in a Spring configuration class located in a package scanned by the application.

[source,java,indent=0]
----
include::example$/quartz-ex1/src/main/java/com/company/demo/config/QuartzConfiguration.java[tags=quartz-configuration]
----
<1> Job implementation class.
<2> Job identifier.
<3> Associates the trigger with the job.
<4> Trigger identifier. Specify it explicitly to avoid creating duplicate triggers after redeployment.
<5> Cron schedule.

`withIdentity()` defines the Quartz identifier of the job or trigger. Always specify an identifier for every trigger created in code.

If a trigger does not have an explicit identifier, Quartz generates a random one. When the application uses persistent Quartz tables, this can create a new trigger on each redeployment and result in multiple triggers executing the same job according to the same schedule.

[[authentication]]
=== Authentication in Jobs

The code executed by the scheduler is not authenticated, so it is not associated with any user.

If you invoke operations that require authentication, for example working with data through `DataManager`, use xref:security:authentication.adoc#system[SystemAuthenticator] or `@Authenticated` annotation:

[source,java,indent=0]
----
include::example$/quartz-ex1/src/main/java/com/company/demo/quartz/SampleAuthenticatedJob.java[tags=auth-job]
----

TIP: You can also use `UnconstrainedDataManager` to work with data in unauthenticated contexts.

[[job-parameters]]
=== Job Parameters

The *Job editor* view allows you to set parameters for the job instance on the *Job data parameters* tab. You can use the parameters in the job class as follows:

[source,java,indent=0]
----
include::example$/quartz-ex1/src/main/java/com/company/demo/quartz/SampleParameterizedJob.java[tags=job-params]
----

[[track-job-execution]]
=== Tracking Job Execution

If you want to track execution of jobs, create a bean implementing the `JobListener` interface or extending `JobListenerSupport`, as follows:

[source,java,indent=0]
----
include::example$/quartz-ex1/src/main/java/com/company/demo/quartz/JobExecutionListener.java[]
----
<1> Invoked by Spring after the bean is instantiated.
<2> Invoked by Quartz scheduler after a job is executed.

In the `jobWasExecuted()` method, you can store information about the executed job in the log or in the database.
