= Конфигурация

[[application-properties]]
== Свойства приложения

[[jmix.authserver.post-logout-url-redirect-parameter-name]]
=== jmix.authserver.post-logout-url-redirect-parameter-name

Имя URL-параметра в запросе `/logout`, указывающего URL для перенаправления пользователя после успешного завершения сеанса (выхода из системы).

Значение по умолчанию: не установлено.

[[jmix.authserver.use-default-configuration]]
=== jmix.authserver.use-default-configuration

Определяет, должна ли использоваться стандартная автоконфигурация, настраивающая сервер авторизации и ресурсный сервер. Если вам необходимо полностью переопределить стандартную конфигурацию, установите это свойство в `false` и определите собственные классы конфигурации.

Значение по умолчанию: `true`.

[[jmix.authserver.use-in-memory-authorization-service]]
=== jmix.authserver.use-in-memory-authorization-service

Если установлено в `true`, использует in-memory хранилище вместо хранения токенов в базе данных.

Значение по умолчанию: `false`.

[[jmix.authserver.use-referer-post-logout]]
=== jmix.authserver.use-referer-post-logout

Если установлено в `true`, значение заголовка `referer` используется как URL для перенаправления после выхода из системы.

Имеет более низкий приоритет, чем URL, установленный свойством <<jmix.authserver.post-logout-url-redirect-parameter-name,jmix.authserver.post-logout-url-redirect-parameter-name>>.

Значение по умолчанию: `false`.