= Protecting Resources

The {oauth-specification-page}#section-1.1[resource server^] security is defined in the auto-configuration of the Authorization Server add-on. This configuration provides extension points that can be used to define any URL pattern as protected. See the xref:security:custom-endpoints.adoc#token-based-authentication[Token Based Authentication] section for details on how to configure protected resources.

[[sending-access-token]]
== Sending Access Token

After the above configuration is defined, all requests to `pass:[/greeting/**]` endpoints will need an access token in the `Authorization` header. The header value must contain the word `Bearer` followed by the access token value. For example:

[source]
----
GET /greeting/hello HTTP/1.1
Host: server.example.com
Authorization: Bearer <ACCESS_TOKEN>
----

[[protecting-rest-api-endpoints]]
== Protecting Generic REST API Endpoints

When you simply add the xref:rest:index.adoc[REST API] add-on to your application, REST endpoints will not be protected by default.

To configure token-based authentication you need to define the following application property (see its description xref:security:custom-endpoints.adoc#application-properties[here]):

[source,properties]
----
include::example$/authserver-ex1/src/main/resources/application.properties[tags=rest-authenticated-url-patterns]
----

To access REST endpoints, you need to obtain an access token and pass it in the `Authorization` header of the HTTP request. The header value must contain the word `Bearer` followed by the access token value. For example:

[source]
----
GET /rest/entities/User HTTP/1.1
Host: server.example.com
Authorization: Bearer <ACCESS_TOKEN>
----