= Защита ресурсов

Безопасность {oauth-specification-page}#section-1.1[ресурсного сервера^] определяется в автоконфигурации дополнения Authorization Server. Эта конфигурация предоставляет точки расширения, которые могут быть использованы для определения любого URL-шаблона как защищенного. Подробности о том, как настроить защищенные ресурсы, смотрите в разделе xref:security:custom-endpoints.adoc#token-based-authentication[Аутентификация на основе токенов].

[[sendiong-access-token]]
== Отправка Access Token

После определения вышеуказанной конфигурации все запросы к эндпойнтам `pass:[/greeting/**]` будут требовать access token в заголовке `Authorization`. Значение заголовка должно содержать слово `Bearer`, за которым следует значение access token. Например:

[source]
----
GET /greeting/hello HTTP/1.1
Host: server.example.com
Authorization: Bearer <ACCESS_TOKEN>
----

[[protecting-rest-api-endpoints]]
== Защита общих REST API эндпойнтов

Когда вы просто добавляете дополнение xref:rest:index.adoc[REST API] в ваше приложение, REST эндпойнты по умолчанию не будут защищены.

Для настройки аутентификации на основе токенов вам необходимо определить следующее свойство приложения (смотрите его описание xref:security:custom-endpoints.adoc#application-properties[здесь]):

[source,properties]
----
include::example$/authserver-ex1/src/main/resources/application.properties[tags=rest-authenticated-url-patterns]
----

Для доступа к REST эндпойнтам вам необходимо получить access token и передать его в заголовке `Authorization` HTTP-запроса. Значение заголовка должно содержать слово `Bearer`, за которым следует значение access token. Например:

[source]
----
GET /rest/entities/User HTTP/1.1
Host: server.example.com
Authorization: Bearer <ACCESS_TOKEN>
----