= Bulk Editor

Дополнение Bulk Editor (массовый редактор) предоставляет пользователям приложений возможность изменять значения атрибутов для нескольких экземпляров сущности одновременно.

Дополнение содержит xref:flow-ui:actions.adoc[действие], которое открывает диалоговое окно, в котором пользователь может ввести значения атрибутов. После этого действие обновляет выбранные сущности в хранилище данных и в пользовательском интерфейсе.

[[installation]]
== Установка

Для автоматической установки через маркетплейс Jmix следуйте инструкциям в разделе xref:ROOT:add-ons.adoc#installation[Дополнения].

Для ручной установки добавьте следующую зависимость в `build.gradle` проекта:

[source,groovy,indent=0]
----
implementation 'io.jmix.bulkeditor:jmix-bulkeditor-starter'
----

[[usage]]
== Использование

Тип действия, предоставляемого дополнением - `bulked_edit`. Это xref:flow-ui:actions/list-actions.adoc[действие компонентов списка], поэтому его можно добавить в xref:flow-ui:vc/components/dataGrid.adoc[] и xref:flow-ui:vc/components/treeDataGrid.adoc[].

Пример использования:

[source,xml]
----
<hbox id="buttonsPanel" classNames="buttons-panel">
    <!-- ... -->
    <button action="booksDataGrid.bulkEdit"/>
</hbox>
<dataGrid id="booksDataGrid" dataContainer="booksDc" columnReorderingAllowed="true"
            selectionMode="MULTI">
    <actions>
        <!-- ... -->
        <action id="bulkEdit" type="bulked_edit"/>
    </actions>
----

Чтобы иметь возможность выбирать несколько сущностей, установите `selectionMode="MULTI"` для `dataGrid`.

[[parameterization]]
=== Параметризация

Действие `bulked_edit` предоставляет дополнительные свойства, которые можно настраивать либо в XML, либо программно с использованием методов-сеттеров в Java.

В XML настройте эти свойства с помощью вложенного элемента `<properties>`. Каждый элемент `<property>` соответствует методу-сеттеру в классе действия:

[source,xml]
----
<action id="bulkEditAction" type="bulked_edit">
    <properties>
        <property name="includeProperties" value="username, email"/>
    </properties>
</action>
----

==== Доступные свойства

* `includeProperties` - определяет атрибуты сущности для отображения в окне массового редактора. Если задано, все остальные атрибуты исключаются из редактирования.

* `exclude` - определяет регулярное выражение для явного исключения конкретных полей из списка атрибутов, доступных для редактирования.

* `useConfirmDialog` - управляет показом диалога подтверждения пользователям перед сохранением изменений. Значение по умолчанию: `true`.