= Bulk Editor

This add-on is designed to allow users to change attribute values for multiple entity instances at once.

It provides an xref:flow-ui:actions.adoc[action] that opens a dialog where the user can enter attribute values. After that, the action updates the selected entities in the data store and in the UI.

[[installation]]
== Installation

For automatic installation through Jmix Marketplace, follow instructions in the xref:ROOT:add-ons.adoc#installation[Add-ons] section.

For manual installation, add the following dependency to your `build.gradle`:

[source,groovy,indent=0]
----
implementation 'io.jmix.bulkeditor:jmix-bulkeditor-starter'
----

[[usage]]
== Usage

The type of action provided by the add-on is `bulked_edit`. It is a xref:flow-ui:actions/list-actions.adoc[list component action], so it can be added to xref:flow-ui:vc/components/dataGrid.adoc[] and xref:flow-ui:vc/components/treeDataGrid.adoc[].

Usage example:

[source,xml]
----
<hbox id="buttonsPanel" classNames="buttons-panel">
    <!-- ... -->
    <button action="booksDataGrid.bulkEdit"/>
</hbox>
<dataGrid id="booksDataGrid" dataContainer="booksDc" columnReorderingAllowed="true"
            selectionMode="MULTI">
    <actions>
        <!-- ... -->
        <action id="bulkEdit" type="bulked_edit"/>
    </actions>
----

To be able to select multiple entities, set `selectionMode="MULTI"` for `dataGrid`.

[[parameterization]]
=== Parameterization

The `bulked_edit` action provides additional properties that can be configured either in XML or programmatically using setter methods in Java.

In XML, configure these properties using the nested `<properties>` element. Each `<property>` element corresponds to a setter method in the action class:

[source,xml]
----
<action id="bulkEditAction" type="bulked_edit">
    <properties>
        <property name="includeProperties" value="username, email"/>
    </properties>
</action>
----

==== Available Properties

* `includeProperties` - specifies the entity attributes to display in the bulk editor window. When set, all other attributes are excluded from editing.

* `exclude` - defines a regular expression to explicitly exclude specific fields from the list of attributes available for editing.

* `useConfirmDialog` - controls whether to show a confirmation dialog to users before saving changes. Default value is `true`.