= Data Stores

A data store represents a database or any other source of data in your application.

Jmix core subsystem provides `JpaDataStore` which stores xref:entities.adoc#jpa[JPA entities] in a relational database. This is the main persistence mechanism in Jmix applications, and when we mention a data store in this manual, we mean the JPA data store if not explicitly stated otherwise.

The xref:rest-ds:index.adoc[] add-on provides `RestDataStore` which works with xref:entities.adoc#jpa[DTO entities] mapped to the xref:rest:index.adoc[] exposed by a remote Jmix application. The REST data store has some limitations compared to the JPA data store.

[[supported-databases]]
== Supported Databases

The following databases are supported in Jmix out-of-the-box:

* HSQLDB (Java in-memory database)
* PostgreSQL
* MySQL 5.1+
* MariaDB
* Microsoft SQL Server 2008+
* Oracle
* H2 (experimental support)

The xref:studio:data-stores.adoc[data store editor] in Studio automatically configures connection properties and adds an appropriate JDBC driver to the list of dependencies in `build.gradle`.

If you need to connect a relational database not supported in Jmix out-of-the-box, follow the instructions in the xref:studio:data-stores.adoc#unsupported-database[Studio: Connecting to Unsupported Databases] section.

A non-relational database can be used by creating a <<custom, custom data store>> or directly as described in the xref:mongodb-integration-guide:index.adoc[] guide.

[[main]]
== Main Store

When you create a new Jmix project in Studio, it has a single data store called _main_ that connects to a relational database. The connection parameters are specified in the following application properties:

[source,properties]
----
include::example$/data-model-ex1/src/main/resources/application.properties[tags=main-data-store]
----

TIP: Use Studio xref:studio:data-stores.adoc[data store management features] to define database connection properties for a data store.

The main application class contains a corresponding JDBC `DataSource` bean declaration:

[source,java,indent=0]
----
include::example$/data-model-ex1/src/main/java/com/company/demo/DataModelEx1Application.java[tags=main-data-source]
----

All JPA entities by default are associated with the main data store.

[[additional]]
== Additional Stores

In order to work with multiple databases, you need additional data stores.

TIP: Use Studio xref:studio:data-stores.adoc[data store management features] to define additional data stores.

Each additional store has a unique name, which is specified in the comma-separated list of the `jmix.core.additional-stores` application property. Parameters of the database connection have the store name as a prefix. In the examples below, the `locations` additional store is configured:

[source,properties]
----
include::example$/data-model-ex1/src/main/resources/application.properties[tags=add-data-store]
----

For each additional store, Studio creates a Spring configuration class and defines the JDBC `DataSource` and other related beans in it:

[source,java,indent=0]
----
include::example$/data-model-ex1/src/main/java/com/company/demo/LocationsStoreConfiguration.java[tags=add-data-source]
----

To associate an entity with an additional data store, use the `@Store` annotation on the entity class:

[source,java,indent=0]
----
include::example$/data-model-ex1/src/main/java/com/company/demo/entity/Country.java[tags=store-ann]
----

TIP: Studio adds `@Store` annotation when you select an additional data store for the entity in the entity designer.

In the example above, the `Country` entity will be stored in the database connected as the `locations` data store.

[[custom]]
== Custom Data Store

A custom data store may help you to work with some DTO entities in the same way as with JPA entities - by using `DataManager`. If your DTO entity is associated with a custom store, `DataManager` will delegate its CRUD operations to your data store and use it when resolving references to your DTOs from other entities.

Let's consider the process of creating a custom data store. Imagine a transient `Metric` entity and an in-memory store for it.

. Create a class that implements the `DataStore` interface. The class must be a Spring prototype bean. The example below contains a primitive implementation that is capable of storing entities of different types in memory.
+
[source,java,indent=0]
----
include::example$/data-model-ex1/src/main/java/com/company/demo/store/InMemoryStore.java[tags=custom-store-1;custom-store-2]
----

. Create a class that implements the `StoreDescriptor` interface. It must be a Spring singleton bean, and its `getBeanName()` method must return the name of the data store implementation bean created in the previous step:
+
[source,java,indent=0]
----
include::example$/data-model-ex1/src/main/java/com/company/demo/store/InMemoryStoreDescriptor.java[tags=custom-store]
----

. Add the data store name (`inmem` in this case) to the `jmix.core.additionalStores` property:
+
[source,properties]
----
include::example$/data-model-ex1/src/main/resources/application.properties[tags=custom-data-store-1]
----

. Set the `StoreDescriptor` bean name in the `jmix.core.store-descriptor-<store_name>` property:
+
[source,properties]
----
include::example$/data-model-ex1/src/main/resources/application.properties[tags=custom-data-store-2]
----

. Add `@Store` annotation to the entity:
+
[source,java,indent=0]
----
include::example$/data-model-ex1/src/main/java/com/company/demo/entity/Metric.java[tags=custom-store]
----
<1> The `@Store` annotation specifies a custom data store.
<2> See xref:data-model:entities.adoc#jmix-entity[@JmixEntity] description for more details.

. Now you can save and load the entity using `DataManager` and it will delegate the CRUD operations to your custom data store:
+
[source,java,indent=0]
----
include::example$/data-model-ex1/src/test/java/com/company/demo/EntitiesTest.java[tags=custom-store]
----
+
Also, if another entity has a reference to `Metric`, the `Metric` instance will be loaded automatically when accessing the reference attribute.
