= Enumerations

An enumeration is a set of constants that can be used as values of an xref:entities.adoc[entity] attribute.

In Jmix, an enumeration is a Java enum implementing the `EnumClass` interface and having an `id` field of `Integer` or `String` type. This field is stored in the database instead of `ordinal()` or `name()` of the enum, which has the following advantages:

* You can rename and reorder enum constants, and as long as you keep the identifiers, your data model will be compatible with the database content.

* Even if the database contains a value that does not correspond to any enum constant (it happens if an old and a new version of an application work with the same database), the entity still can be loaded with the enum attribute containing null. With the standard JPA approach, loading such an instance is impossible.

TIP: Use xref:studio:entity-designer.adoc#enumerations[Studio enumeration designer] to create Jmix enumerations.

Below is an example of Jmix enumeration class:

.CustomerGrade.java
[source,java,indent=0]
----
include::example$/data-model-ex1/src/main/java/com/company/demo/entity/CustomerGrade.java[tags=enum]
----

<1> The `EnumClass` interface is parameterized by the Id type (`String` in this case).
<2> Each enum constant is defined with a corresponding Id value passed to the constructor.
<3> `getId()` and `fromId()` methods convert an enum constant to its Id and back.

The enum should be used in an entity as follows:

.Customer.java
[source,java,indent=0]
----
include::example$/data-model-ex1/src/main/java/com/company/demo/entity/Customer.java[tags=enum]
----

<1> The persistent field has the type of the enum's identifier (`Integer` or `String`)
<2> Getter and setter convert from Id type to the enum type and back.

TIP: When creating an attribute in Studio entity designer, select *ENUM* in the *Attribute type* field and find your enum in the *Type* field.