= Custom Endpoints

Requests to the Jmix application are protected by the Spring Security framework. This section explains how you can configure access to custom API endpoints.

[[general-information]]
== General Information

To gain a deep understanding of how endpoint security works, read the relevant sections of the Spring Security documentation:

* {spring-security-doc}/servlet/architecture.html[Spring Security Architecture^]
* {spring-security-doc}/servlet/authorization/authorize-http-requests.html[Authorize HttpServletRequests^]

Spring Security uses special {spring-security-doc}/servlet/architecture.html#servlet-securityfilterchain[SecurityFilterChain^] beans to determine which URLs should be protected. Each `SecurityFilterChain` bean is configured by the {spring-security-doc}/servlet/configuration/java.html#jc-httpsecurity[HttpSecurity^] builder. An application can have multiple `SecurityFilterChain` beans declared. In this case, it is extremely important to indicate their correct order. See the {spring-security-doc}/servlet/configuration/java.html#_multiple_httpsecurity_instances[Multiple HttpSecurity Instances^] section of the Spring Security documentation for how to configure multiple `HttpSecurity` objects.

Each Jmix application by default contains a security configuration that extends the {vaadin-docs}/security/enabling-security#security-configuration-class[VaadinWebSecurity^] class. This configuration sets up access to internal Vaadin endpoints and delegates all requests authorization to Jmix and Vaadin mechanisms (grants access to views using view controller annotation or by analyzing user's resource roles). `SecurityFilterChain` created by this configuration always has the lowest priority and is always invoked last. The <<custom-endpoints-security>> section below explains how to define your own `SecurityFilterChain` to protect custom endpoints. The <<static-public-resources>> section explains how to completely bypass Spring Security for some URLs.

Add-ons like xref:oidc:index.adoc[OpenID Connect] or xref:authorization-server:index.adoc[Authorization Server] bring their own `SecurityFilterChain` beans that protect authorization or resource server endpoints. These beans are always invoked before the one from the UI module. See the <<token-based-authentication>> section below for how to protect API endpoints when using these add-ons.

[[static-public-resources]]
== Static Public Resources

To completely ignore Spring Security rules for static public resources, create a configuration class extending `FlowuiVaadinWebSecurity` and register your public URL patterns with the `ignoring()` method of `WebSecurity`:

[source,java,indent=0]
----
include::example$/security-ex1/src/main/java/com/company/demo/security/DemoSecurityConfiguration.java[]
----

The example configuration above gives public access to all files located inside the `src/main/resources/public/images` directory of your project (see how to serve static content in the https://docs.spring.io/spring-boot/docs/current/reference/html/web.html#web.servlet.spring-mvc.static-content[Spring Boot documentation^]).

[[custom-endpoints-security]]
== Custom Endpoints Security

To define custom security rules for endpoints, declare a new `SecurityFilterChain` bean. It is important that the order of this bean must be less than the order of `SecurityFilterChain` beans provided by Jmix framework.

You can find order value constants used by Jmix in the `JmixSecurityFilterChainOrder` interface. The rule of thumb is to use the `JmixSecurityFilterChainOrder.CUSTOM`, `JmixSecurityFilterChainOrder.CUSTOM - 10` and similar values for your security filter chains.

A simple `SecurityFilterChain` bean definition may look as follows:

[source,java,indent=0]
----
include::example$/security-ex1/src/main/java/com/company/demo/security/api/SimplePublicSecurityConfiguration.java[tags=public-filter-chain]
----

The configuration above grants access to all requests that match the `/public-api/**` pattern.

[[public-endpoints-example]]
=== Public Endpoints

Let's assume that you have a controller with two methods, and you want these methods to be available for any user without authentication.

[source,java,indent=0]
----
include::example$/security-ex1/src/main/java/com/company/demo/controller/GreetingController.java[tags=whole-class]
----

Public access can be configured using the following configuration:

[source,java,indent=0]
----
include::example$/security-ex1/src/main/java/com/company/demo/security/api/AnonymousControllerSecurityConfiguration.java[tags=whole-class]
----
<1> `JmixSecurityFilterChainOrder.CUSTOM` order is less than any other Jmix security filter chain order, so your filter chain will be used before any filter chain from Jmix.
<2> {spring-security-doc}/servlet/authorization/authorize-http-requests.html#security-matchers[securityMatcher()^] is used to determine whether a given `HttpSecurity` should be applied to the request. The request matcher from the example will match requests with URLs that follow the pattern `/greeting/**`. Requests for other URLs will be processed by a default security filter chain from Jmix UI module.
<3> `permitAll()` instruction grants access to endpoints.
<4> Disables CSRF for POST requests.
<5> The invocation of `JmixHttpSecurityUtils.configureAnonymous(http)` configures anonymous authentication by setting the anonymous user returned by the Jmix `UserRepository` to the security context.

[[http-basic-authentication-example]]
=== HTTP Basic Authentication

The example demonstrates how to protect controller endpoints using https://en.wikipedia.org/wiki/Basic_access_authentication[HTTP Basic authentication^].

The controller class:

[source,java,indent=0]
----
include::example$/security-ex1/src/main/java/com/company/demo/controller/BasicGreetingController.java[tags=whole-class]
----

Requests with URLs matching the `pass:[/api/**]` pattern should be protected with HTTP Basic authentication, while requests to `pass:[/api/public/**]` should be available to all users. This can be achieved by using the configuration below:

[source,java,indent=0]
----
include::example$/security-ex1/src/main/java/com/company/demo/security/api/BasicControllerSecurityConfiguration.java[tags=whole-class]
----
<1> `JmixSecurityFilterChainOrder.CUSTOM` order is less than any other Jmix security filter chain order, so your filter chain will be used before any filter chain from Jmix.
<2> Security matcher indicates that the HttpSecurity will only be applied for `pass:[/api/**]` requests.
<3> If the request is selected by security matcher then we can provide further rules. All requests for `pass:[/api/public/**]` must be permitted without authentication.
<4> All requests that don't match the `pass:[/api/public/**]` pattern defined above must be authenticated.
<5> Enable basic authentication.
<6> Use the `AuthenticationManager` configured by Jmix for basic authentication.

Requests to `pass:[/api/**]` endpoints must contain a header in the form of `Authorization: Basic <credentials>`, where `<credentials>` is the Base64 encoding of username and password joined by a single colon. For example:

[source]
----
GET /api/hello HTTP/1.1
Host: server.example.com
Authorization: Basic YWRtaW46YWRtaW4=
----

TIP: In this example, public access to `pass:[/api/public/**]` could be alternatively configured using another `SecurityFilterChain` bean that has `pass:[securityMatcher("/api/public/**")]` and an order less than the current one, e.g. `JmixSecurityFilterChainOrder.CUSTOM - 10`.

[[token-based-authentication]]
== Token Based Authentication

You can protect custom endpoints using bearer tokens issued by the xref:authorization-server:index.adoc[Authorization Server] or an external identity provider, such as Keycloak, when using the xref:oidc:index.adoc[OpenID Connect] add-on. The security configurations of the Authorization Server and the OpenID Connect add-ons provide extension points for this purpose. In the context of the OAuth 2.1 specification, your application that hosts the protected endpoints acts as a *resource server*.

Suppose you have a REST controller:

[source,java,indent=0]
----
include::example$/security-ex1/src/main/java/com/company/demo/controller/GreetingController.java[tags=whole-class]
----

There are several ways to determine which endpoints should be protected with token-based authentication and which can be accessed anonymously.

[[application-properties]]
=== Application Properties

The simplest way to determine which endpoints of a resource server should be protected and which should have public access, is by using the following application properties:

[source,properties,indent=0]
----
include::example$/security-ex1/src/main/resources/application.properties[tags=resource-server-endpoints-security]
----

[[url-patterns-providers]]
=== URL Patterns Providers

Another way to define which endpoints need to be protected with token-based authentication is to create a bean implementing the `AuthenticatedUrlPatternsProvider` interface and return a list of URL patterns from its `getAuthenticatedUrlPatterns()` method. This approach is more flexible and allows you to define more complex rules for endpoint protection.

[source,java,indent=0]
----
include::example$/security-ex1/src/main/java/com/company/demo/security/resserver/GreetingAuthenticatedUrlPatternsProvider.java[tags=whole-class]
----

Resource server endpoints that must be accessed anonymously can be defined in the same way using the `AnonymousUrlPatternsProvider` interface.

[source,java,indent=0]
----
include::example$/security-ex1/src/main/java/com/company/demo/security/resserver/GreetingAnonymousUrlPatternsProvider.java[tags=whole-class]
----

[[request-matcher-provider]]
=== RequestMatcher Provider

Application properties and URL patterns providers allow you to define endpoints protection rules that operate on a collection of strings with URL patterns. If you need more complex rules than just the URL pattern, such as the HTTP method as well, you can implement the `AuthenticatedRequestMatcherProvider` interface and return a `RequestMatcher` object from its `getAuthenticatedRequestMatcher()` method.

[source,java,indent=0]
----
include::example$/security-ex1/src/main/java/com/company/demo/security/resserver/GreetingAuthenticatedRequestMatcherProvider.java[tags=whole-class]
----

`RequestMatcher` for public endpoints of the resource server can be defined in the same way using the `AnonymousRequestMatcherProvider` interface.

[source,java,indent=0]
----
include::example$/security-ex1/src/main/java/com/company/demo/security/resserver/GreetingAnonymousRequestMatcherProvider.java[tags=whole-class]
----

[[accessing-resource-server-endpoints]]
=== Accessing Resource Server Endpoints

After any of the above configurations are defined, all requests to protected `pass:[/greeting/**]` endpoints of the resource server will require a bearer access token in the `Authorization` header. For example:

[source]
----
GET /greeting/hello HTTP/1.1
Host: server.example.com
Authorization: Bearer <ACCESS_TOKEN>
----

[[troubleshooting]]
== Troubleshooting

If you come across a 401 Unauthorized or 403 Forbidden HTTP error or have any other issues related to endpoint security, then Spring Security {spring-security-doc}/servlet/architecture.html#servlet-logging[logging^] will likely help you understand what is going on.

To enable logging, add the following application property with `DEBUG` or `TRACE` value to the `application.properties` file:

[source,properties]
----
logging.level.org.springframework.security = TRACE
----