= Пользователи

[[entity]]
== Сущность User

Пользователи приложения Jmix определяются классом `User`, который xref:studio:project.adoc#creating-new-project[Studio] автоматически создает в новом проекте. Это xref:data-model:entities.adoc#jpa[сущность JPA], реализующая интерфейс `JmixUserDetails`, который имеет ряд методов, требуемых фреймворком:

* `getUsername()` возвращает уникальное имя пользователя.
* `getPassword()` возвращает хэшированный пароль.
* `isEnabled()`, `isAccountNonExpired()`, `isAccountNonLocked()`, `isCredentialsNonExpired()` указывают, может ли пользователь войти в систему.
* `getAuthorities()`, `setAuthorities()` используются фреймворком для привязки пользователя к набору разрешений при входе в систему.

Пользователи хранятся в основной базе данных приложения. По умолчанию сущность `User` и соответствующая таблица базы данных имеют следующие атрибуты:

* `id`, `version` являются стандартными атрибутами первичного ключа и оптимистической блокировки.
* `username`, `password`, `enabled` хранят значения, возвращаемые методами интерфейса `JmixUserDetails`.
* `email`, `firstName`, `lastName` хранят дополнительную информацию о пользователях.

Вы можете определить любое количество дополнительных атрибутов, необходимых для приложения, например, `department` или `position`.

[[management]]
== Управление пользователями

Новый проект содержит скрипт xref:data-model:db-migration.adoc#changelogs[миграции базы данных] `010-init-user.xml`, который создает пользователя с именем и паролем `admin`/`admin` и предоставляет ему полный доступ к приложению, связывая сущность с xref:resource-roles.adoc[ролью] `system-full-access`.

Новый проект также содержит экраны UI для управления пользователями, см. *Application* -> *Users*. Эти экраны позволяют создавать, редактировать и удалять пользователей, изменять и сбрасывать их пароли. Чтобы назначить роли пользователю, нажмите кнопку *Role assignments* в экране списка пользователей.

NOTE: Новый проект содержит роль `ui-minimal`, которая дает разрешения на вход в UI и главный экран. Назначьте эту роль новым пользователям, которые будут взаимодействовать с приложением через UI, так как в противном случае они не смогут войти в систему.

TIP: В примере https://github.com/jmix-framework/jmix-samples-2/tree/main/user-registration[User Registration^] показано, как можно реализовать самостоятельную регистрацию пользователей.

[[built-in]]
== Встроенные пользователи

Любое приложение Jmix со стандартной подсистемой безопасности имеет два встроенных пользователя:

* Пользователь _Anonymous_ соответствует не прошедшим аутентификацию пользователям чей доступ к приложению ограничен экраном логина. Настроив этот объект, можно предоставить некоторые разрешения перед тем как пользователь войдет в систему.

* Пользователь _System_ требуется для механизма xref:authentication.adoc#system[системной аутентификации]. Он используется, когда нет реального пользователя, взаимодействующего с приложением, например, при его запуске или при вызове бизнес-метода планировщиком.

Встроенные объекты пользователей не хранятся в базе данных, а создаются при запуске приложения классом проекта `DatabaseUserRepository`. Обоих пользователей можно настроить в методах `initAnonymousUser()` и `initSystemUser()` этого класса.

.DatabaseUserRepository.java
[source,java,indent=0]
----
include::example$/security-ex1/src/main/java/com/company/demo/security/DatabaseUserRepository.java[tags=init-built-in-users]
----

<1> По умолчанию системный пользователь связан с ролью `system-full-access` и, следовательно, имеет все разрешения.
<2> Анонимный пользователь по умолчанию не имеет никаких разрешений.
+
TIP: Чтобы упростить предоставление анонимного доступ к отдельным экранам используйте аннотацию xref:flow-ui:views/view-annotations.adoc#common-annotations[@AnonymousAllowed].

[[user-substitution]]
== Замещение пользователя

Системный администратор может предоставить пользователю возможность замещать другого пользователя. Замещение означает, что пользователь получает xref:security:resource-roles.adoc[ресурсные роли] и xref:security:row-level-roles.adoc[роли уровня строк] замещенного пользователя. Например, если Алиса замещает Боба, она входит в приложение как Алиса, но выполняет роли Боба.

Чтобы увидеть функцию в действии, выполните следующие действия:

. Войдите в систему как `admin` и создайте по крайней мере еще одного пользователя с ролью `UI: minimal access`.
. Выберите `admin` в таблице *Users* и нажмите *Additional -> User substitution*. Вы увидите список пользователей, которых может заместить `admin`.
. Создайте новую запись с пользователем, которых замещает `admin`, затем нажмите *OK* в экране списка.
. Если основной экран вашего проекта содержит компонент xref:flow-ui:vc/components/userMenu.adoc[] с действием xref:flow-ui:actions/user-menu-actions.adoc#sec_userMenuSubstituteUser[sec_userMenuSubstituteUser], выпадающий список компонента покажет пункт меню с замещаемым пользователем.
. Если основной экран вашего проекта включает компонент `userIndicator`, имя текущего пользователя изменится на выпадающий список, который содержит замещаемого пользователя.
. Если выбрать замещаемого пользователя в `userMenu` или `userIndicator`, то рабочее пространство изменится, как если бы вы повторно вошли в систему как этот пользователь. Но все функции аудита зарегистрируют `admin` ‒ вошедшего в систему пользователя.

Бин `CurrentUserSubstitution` может использоваться для получения текущего замещенного пользователя, аутентифицированного или действующего пользователя (который в случае замещения является замещенным пользователем, а в противном случае аутентифицированным).

Например:

[source,java,indent=0]
----
include::example$/security-ex1/src/main/java/com/company/demo/view/main/MainView.java[tags=user-substitution]
----

* Метод `CurrentAuthentication.getUser()` всегда возвращает аутентифицированного пользователя.

* `CurrentAuthentication.getAuthentication().getAuthorities()` возвращает полномочия действующего пользователя. То есть в случае замещения эти полномочия отличаются от полномочий аутентифицированного пользователя.