= Getting Started with Message Templates

This tutorial will guide you through the process of integrating the Message Templates add-on into your application.

[[project-setup]]
== Project Setup

We are developing a Room Booking Application that demonstrates the use of the Message Templates add-on in a Jmix project with the provided `Booking` entity. This application will show how to create, manage, and use message templates for booking notifications.

Application administrators define message templates that are used to notify users after a meeting room reservation is made. Users receive both an email and a direct in-app notification following their booking.

. Create a base Jmix project. You can refer to the xref:tutorial:project-setup.adoc[Tutorial] section, which offers a detailed, step-by-step guide for developing the base application.
. Add the Message Templates add-on according to the xref:index.adoc#installation[installation] section.
. To enable sending emails and in-app notifications, you'll also need to install the xref:email:index.adoc[Email Sending] and xref:notifications:index.adoc[Notifications] add-ons.

[[about-app]]
== About the Sample Application

This sample application demonstrates a basic Room Booking system. It provides a practical example of how to handle bookings and send notifications either directly within the application or via email, using a pre-existing message template.

The `Booking` entity is the core of the application, and the `User` entity (referenced as `creator`) represents the user who created the booking.