= История

История (History) это компонент, который фиксирует всё что происходило во время выполнения процесса, и хранит эту информацию на постоянной основе. В отличие от данных времени выполнения, данные истории остаются в базе данных даже после завершения экземпляров процессов.

Существует шесть сущностей истории:

[[historic-process-instances]]
* *Historic Process Instances* — содержат информацию о текущих и прошлых экземплярах процессов.
* *Historic Variable Instances* — содержат последнее значение переменной процесса или переменной задачи.
* *Historic Activity Instances* — содержат информацию о единственном выполнении активности (node in the process).
* *Historic Task Instances* — содержат информацию о текущих и прошлых (completed and deleted) экземплярах задач.
* *Historic Identity Links* — содержат информацию о текущих и прошлых связях идентификации для задач и экземпляров процессов.
* *Historic Details* — содержат различные виды информации, относящейся к историческому экземпляру процесса, экземпляру активности или экземпляру задачи.

Поскольку база данных содержит исторические данные как для прошлых, так и для текущих экземпляров, вы можете выполнять запросы к этим таблицам, чтобы снизить количество обращений к данным рантайма и поддерживать производительность.

Для получения подробной информации посетите раздел https://www.flowable.com/open-source/docs/bpmn/ch10-History[History^] в документации Flowable.