= BPM

Business Process Management (BPM) — это систематический подход к улучшению процессов в организациях. Он включает проектирование, выполнение, мониторинг и оптимизацию бизнес-процессов для повышения эффективности и результативности.

В Jmix функциональность моделирования и запуска бизнес-процессов предоставляется дополнением BPM.

TIP: Приложение https://demo.jmix.ru/bookstore/[Bookstore^] демонстрирует возможности дополнения Jmix BPM.

[[installation]]
== Установка
[NOTE]
====
Дополнение BPM доступно по https://www.jmix.ru/subscription-plans-and-prices/[BPM подписке^]. Чтобы ознакомиться с дополнением, воспользуйтесь xref:ROOT:account-management.adoc#enterprise-trial[Пробной Enterprise+BPM подпиской].
====

Для автоматической установки через *Jmix Marketplace*, следуйте инструкциям в разделе xref:ROOT:add-ons.adoc#installation[Дополнения].

Для ручной установки выполните следующие шаги:

. Настройте доступ к премиум репозиторию.
+
include::ROOT:partial$premium-repo.adoc[]

. Добавьте зависимости в `build.gradle`:
+
[source,groovy,indent=0]
----
implementation 'io.jmix.bpm:jmix-bpm-starter'
implementation 'io.jmix.bpm:jmix-bpm-flowui-starter'
----

include::ROOT:single-menu-note.adoc[]