= BPM

业务流程管理（Business Process Management）是指改进组织流程的系统方法。
包括对业务流程的设计、执行、监控、
优化，以提高组织的效率。

In Jmix, the functionality for modeling and running business processes is provided by the BPM add-on.

在 Jmix 中，建模和运行业务流程的功能通过 BPM 扩展组件提供。

TIP: 通过 https://demo.jmix.io/bookstore/[Bookstore^] 在线示例了解 BPM 扩展组件的实际应用。


[[installation]]
== 安装
[NOTE]
====
此扩展组件需要 BPM 版 https://www.jmix.cn/subscription-plans-and-prices/[订阅^]。
如果没有 BPM 版订阅，可以按照 xref:ROOT:account-management.adoc#enterprise-trial[企业+BPM 版试用] 介绍的方法试用。
====

请按照 xref:ROOT:add-ons.adoc#installation[扩展组件] 章节的介绍通过 Jmix 市场自动安装。

手动安装步骤：

. 配置 premium 仓库的访问
+
include::ROOT:partial$premium-repo.adoc[]

. 在 `build.gradle` 中添加依赖
+
[source,groovy,indent=0]
----
implementation 'io.jmix.bpm:jmix-bpm-starter'
implementation 'io.jmix.bpm:jmix-bpm-flowui-starter'
----

include::ROOT:single-menu-note.adoc[]

[[oracle-db-note]]
== Oracle 数据库说明

当应用程序启动时，Flowable 引擎会检查是否存在 xref:bpm:introduction.adoc#database-table-names[`ACT_GE_PROPERTY`] 表。在使用 Oracle 做数据库时，可能会看到下面这个错误：

----
oracle.jdbc.OracleDatabaseException: ORA-00942: table or view does not exist
----

https://docs.oracle.com/en/error-help/db/ora-00942[ORA-00942^] 这个错误的一个可能原因是，这个表格属于另一个非默认的 schema，且没有正确引用，一般发生在数据库有多用户的情况。

要解决这个问题，可以显式在 `application.properties` 文件设置 schema：

.application.properties
----
flowable.database-schema=<db_username>
----

将 `<db_username>` 替换为真实的数据库 username。

