= BPM

Нотация Business Process Management (BPM) предлагает систематический подход к улучшению процессов в организациях. Дополнение Jmix BPM предоставляет функциональность для моделирования и выполнения бизнес-процессов в приложениях Jmix.

TIP: Приложение https://demo.jmix.ru/bookstore/[Bookstore^] демонстрирует возможности дополнения Jmix BPM.

[[installation]]
== Установка
[NOTE]
====
Данное дополнение доступно по https://www.jmix.ru/subscription-plans-and-prices/[Enterprise подписке^]. Чтобы ознакомиться с дополнением, воспользуйтесь xref:ROOT:account-management.adoc#enterprise-trial[Пробной Enterprise подпиской].
====

Для автоматической установки через *Jmix Marketplace*, следуйте инструкциям в разделе xref:ROOT:add-ons.adoc#installation[Дополнения].

Для ручной установки выполните следующие шаги:

. Настройте доступ к премиум репозиторию.
+
include::ROOT:partial$premium-repo.adoc[]

. Добавьте зависимости в `build.gradle`:
+
[source,groovy,indent=0]
----
implementation 'io.jmix.bpm:jmix-bpm-starter'
implementation 'io.jmix.bpm:jmix-bpm-flowui-starter'
----