= BPM

Business Process Management (BPM) refers to the systematic approach to improving an organization’s processes.
It encompasses the design, execution, monitoring,
and optimization of business processes to enhance efficiency and effectiveness.

BPM add-on provides functionality for modeling and running business processes.

TIP: Онлайн приложение https://demo.jmix.ru/bookstore/[Bookstore^] демонстрирует возможности дополнения Jmix BPM в действии.

[[installation]]
== Installation
[NOTE]
====
This add-on requires the Enterprise https://www.jmix.io/subscription-plans-and-prices/[subscription^].
If you don't have the subscription, see the xref:ROOT:account-management.adoc#enterprise-trial[Enterprise Trial] section for how to get a trial version.
====

For automatic installation through *Jmix Marketplace*, follow instructions in the xref:ROOT:add-ons.adoc#installation[Add-ons] section.

For manual installation, follow the steps below.

. Configure access to the premium repository.
+
include::ROOT:partial$premium-repo.adoc[]

. Add dependencies to your `build.gradle`:
+
[source,groovy,indent=0]
----
implementation 'io.jmix.bpm:jmix-bpm-starter'
implementation 'io.jmix.bpm:jmix-bpm-flowui-starter'
----