= BPM

Business Process Management (BPM) refers to the systematic approach to improving an organization’s processes.
It encompasses the design, execution, monitoring,
and optimization of business processes to enhance efficiency and effectiveness.

In Jmix, the functionality for modeling and running business processes is provided by the BPM add-on.

TIP: Explore the https://demo.jmix.io/bookstore/[Bookstore^] online demo application to see Jmix BPM add-on in action.


[[installation]]
== Installation
[NOTE]
====
The Jmix BPM add-on requires the https://www.jmix.io/subscription-plans-and-prices/[BPM subscription^].
If you don't have the subscription, see the xref:ROOT:account-management.adoc#enterprise-trial[Enterprise+BPM Trial] section for how to get a trial version.
====

For automatic installation through *Jmix Marketplace*, follow instructions in the xref:ROOT:add-ons.adoc#installation[Add-ons] section.

For manual installation, follow the steps below.

. Configure access to the premium repository.
+
include::ROOT:partial$premium-repo.adoc[]

. Add dependencies to your `build.gradle`:
+
[source,groovy,indent=0]
----
implementation 'io.jmix.bpm:jmix-bpm-starter'
implementation 'io.jmix.bpm:jmix-bpm-flowui-starter'
----

include::ROOT:single-menu-note.adoc[]

[[oracle-db-note]]
== Oracle Database Note

When the application starts, the Flowable engine checks if the xref:bpm:introduction.adoc#database-table-names[`ACT_GE_PROPERTY`] table exists. If the application is using Oracle Database as the data source, you might see this error:

----
oracle.jdbc.OracleDatabaseException: ORA-00942: table or view does not exist
----

One possible cause of the https://docs.oracle.com/en/error-help/db/ora-00942[ORA-00942^] error is that the table belongs to a schema that is different from default and is not referenced correctly. This can occur when the database has multiple users.

To resolve this issue, explicitly set the schema by adding this line to your `application.properties` file:

.application.properties
----
flowable.database-schema=<db_username>
----

Replace `<db_username>` with the actual database username.