= BPM

Business Process Management (BPM) — это систематический подход к улучшению процессов в организациях. Он включает проектирование, выполнение, мониторинг и оптимизацию бизнес-процессов для повышения эффективности и результативности.

В Jmix функциональность моделирования и запуска бизнес-процессов предоставляется дополнением BPM.

TIP: Приложение https://demo.jmix.ru/bookstore/[Bookstore^] демонстрирует возможности дополнения Jmix BPM.

[[installation]]
== Установка
[NOTE]
====
Дополнение BPM доступно по https://www.jmix.ru/subscription-plans-and-prices/[BPM подписке^]. Чтобы ознакомиться с дополнением, воспользуйтесь xref:ROOT:account-management.adoc#enterprise-trial[Пробной Enterprise+BPM подпиской].
====

Для автоматической установки через *Jmix Marketplace*, следуйте инструкциям в разделе xref:ROOT:add-ons.adoc#installation[Дополнения].

Для ручной установки выполните следующие шаги:

. Настройте доступ к премиум репозиторию.
+
include::ROOT:partial$premium-repo.adoc[]

. Добавьте зависимости в `build.gradle`:
+
[source,groovy,indent=0]
----
implementation 'io.jmix.bpm:jmix-bpm-starter'
implementation 'io.jmix.bpm:jmix-bpm-flowui-starter'
----

include::ROOT:single-menu-note.adoc[]

[[oracle-db-note]]
== Использование совместно с Oracle Database

При запуске приложения, движок Flowable проверяет, существует ли таблица xref:bpm:introduction.adoc#database-table-names[`ACT_GE_PROPERTY`].
Если приложение использует Oracle Database в качестве хранилища данных, вы можете столкнуться с ошибкой:

----
oracle.jdbc.OracleDatabaseException: ORA-00942: table or view does not exist
----

Одной из возможных причин ошибки https://docs.oracle.com/en/error-help/db/ora-00942[ORA-00942^] является то, что таблица принадлежит схеме, отличной от стандартной и которая не указана явно. Это может произойти, если в базе данных несколько пользователей.

Чтобы решить данную проблему, явно укажите схему, добавив следующую строку в файл `application.properties`:

.application.properties
----
flowable.database-schema=<db_username>
----

Замените `<db_username>` на фактическое имя пользователя базы данных.