= Миграция экземпляров процесса

При изменении модели процесса и развертывании новой версии определения процесса, все существующие экземпляры процесса продолжают использовать предыдущую версию определения. При необходимости возможна их миграция в новую версию.

Чтобы мигрировать все экземпляры процесса:

. Перейдите на экран xref:bpm:menu-views/process-definitions.adoc[].
. Нажмите *View details*.
. Выберите версию определения в выпадающем списке.
. Нажмите кнопку *Migrate all instances*.

Перед выполнением миграции все экземпляры проходят валидацию, и если какой-либо экземпляр не может быть мигрирован, отобразится окно с информацией.

Чтобы мигрировать единственный экземпляр:

. Выберите экемпляр на экране xref:bpm:menu-views/process-instances.adoc[]
. Нажмите *Edit* чтобы открыть экран редактирования экземпляра
. На экране редактирования экземпляра нажмите *Migrate*.

Для получения более подробной информации о миграции процессов см. https://documentation.flowable.com/latest/reactmodel/bpmn/concept/process-migration/index.html[Документацию Flowable^].
