= Process Instances Migration

When you modify a process model and deploy a new process definition version, all existing process instances continue using the previous version of the process definition. If necessary, you can migrate them to the new process definition version.

In order to migrate all process instances,

. Go to the xref:bpm:menu-views/process-definitions.adoc[] view.
. Click *View details*.
. Select the definition version from the dropdown list.
. Click the *Migrate all instances* button.

Before migration, all instances are validated, and if any instance cannot be migrated, a window with information will be displayed.

To migrate a single instance:

. Select the instance on the xref:bpm:menu-views/process-instances.adoc[] view.
. Click *Edit* to open the instance editing screen.
. On the instance editing screen, click *Migrate*.

For more details about the process instance migration, see https://flowable.com/open-source/docs/bpmn/ch09-ProcessInstanceMigration/#process-instance-migration-experimental[Flowable documentation^].
