= Event Listeners

There are several approaches to handle process engine events like task creation, activity completion, and so on.

First, you can define an execution listener or a task listener for a particular process node. See https://www.flowable.com/open-source/docs/bpmn/ch07b-BPMN-Constructs#execution-listener[Flowable documentation^] for details.

Process modeler provides UI for configuring listeners.

* In the execution listener editor, the drop-down list contains classes that implement the `org.flowable.engine.delegate.ExecutionListener` interface. 
* In the task listener editor, the drop-down list contains classes that implement `org.flowable.engine.delegate.TaskListener` interface. If the class contains https://flowable.com/open-source/docs/bpmn/ch07b-BPMN-Constructs/#field-injection-on-execution-listeners[injected fields^], then these fields will be automatically added to the *Fields* section of the listener editor.

The second approach is to declare global event listeners provided by the Flowable framework, see https://flowable.com/open-source/docs/bpmn/ch03-Configuration/#event-handlers[Event handlers^] section. You can define them in the *Event listeners* section in the project properties panel.

BPM add-on additionally introduces a set of Spring application events. The following events are published:

* `UserTaskAssignedEvent`
* `UserTaskCreatedEvent`
* `UserTaskCompletedEvent`
* `ActivityStartedEvent`
* `ActivityCompletedEvent`
* `ProcessStartedEvent`
* `ProcessCompletedEvent`

Here is an example of an event listener that sends an email notification each time a user task is assigned to a user:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/listener/TaskAssignedNotificationSender.java[tags=event-listener-1;event-listener-2]
----

<1> Declares that the method is an event listener.
<2> The listener is fired each time the `UserTaskAssignedEvent` is published.
<3> Gets `User` entity to get the user's first name and email address. The `UserTaskAssignedEvent` contains the `username` of the user to whom the task is assigned.
<4> The `UserTaskAssignedEvent` contains a `Task` object which holds information about the user task.
<5> Creates and sends email. See the xref:email:index.adoc[Email Sending Guide] for details.

If you need to get a process variable value in the listener, you can do it this way:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/listener/TaskAssignedNotificationSender2.java[tags=get-variable-1;get-variable-2]
----

By default, a listener is fired when the user task is assigned in any process. If you want to send notifications only for specific process definition, you can check the process definition in the listener method body:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/listener/TaskAssignedNotificationSender.java[tags=specific-process-1;specific-process-2]
----

or you can define a SpEL (Spring Expression Language) expression that should match in order to handle the event:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/listener/TaskAssignedNotificationSender3.java[tags=spel-example-1;spel-example-2]
----