= Event Listeners

Существует несколько подходов к обработке событий процессов, таких как создание задачи, завершение операции и т.д.

Первый подход состоит в определении слушателя выполнения или слушателя задачи для определённого узла процесса. Подробее см. в https://www.flowable.com/open-source/docs/bpmn/ch07b-BPMN-Constructs#execution-listener[документации Flowable].

Моделер процессов предоставляет UI для настройки слушателей.

* В редакторе слушателя завершения выпадающий список содержит классы, реализующие интерфейс `org.flowable.engine.delegate.ExecutionListener`.
* В редакторе слушателя задачи выпадающий список содержит классы, реализующие интерфейс `org.flowable.engine.delegate.TaskListener`. Если класс содержит https://flowable.com/open-source/docs/bpmn/ch07b-BPMN-Constructs/#field-injection-on-execution-listeners[инжектированные поля^], то они будут автоматически добавлены в раздел *Fields* редактора слушателя.

Второй подход – объявить глобальные слушатели событий, предоставляемые фреймворком Flowable, см. раздел https://flowable.com/open-source/docs/bpmn/ch03-Configuration/#event-handlers[Event handlers^] в документации Flowable. Слушатели можно определить в разделе *Event listeners* панели свойств проекта.

Дополнение BPM также представляет набор событий приложений Spring. Публикуются следующие события:

* `UserTaskAssignedEvent`
* `UserTaskCreatedEvent`
* `UserTaskCompletedEvent`
* `ActivityStartedEvent`
* `ActivityCompletedEvent`
* `ProcessStartedEvent`
* `ProcessCompletedEvent`

Ниже представлен пример слушателя, который отправляет уведомление по электронной почте каждый раз, когда пользовательская задача назначается пользователю:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/listener/TaskAssignedNotificationSender.java[tags=event-listener-1;event-listener-2]
----

<1> Аннотация `@EventListenter` указывает что метод является слушателем события.
<2> Слушатель срабатывает всякий раз когда публикуется событие `UserTaskAssignedEvent`.
<3> Загрузка экземпляра сущности `User` с указанным именем пользователя (username). Значение `username` содержит имя пользователя которому назначена задача, оно передается из события `UserTaskAssignedEvent`.
<4> Событие `UserTaskAssignedEvent` содержит объект `Task` с информацией о пользовательской задаче.
<5> Создание и отправка письма. Подробнее см. в разделе xref:email:index.adoc[].

Если вам нужно получить в слушателе значение переменной процесса, то это можно сделать следующим образом:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/listener/TaskAssignedNotificationSender2.java[tags=get-variable-1;get-variable-2]
----

По умолчанию слушатель срабатывает, когда в любом процессе назначается пользовательская задача. Если вы хотите отправлять уведомления только для конкретного определения процесса, вы можете проверить определение процесса в теле метода слушателя;

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/listener/TaskAssignedNotificationSender.java[tags=specific-process-1;specific-process-2]
----

По умолчанию слушатель срабатывает, когда в любом процессе назначается пользовательская задача. Если вы хотите отправлять уведомления только для конкретного определения процесса, вы можете проверить определение процесса в теле метода слушателя;
[source,java,indent=0]

----
include::example$/ex1/src/main/java/bpm/ex1/listener/TaskAssignedNotificationSender3.java[tags=spel-example-1;spel-example-2]
----