= Listeners

There are several approaches to handle process engine events like task creation, activity completion, and so on.


[[execution-listeners]]
== Execution Listeners

See https://www.flowable.com/open-source/docs/bpmn/ch07b-BPMN-Constructs/#execution-listener[Flowable documentation^].

[[task-listeners]]
== Task Listeners

See https://www.flowable.com/open-source/docs/bpmn/ch07b-BPMN-Constructs/#task-listener[Flowable documentation^].

[[spring-events-bpm]]
== Spring Events for BPM

Jmix BPM introduces a set of Spring application events. The following events are published:

* `UserTaskAssignedEvent`
* `UserTaskCreatedEvent`
* `UserTaskCompletedEvent`
* `ActivityStartedEvent`
* `ActivityCompletedEvent`
* `ProcessStartedEvent`
* `ProcessCompletedEvent`

Here is an example of an event listener that sends an email notification each time a user task is assigned to a user:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/listener/TaskAssignedNotificationSender.java[tags=event-listener-1;event-listener-2]
----

<1> Declares that the method is an event listener.
<2> The listener is fired each time the `UserTaskAssignedEvent` is published.
<3> Gets `User` entity to receive a user first name and email address.The `UserTaskAssignedEvent` contains a `username` of a user who is the task assigned to.
<4> The `UserTaskAssignedEvent` contains a `Task` object which holds information about the user task.
<5> Creates and sends email. See the xref:email:index.adoc[Email Sending Guide] for details.

If you need to get a process variable value in the listener, you can do it this way:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/listener/TaskAssignedNotificationSender2.java[tags=get-variable-1;get-variable-2]
----

By default, a listener is fired when the user task is assigned in any process. If you want to send notifications only for specific process definition, you can check the process definition in the listener method body:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/listener/TaskAssignedNotificationSender.java[tags=specific-process-1;specific-process-2]
----

or you can define a SpEL (Spring Expression Language) expression that should match in order to handle the event:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/bpm/ex1/listener/TaskAssignedNotificationSender3.java[tags=spel-example-1;spel-example-2]
----
