= 应用程序属性

[[core]]
== Core

[[jmix.core.anonymous-authentication-token-key]]
=== jmix.core.anonymous-authentication-token-key

用在 Spring Security {spring-security-api}/org/springframework/security/authentication/AnonymousAuthenticationProvider.html[AnonymousAuthenticationProvider^] 和
{spring-security-api}/org/springframework/security/web/authentication/AnonymousAuthenticationFilter.html[AnonymousAuthenticationFilter^] 中的 key。

默认值：`de72c623-6d3d-458c-a187-c526de515ecd`

[[jmix.core.available-locales]]
=== jmix.core.available-locales

定义应用程序中使用的语言环境，用英文逗号分隔。参阅 xref:localization:message-bundles.adoc#setting-locales[配置语言环境] 章节。

示例：

[source,properties]
----
jmix.core.available-locales = en,zh_CN
----

[[jmix.core.conf-dir]]
=== jmix.core.conf-dir

设置配置文件的目录，可以在运行时修改。`Resources` 接口的默认实现会使用该参数，在对 classpath 进行搜索之前先加载该文件夹内的资源文件。

默认值：`${user.dir}/.jmix/conf`

TIP: `${user.dir}` 是用户的工作目录（即 JVM 的启动目录）。

[[jmix.core.cross-data-store-reference-loading-batch-size]]
=== jmix.core.cross-data-store-reference-loading-batch-size

定义为实体集合批量加载 xref:data-model:entities.adoc#cross-data-store-ref[跨数据存储引用] 实体的数量。

默认值：`50`


[[jmix.core.default-file-storage]]
=== jmix.core.default-file-storage

如果应用程序使用了 xref:files:file-storage.adoc#multiple-fs[多个文件存储]，用该参数指定默认的文件存储。

[[jmix.core.exclude-beans]]
=== jmix.core.exclude-beans

排除在 Spring 应用程序上下文之外的一组 bean 名称，用逗号分隔。可以用来 xref:modularity:extension.adoc#beans[覆盖] 已经在某些扩展组件中使用了 `@Primary` 注解的 bean。

示例：

[source,properties]
----
jmix.core.exclude-beans = abc_FooService,abc_BarService
----

[[jmix.core.fetch-plans-config]]
=== jmix.core.fetch-plans-config

设置共享 fetch plan 仓库配置文件的路径。请参考 xref:data-access:fetching.adoc#creating-fetch-plans[创建 Fetch Plans] 部分。

示例：
[source,properties]
----
jmix.core.fetch-plans-config = com/company/demo/fetch-plans.xml
----

[[jmix.core.temp-dir]]
=== jmix.core.temp-dir

定义应用程序保存临时文件的目录。

框架和扩展组件的导入/导出、上传/下载会使用该属性。

默认值：`${user.dir}/.jmix/temp`

TIP: `${user.dir}` 是用户的工作目录（JVM 的启动目录）。

[[jmix.core.trigger-files-enabled]]
=== jmix.core.trigger-files-enabled

启用 bean 调用触发器文件。

触发器文件，是一个放置于应用程序 <<jmix.core.temp-dir,临时文件夹>> 下 `triggers` 子文件夹的文件。文件名由 `#` 分隔的两部分组成：第一部分是 bean 类名，第二部分是 bean 的方法名。例如，`io.jmix.core.Messages#clearCache`。触发器文件的处理器会监控这个文件夹，检查新的触发器文件并调用相应的方法，然后删除这些文件。

默认值：`true`

[[jmix.core.trigger-files-process-interval]]
=== jmix.core.trigger-files-process-interval

搜索和处理 <<jmix.core.trigger-files-enabled,触发器文件>> 的间隔，单位为毫秒。

默认值：`5000`

[[jmix.core.web-host-name]]
=== jmix.core.web-host-name

设置应用程序运行服务器的名称。

该属性可以在多个应用程序子系统中使用。如果某个子系统需要使用该属性，应当在文档中提及。

NOTE: 这个属性并不会影响应用程序运行的实际服务器地址。如需绑定特定的地址，使用 `server.address` Spring Boot 配置。

[[jmix.core.web-port]]
=== jmix.core.web-port

设置应用程序运行服务器的端口。

该属性可以在多个应用程序子系统中使用。如果某个子系统需要使用该属性，应当在文档中提及。

NOTE: 这个属性并不会影响应用程序运行的实际服务器端口。如需绑定特定的端口，使用 `server.port` Spring Boot 配置。

[[jmix.core.work-dir]]
=== jmix.core.work-dir

定义应用程序可以存储数据的工作目录。

由 xref:files:file-storage.adoc#local-fs[本地文件存储] 使用，默认会在其 `filestorage` 子文件夹创建文件存储结构。

默认值：`${user.dir}/.jmix/work`

TIP: `${user.dir}` 是用户的工作目录（JVM 的启动目录）。

[[cors]]
== CORS

关于 CORS 的更多信息，参阅 REST API 扩展组件的 xref:rest:cors.adoc[CORS] 章节。

[[jmix.cors.allow-credentials]]
=== jmix.cors.allow-credentials

是否支持用户凭证。

默认值：`false`

[[jmix.cors.allowed-headers]]
=== jmix.cors.allowed-headers

预检（pre-flight）请求中给出在实际请求中可以使用的请求头列表。特殊值 “*” 表示允许实际请求发送任何请求头。

默认值：`*`

[[jmix.cors.allowed-methods]]
=== jmix.cors.allowed-methods

允许的 HTTP 方法，例如 "GET"、"POST"、"PUT" 等。
特殊值 “*” 表示允许所有方法。

默认值：`*`

[[jmix.cors.allowed-origins]]
=== jmix.cors.allowed-origins

定义 origin 列表，列表中的 origin 可以使用跨域访问。 特殊值 “*” 表示允许所有 origin。

例如，

[source,properties]
----
jmix.cors.allowed-origins = https://www.allowed1.com, https://www.allowed2.com
----

默认值：`*`

[[session]]
== Session

[[jmix.core.session.maximum-sessions-per-user]]
=== jmix.core.session.maximum-sessions-per-user

每个用户可以拥有的最大 xref:security:authentication.adoc#user-session[session] 数量。

这个属性会影响 Spring Security 的 {spring-security-api}/org/springframework/security/config/annotation/web/configurers/SessionManagementConfigurer.html#maximumSessions(int)[SessionManagementConfigurer.maximumSessions^] 参数。

默认值：`100`

[[long-classpath-issues-windows]]
== Windows 中 Classpath 超长的问题

[[io.jmix.flowui.read-class-path-from-temp-jar]]
=== io.jmix.flowui.read-class-path-from-temp-jar

在 Windows 中，classpaths 超长的应用程序可能会在 Flow UI 中遇到 UI 渲染问题。

Jmix 提供了一个配置属性来解决这个 Windows 中独有的问题：

[source,properties]
----
io.jmix.flowui.read-class-path-from-temp-jar = true
----

默认值：`true`

启用后：

* 仅在 Windows 操作系统上自动激活。
* 从 Gradle 临时 JAR 内的 `MANIFEST.MF` 文件中提取 classpath。
* 确保 Spring Boot 正确识别所有 classpath 条目。
* 恢复正确的 UI 资源加载和组件渲染。

[[see-also]]
== 参考

* xref:data-access:data-properties.adoc[数据访问配置]
* xref:data-access:cache.adoc[实体和查询缓存]
* xref:email:configuration.adoc[发送电子邮件配置]
* xref:ldap:properties.adoc[LDAP 配置]
* xref:pessimistic-lock:index.adoc[悲观锁]
* xref:reports:configuration.adoc[报表配置]
* xref:rest:app-properties.adoc[REST 配置]
* xref:superset:properties.adoc[Superset 配置]
// todo flowui search
// * xref:search:search-properties.adoc[Search Properties]
* xref:flow-ui:ui-properties.adoc[UI 配置]
// todo flowui webdav
// * xref:webdav:configuration.adoc[WebDAV Configuration]
