= Свойства приложения

[[core]]
== Основные

[[jmix.core.anonymous-authentication-token-key]]
=== jmix.core.anonymous-authentication-token-key

Ключ, используемый в Spring Security {spring-security-api}/org/springframework/security/authentication/AnonymousAuthenticationProvider.html[AnonymousAuthenticationProvider^] и
{spring-security-api}/org/springframework/security/web/authentication/AnonymousAuthenticationFilter.html[AnonymousAuthenticationFilter^].

Значение по умолчанию: `de72c623-6d3d-458c-a187-c526de515ecd`

[[jmix.core.available-locales]]
=== jmix.core.available-locales

Определяет локали, используемые в приложении, в виде списка кодов локалей, разделенных запятыми. См. xref:localization:message-bundles.adoc#setting-locales[настройка локалей] для получения дополнительной информации.

Например:

[source,properties]
----
jmix.core.available-locales = en,ru
----

[[jmix.core.conf-dir]]
=== jmix.core.conf-dir

Указывает каталог для файлов конфигурации, которые можно изменять во время выполнения приложения. Используется реализацией по умолчанию интерфейса `Resources` для загрузки файлов ресурсов из каталога перед поиском в classpath.

Значение по умолчанию: `${user.dir}/.jmix/conf`

TIP: `${user.dir}` - это рабочий каталог пользователя (где была запущена JVM).

[[jmix.core.cross-data-store-reference-loading-batch-size]]
=== jmix.core.cross-data-store-reference-loading-batch-size

Определяет размер пакета при загрузке xref:data-model:entities.adoc#cross-data-store-ref[перекрестных ссылок между хранилищами данных] для коллекции сущностей.

Значение по умолчанию: `50`

[[jmix.core.default-file-storage]]
=== jmix.core.default-file-storage

Задает файловое хранилище по умолчанию, если в приложении используются xref:files:file-storage.adoc#multiple-fs[несколько файловых хранилищ].

[[jmix.core.exclude-beans]]
=== jmix.core.exclude-beans

Список имен бинов, которые следует исключить из контекста приложения Spring. Это свойство можно использовать для xref:modularity:extension.adoc#beans[переопределения бинов], уже имеющих аннотации `@Primary` в некотором дополнении.

Например:

[source,properties]
----
jmix.core.exclude-beans = abc_FooService,abc_BarService
----

[[jmix.core.fetch-plans-config]]
=== jmix.core.fetch-plans-config

Путь к файлу конфигурации общего репозитория фетч-планов. См. дополнительную информацию в разделе xref:data-access:fetching.adoc#creating-fetch-plans[создание фетч-планов].

Например:
[source,properties]
----
jmix.core.fetch-plans-config = com/company/demo/fetch-plans.xml
----

[[jmix.core.temp-dir]]
=== jmix.core.temp-dir

Определяет каталог, в котором приложение может хранить временные файлы.

Используется фреймворком и дополнениями для некоторых операций, таких как экспорт/импорт и загрузка/скачивание.

Значение по умолчанию: `${user.dir}/.jmix/temp`

TIP: `${user.dir}` - это рабочий каталог пользователя (в котором была запущена JVM).

[[jmix.core.trigger-files-enabled]]
=== jmix.core.trigger-files-enabled

Включает обработку файлов-триггеров вызова бинов.

Файл-триггер - это файл, размещаемый в подкаталоге `triggers` <<jmix.core.temp-dir,временного каталога>> приложения. Имя файла состоит из двух частей, разделенных символом `#`: первая часть - это имя класса бина, вторая часть - это имя метода бина для вызова. Например: `io.jmix.core.Messages#clearCache`. Обработчик файлов-триггеров следит за появлением в папке новых файлов-триггеров, вызывает соответствующие методы, а затем удаляет файлы.

Значение по умолчанию: `true`

[[jmix.core.trigger-files-process-interval]]
=== jmix.core.trigger-files-process-interval

Период поиска и обработки файлов-триггеров в миллисекундах.

Значение по умолчанию: `5000`

[[jmix.core.web-host-name]]
=== jmix.core.web-host-name

Указывает имя хоста, на котором работает приложение.

Это свойство может использоваться различными подсистемами приложения. Если свойство необходимо для подсистемы, это должно быть указано в ее документации.

NOTE: Это свойство не влияет на фактический адрес сервера, на котором работает приложение. Для привязки к конкретному адресу используйте свойство Spring Boot `server.address`.

[[jmix.core.web-port]]
=== jmix.core.web-port

Указывает порт, на котором работает приложение.

Это свойство может использоваться различными подсистемами приложения. Если свойство необходимо для подсистемы, это должно быть указано в ее документации.

NOTE: Это свойство не влияет на фактический порт сервера, на котором работает приложение. Для привязки к конкретному порту используйте свойство Spring Boot `server.port`.

[[jmix.core.work-dir]]
=== jmix.core.work-dir

Определяет рабочий каталог, в котором приложение может хранить некоторые данные.

Используется xref:files:file-storage.adoc#local-fs[локальным файловым хранилищем], которое по умолчанию создает структуру файлового хранилища в своем подкаталоге `filestorage`.

Значение по умолчанию: `${user.dir}/.jmix/work`

TIP: `${user.dir}` - это рабочий каталог пользователя (в котором была запущена JVM).

[[cors]]
== CORS

Дополнительную информацию о CORS смотрите в разделе xref:rest:cors.adoc[CORS] дополнения Универсальный REST.

[[jmix.cors.allow-credentials]]
=== jmix.cors.allow-credentials

Определяет, поддерживаются ли учетные данные пользователя.

Значение по умолчанию: `false`

[[jmix.cors.allowed-headers]]
=== jmix.cors.allowed-headers

Список заголовков, которые могут быть указаны в pre-flight запросе и разрешены для использования во время фактического запроса. Специальное значение "*" позволяет фактическим запросам отправлять любой заголовок.

Значение по умолчанию: `*`

[[jmix.cors.allowed-methods]]
=== jmix.cors.allowed-methods

HTTP-методы, разрешенные для использования, например, "GET", "POST", "PUT" и т. д. Специальное значение "*" разрешает все методы.

Значение по умолчанию: `*`

[[jmix.cors.allowed-origins]]
=== jmix.cors.allowed-origins

Определяет список источников, для которых разрешены междоменные запросы. Используйте специальное значение `*` для всех источников.

Например:

[source,properties]
----
jmix.cors.allowed-origins = https://www.allowed1.com, https://www.allowed2.com
----

Значение по умолчанию: `*`

[[session]]
== Session

[[jmix.core.session.maximum-sessions-per-user]]
=== jmix.core.session.maximum-sessions-per-user

Максимальное количество xref:security:authentication.adoc#user-session[сессий] на пользователя.

Это свойство влияет на параметр {spring-security-api}/org/springframework/security/config/annotation/web/configurers/SessionManagementConfigurer.html#maximumSessions(int)[SessionManagementConfigurer.maximumSessions^] в Spring Security.

Значение по умолчанию: `100`

[[long-classpath-issues-windows]]
== Проблемы длинного classpath в Windows

[[io.jmix.flowui.read-class-path-from-temp-jar]]
=== io.jmix.flowui.read-class-path-from-temp-jar

В операционной системе Windows приложения с большим количеством путей в classpath могут столкнуться с проблемами отрисовки пользовательского интерфейса в Flow UI.

Jmix предоставляет свойство конфигурации для решения этой специфической для Windows проблемы:

[source,properties]
----
io.jmix.flowui.read-class-path-from-temp-jar = true
----

Значение по умолчанию: `true`

При включении:

* Автоматически активируется только в операционной системе Windows.
* Извлекает classpath из файла `MANIFEST.MF` внутри временного JAR-файла, созданного Gradle.
* Гарантирует, что Spring Boot правильно идентифицирует все записи classpath.
* Восстанавливает корректную загрузку ресурсов пользовательского интерфейса и отрисовку компонентов.

[[see-also]]
== Смотрите также

* xref:data-access:data-properties.adoc[Свойства доступа к данным]
* xref:data-access:cache.adoc[Кэш сущностей и запросов]
* xref:email:configuration.adoc[Настройка отправки электронной почты]
* xref:ldap:properties.adoc[Свойства LDAP]
* xref:pessimistic-lock:index.adoc[Пессимистическая блокировка]
* xref:reports:configuration.adoc[Настройка отчетов]
* xref:rest:app-properties.adoc[Свойства REST]
* xref:superset:properties.adoc[Свойства Superset]
// todo flowui search
// * xref:search:search-properties.adoc[Свойства поиска]
* xref:flow-ui:ui-properties.adoc[Свойства UI]
// todo flowui webdav
// * xref:webdav:configuration.adoc[Настройка WebDAV]