= Application Properties

[[core]]
== Core

[[jmix.core.anonymous-authentication-token-key]]
=== jmix.core.anonymous-authentication-token-key

A key that is used in Spring Security's {spring-security-api}/org/springframework/security/authentication/AnonymousAuthenticationProvider.html[AnonymousAuthenticationProvider^] and
{spring-security-api}/org/springframework/security/web/authentication/AnonymousAuthenticationFilter.html[AnonymousAuthenticationFilter^].

Default value: `de72c623-6d3d-458c-a187-c526de515ecd`

[[jmix.core.available-locales]]
=== jmix.core.available-locales

Defines the locales used in the application as a comma-separated list of locale codes. See xref:localization:message-bundles.adoc#setting-locales[Setting Up Locales] for more information.

For example:

[source,properties]
----
jmix.core.available-locales = en,de
----

[[jmix.core.conf-dir]]
=== jmix.core.conf-dir

Indicates the directory for configuration files that can be changed at runtime. It is used by the default implementation of the `Resources` interface to load resource files from the directory before searching in the classpath.

Default value: `${user.dir}/.jmix/conf`, where`${user.dir}` is the user working directory, that is, the directory where the JVM was started.

[IMPORTANT]
====
This directory is used by Hot Deploy and may be cleaned before startup by Jmix Studio or Gradle.
For details, see xref:studio:hot-deploy.adoc[Hot Deploy].
====

[[jmix.core.cross-data-store-reference-loading-batch-size]]
=== jmix.core.cross-data-store-reference-loading-batch-size

Defines the batch size when loading xref:data-model:entities.adoc#cross-data-store-ref[cross-datastore references] for a collection of entities.

Default value: `50`


[[jmix.core.default-file-storage]]
=== jmix.core.default-file-storage

Specifies a default file storage if xref:files:file-storage.adoc#multiple-fs[multiple file storages] are used in the application.

[[jmix.core.exclude-beans]]
=== jmix.core.exclude-beans

A comma-separated list of bean names to exclude from the Spring application context. It can be used to xref:modularity:extension.adoc#beans[override beans] already having `@Primary` annotations in some add-on.

For example:

[source,properties]
----
jmix.core.exclude-beans = abc_FooService,abc_BarService
----

[[jmix.core.fetch-plans-config]]
=== jmix.core.fetch-plans-config

A path to the shared fetch plan repository configuration file. See more information in the xref:data-access:fetching.adoc#creating-fetch-plans[Creating Fetch Plans] section.

For example:
[source,properties]
----
jmix.core.fetch-plans-config = com/company/demo/fetch-plans.xml
----

[[jmix.core.temp-dir]]
=== jmix.core.temp-dir

Defines the directory where the application can store temporary files.

Used by the framework and add-ons for operations like export/import and upload/download.

Default value: `${user.dir}/.jmix/temp`

TIP: `${user.dir}` is the user working directory (where JVM was started).

[[jmix.core.trigger-files-enabled]]
=== jmix.core.trigger-files-enabled

Enables processing of bean invocation trigger files.

The trigger file is a file that is placed in the `triggers` subdirectory of the application's <<jmix.core.temp-dir,temporary directory>>. The file name consists of two parts separated with the `#` symbol: the first part is the bean class, the second part is the method name of the bean to invoke. For example: `io.jmix.core.Messages#clearCache`. The trigger files handler monitors the folder for new trigger files, invokes the appropriate methods and then removes the files.

Default value: `true`

[[jmix.core.trigger-files-process-interval]]
=== jmix.core.trigger-files-process-interval

Period for searching and processing <<jmix.core.trigger-files-enabled,trigger files>> in milliseconds.

Default value: `5000`

[[jmix.core.web-host-name]]
=== jmix.core.web-host-name

Indicates the name of the host on which the application is running.

This property can be used by various application subsystems. If the property is needed for a subsystem, it should be mentioned in its documentation.

NOTE: This property doesn't affect the actual server address on which the application is running. To bind to a specific address, use the `server.address` Spring Boot property.

[[jmix.core.web-port]]
=== jmix.core.web-port

Indicates the port on which the application is running.

This property can be used by various application subsystems. If the property is needed for a subsystem, it should be mentioned in its documentation.

NOTE: This property doesn't affect the actual server port on which the application is running. To bind to a specific port, use the `server.port` Spring Boot property.

[[jmix.core.work-dir]]
=== jmix.core.work-dir

Defines the work directory where the application can store some data.

Used by the xref:files:file-storage.adoc#local-fs[Local File Storage] which by default creates the file storage structure in its `filestorage` subdirectory.

Default value: `${user.dir}/.jmix/work`

TIP: `${user.dir}` is the user working directory (where JVM was started).

[[cors]]
== CORS

See more information on CORS in the xref:rest:cors.adoc[CORS] section of the REST API add-on.

[[jmix.cors.allow-credentials]]
=== jmix.cors.allow-credentials

Whether user credentials are supported.

Default value: `false`

[[jmix.cors.allowed-headers]]
=== jmix.cors.allowed-headers

The list of headers that a pre-flight request can list as allowed for use during an actual request. The special value "*" allows actual requests to send any header.

Default value: `*`

[[jmix.cors.allowed-methods]]
=== jmix.cors.allowed-methods

The HTTP methods to allow, e.g. "GET", "POST", "PUT", etc.
The special value "*" allows all methods.

Default value: `*`

[[jmix.cors.allowed-origins]]
=== jmix.cors.allowed-origins

Defines a comma-separated list of origins for which cross-origin requests are allowed. Use the special value `*` for all origins.

For example:

[source,properties]
----
jmix.cors.allowed-origins = https://www.allowed1.com, https://www.allowed2.com
----

Default value: `*`

[[session]]
== Session

[[jmix.core.session.maximum-sessions-per-user]]
=== jmix.core.session.maximum-sessions-per-user

Maximum number of xref:security:authentication.adoc#user-session[sessions] per user.

This property affects the Spring Security's {spring-security-api}/org/springframework/security/config/annotation/web/configurers/SessionManagementConfigurer.html#maximumSessions(int)[SessionManagementConfigurer.maximumSessions^] parameter.

Default value: `100`

[[long-classpath-issues-windows]]
== Long Classpath Issues on Windows

[[io.jmix.flowui.read-class-path-from-temp-jar]]
=== io.jmix.flowui.read-class-path-from-temp-jar

On Windows OS, applications with extensive classpaths may encounter UI rendering issues in Flow UI.

Jmix provides a configuration property to resolve this Windows-specific issue:

[source,properties]
----
io.jmix.flowui.read-class-path-from-temp-jar = true
----

Default value: `true`

When enabled:

* Automatically activates on Windows OS only.
* Extracts the classpath from the `MANIFEST.MF` file within Gradle's temporary JAR.
* Ensures Spring Boot correctly identifies all classpath entries.
* Restores proper UI resource loading and component rendering.

[[see-also]]
== See Also

* xref:data-access:data-properties.adoc[Data Access Properties]
* xref:data-access:cache.adoc[Entity and Query Cache]
* xref:email:configuration.adoc[Email Sending Configuration]
* xref:ldap:properties.adoc[LDAP Properties]
* xref:pessimistic-lock:index.adoc[Pessimistic Locking]
* xref:reports:configuration.adoc[Reports Configuration]
* xref:rest:app-properties.adoc[REST Properties]
* xref:superset:properties.adoc[Superset Properties]
// todo flowui search
// * xref:search:search-properties.adoc[Search Properties]
* xref:flow-ui:ui-properties.adoc[UI Properties]
// todo flowui webdav
// * xref:webdav:configuration.adoc[WebDAV Configuration]