= 介绍
:page-aliases: quick-start:index.adoc

欢迎使用 https://www.jmix.cn[Jmix^] 文档！

[[whats-jmix]]
== 什么是 Jmix？

*Jmix* 是企业级 Web 应用程序开发的高级别全栈框架。配备了先进的开发工具和丰富的功能模块。

Jmix 旨在快速开发具有大型数据模型和复杂 UI 且面向组织内部用户的 Web 应用程序。这种类型的应用程序主要有：增删改查、网站的管理端 UI、业务自动化工具、CRM 或者 ERP 类型的系统。以及任何需要在成百上千的页面中处理几十或上百个互相关联的实体，而主要使用标准 UI 组件（如各种字段、表单和表格）的系统。

Jmix 基于 Spring Boot，这是企业级 Java web 应用程序的事实标准。也就是说，除了使用 Jmix 提供的功能之外，还能以最小的配置使用很多第三方库和框架。

Jmix 是一个开源框架，开发者可以完全掌控使用 Jmix 开发的应用程序。使用 Jmix 构建的应用程序完全由开发者所有，无供应商锁定或专有限制，可以根据需要进行自由定制、部署和扩展。

*Jmix Studio* 是 IntelliJ IDEA 的一个插件，可以在整个应用程序开发周期为开发者提供帮助：创建和配置项目、定义数据模型、生成数据库脚本以及在可视化编辑器开发 UI 视图。更是为 Jmix 项目提供了代码的高级导航、自动完成和提示功能。

[[getting-started]]
== 开始使用

如果之前没有接触过 Jmix，请先观看我们的 https://www.bilibili.com/video/BV1TV4y1U7Dc[快速入门^] 视频，花 15 分钟了解下如何使用 Jmix 构建应用程序。

*Jmix AI 助手* 可以在 https://ai-assistant.jmix.io[ai-assistant.jmix.io^] 使用，也可以在 xref:studio:ai-assistant.adoc[IDE] 中使用，能咨询任何关于 Jmix 和应用程序开发的问题。

本文档包含使用 Jmix 开发需要了解的所有内容：

* xref:concepts:index.adoc[] 章节介绍了 Jmix 的核心原理和概念。

* xref:guides.adoc[Guides] 是关于如何使用 Jmix 各种功能的详细说明和解释的综合资源。

* xref:studio:index.adoc[] 章节详细介绍了 Jmix Studio 的功能和安装选项。

* 从 xref:data-model:index.adoc[] 至 xref:deployment:index.adoc[] 章节包含参考信息和使用指南，可以帮助使用 Jmix 开发应用程序。

* xref:ROOT:add-ons.adoc[] 章节介绍了项目中能用到的附加模块功能。

https://demo.jmix.io/ui-samples[Jmix UI 示例^] 应用程序中有关于 UI 的大量示例。

其他 https://www.jmix.io/live-demo[在线示例^] 提供了 Jmix 中不同功能的示例应用。
