= Introduction
:page-aliases: quick-start:index.adoc

Welcome to the https://www.jmix.io[Jmix^] documentation!

[[whats-jmix]]
== What is Jmix?

*Jmix* is a high-level full-stack framework for enterprise web applications. It comes with advanced tooling and a rich set of functional modules.

Jmix is intended for fast development of web applications with a large data model and complex UI aimed at internal users of an organization. There are various types of applications in this category, including just CRUD, an admin UI for a website, a business automation tool, a CRM, or an ERP-class system. Anything that involves working with tens or hundreds of interconnected entities in hundreds or thousands of screens, while using mostly standard UI components like fields, forms, and tables.

Jmix is based on Spring Boot, which is a de facto standard for creating enterprise Java web applications. It means that you can use many third-party libraries and frameworks with minimal configuration, in addition to the functionality provided by Jmix.

Jmix is an open-source framework, giving developers full control over their applications. Applications built with Jmix are owned entirely by the developers, with no vendor lock-in or proprietary restrictions, ensuring complete freedom to customize, deploy, and scale as needed.

*Jmix Studio* is a plugin for IntelliJ IDEA that helps you at all stages of application development: creating and configuring a project, defining the data model, generating database migration scripts, and developing UI views in a visual editor. It provides advanced navigation, code completion, and inspections specific to Jmix projects.

[[getting-started]]
== Getting Started

If you are new to Jmix, check out the https://www.youtube.com/watch?v=MKDZU4PyUTY[Jmix Introduction for Developers^] video.

Use the *Jmix AI assistant* at https://ai-assistant.jmix.io[ai-assistant.jmix.io^] and in xref:studio:ai-assistant.adoc[your IDE] for any questions about Jmix and application development.

The documentation contains everything you need to know for developing with Jmix:

* The xref:concepts:index.adoc[] section explains the core principles and concepts of Jmix.

* xref:guides.adoc[Guides] are comprehensive resources that provide step-by-step instructions and explanations on how to use various features of Jmix.

* xref:studio:index.adoc[] section gives you detailed information about Jmix Studio features and installation options.

* The top-level sections from xref:data-model:index.adoc[] to xref:deployment:index.adoc[] contain reference information and how-to guides that will help you develop applications with Jmix.

* The xref:ROOT:add-ons.adoc[] section describes additional modules that can be used in your project.

https://demo.jmix.io/ui-samples[Jmix UI Samples^] application includes a large collection of examples related to UI.

Other https://www.jmix.io/live-demo[online demo^] applications provide examples of the various features available in Jmix.