= Введение
:page-aliases: quick-start:index.adoc

Добро пожаловать в документацию https://www.jmix.ru[Jmix^]!

[[whats-jmix]]
== Что такое Jmix?

*Jmix* – это высокоуровневый фулл-стек фреймворк для разработки корпоративных веб-приложений. Он предлагает развитый инструментарий и богатый набор функциональных модулей.

Jmix предназначен для быстрой разработки веб-приложений с большой моделью данных и сложным UI, ориентированным на внутренних пользователей организации. В этой категории существует множество типов приложений, включая простые CRUD, админ-UI для веб-сайтов, инструменты автоматизации бизнеса, CRM-системы или системы класса ERP. Все, что предполагает работу с десятками или сотнями взаимосвязанных сущностей на сотнях или тысячах экранов, при этом в основном используя стандартные компоненты пользовательского интерфейса, такие как поля, формы и таблицы.

Jmix основан на Spring Boot, что является фактически стандартом для разработки корпоративных веб-приложений на Java. Это означает, что вы можете использовать множество сторонних библиотек и фреймворков после минимальной конфигурации в дополнение к функционалу самого Jmix.

Jmix является фреймворком с открытым исходным кодом. Приложения, созданные с помощью Jmix, полностью принадлежат разработчикам, без зависимости от поставщика или проприетарных ограничений, что обеспечивает полную свободу в настройке, развертывании и масштабировании по мере необходимости.

*Jmix Studio* – это плагин для Java IDE (IntelliJ IDEA или OpenIDE), который помогает на всех этапах разработки приложений: создание и конфигурация проекта, определение модели данных, генерация скриптов для миграции базы данных, разработка UI экранов в визуальном редакторе. Он предоставляет продвинутую навигацию, автодополнение кода и инспекции, специфичные для Jmix-проектов.

[[getting-started]]
== Начало работы

Если вы новичок в Jmix, посмотрите видео https://www.youtube.com/watch?v=MKDZU4PyUTY[Jmix Introduction for Developers^].

Используйте *Jmix AI assistant* на https://ai-assistant.jmix.io[ai-assistant.jmix.io^] и в xref:studio:ai-assistant.adoc[вашей IDE] для любых вопросов о Jmix и разработке приложений.

В данной документации:

* Раздел xref:concepts:index.adoc[] рассказывает об основных принципах и возможностях Jmix.

* Раздел xref:guides.adoc[Руководства] содержит пошаговые инструкции и объяснения по использованию различных функций Jmix.

* В разделе xref:studio:index.adoc[Использование Studio] детально представлены особенности Jmix Studio и варианты установки.

* Корневые разделы от xref:data-model:index.adoc[Модели данных] до xref:deployment:index.adoc[Развертывания] содержат справочную информацию и руководства, помогающие при разработке приложений любого типа.

* Раздел xref:ROOT:add-ons.adoc[Дополнения] описывает дополнительные модули, которые вы можете использовать в своем проекте.

Приложение https://demo.jmix.ru/ui-samples[Jmix UI Samples^] включает в себя большую коллекцию примеров работы с пользовательским интерфейсом.

Другие https://www.jmix.ru/live-demo[онлайн демо^] приложения предоставляют примеры использования различных возможностей Jmix.