= Миграция с Classic UI

Вследствие несовместимости между Classic и Flow UI автоматическое обновление с Jmix 1.x Classic UI до Jmix {page-component-display-version} невозможно.

Есть два метода ручной миграции. Первый из них более универсальный и применим к проектам, использующим как Jmix 1.5, так и 1.6, но он также более трудоемкий. Этот метод подробно описан в https://forum.jmix.io/t/jmix-2-x-upgrade-a-practical-guide-for-rent-your-stuff-example/4920[руководстве на форуме^].

Второй метод основан на том, что в составе Jmix 1.5 есть экспериментальная реализация Flow UI, и Studio может автоматически мигрировать проекты, использующие Flow UI, с версии 1.5 на последнюю версию 2.x. Этот метод может использоваться только для проектов, основанных на Jmix 1.5.

Ниже в данном разделе приведена инструкция по апгрейду приложения на основе Jmix 1.5 Classic UI используя второй метод.

[[converting-project-to-flow-ui]]
== Преобразование в проект на Flow UI

Сначала необходимо удалить Classic UI из проекта и адаптировать структуру проекта и скрипты сборки к Flow UI.

. Откройте проект на Classic UI в IDE.
+
Далее мы будем называть этот проект "мигрирующим".

. Создайте новый проект на последней версии Jmix 1.5 в другом каталоге, используя шаблон `Full-Stack Application with Incubating FlowUI`. Выберите то же имя и базовый пакет, что и в мигрирующем проекте.
+
Далее мы будем называть этот проект "созданным".

. Скопируйте следующие файлы из корневого каталога созданного проекта в мигрирующий:
+
[source,text]
----
.gitignore
build.gradle
package.json
tsconfig.json
types.d.ts
vite.config.ts
----
+
Здесь и далее производите копирование, выполнив команду *Copy* в окне инструментов *Project* исходного проекта, а затем команду *Paste* на соответствующем узле целевого проекта.

. В мигрирующем проекте удалите следующие каталоги (выключите *Safe delete* чтобы избежать бесполезных предупреждений от IDE):
.. `src/main/java/<base_package>/screen`
.. `src/main/resources/<base_package>/screen`
.. `src/main/themes`
.. `src/main/resources/<base_package>/theme`

. Скопируйте следующие каталоги из созданного проекта в мигрирующий:

.. `frontend`
.. `src/main/java/<base_package>/view`
.. `src/main/resources/<base_package>/view`
.. `src/main/resources/META-INF`

. В файле `application.properties` мигрирующего проекта:
.. Удалите свойства `++jmix.ui.*++`.
.. Скопируйте свойства `++jmix.flowui.*++`, `++ui.*++`, `++vaadin.*++` из созданного проекта в мигрирующий.

. Скопируйте файл `src/main/resources/<base_package>/menu.xml` из созданного проекта в мигрирующий и перезапишите существующий файл.

. Откройте файл `src/main/resources/<base_package>/messages_en.properties` мигрирующего проекта и удалите сообщения `++<base_package>.screen.*++` и `++<base_package>/menu.application++`. Скопируйте сообщения `++<base_package>.view.*++` и `++<base_package>/menu.application.title++` из такого же файла созданного проекта.

. Скопируйте классы `FullAccessRole` и `UiMinimalRole` пакета `<base_package>.security` из созданного проекта в мигрирующий.

. В других имеющихся ролях мигрирующего проекта удалите аннотации `io.jmix.securityui.role.annotation.MenuPolicy` и `io.jmix.securityui.role.annotation.ScreenPolicy`.

. Добавьте следующий код в заголовок главного класса приложения:
+
[source,java]
----
@Push
@Theme(value = "<project_name>")
@PWA(name = "<project_name>", shortName = "<project_name>")
class ... implements AppShellConfigurator
----
+
Например:
+
[source,java]
----
// ...
import com.vaadin.flow.component.page.AppShellConfigurator;
import com.vaadin.flow.component.page.Push;
import com.vaadin.flow.server.PWA;
import com.vaadin.flow.theme.Theme;
// ...

@Push
@Theme(value = "onboarding")
@PWA(name = "Onboarding", shortName = "Onboarding")
@SpringBootApplication
public class OnboardingApplication implements AppShellConfigurator {
----

. Запустите команду *Reload All Gradle Projects* в окне инструментов *Gradle* чтобы заново импортировать проект в IDE.

. Обновите проект до версии Jmix {page-component-display-version}, используя стандартную xref:studio:project.adoc#upgrading-project[процедуру апгрейда проекта] в Studio.

. Добавьте в проект необходимые дополнения используя Marketplace или руководствуясь инструкциями по ручной установке этих дополнений.

. Выполните команду *Build* -> *Build Project* и устраните ошибки компиляции, если они возникнут.

. Запустите приложение.

.. Studio отбразит окно *Liquibase Root Changelog Check* и предложит удалить команды `include`, ссылающиеся на модули, которых нет в проекте Jmix {page-component-display-version} Flow UI (например, `/io/jmix/uidata/liquibase/changelog.xml`). Примите предложенные изменения и продолжите.

.. Studio создаст Liquibase changelog с командами для удаления таблиц `UI_FILTER_CONFIGURATION`, `UI_SETTING` и `UI_TABLE_PRESENTATION`. Эти команды следует сохранить и применить, так как данные таблицы не содержат никаких полезных данных для Flow UI.

.. Если в базе данных есть таблицы дополнений, отсутствующих в Jmix {page-component-display-version}, убедитесь что эти таблицы не будут удалены. Либо нажмите *Remove from Changelog* -> *Remove and Ignore* для соответствующего узла с командой `dropTable` в окне генерации файлов Liquibase changelog, либо отмените процесс и добавьте свойство `main.datasource.studio.liquibase.exclude-prefixes` перед тем как запускать приложение снова. Например:
+
[source,properties]
----
main.datasource.studio.liquibase.exclude-prefixes = FOO_
----

После старта приложения вы сможете войте в приложение и открыть стандартные экраны управления пользователями.

[[developing-views]]
== Разработка новых экранов

На данный момент вы получили работающее приложение, основанное на Jmix {page-component-display-version}. Его пользовательский интерфейс включает в себя только экраны, предоставляемые шаблоном нового приложения: `LoginView`, `MainView`, `UserListView` и `UserDetailView`.

На следующем шаге можно создать CRUD-экраны для объектов вашей модели данных, используя xref:studio:view-wizard.adoc[].

В результате у вас получится приложение со старой моделью данных и бэкенд-логикой, а также с новым пользовательским интерфейсом, который позволяет управлять данными с помощью стандартных экранов списка/деталей. Теперь вам нужно кастомизировать пользовательский интерфейс, используя xref:flow-ui:index.adoc[Flow UI] API и его набор компонентов.
