= Свойства Tabbed Application Mode

[[jmix.tabmod.max-tab-count]]
== jmix.tabmod.max-tab-count

Определяет максимальное количество вкладок, которые можно открыть в главном экране приложения. Значение `0` отключает это ограничение.

Значение по умолчанию: `20`

[[jmix.tabmod.show-breadcrumbs]]
== jmix.tabmod.show-breadcrumbs

Определяет, отображаются ли хлебные крошки, которые обычно показываются в верхней части рабочей области главного экрана.

Значение по умолчанию: `true`

[[jmix.tabmod.multiple-open]]
== jmix.tabmod.multiple-open

Определяет, должен ли экран открываться несколько раз из главного меню, если у него отсутствует аннотация `@MultipleOpen`.

Значение по умолчанию: `false`

[[jmix.tabmod.default-view-closeable]]
== jmix.tabmod.default-view-closeable

Определяет, можно ли закрыть экран, заданный в xref:flow-ui:ui-properties.adoc#jmix.ui.default-view-id[jmix.ui.default-view-id], стандартными операциями, такими как кнопка закрытия вкладки и действия закрытия вкладок.

Значение по умолчанию: `true`

[[jmix.tabmod.open-next-tab-shortcut]]
== jmix.tabmod.open-next-tab-shortcut

Определяет xref:flow-ui:keyboard-shortcuts.adoc[комбинацию клавиш], используемую для перехода к следующей вкладке. Например:

[source,properties]
----
jmix.tabmod.open-next-tab-shortcut=CONTROL-SHIFT-ARROW_RIGHT
----

[[jmix.tabmod.open-previous-tab-shortcut]]
== jmix.tabmod.open-previous-tab-shortcut

Определяет xref:flow-ui:keyboard-shortcuts.adoc[комбинацию клавиш], используемую для перехода к предыдущей вкладке. Например:

[source,properties]
----
jmix.tabmod.open-previous-tab-shortcut=CONTROL-SHIFT-ARROW_LEFT
----

[[jmix.tabmod.close-this-tab-shortcut]]
== jmix.tabmod.close-this-tab-shortcut

Определяет xref:flow-ui:keyboard-shortcuts.adoc[комбинацию клавиш], используемую для выполнения действия xref:main-tab-sheet.adoc#tabmod_closeThisTab[tabmod_closeThisTab].

[[jmix.tabmod.close-other-tabs-shortcut]]
== jmix.tabmod.close-other-tabs-shortcut

Определяет xref:flow-ui:keyboard-shortcuts.adoc[комбинацию клавиш], используемую для выполнения действия xref:main-tab-sheet.adoc#tabmod_closeOtherTabs[tabmod_closeOtherTabs].

[[jmix.tabmod.close-all-tabs-shortcut]]
== jmix.tabmod.close-all-tabs-shortcut

Определяет xref:flow-ui:keyboard-shortcuts.adoc[комбинацию клавиш], используемую для выполнения действия xref:main-tab-sheet.adoc#tabmod_closeAllTabs[tabmod_closeAllTabs].
