= Migration to Tabbed Mode

When the Tabbed Application Mode add-on is added, Vaadin's navigation functionality is disabled. As a result, navigation events like `BeforeEnterEvent` and `AfterNavigationEvent` are no longer sent to views. Consequently, you may need to refactor views that rely on these events.

To simplify refactoring, the base `View` class provides the `processBeforeEnterInternal()` method, which accepts a `BeforeEnterEvent` as an argument.

[[regular-views]]
== Regular Views

For example, consider a view that has a mandatory route parameter used to find the data required for further operations:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/roleassignment/RoleAssignmentView.java[tags=roleAssignmentViewBegin;findUser;roleAssignmentViewEnd]
----
<1> View route includes a mandatory parameter.
<2> Obtains route parameters and uses them to find a user instance.
<3> Gets a particular route parameter and loads a user instance.

To make this view work within a tab, override the `processBeforeEnterInternal()` method and call the `findUser` method inside it:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/roleassignment/RoleAssignmentView.java[tags=findUserRefactored]
----

[[detail-views]]
== Detail Views

A detail view provides two methods for initializing the edited entity:

* `setupEntityToEdit(String)` - invoked when a detail view is opened via navigation, and the edited entity is loaded using its `ID`, passed as a route parameter.

* `setupEntityToEdit(Entity)` - invoked when a detail view is opened in a dialog window, and the edited entity is passed directly.

Consider an example where your detail view has custom code that initializes the edited entity based on the route parameter:

[source,java,indent=0]
----
@Override
protected void initExistingEntity(String serializedEntityCode) {
    String code = urlParamSerializer.deserialize(String.class, serializedEntityCode);
    ResourceRole roleByCode = roleRepository.findRoleByCode(code);

    ResourceRoleModel resourceRoleModel = roleModelConverter.createResourceRoleModel(roleByCode);

    childRolesDc.mute();
    childRolesDc.setItems(loadChildRoleModels(resourceRoleModel));
    childRolesDc.unmute();

    ResourceRoleModel merged = dataContext.merge(resourceRoleModel);
    roleModelDc.setItem(merged);
}
----

In the example above, the actual edited entity instance is obtained by converting the data stored in the database, which is loaded using the `id` passed as a route parameter. Because this view is not intended to be opened in a dialog, it lacks corresponding code for handling a directly passed entity instance. To enable this view to function within a tab, override the `setupEntityToEdit()` method and provide an empty implementation:

[source,java,indent=0]
----
@Override
protected void setupEntityToEdit(ResourceRoleModel entityToEdit) {
    // do nothing
}
----