= Открытие экранов

Экраны открываются из главного экрана через xref:flow-ui:actions/standard-actions.adoc[стандартные действия] либо программно из других экранов.

В этом разделе описывается, как открывать экраны программно в коде приложения.

[[using-viewbuilders-bean]]
== Использование бина ViewBuilders

Бин `ViewBuilders` предоставляет fluent-интерфейс для открытия экранов. Его терминальные методы предоставляют доступ к экземпляру открытого экрана. Он позволяет передавать входные параметры непосредственно в экземпляр экрана и добавлять слушатели для получения результатов из открываемого экрана после его закрытия.

Чтобы открыть экран, инжектируйте бин `ViewBuilders` и вызовите метод `view()`, передав ему текущий экран и класс или идентификатор открываемого экрана. Затем вызовите терминальный метод `open()`:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/viewopeningsandbox/ViewOpeningSandboxView.java[tags=viewBuilders;openView]
----

[[opening-detail-views]]
=== Открытие экранов деталей

В большинстве случаев вы можете открывать экраны деталей с помощью стандартных действий, таких как xref:flow-ui:actions/list-actions.adoc#list_create[list_create]. Рассмотрим примеры, когда можно использовать API `ViewBuilders` напрямую, чтобы открыть экран деталей из xref:flow-ui:actions.adoc[действия] или обработчика xref:flow-ui:vc/components/button.adoc#ClickEvent[кнопки].

Чтобы создать новый экземпляр сущности в экране деталей, вызовите метод `newEntity()`. Например:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/viewopeningsandbox/ViewOpeningSandboxView.java[tags=viewBuilders;openDetailViewToCreate]
----

Чтобы отредактировать существующую сущность в экране деталей, используйте метод `editEntity()`, передав редактируемый экземпляр сущности:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/viewopeningsandbox/ViewOpeningSandboxView.java[tags=viewBuilders;openDetailViewToEdit]
----

В приведенных выше примерах экран деталей создаст или обновит сущность, но вызывающий экран не получит обновленный экземпляр.

Если вам нужно отредактировать сущность, отображаемую компонентом списка данных (например, xref:flow-ui:vc/components/dataGrid.adoc[dataGrid]), используйте следующий способ вызова. Он более лаконичен и автоматически обновляет `dataGrid`:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/viewopeningsandbox/ViewOpeningSandboxView.java[tags=usersDataGrid;viewBuilders;openDetailViewDataGridToEdit]
----

Чтобы создать новый экземпляр сущности и открыть его экран деталей, просто вызовите метод `newEntity()`:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/viewopeningsandbox/ViewOpeningSandboxView.java[tags=usersDataGrid;viewBuilders;openDetailViewDataGridToCreate]
----

Используйте ту же лаконичную форму, если хотите создать или отредактировать сущность, установленную в поле:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/viewopeningsandbox/ViewOpeningSandboxView.java[tags=userPicker;viewBuilders;openDetailViewFieldToEdit]
----

`ViewBuilders` предоставляет множество методов для задания необязательных параметров открываемого экрана. Например, следующий код создает новый экземпляр сущности, инициализирует его, а затем редактирует в экране деталей, открытом в виде диалогового окна:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/viewopeningsandbox/ViewOpeningSandboxView.java[tags=viewBuilders;openDetailViewDialog]
----

[[opening-lookup-views]]
=== Открытие экранов выбора

Рассмотрим несколько примеров работы с экранами выбора. Как и экраны деталей, их обычно открывают с помощью стандартных действий, таких как xref:flow-ui:actions/entity-picker-actions.adoc#entity_lookup[entity_lookup]. Приведенные ниже примеры демонстрируют использование API ViewBuilders, которое может быть полезно, если вы не используете стандартные действия.

Чтобы выбрать сущности из экрана списка, откройте экран с помощью метода `lookup()`:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/viewopeningsandbox/ViewOpeningSandboxView.java[tags=viewBuilders;openLookupView]
----

Если вам нужно установить выбранную сущность в поле, используйте более лаконичную форму:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/viewopeningsandbox/ViewOpeningSandboxView.java[tags=userPicker;viewBuilders;openLookupViewSelect]
----

Используйте ту же лаконичную форму, если хотите добавить выбранную сущность в компонент списка данных, например `dataGrid`:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/viewopeningsandbox/ViewOpeningSandboxView.java[tags=usersDataGrid;viewBuilders;openLookupViewDataGrid]
----

Аналогично экранам деталей, используйте методы билдера для задания необязательных параметров открываемого экрана. Например, следующий код демонстрирует выбор сущности `User` с помощью определенного экрана выбора, открытого в виде диалогового окна:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/viewopeningsandbox/ViewOpeningSandboxView.java[tags=viewBuilders;openLookupViewDialog]
----

[[passing-parameters-to-views]]
== Передача параметров в экраны

Если вам нужно передать параметры в открываемый экран, добавьте обработчик конфигурации экрана с помощью метода `withViewConfigurer`.

Рассмотрим следующий экран:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/fancymessage/FancyMessageView.java[tags=fancyMessageViewFull]
----

В обработчике `ViewConfigurer` вы можете вызывать публичные сеттеры открываемого экрана:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/viewopeningsandbox/ViewOpeningSandboxView.java[tags=viewBuilders;openViewWithParameters]
----

[[executing-code-after-close]]
== Выполнение кода после закрытия и возврат значений

Каждый экран отправляет xref:flow-ui:views/view-events.adoc#after-close-event[AfterCloseEvent] при закрытии. При использовании `ViewBuilders` вы можете предоставить слушатель с помощью метода `withAfterCloseListener()`:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/viewopeningsandbox/ViewOpeningSandboxView.java[tags=viewBuilders;notifications;openViewWithCloseListener]
----

Объект события предоставляет информацию о том, как был закрыт экран. Эту информацию можно получить двумя способами:

* Проверив, был ли экран закрыт с одним из стандартных результатов, определенных перечислением `StandardOutcome`.

* Получив объект `CloseAction`.

Первый подход проще, второй предоставляет большую гибкость.

Рассмотрим первый подход: закрытие экрана со стандартным результатом и его проверку в вызывающем коде. Вот экран, который мы будем открывать:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/other/OtherView.java[tags=otherViewFull;!closeAction]
----
<1> Нажатие кнопки *Save* устанавливает состояние результата и закрывает экран со значением перечисления `StandardOutcome.SAVE`.
<2> Нажатие кнопки *Close* закрывает экран со значением `StandardOutcome.CLOSE`.

В слушателе `AfterCloseEvent` вы можете использовать метод `closedWith()` события, чтобы проверить, как был закрыт экран. При необходимости вы также можете прочитать значение результата:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/viewopeningsandbox/ViewOpeningSandboxView.java[tags=viewBuilders;notifications;openViewWithResult]
----

[[using-custom-close-action]]
=== Использование пользовательского CloseAction

Другой способ возвращать значения из экранов — использование пользовательских реализаций `CloseAction`. Перепишем предыдущий пример с использованием следующего класса действия:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/action/MyCloseAction.java[tags=myCloseAction]
----

Затем мы можем использовать это действие при закрытии экрана:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/other/OtherView.java[tags=otherViewFull;!resultField]
----
<1> Нажатие кнопки *Ok* создает пользовательское действие закрытия и устанавливает в нем значение результата.
<2> Нажатие кнопки *Close* закрывает экран со стандартным действием, предоставляемым фреймворком.

В слушателе `AfterCloseEvent` вы можете получить `CloseAction` из события и прочитать значение результата:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/viewopeningsandbox/ViewOpeningSandboxView.java[tags=viewBuilders;notifications;openViewWithCloseAction]
----

Как видите, когда значения возвращаются через пользовательский `CloseAction`, вызывающему коду не нужно знать класс открытого экрана, поскольку он не вызывает методы конкретного контроллера экрана. Поэтому экран может быть создан по своему строковому идентификатору.

[[view-inference-conventions]]
== Соглашения о выводе экранов

Экран выбора или экран деталей можно открыть, указав класс сущности.

При вызове `viewBuilders.lookup(this, SomeEntity.class)` фреймворк определяет экран выбора в следующем порядке порядке:

. Экран, помеченный аннотацией `@PrimaryLookupView(SomeEntity.class)`.
. Экран с идентификатором `SomeEntity.lookup`.
. Экран, помеченный аннотацией `@PrimaryListView(SomeEntity.class)`.
. Экран с идентификатором `SomeEntity.list`.

При вызове `viewBuilders.detail(this, SomeEntity.class)` фреймворк определяет экран деталей в следующем порядке:

. Экран, помеченный аннотацией `@PrimaryDetailView(SomeEntity.class)`.
. Экран с идентификатором `SomeEntity.detail`.
