= Opening Views

You can open views from the main view through xref:flow-ui:actions/standard-actions.adoc[standard actions] when working with list and detail entity views, or programmatically from another view.

The following section describes how to open views programmatically in your application code.

[[using-viewbuilders-bean]]
== Using ViewBuilders Bean

The `ViewBuilders` bean provides a fluent interface for opening views. Its terminal methods give access to the opened view instance. It allows you to pass input parameters directly to the view instance and add listeners for getting results back from the opened view after it is closed.

To open a view, inject the `ViewBuilders` bean and invoke the `view()` method, passing the current view and either the opened view's class or ID to it. Then, invoke the `open()` terminal method:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/viewopeningsandbox/ViewOpeningSandboxView.java[tags=viewBuilders;openView]
----

[[opening-detail-views]]
=== Opening Detail Views

In most cases, you can open detail views using standard actions such as xref:flow-ui:actions/list-actions.adoc#list_create[list_create]. Let’s look at the examples when you can use the `ViewBuilders` API directly to open a detail view from an xref:flow-ui:actions.adoc[action] or xref:flow-ui:vc/components/button.adoc#ClickEvent[button] handler.

To create a new entity instance in a detail view, invoke the `newEntity()` method. For example:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/viewopeningsandbox/ViewOpeningSandboxView.java[tags=viewBuilders;openDetailViewToCreate]
----

To edit an existing entity in a detail view, use the `editEntity()` method, providing the entity instance to edit:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/viewopeningsandbox/ViewOpeningSandboxView.java[tags=viewBuilders;openDetailViewToEdit]
----

In the examples above, the detail view will create or update the entity, but the caller view will not receive the updated instance.

If you need to edit an entity displayed by a list data view component (for example, a xref:flow-ui:vc/components/dataGrid.adoc[dataGrid]), use the following invocation method. It's more concise and automatically updates the `dataGrid`:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/viewopeningsandbox/ViewOpeningSandboxView.java[tags=usersDataGrid;viewBuilders;openDetailViewDataGridToEdit]
----

To create a new entity instance and open its detail view, just call the `newEntity()` method on the builder:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/viewopeningsandbox/ViewOpeningSandboxView.java[tags=usersDataGrid;viewBuilders;openDetailViewDataGridToCreate]
----

Use the same concise form if you want to create or edit an entity set to a field:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/viewopeningsandbox/ViewOpeningSandboxView.java[tags=userPicker;viewBuilders;openDetailViewFieldToEdit]
----

`ViewBuilders` offers many methods for setting optional parameters of the opened view. For example, the following code creates a new entity, initializes it, and then edits it in a detail view that's opened as a dialog:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/viewopeningsandbox/ViewOpeningSandboxView.java[tags=viewBuilders;openDetailViewDialog]
----

[[opening-lookup-views]]
=== Opening Lookup Views

Let’s look at some examples of working with lookup views. As with detail views, you typically open them using standard actions like xref:flow-ui:actions/entity-picker-actions.adoc#entity_lookup[entity_lookup]. The examples below demonstrate using the ViewBuilders API, which can be helpful if you don't use standard actions.

To select entities from a list view, open the view using the `lookup()` method:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/viewopeningsandbox/ViewOpeningSandboxView.java[tags=viewBuilders;openLookupView]
----

If you need to set the looked up entity to a field, use the more concise form:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/viewopeningsandbox/ViewOpeningSandboxView.java[tags=userPicker;viewBuilders;openLookupViewSelect]
----

Use the same concise form if you want to add the looked-up entity to a list data component, such as a `dataGrid`, for example:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/viewopeningsandbox/ViewOpeningSandboxView.java[tags=usersDataGrid;viewBuilders;openLookupViewDataGrid]
----

Similar to detail views, use builder methods to set optional parameters for the opened view. For example, the following code demonstrates how to look up a `User` entity using a particular lookup view opened as a dialog:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/viewopeningsandbox/ViewOpeningSandboxView.java[tags=viewBuilders;openLookupViewDialog]
----

[[passing-parameters-to-views]]
== Passing Parameters to Views

If you need to pass parameters to the opened view, add a view configurer handler using the `withViewConfigurer` method.

Consider the following view:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/fancymessage/FancyMessageView.java[tags=fancyMessageViewFull]
----

In the `ViewConfigurer` handler, you can invoke public setters of the opened view:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/viewopeningsandbox/ViewOpeningSandboxView.java[tags=viewBuilders;openViewWithParameters]
----

[[executing-code-after-close]]
== Executing Code after Close and Returning Values

Each view sends xref:flow-ui:views/view-events.adoc#after-close-event[AfterCloseEvent] upon closing. When using `ViewBuilders`, you can provide a listener using the `withAfterCloseListener()` method:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/viewopeningsandbox/ViewOpeningSandboxView.java[tags=viewBuilders;notifications;openViewWithCloseListener]
----

The event object provides information about how the view was closed. This information can be accessed in two ways:

* By testing whether the view was closed with one of the standard outcomes defined by the `StandardOutcome` enum.

* By retrieving the `CloseAction` object.

The former approach is simpler, while the latter offers greater flexibility.

Let's examine the first approach: closing a view with a standard outcome and testing it in the calling code. Here is the view we will invoke:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/other/OtherView.java[tags=otherViewFull;!closeAction]
----
<1> Clicking the *Save* button sets a result state and closes the view with the `StandardOutcome.SAVE` enum value.
<2> Clicking the *Close* button closes the view with `StandardOutcome.CLOSE`.

In the `AfterCloseEvent` listener, you can use the `closedWith()` method of the event to check how the view was closed. If needed, you can also read the result value:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/viewopeningsandbox/ViewOpeningSandboxView.java[tags=viewBuilders;notifications;openViewWithResult]
----

[[using-custom-close-action]]
=== Using Custom CloseAction

Another way to return values from views is by using custom `CloseAction` implementations. Let’s rewrite the previous example to use the following action class:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/action/MyCloseAction.java[tags=myCloseAction]
----

We can then use this action when closing the view:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/other/OtherView.java[tags=otherViewFull;!resultField]
----
<1> Clicking the *Ok* button creates a custom close action and sets the result value within it.
<2> Clicking the *Close* button closes the view with a default action provided by the framework.

In the `AfterCloseEvent` listener, you can retrieve the `CloseAction` from the event and read the result value:

[source,java,indent=0]
----
include::example$/tabbedmode-ex1/src/main/java/com/company/demo/view/viewopeningsandbox/ViewOpeningSandboxView.java[tags=viewBuilders;notifications;openViewWithCloseAction]
----

As you can see, when values are returned through a custom `CloseAction`, the caller doesn’t have to know the opened view class because it doesn’t invoke methods of the specific view controller. So the view can be created by its string id.

[[view-inference-conventions]]
== View Inference Conventions

A lookup view or a detail view can be inferred from the entity class.

When opening a list view for lookup using `viewBuilders.lookup(this, SomeEntity.class)`, the framework selects a view according the following order:

. A view annotated with `@PrimaryLookupView(SomeEntity.class)`.
. A view with the `SomeEntity.lookup` id.
. A view annotated with `@PrimaryListView(SomeEntity.class)`.
. A view with the `SomeEntity.list` id.

When opening a detail view using `viewBuilders.detail(this, SomeEntity.class)`, the framework selects a view according the following order:

. A view annotated with `@PrimaryDetailView(SomeEntity.class)`.
. A view with the `SomeEntity.detail` id.