= Аннотации экранов

В этом разделе описываются аннотации, которые можно добавить к контроллеру экрана для задания дополнительных настроек.

[[tabbed-mode-view-properties]]
== TabbedModeViewProperties

Аннотация `@TabbedModeViewProperties` определяет параметры экрана, специфичные для Tabbed Application Mode. Она предоставляет следующие свойства:

* `closeable` - определяет, можно ли закрыть экран стандартными способами, такими как кнопка закрытия вкладки, xref:main-tab-sheet.adoc[действия закрытия вкладок], методы `io.jmix.tabbedmode.Views.OpenedViews` и `io.jmix.tabbedmode.Views.ViewStack`. Это означает, что закрыть такой экран можно только вызвав метод xref:flow-ui:views/view-methods.adoc#methods-of-all-views[close()] этого экрана.

* `forceDialog` - если установлено значение `true`, экран всегда открывается в диалоговом окне, независимо от начальной настройки `ViewOpenMode`.

[[multiple-open]]
== MultipleOpen

Аннотация `@MultipleOpen` позволяет открывать один и тот же экран из главного меню несколько раз. По умолчанию при выборе пункта меню фреймворк проверяет, открыт ли уже экран того же класса и с тем же идентификатором. Если такой экран найден, он закрывается, а новый экземпляр открывается в новой вкладке.

При наличии `@MultipleOpen` эта проверка не выполняется: каждый раз в новой вкладке открывается новый экземпляр экрана.
