= SAML

Дополнение Jmix SAML предоставляет аутентификацию SAML 2.0 в приложениях Jmix.

[[installation]]
== Установка

Для автоматической установки через Jmix Marketplace следуйте инструкциям в разделе xref:ROOT:add-ons.adoc#installation[Дополнения].

Для ручной установки добавьте следующую зависимость в ваш `build.gradle`:

[source,groovy,indent=0]
----
implementation 'io.jmix.saml:jmix-saml-starter'
----

[[default-configuration]]
== Конфигурация Jmix SAML по умолчанию

При конфигурации Jmix SAML по умолчанию:

* Неаутентифицированные пользователи перенаправляются на страницу входа identity provider.
* Пользователи прошедшие аутентификацию хранятся в памяти приложения. В security context при этом помещается экземпляр `DefaultJmixSamlUserDetails`; пользователи не сохраняются в базе данных.
* Атрибуты пользователя не сопоставляются автоматически.
* Коды ролей пользователя берутся из атрибута `Role` в SAML assertion. Ресурсные роли и роли уровня строк с этими кодами применяются к объекту аутентификации пользователя.

Следуйте инструкциям xref:saml:keycloak-saml.adoc[], чтобы настроить это поведение по умолчанию. Дополнительные инструкции по расширению конфигурации по умолчанию см. в xref:saml:additional-setup.adoc[].