= SAML

NOTE: Этот раздел находится в работе и вскоре будет завершён.

Дополнение Jmix SAML предоставляет аутентификацию SAML 2.0 в приложениях Jmix.

[[installation]]
== Установка

Для автоматической установки через Jmix Marketplace следуйте инструкциям в разделе xref:ROOT:add-ons.adoc#installation[Дополнения].

Для ручной установки:

. Добавьте зависимость в `build.gradle`:
+
[source,groovy,indent=0]
----
implementation 'io.jmix.saml:jmix-saml-starter'
----
+
. Добавьте репозиторий в `build.gradle`:
+
[source,groovy,indent=0]
----
maven {
    url 'https://build.shibboleth.net/nexus/content/repositories/releases'
}
----

[[default-configuration]]
== Cтандартная конфигурация Jmix SAML

При стандартной конфигурации Jmix SAML:

* Неаутентифицированные пользователи перенаправляются на страницу входа провайдера удостоверений.
* Пользователь, аутентифицированный через SAML, создаётся в памяти приложения после аутентификации. В контекст безопасности помещается экземпляр `DefaultJmixSamlUserDetails`; пользователи не сохраняются в базе данных.
* Атрибуты пользователя автоматически не сопоставляются.
* Коды ролей пользователя передаются из атрибута `Role` в SAML Assertion. Затем ресурсные роли и роли уровня строк с этими кодами применяются к объекту аутентификации пользователя.

Следуйте инструкциям в xref:saml:keycloak-saml.adoc[] для настройки поведения по умолчанию. Дополнительные инструкции по расширению конфигурации см. в xref:saml:additional-setup.adoc[].