= Свойства Jmix SAML

[[jmix.saml.use-default-configuration]]
== jmix.saml.use-default-configuration
Определяет, применять ли всю авто-конфигурацию по умолчанию целиком. (По умолчанию: `true`)

[[jmix.saml.use-default-ui-configuration]]
== jmix.saml.use-default-ui-configuration
Определяет, применять ли конфигурацию Spring Security по умолчанию. (По умолчанию: `true`)

[[jmix.saml.max-concurrent-user-mapping]]
== jmix.saml.max-concurrent-user-mapping
Максимальное количество параллельных процессов сопоставления пользователей в `io.jmix.saml.mapper.user.BaseSamlUserMapper`. (По умолчанию: `128`)

[[jmix.saml.default-saml-assertion-roles-mapper.roles-assertion-attribute]]
== jmix.saml.default-saml-assertion-roles-mapper.roles-assertion-attribute
Имя атрибута в SAML assertion, который содержит роли. (По умолчанию: `Role`)

[[jmix.saml.default-saml-assertion-roles-mapper.resource-role-prefix]]
== jmix.saml.default-saml-assertion-roles-mapper.resource-role-prefix
Префикс, который можно использовать для распознавания ресурсной роли от сервера авторизации. (По умолчанию: не указан)

[[jmix.saml.default-saml-assertion-roles-mapper.row-level-role-prefix]]
== jmix.saml.default-saml-assertion-roles-mapper.row-level-role-prefix
Префикс, который можно использовать для распознавания роли уровня строки от сервера авторизации. (По умолчанию: не указан)

[[jmix.saml.filter-chain.force-ui-scope-enabled]]
== jmix.saml.filter-chain.force-ui-scope-enabled
Определяет, включен ли принудительный UI scope для Security filter chains, заданных через `jmix.saml.filter-chain.ui-scope-security-filter-chain-names`. (По умолчанию: `true`)

[[jmix.saml.filter-chain.ui-scope-security-filter-chain-names]]
== jmix.saml.filter-chain.ui-scope-security-filter-chain-names
Представляет список имен security filter chains, которые должны быть настроены с помощью `io.jmix.saml.filter.SamlVaadinSecurityFilterChainCustomizer`. (По умолчанию: `VaadinSecurityFilterChainBean`)

[[jmix.saml.force-redirect-binding-logout]]
== jmix.saml.force-redirect-binding-logout
Определяет, следует ли принудительно использовать binding `redirect` для logout запросов. Если установлено `true`, logout запросы всегда будут использовать binding `redirect`. В противном случае binding будет определяться на основе `RelyingPartyRegistration`. (По умолчанию: `true`)