= Delete Entities

The Entities API also allows you to delete entities that should be removed from the application. The corresponding endpoint is once again: `/entities/:entityName/:entityId` using the HTTP method `DELETE`.

[[delete-entity]]
== Delete an Entity

The following example removes a previously created Customer:

[source, http request]
.Request
----
DELETE http://localhost:8080/rest
            /entities
            /sample_Customer
            /13f01f59-8e5f-4fd9-802b-66501d49ac99
----

In case the entity exists, the response status `200 - OK` is returned without any response body, and the entity is deleted from the application. In case the entity is not found, `404 - Not Found` is returned.

TIP: The Entities API takes xref:data-model:soft-deletion.adoc[Soft Deletion] into consideration. Depending on the setting of the entity, the instance is either only soft-deleted or deleted entirely from the database.

[[bulk-delete]]
== Bulk Delete

The Delete-Entity API also allows you to delete multiple entities within one request. For this, the JSON request body should contain an array of IDs representing each entity.

[source, http request]
.Bulk Delete Request
----
DELETE http://localhost:8080/rest
            /entities
            /sample_Customer

[
  "3b9a1d43-1397-d2ae-eedd-f79eec1b81e2",
  "20ba4218-6690-c14c-9453-9ccd4b0add37"
]
----

In case all entities could be deleted, the HTTP response code `200 - OK` is returned.

////
NOTE: All entities of the Bulk API are processed as part of one database transaction. This means if there is a validation violation in at least one of the entities, none of the entities will be created at all.
////