= Getting Started with LDAP

Let's assume we will use LDAP authentication and maintain users in the application.

First, add the LDAP add-on to your project according to the xref:ldap:index.adoc#installation[installation] section.

[[configuring-main-properties]]
== Configuring Main Properties

Now, add the main LDAP properties. We will use a test LDAP server, `\ldap://ldap.forumsys.com:389/`, that has some https://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/[test users^].

[source,properties,indent=0]
----
include::example$/ex1/src/main/resources/application.properties[tags=properties]
----

xref:ldap:properties.adoc#jmix.ldap.default-roles[jmix.ldap.default-roles] contains a list of roles that will be assigned to every user authenticated in LDAP. It is needed since a user without any roles will not be able to log in to the application.

Set the `jmix.ldap.default-roles` property to `ui-minimal`.

[source,properties,indent=0]
----
include::example$/ex1/src/main/resources/application.properties[tags=default-roles]
----

You can find out more about the meaning of each property in the xref:ldap:properties.adoc[Properties] section.

[[configuring-synchronization]]
== Configuring Synchronization

Now we need to describe the way we want users to be synchronized.

We will implement the default scenario when the add-on authenticates users from the application against LDAP. If a user is successfully authenticated in LDAP, but does not have `UserDetails` in the application, it will be automatically synchronized, and `UserDetails` will be created in accordance with the corresponding LDAP entry.

Let's declare a bean implementing the `LdapUserDetailsSynchronizationStrategy` interface. The add-on comes with a basic abstract implementation: `AbstractLdapUserDetailsSynchronizationStrategy`, so in a simple case the strategy can be declared by only specifying a concrete `User` class and implementing a simple mapping:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ldap/ex1/app/CustomUserSynchronizationStrategy.java[tags=strategy]
----

Note that `AbstractLdapUserDetailsSynchronizationStrategy` also persists role assignments that were obtained during the role mapping flow. After each synchronization execution, role assignments are rewritten with the new ones. It is done in order not to preserve the obsolete role assignments.

So, let's set the xref:ldap:properties.adoc#jmix.ldap.synchronize-role-assignments[jmix.ldap.synchronize-role-assignments] to `false` in order to manage user roles manually in the application.

After the synchronization strategy is declared, users will be synchronized on every login. If you want to disable user synchronization on login, set the xref:ldap:properties.adoc#jmix.ldap.synchronize-user-on-login[jmix.ldap.synchronize-user-on-login] to `false`.

If you want to manage users fully in LDAP and not maintain them in the application, see the xref:ldap:in-memory-user-management.adoc[In-memory User Management] section.