= In-memory User Management

If you want to manage users fully in LDAP, set the following property:

[source,properties,indent=0]
----
jmix.ldap.user-details-source = ldap
----

In this case, standard `LdapUserDetails` objects are created by Spring Security after each authentication and preserved in memory instead of being taken from the database as the `User` entity. User authorities are obtained by the role mapping process described in the xref:ldap:obtaining-user-authorities.adoc[Obtaining User Authorities] section.

The case when maintaining users in the application is described in the xref:ldap:getting-started.adoc[Getting Started] section.

[[ldap-user-repository]]
== LDAP User Repository

When users are primarily managed in LDAP, you may need to choose or find them in the application using `SuggestionField`. For this purpose, the add-on comes with the LDAP implementation of `UserRepository`. This user repository provides access to users from LDAP, but it does not provide `system` or `anonymous` users. Also, you may want users from the database to be searchable as well.

To achieve this, declare the `CompositeUserRepository` bean, which comprises all instances of `UserRepository` in the application, for example, `LdapUserRepository` and `DatabaseUserRepository`.

Remove the `@Primary` annotation from the `DatabaseUserRepository` to avoid conflict with the composite repository. Make this `UserRepository` primary in the application:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/ldap/ex1/LdapSampleApplication.java[tags=user-repository]
----
