= LDAP

Дополнение предоставляет простой способ включения LDAP-аутентификации в приложениях Jmix. Оно позволяет синхронизировать пользователей и сопоставлять группы LDAP и атрибуты пользователей с ролями безопасности Jmix. Вы можете использовать дополнение с Active Directory и любой другой реализацией LDAP.

Кроме того, дополнение поддерживает случай, когда пользователи управляются только в LDAP, и вы не храните сущность пользователя в базе данных.

Дополнение использует Spring Security LDAP и предоставляет готовую конфигурацию безопасности, которую можно легко включить, добавив дополнение в приложение. Процесс и основные настройки LDAP-аутентификации описаны в {spring-security-doc}/servlet/authentication/passwords/ldap.html[документации Spring Security^].

[[installation]]
== Установка

Для автоматической установки через Jmix Marketplace следуйте инструкциям в разделе xref:ROOT:add-ons.adoc#installation[Дополнения].

Для ручной установки добавьте следующую зависимость в ваш `build.gradle`:

[source,groovy,indent=0]
----
include::example$/ex1/build.gradle[tags=ldap-dep]
----

Чтобы начать работу с приложением, вам необходимо настроить основные свойства LDAP. Смотрите пример в разделе xref:ldap:getting-started.adoc#configuring-main-properties[Начало работы].