= LDAP

The add-on provides an easy way to enable LDAP authentication in Jmix applications. It allows you to synchronize users and map LDAP groups and user attributes to Jmix security roles. You can use the add-on with Active Directory and any other LDAP implementation.

Also, the add-on supports the case when users are managed only in LDAP, and you don't store a user entity in the database.

The add-on uses Spring Security LDAP and provides a ready-to-go security configuration that can be easily enabled by including the add-on in the application. The process and main settings of LDAP authentication are described in the {spring-security-doc}/servlet/authentication/passwords/ldap.html[Spring Security documentation^].

[[installation]]
== Installation

For automatic installation through Jmix Marketplace, follow instructions in the xref:ROOT:add-ons.adoc#installation[Add-ons] section.

For manual installation, add the following dependency to your `build.gradle`:

[source,groovy,indent=0]
----
include::example$/ex1/build.gradle[tags=ldap-dep]
----

To start working with the application, you need to configure main LDAP properties. See an example in the xref:ldap:getting-started.adoc#configuring-main-properties[Getting Started] section.

