= Свойства LDAP

[[jmix.ldap.enabled]]
== jmix.ldap.enabled

Определяет, включена ли LDAP-аутентификация.

Значение по умолчанию: `true`

[[jmix.ldap.default-roles]]
== jmix.ldap.default-roles

Определяет список ролей, которые будут назначены каждому пользователю после успешной аутентификации.

Пример: `jmix.ldap.default-roles = ui-minimal, ui-filter`

[[jmix.ldap.user-details-source]]
== jmix.ldap.user-details-source

Определяет источник объектов `UserDetails`, возвращаемых после успешной аутентификации.

Возможные значения:

* `app` - `UserDetails` получаются из основного `UserDetailsService` приложения, обычно из базы данных.
* `ldap` - стандартные объекты `LdapUserDetails`, создаваемые Spring Security.

Значение по умолчанию: `app`

[[jmix.ldap.urls]]
== jmix.ldap.urls

Указывает URL-адреса LDAP-сервера. Также могут использоваться защищенные SSL URL-адреса LDAP, учитывая, что Spring Security может подключиться к серверу. Обратите внимание, что эти URL-адреса не должны включать базовый DN. Несколько URL-адресов можно указать в списке, разделенном запятыми. В этом случае соединение будет установлено с любым из предоставленных URL-адресов LDAP-сервера.

Пример: `ldap://ldap.company.com:389`

[[jmix.ldap.base-dn]]
== jmix.ldap.base-dn

Определяет базовый DN. Если настроено, все операции LDAP с контекстами, полученными из этого `ContextSource`, относятся к этому DN. Значение по умолчанию - пустое отличаемое имя, то есть все операции относятся к корню каталога.

[[jmix.ldap.manager-dn]]
== jmix.ldap.manager-dn

Указывает DN, используемый для аутентификации. Обычно это отличаемое имя пользователя "manager".

[[jmix.ldap.manager-password]]
== jmix.ldap.manager-password

Определяет пароль для пользователя "manager".

[[jmix.ldap.user-search-base]]
== jmix.ldap.user-search-base

Определяет базу поиска для поиска пользователей. Используется вместе с <<jmix.ldap.user-search-filter,jmix.ldap.user-search-filter>>.

[[jmix.ldap.user-search-filter]]
== jmix.ldap.user-search-filter

Фильтр LDAP, используемый для поиска пользователей. Подставляемым параметром является имя для входа пользователя.

Пример: `(uid=\{0})`

[[jmix.ldap.username-attribute]]
== jmix.ldap.username-attribute

Атрибут LDAP, соответствующий имени пользователя. Используется во время синхронизации пользователей для назначения правильного имени пользователя.

Значение по умолчанию: `uid`

[[jmix.ldap.group-role-attribute]]
== jmix.ldap.group-role-attribute

Атрибут группы LDAP, соответствующий названию права.

Значение по умолчанию: `cn`

[[jmix.ldap.group-search-base]]
== jmix.ldap.group-search-base

Определяет базу поиска для поиска групп.

Значение по умолчанию: пустая строка.

[[jmix.ldap.group-search-subtree]]
== jmix.ldap.group-search-subtree

Если установлено в `true`, будет выполнен поиск в области поддерева. Если `false`, используется одноуровневый поиск.

Значение по умолчанию: `false`

[[jmix.ldap.group-search-filter]]
== jmix.ldap.group-search-filter

Фильтр LDAP, используемый для поиска групп пользователя (опционально). Подставляемым параметром является имя для входа пользователя.

Значение по умолчанию: `(uniqueMember=\{0})`

[[jmix.ldap.use-active-directory-configuration]]
== jmix.ldap.use-active-directory-configuration

Определяет, следует ли использовать специфичную для Active Directory конфигурацию безопасности вместо конфигурации по умолчанию.

Значение по умолчанию: `false`

[[jmix.ldap.active-directory-domain]]
== jmix.ldap.active-directory-domain

Используется только с конфигурацией ActiveDirectory. Указывает доменное имя Active Directory.

Пример: `mydomain.com`

[[jmix.ldap.group-for-synchronization]]
== jmix.ldap.group-for-synchronization

DN группы, содержащей пользователей для синхронизации в приложении.

[[jmix.ldap.synchronize-role-assignments]]
== jmix.ldap.synchronize-role-assignments

Определяет, сохранять ли назначения ролей во время синхронизации пользователей.

Значение по умолчанию: `true`

[[jmix.ldap.standard-authentication-users]]
== jmix.ldap.standard-authentication-users

Определяет список пользователей, которые всегда должны аутентифицироваться с помощью стандартной аутентификации.

Значение по умолчанию: `admin, system`

Пример: `jmix.ldap.standard-authentication-users = admin, operator`

[[jmix.ldap.synchronize-user-on-login]]
== jmix.ldap.synchronize-user-on-login

Определяет, синхронизируются ли пользователи при каждом входе в систему. Например, если вы хотите заранее загружать пользователей из LDAP и синхронизировать их раз в день по запланированной задаче, установите свойство в `false`.

Значение по умолчанию: `true`

[[jmix.ldap.member-attribute]]
== jmix.ldap.member-attribute

Атрибут группы LDAP для указания участника группы.

Значение по умолчанию: `uniqueMember`