= Использование с Active Directory

Дополнение предоставляет отдельную конфигурацию безопасности для использования с Active Directory. Поскольку Active Directory поддерживает собственные нестандартные варианты аутентификации, такие как аутентификация с использованием доменного имени пользователя в форме `user@domain` вместо отличаемого имени LDAP, Spring Security предоставляет отдельный `AuthenticationProvider`, настроенный для типичной настройки Active Directory.

Если вы собираетесь работать с Active Directory, установите свойство:

[source,properties,indent=0]
----
jmix.ldap.use-active-directory-configuration = true
----

Установив это свойство, вы указываете приложению использовать `ActiveDirectoryLdapAuthenticationProvider`, который более подходит для использования с Active Directory.

Вам следует указать фильтр поиска пользователей, используемый `ActiveDirectoryLdapAuthenticationProvider` для поиска пользователя:

[source,properties,indent=0]
----
jmix.ldap.user-search-filter = (&(objectClass=user)(userPrincipalName={0}))
----

В приведенном выше примере пользователи будут вводить свое имя пользователя в форме `username@domain`.

Альтернативно вы можете настроить провайдер аутентификации следующим образом:

[source,properties,indent=0]
----
jmix.ldap.user-search-filter = (&(objectClass=user)(sAMAccountName={1}))
jmix.ldap.active-directory-domain = somedomain
----

В этом случае пользователям нужно будет вводить только свое имя пользователя (без домена) в форме входа.