= dataLoadCoordinator
:page-aliases: facets/data-load-coordinator.adoc

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/data-load-coordinator" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Фасет `dataLoadCoordinator` предназначен для запуска загрузчиков данных и для декларативной привязки загрузчиков данных к контейнерам данных, визуальным компонентам и событиям жизненного цикла экрана.

[[basics]]
== Основное использование

Чтобы запустить все загрузчики данных на событии `BeforeShowEvent` экрана, просто добавьте `dataLoadCoordinator` с атрибутом `auto="true"` в XML-дескриптор экрана:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/department/department-list-view.xml[tags=dataLoadCoordinator]
----

[[working-modes]]
== Режимы работы

`dataLoadCoordinator` можно настроить для работы в автоматическом, ручном или полуавтоматическом режиме.

[[automatic-mode]]
=== Автоматический режим

В этом режиме `dataLoadCoordinator` полагается на имена параметров с определенными префиксами. Префикс обозначает компонент, который предоставляет значение параметра и событие его изменения.

По умолчанию префикс параметра - `container_` для контейнеров данных и `component_` для визуальных компонентов. Атрибуты <<componentPrefix,componentPrefix>> и <<containerPrefix,containerPrefix>> позволяют использовать другие префиксы.

Загрузчик запускается на `BeforeShowEvent`, если в его тексте запроса нет параметров без распознанных префиксов. Это означает, что если запрос содержит произвольный параметр, например `select e from User e where e.department = :department`, то загрузчик не будет запущен автоматически при открытии экрана. Необходимо установить значение параметра и вызвать `userDl.load()` вручную.

Параметры в xref:data/data-loaders.adoc#query-conditions[условиях запроса] не препятствуют запуску загрузчика на `BeforeShowEvent`.

[[manual-mode]]
=== Ручной режим

В этом режиме момент запуска загрузчиков данных определяют вложенные элементы <<refresh,refresh>>.

[[semi-automatic-mode]]
=== Полуавтоматический режим

Если атрибут `auto` установлен в `true`, и при этом есть некоторые вручную настроенные триггеры, `DataLoadCoordinator` автоматически настраивает все загрузчики, не имеющие ручной конфигурации.

[[attributes]]
== Атрибуты

include::facet-tip.adoc[]

[[auto]]
* `auto` - определяет рабочий режим `DataLoadCoordinator`.
Значение по умолчанию - `false`.

[[componentPrefix]]
* `componentPrefix` - определяет префикс для параметров, которые относятся к xref:vc/components.adoc[визуальным компонентам], из которых `DataLoadCoordinator` будет брать значения параметров в автоматическом режиме. Значение по умолчанию - `component_`.

[[containerPrefix]]
* `containerPrefix` - определяет префикс для параметров, которые относятся к xref:data/data-containers.adoc[контейнерам данных], из которых `DataLoadCoordinator` будет брать значения параметров в автоматическом режиме. Значение по умолчанию - `container_`.

[[refresh]]
== Элемент refresh

Элемент `refresh` позволяет определить условия, при которых должен быть запущен загрузчик данных.

[[loader]]
Единственный атрибут этого элемента - `loader`, который определяет `id` загрузчика.

Элемент `refresh` может иметь следующие вложенные элементы, определяющие условия срабатывания загрузчика:

[[onComponentValueChanged]]
. `onComponentValueChanged` - запуск загрузчика при изменении значение визуального компонента. Он имеет следующие атрибуты:
+
--
[[component]]
* `component` - указывает `id` визуального компонента.

[[likeClause]]
* `likeClause` - если вы используете выражение `like` в xref:data/data-loaders.adoc#query-conditions[условии запроса], вы можете определить один из трех возможных режимов поиска:
** `NONE` - значение по умолчанию.
** `CASE_SENSITIVE` - поиск с учетом регистра символов.
** `CASE_INSENSITIVE` - поиск без учета регистра символов.

[[component-param]]
* `param` - указывает имя параметра запроса.
--
[[onContainerItemChanged]]
. `onContainerItemChanged` - запуск загрузчика, когда меняется текущий элемент в контейнере данных. Он имеет следующие атрибуты:
+
--
[[container]]
* `container` - указывает `id` контейнера данных.

[[container-param]]
* `param` - указывает имя параметра запроса.
--
[[onViewEvent]]
. `onViewEvent` - запуска загрузчика на событии жизненного цикла экрана. Он имеет следующий атрибут:
+
--
[[onViewEvent-type]]
* `type` - определяет тип события экрана. Возможные значения:
** `Init` - для запуска на событии `InitEvent`.
** `BeforeShow` - для запуска на событии `BeforeShowEvent`.
** `Ready` - для запуска на событии `ReadyEvent`.
--

[[see-also]]
== См. также

Следующие онлайн-примеры демонстрируют `dataLoadCoordinator` в действии:

* https://demo.jmix.ru/ui-samples/sample/data-load-coordinator[DataLoadCoordinator^]
* https://demo.jmix.ru/ui-samples/sample/cascading-dropdowns[Каскадные выпадающие списки^]
* https://demo.jmix.ru/ui-samples/sample/custom-filter[Фильтр с использованием декларативных условий^]