= settings
:page-aliases: facets/screen-settings-facet.adoc

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/settings-facet" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Фасет `settings` сохраняет и восстанавливает настройки визуальных компонентов для текущего пользователя. Поддерживаются следующие компоненты:

* xref:flow-ui:vc/components/dataGrid.adoc[dataGrid], xref:vc/components/treeDataGrid.adoc[treeDataGrid] - фасет сохраняет порядок и ширину колонок, а также параметры сортировки.
* xref:flow-ui:vc/layouts/details.adoc[details], xref:vc/components/genericFilter.adoc[genericFilter] - фасет сохраняет состояние открытия.
* xref:vc/components/simplePagination.adoc[simplePagination] - фасет сохраняет выбранный размер страницы, если `itemsPerPageVisible` имеет значение `true`.

[[basic-usage]]
== Базовое использование

При добавлении на экран с атрибутом `auto="true"` фасет управляет настройками всех поддерживаемых компонентов экрана, имеющих идентификаторы:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/customer/customer-list-view.xml[tags=facets;settings]
----

Для управления настройками конкретного компонента используйте вложенные элементы `component`, например:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/city/city-list-view.xml[tags=facets;settings]
----

Чтобы исключить какой-либо компонент, используйте `auto="true"` для фасета и `enabled="false"` для компонента:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/hobby/hobby-list-view.xml[tags=facets;settings]
----

Настройки хранятся в основном хранилище данных в таблице `FLOWUI_USER_SETTINGS` в формате JSON. Вы можете управлять сохраненными настройками, открыв сущность `flowui_UserSettingsItem` в xref:data-tools:entity-inspector.adoc[Инспекторе сущностей].

[[handlers]]
== Обработчики

include::flow-ui:vc/handler-generation-tip.adoc[]

[[applySettingsDelegate]]
=== applySettingsDelegate

`applySettingsDelegate` вызывается перед обработчиком события `ReadyEvent` экрана.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/facets/SettingsFacetView.java[tags=checkbox;settings;applySettingsDelegate]
----

[[applyDataLoadingSettingsDelegate]]
=== applyDataLoadingSettingsDelegate

`applyDataLoadingSettingsDelegate` вызывается перед обработчиком события `BeforeShowEvent` экрана и позволяет восстановить настройки, связанные с загрузкой данных.

[[saveSettingsDelegate]]
=== saveSettingsDelegate

Обработчик `saveSettingsDelegate` вызывается перед обработчиком события `DetachEvent` экрана.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/facets/SettingsFacetView.java[tags=checkbox;settings;saveSettingsDelegate]
----