= settings
:page-aliases: facets/screen-settings-facet.adoc

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/settings-facet" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

The `settings` facet saves and restores settings of visual components for the current user. The following components are supported:

* xref:flow-ui:vc/components/dataGrid.adoc[dataGrid], xref:vc/components/treeDataGrid.adoc[treeDataGrid] - the facet saves the order and width of columns, as well as sorting parameters.
* xref:flow-ui:vc/layouts/details.adoc[details], xref:vc/components/genericFilter.adoc[genericFilter] - the facet saves the opened state.
* xref:vc/components/simplePagination.adoc[simplePagination] - the facet saves the selected page size if `itemsPerPageVisible` is `true`.

[[basic-usage]]
== Basic Usage

When added to a view with the `auto="true"` attribute, the facet manages settings of all supported components of the view that have identifiers:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/customer/customer-list-view.xml[tags=facets;settings]
----

To manage settings of a particular component, use the nested `component` elements, for example:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/city/city-list-view.xml[tags=facets;settings]
----

To exclude some component, use `auto="true"` for the facet and `enabled="false"` for the component:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/hobby/hobby-list-view.xml[tags=facets;settings]
----

The settings are stored in the main data store in the `FLOWUI_USER_SETTINGS` table in JSON format. You can manage the saved settings by opening the `flowui_UserSettingsItem` entity in the xref:data-tools:entity-inspector.adoc[Entity Inspector].

[[handlers]]
== Handlers

include::flow-ui:vc/handler-generation-tip.adoc[]

[[applySettingsDelegate]]
=== applySettingsDelegate

`applySettingsDelegate` is invoked before the view `ReadyEvent` handler.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/facets/SettingsFacetView.java[tags=checkbox;settings;applySettingsDelegate]
----

[[applyDataLoadingSettingsDelegate]]
=== applyDataLoadingSettingsDelegate

`applyDataLoadingSettingsDelegate` is invoked before the view `BeforeShowEvent` handler and allows you to restore settings related to data loading.

[[saveSettingsDelegate]]
=== saveSettingsDelegate

The `saveSettingsDelegate` handler is invoked before the view `DetachEvent` handler.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/facets/SettingsFacetView.java[tags=checkbox;settings;saveSettingsDelegate]
----