= timer

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/timer-facet" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Фасет `timer` предназначен для запуска кода UI через указанные интервалы времени.

Действие таймера инициируется из браузера как запрос пользователя, и его обработчик может обновлять xref:vc/components.adoc[компоненты UI]. Таймер прекращает работу, когда экран, для которого он был создан, закрывается.

[[basic-usage]]
== Основное использование

Добавьте `timer` в элемент `facets` XML-дескриптора экрана:

[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/view/timer/timer-view.xml[tags=timer]
----

Создайте обработчик `TimerActionEvent`:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/timer/TimerView.java[tag=timer-action]
----

Обработчик будет вызываться каждые 3 секунды после открытия экрана.

[[attributes]]
== Атрибуты

`timer` определяется в элементе `facets` XML-дескриптора экрана и имеет следующие атрибуты:

<<autostart, autostart>> -
<<delay, delay>> -
xref:vc/common-attributes.adoc#id[id] -
<<repeating, repeating>>

[[delay]]
=== delay

Обязательный атрибут. Определяет интервал срабатывания таймера в миллисекундах.

[[autostart]]
=== autostart

Необязательный атрибут. Значение по умолчанию — `false`, что означает, что таймер начнет работу только при вызове его метода `start()`. Если установлено значение `true`, таймер запускается сразу после открытия экрана.

[[repeating]]
=== repeating

Необязательный атрибут. Если атрибут установлен в `true`, таймер работает циклически с равными интервалами, определенными в атрибуте `delay`. В противном случае таймер выполняется только один раз по истечении таймаута, указанного в атрибуте `delay`, после запуска таймера.

[[handlers]]
== Обработчики

include::flow-ui:vc/handler-generation-tip.adoc[]

[[timer-action-event]]
=== TimerActionEvent

`TimerActionEvent` срабатывает после прохождения указанного времени в атрибуте `delay` с момента запуска таймера. Если атрибут `repeating` установлен в `true`, это событие отправляется периодически до тех пор, пока таймер не будет остановлен.

Чтобы зарегистрировать обработчик программно, используйте метод `addTimerActionListener()` фасета.

[[timer-stop-event]]
=== TimerStopEvent

`TimerStopEvent` отправляется, когда таймер останавливается вызовом метода `stop()` фасета.

Чтобы зарегистрировать обработчик программно, используйте метод `addTimerStopListener()` фасета.

[[see-also]]
== См. также

Онлайн-пример https://demo.jmix.ru/ui-samples/sample/delayed-data-load[Задержка загрузки данных^] демонстрирует, как помощью таймера можно отложить затратную операцию загрузки данных.
