= timer

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/timer-facet" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

`timer` facet is designed to run UI code at specified time intervals.

The timer action is initiated from the browser as a user request and its handler can update xref:vc/components.adoc[UI components]. The timer stops working when the view it was created for is closed.

[[basic-usage]]
== Basic Usage

Add `timer` to the `facets` element of the view XML descriptor:

[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/view/timer/timer-view.xml[tags=timer]
----

Create `TimerActionEvent` handler:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/timer/TimerView.java[tag=timer-action]
----

The handler will be invoked every 3 seconds after the view is opened.

[[attributes]]
== Attributes

`timer` is defined in the `facets` element of the view XML descriptor and has the following attributes:

<<autostart, autostart>> -
<<delay, delay>> -
xref:vc/common-attributes.adoc#id[id] -
<<repeating, repeating>>

[[delay]]
=== delay

Required attribute. Defines timer interval in milliseconds.

[[autostart]]
=== autostart

Optional attribute. The default value is `false`, which means that the timer will start only when its `start()` method is invoked. When it is set to `true`, the timer starts immediately after the view opening.

[[repeating]]
=== repeating

Optional attribute. Turns on repeated executions of the timer. If the attribute is set to `true`, the timer runs in cycles at equal intervals defined in the `delay` attribute. Otherwise, the timer runs only once after the timeout specified in the `delay` attribute after the timer start.

[[handlers]]
== Handlers

include::flow-ui:vc/handler-generation-tip.adoc[]

[[timer-action-event]]
=== TimerActionEvent

`TimerActionEvent` is triggered after the specified time interval in the `delay` attribute has passed since the timer started. If the `repeating` attribute is set to `true`, this event is sent periodically, until the timer is stopped.

To register the event handler programmatically, use the `addTimerActionListener()` method of the facet.

[[timer-stop-event]]
=== TimerStopEvent

`TimerStopEvent` is sent when the timer is stopped by invoking the `stop()` method of the facet.

To register the event handler programmatically, use the `addTimerStopListener()` method of the facet.

[[see-also]]
== See Also

The https://demo.jmix.io/ui-samples/sample/delayed-data-load[Delayed data loading^] online example shows how to use the `timer` facet to delay a costly data loading operation.
