= timer

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/timer-facet" class="live-demo-btn" target="_blank">在线示例</a>
</div>
++++

`timer`（定时器）facet 支持以指定的时间间隔运行 UI 代码。

timer 的操作以用户请求的方式从浏览器发起，其事件处理器中可以更新 xref:vc/components.adoc[UI 组件]。当创建 timer 的视图关闭之后，timer 就会停止运行。

[[basic-usage]]
== 基本用法

在视图 XML 的 `facets` 元素中添加 `timer`：

[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/view/timer/timer-view.xml[tags=timer]
----

创建 `TimerActionEvent` 事件的处理方法：

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/timer/TimerView.java[tag=timer-action]
----

视图打开后，每隔 3 秒就会调用一次处理方法。

[[attributes]]
== 属性

`timer` 在视图 XML 的 `facets` 元素中定义，具有下列属性：

<<autostart, autostart>> -
<<delay, delay>> -
xref:vc/common-attributes.adoc#id[id] -
<<repeating, repeating>>

[[delay]]
=== delay

必需属性。定义定时器的时间间隔，单位为毫秒。

[[autostart]]
=== autostart

可选属性。默认为 `false`，即仅当调用 `start()` 方法时才会启动计时器。当设置为 `true` 时，计时器在视图打开时立即启动。

[[repeating]]
=== repeating

可选属性。启用计时器的重复执行功能。如果设置为 `true`，则计时器以 `delay` 属性设置的时间间隔反复运行。否则，仅在计时器启动后按 `delay` 设置的间隔运行一次。

[[handlers]]
== 事件和处理器

include::flow-ui:vc/handler-generation-tip.adoc[]

[[timer-action-event]]
=== TimerActionEvent

`TimerActionEvent` 在计时器启动且 `delay` 属性指定的时间过去后触发。如果 `repeating` 属性为 `true`，则会周期性的发送该事件，直至计时器停止。

如需编程式注册事件的处理方法，可以使用 facet 的 `addTimerActionListener()` 方法。

[[timer-stop-event]]
=== TimerStopEvent

`TimerStopEvent` 当调用 facet 的 `stop()` 方法停止计时器后发送。

如需编程式注册事件的处理方法，可以使用 facet 的 `addTimerStopListener()` 方法。

[[see-also]]
== 参考

https://demo.jmix.io/ui-samples/sample/delayed-data-load[延迟数据加载^] 在线示例展示如何使用 `timer` facet 延迟一个费时的数据加载操作。