= urlQueryParameters

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/url-query-parameters?genericFilterCondition=property%3Aage_greater_30" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

`urlQueryParameters` facet is designed for declarative binding of the view state to the URL. It allows you to preserve the view state when xref:flow-ui:views/opening-views.adoc[navigating] between views or refreshing the browser page.

If the entire view state comes from the database, which is the case for xref:views/views.adoc#standard-detail-view[entity detail views], the entity identifier in the URL route is enough to restore the state. But if some view components contain values that are not stored in the database, you need to encode them in the URL to restore when the view is reinitialised.

The obvious example is the entity list view with pagination and filtering. You will want to preserve pagination and filtering parameters when refreshing the browser page and when navigating to a detail view and back.

The entire view state encoded in the URL also provides a deep link representing exactly what is shown on the screen.

[[basics]]
== Basic Usage

To bind pagination and filtering parameters to the URL, define `urlQueryParameters` and use nested elements to connect existing components by their identifiers. In the following example, the `urlQueryParameters` facet is used with `genericFilter` and `simplePagination` components:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/user/user-list-view.xml[tags=url-query-params]
----

As a result, filtering the `User` entity list view by the `active` attribute and selecting the second page will be reflected in the URL like this:

`++http://localhost:8080/users?genericFilterCondition=property%3Aactive_equal_true&maxResults=50&firstResult=100++`

include::facet-tip.adoc[]

[[components]]
== Supported Components

[[pagination]]
=== pagination

The `pagination` nested element allows you to connect the `urlQueryParameters` facet to the xref:vc/components/simplePagination.adoc[] component.

Attributes of the `pagination` element:

* `component` - identifier of the pagination component to connect to.

* `firstResultParam` - (optional) name of the query parameter for representing the beginning of the current page.

* `maxResultsParam` - (optional) name of the query parameter for representing the page size.

[[propertyFilter]]
=== propertyFilter

The `propertyFilter` nested element allows you to connect the `urlQueryParameters` facet to the xref:vc/components/propertyFilter.adoc[] component.

Attributes of the `propertyFilter` element:

* `component` - identifier of the `propertyFilter` component to connect to.

* `param` - (optional) name of the query parameter for representing the filter value.

[[genericFilter]]
=== genericFilter

The `genericFilter` nested element allows you to connect the `urlQueryParameters` facet to the `genericFilter` component.

Attributes of the `genericFilter` element:

* `component` - identifier of the `genericFilter` component to connect to.

* `conditionParam` - (optional) name of the query parameter for representing the filter conditions.

* `configurationParam` - (optional) name of the query parameter for representing the selected filter configuration.

[[custom-binding]]
== Custom State Binding

The `urlQueryParameters` facet allows you to bind any custom view state to the URL.

Let's consider an example of a view with the following components:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/facets/url-query-parameters-view.xml[tags=custom-binding]
----

Imagine that the goal is to preserve the `opened` state of the xref:vc/layouts/details.adoc[] layout and the value of the xref:vc/components/textField.adoc[].

Then you need to implement a binder object and register it in the `urlQueryParameters` facet:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/facets/UrlQueryParametersView.java[tags=custom-binding]
----
<1> - inherit the binder class from the `AbstractUrlQueryParametersBinder` base class.
<2> - in the binder's constructor, add component listeners that will invoke the `fireQueryParametersChanged()` method of the binder when the components' state changes.
<3> - in the binder's `updateState()` method, update the state of the components.
<4> - create the binder instance and register it in the `urlQueryParameters` facet on view initialization.

NOTE: The `urlQueryParameters` facet uses {vaadin-api}/com/vaadin/flow/router/QueryParameters.html[QueryParameters^] class from the Vaadin API to send and receive the query parameters.