= urlQueryParameters

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/url-query-parameters?genericFilterCondition=property%3Aage_greater_30" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Фасет `urlQueryParameters` предназначен для декларативной привязки состояния экрана к URL. Он позволяет сохранять состояние экрана при xref:flow-ui:views/opening-views.adoc[навигации] между экранами и при обновлении страницы браузера.

Если всё состояние экрана берется из базы данных, как в случае xref:views/views.adoc#standard-detail-view[экранов деталей сущности], для восстановления состояния достаточно идентификатора сущности в URL. Но если некоторые компоненты экрана содержат значения, которые не хранятся в базе данных, то для восстановления при переинициализации экрана их нужно закодировать в URL.

Очевидным примером такой необходимости является экран списка сущностей с пагинацией и фильтрацией. Параметры пагинации и фильтрации необходимо сохранить при обновлении страницы браузера и при переходе к экрану деталей и обратно.

Состояние экрана, закодированное в URL, также предоставляет глубокую ссылку, точно соответствующую тому, что отображается на экране.

[[basics]]
== Основное использование

Чтобы привязать параметры пагинации и фильтрации к URL, определите `urlQueryParameters` в экране и используйте вложенные элементы для соединения существующих компонентов по их идентификаторам. В следующем примере фасет `urlQueryParameters` используется с компонентами `genericFilter` и `simplePagination`:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/user/user-list-view.xml[tags=url-query-params]
----

В результате, фильтрация экрана списка сущностей `User` по атрибуту `active` и выбор второй страницы будут отображены в URL следующим образом:

`++http://localhost:8080/users?genericFilterCondition=property%3Aactive_equal_true&maxResults=50&firstResult=100++`

include::facet-tip.adoc[]

[[components]]
== Поддерживаемые компоненты

[[pagination]]
=== pagination

Вложенный элемент `pagination` позволяет подключить фасет `urlQueryParameters` к компоненту xref:vc/components/simplePagination.adoc[].

Атрибуты элемента `pagination`:

* `component` - идентификатор компонента пагинации для подключения.

* `firstResultParam` - (необязательно) имя параметра запроса для начала текущей страницы.

* `maxResultsParam` - (необязательно) имя параметра запроса для размера страницы.

[[propertyFilter]]
=== propertyFilter

Вложенный элемент `propertyFilter` позволяет подключить фасет `urlQueryParameters` к компоненту xref:vc/components/propertyFilter.adoc[].

Атрибуты элемента `propertyFilter`:

* `component` - идентификатор компонента `propertyFilter` для подключения.

* `param` - (необязательно) имя параметра запроса для значения фильтра.

[[genericFilter]]
=== genericFilter

Вложенный элемент `genericFilter` позволяет подключить фасет `urlQueryParameters` к компоненту `genericFilter`.

Атрибуты элемента `genericFilter`:

* `component` - идентификатор компонента `genericFilter` для подключения.

* `conditionParam` - (необязательно) имя параметра запроса для условий фильтра.

* `configurationParam` - (необязательно) имя параметра запроса для выбранной конфигурации фильтра.

[[custom-binding]]
== Привязка пользовательского состояния

Фасет `urlQueryParameters` позволяет привязать любое пользовательское состояние экрана к URL.

Рассмотрим пример экрана с следующими компонентами:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/facets/url-query-parameters-view.xml[tags=custom-binding]
----

Предположим, что целью является сохранение состояния `opened` макета xref:vc/layouts/details.adoc[] и значения компонента xref:vc/components/textField.adoc[].

Тогда нужно реализовать объект-связыватель и зарегистрировать его в фасете `urlQueryParameters`:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/facets/UrlQueryParametersView.java[tags=custom-binding]
----
<1> - наследуйте класс-связыватель от базового класса `AbstractUrlQueryParametersBinder`.
<2> - в конструкторе связывателя добавьте слушатели компонентов, которые будут вызывать метод `fireQueryParametersChanged()` связывателя при изменении состояния компонентов.
<3> - в методе `updateState()` связывателя обновите состояние компонентов.
<4> - создайте экземпляр связывателя и зарегистрируйте его в фасете `urlQueryParameters` при инициализации экрана.

NOTE: Фасет `urlQueryParameters` использует класс {vaadin-api}/com/vaadin/flow/router/QueryParameters.html[QueryParameters^] из API Vaadin для отправки и приема параметров запроса.