= Events

The map and features have the following events.

== Map Events

[[MapClickEvent]]
=== MapClickEvent

An event that is fired when the map is clicked. Please note that if the user double-clicks, the event will be triggered twice.

Below is an example of handling a map click event. When a user clicks on the map, a notification is displayed with the event name and the coordinates of the map click location:

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/events/EventsView.java[tags=geometryFactory;notifications;MapClickEvent]
----

[[MapSingleClickEvent]]
=== MapSingleClickEvent

A map single-click event is fired after 250 ms to ensure that it is not a double-click.

[[MapDoubleClickEvent]]
=== MapDoubleClickEvent

An event is fired when a user double-clicks on a map.

Below is an example of handling a map double-click event.

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/events/EventsView.java[tags=geoMap;MapDoubleClickEvent]
----

[[MapMoveEndEvent]]
=== MapMoveEndEvent

An event is fired after the map is moved (for instance, after zooming, panning, or dragging the map).

Here's an example of how to handle a map move event.

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/events/EventsView.java[tags=notifications;MapMoveEndEvent]
----

[[MapZoomChangedEvent]]
=== MapZoomChangedEvent

An event is triggered when the resolution of the map view is changed.

Here's an example demonstrating how to handle a map zoom change event.

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/events/EventsView.java[tags=notifications;MapZoomChangedEvent]
----

[[source-events]]
== Source Events

[[SourceFeatureClickEvent]]
=== SourceFeatureClickEvent

An event that is fired when the xref:maps:features-geometries.adoc[feature] is clicked. Note that if the user double-clicks, the event will be fired twice.

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/events/EventsView.java[tags=vectorSource;onInit;addSourceFeatureClickListener]
----

[[SourceFeatureSingleClickEvent]]
=== SourceFeatureSingleClickEvent

A feature single click event is fired after 250 ms to ensure that it is not a double click.

[[SourceFeatureDoubleClickEvent]]
=== SourceFeatureDoubleClickEvent

An event is fired when a user double-clicks on a feature.

[[SourceFeatureSelectEvent]]
=== SourceFeatureSelectEvent

An event is triggered when features are selected or deselected. Keep in mind that the event only includes the features that were just selected or deselected. For example, if one feature is already selected out of a total of two, and the second feature is then selected, the event will only contain the newly selected feature.

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/layers/SelectModeView.java[tags=notifications;featureSelectEvent]
----

[[SourceFeatureDragStartEvent]]
=== SourceFeatureDragStartEvent

An event is fired when the user starts dragging a feature.

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/layers/DragModeView.java[tags=notifications;featureDragStartEvent]
----

[[SourceFeatureDragEndEvent]]
=== SourceFeatureDragEndEvent

An event is fired when the user finishes dragging a feature.

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/layers/DragModeView.java[tags=notifications;featureDragEndEvent]
----

[[SourceFeatureModifyStartEvent]]
=== SourceFeatureModifyStartEvent

An event is fired when a feature modification is initiated.

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/layers/ModifyModeView.java[tags=notifications;featureModifyStartEvent]
----

[[SourceFeatureModifyEndEvent]]
=== SourceFeatureModifyEndEvent

An event is fired when a feature modification is completed.

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/layers/ModifyModeView.java[tags=notifications;featureModifyEndEvent]
----

[[SourceFeatureDeleteEvent]]
=== SourceFeatureDeleteEvent

An event is fired when a feature is deleted from a source.

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/layers/ModifyModeView.java[tags=notifications;featureDeleteEvent]
----

[[GeoObjectClickEvent]]
=== GeoObjectClickEvent

An event that is fired when the geo-object is clicked. Note that if the user double-clicks, the event will be fired twice.

[source,java,indent=0]
----
include::example$/maps-ex1/src/main/java/com/company/onboarding/view/location/LocationDetailView.java[tags=dataVectorSource;notifications;onInit;addGeoObjectClickListener]
----

[[GeoObjectSingleClickEvent]]
=== GeoObjectSingleClickEvent

A geo-object single click event is fired after 250 ms to ensure that it is not a double click.

[[GeoObjectDoubleClickEvent]]
=== GeoObjectDoubleClickEvent

An event is fired when a user double-clicks on a geo-object.

[[GeoObjectSelectEvent]]
=== GeoObjectSelectEvent

A selection event is triggered when geo-objects are selected or deselected. Keep in mind that the event only includes the newly selected or deselected geo-objects. For example, if one geo-object is already selected out of a total of two, and you then select the second geo-object, the event will only contain information about the second geo-object you just selected.

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/layers/SelectModeView.java[tags=notifications;selectEvent]
----

[[GeoObjectDragStartEvent]]
=== GeoObjectDragStartEvent

An event is fired when the user starts dragging a geo-object.

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/layers/DragModeView.java[tags=notifications;dragStartEvent]
----

[[GeoObjectDragEndEvent]]
=== GeoObjectDragEndEvent

An event is fired when the user finishes dragging a geo-object.

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/layers/DragModeView.java[tags=notifications;dragEndEvent]
----

[[GeoObjectModifyStartEvent]]
=== GeoObjectModifyStartEvent

An event is fired when a geo-object modification is initiated.

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/layers/ModifyModeView.java[tags=notifications;modifyStartEvent]
----

[[GeoObjectModifyEndEvent]]
=== GeoObjectModifyEndEvent

An event is fired when a geo-object modification is completed.

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/layers/ModifyModeView.java[tags=notifications;modifyEndEvent]
----

== Feature Events

[[FeatureClickEvent]]
=== FeatureClickEvent

An event that is fired when a feature is clicked. Note that if the user double-clicks, the event will be fired twice.

[[FeatureSingleClickEvent]]
=== FeatureSingleClickEvent

An event is fired after 250 ms to ensure that it is not a double click.

[[FeatureDoubleClickEvent]]
=== FeatureDoubleClickEvent

An event is fired when a user double-clicks on a feature.
