= 事件

地图和地图要素具有下列事件。

== 地图事件

[[MapClickEvent]]
=== MapClickEvent

用户点击地图触发的事件。注意，如果用户双击地图，该事件会触发两次。

下面是处理地图点击事件的示例。用户点击时，显示一条消息，包含事件的名称和地图中点击的坐标：

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/events/EventsView.java[tags=geometryFactory;notifications;MapClickEvent]
----

[[MapSingleClickEvent]]
=== MapSingleClickEvent

地图单击事件会延迟 250ms 发送，以确保用户不是双击。

[[MapDoubleClickEvent]]
=== MapDoubleClickEvent

用户双击地图时发送的事件。

下面是处理地图双击事件的示例。

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/events/EventsView.java[tags=geoMap;MapDoubleClickEvent]
----

[[MapMoveEndEvent]]
=== MapMoveEndEvent

地图移动时发送的事件，包括缩放、平移或者拖动等。

下面是处理地图移动事件的示例。

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/events/EventsView.java[tags=notifications;MapMoveEndEvent]
----

[[MapZoomChangedEvent]]
=== MapZoomChangedEvent

地图缩放发生变化时发送的事件。

下面是处理地图缩放事件的示例。

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/events/EventsView.java[tags=notifications;MapZoomChangedEvent]
----

[[source-events]]
== 源事件

[[SourceFeatureClickEvent]]
=== SourceFeatureClickEvent

用户点击 xref:maps:features-geometries.adoc[地图要素] 时触发的事件。注意，如果用户双击，该事件会触发两次。

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/events/EventsView.java[tags=vectorSource;onInit;addSourceFeatureClickListener]
----

[[SourceFeatureSingleClickEvent]]
=== SourceFeatureSingleClickEvent

地图要素单击事件会延迟 250ms 发送，以确保用户不是双击。

[[SourceFeatureDoubleClickEvent]]
=== SourceFeatureDoubleClickEvent

用户双击地图要素时发送的事件。

[[SourceFeatureSelectEvent]]
=== SourceFeatureSelectEvent

该事件在选择或取消选择地图要素时触发。事件中仅包括刚选择或取消选择的要素。例如，如果已经选择了两个要素之一，此时选择剩下一个要素时，触发的该事件内仅包含第二个要素。

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/layers/SelectModeView.java[tags=notifications;featureSelectEvent]
----

[[SourceFeatureDragStartEvent]]
=== SourceFeatureDragStartEvent

该事件在用户开始拖拽地图要素时触发。

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/layers/DragModeView.java[tags=notifications;featureDragStartEvent]
----

[[SourceFeatureDragEndEvent]]
=== SourceFeatureDragEndEvent

该事件在用户完成拖拽地图要素时触发。

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/layers/DragModeView.java[tags=notifications;featureDragEndEvent]
----

[[SourceFeatureModifyStartEvent]]
=== SourceFeatureModifyStartEvent

该事件在开始编辑地图要素时触发。

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/layers/ModifyModeView.java[tags=notifications;featureModifyStartEvent]
----

[[SourceFeatureModifyEndEvent]]
=== SourceFeatureModifyEndEvent

该事件在完成编辑地图要素时触发。

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/layers/ModifyModeView.java[tags=notifications;featureModifyEndEvent]
----

[[SourceFeatureDeleteEvent]]
=== SourceFeatureDeleteEvent

当从源中删除一个要素时触发。

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/layers/ModifyModeView.java[tags=notifications;featureDeleteEvent]
----

[[GeoObjectClickEvent]]
=== GeoObjectClickEvent

用户点击地理对象时发送的事件。注意，如果用户双击，该事件会触发两次。

[source,java,indent=0]
----
include::example$/maps-ex1/src/main/java/com/company/onboarding/view/location/LocationDetailView.java[tags=dataVectorSource;notifications;onInit;addGeoObjectClickListener]
----

[[GeoObjectSingleClickEvent]]
=== GeoObjectSingleClickEvent

地理对象单击事件会延迟 250ms 发送，以确保用户不是双击。

[[GeoObjectDoubleClickEvent]]
=== GeoObjectDoubleClickEvent

用户双击地理对象时发送的事件。

[[GeoObjectSelectEvent]]
=== GeoObjectSelectEvent

该事件在选择或取消选择地理对象时触发。事件中仅包括刚选择或取消选择的对象。例如，如果已经选择了两个地理对象之一，此时选择剩下一个对象时，触发的该事件内仅包含第二个对象。

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/layers/SelectModeView.java[tags=notifications;selectEvent]
----

[[GeoObjectDragStartEvent]]
=== GeoObjectDragStartEvent

该事件在用户开始拖拽地理对象时触发。

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/layers/DragModeView.java[tags=notifications;dragStartEvent]
----

[[GeoObjectDragEndEvent]]
=== GeoObjectDragEndEvent

该事件在用户完成拖拽地理对象时触发。

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/layers/DragModeView.java[tags=notifications;dragEndEvent]
----

[[GeoObjectModifyStartEvent]]
=== GeoObjectModifyStartEvent

该事件在开始编辑地理对象时触发。

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/layers/ModifyModeView.java[tags=notifications;modifyStartEvent]
----

[[GeoObjectModifyEndEvent]]
=== GeoObjectModifyEndEvent

该事件在完成编辑地理对象时触发。

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/layers/ModifyModeView.java[tags=notifications;modifyEndEvent]
----

== 要素事件

[[FeatureClickEvent]]
=== FeatureClickEvent

用户点击地图要素时触发的事件。注意，如果用户双击地图，该事件会触发两次。

[[FeatureSingleClickEvent]]
=== FeatureSingleClickEvent

地图要素单击事件会延迟 250ms 发送，以确保用户不是双击。

[[FeatureDoubleClickEvent]]
=== FeatureDoubleClickEvent

用户双击地图要素时发送的事件。
