= События

Карта и объекты имеют следующие события.

==  События карты

[[MapClickEvent]]
=== MapClickEvent

Событие, которое возникает при щелчке по карте. Обратите внимание, что если пользователь дважды щелкнет, событие будет сработано дважды.

Ниже приведен пример обработки события щелчка по карте. Когда пользователь щелкает на карте, отображается уведомление с названием события и координатами места щелчка на карте:

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/events/EventsView.java[tags=geometryFactory;notifications;MapClickEvent]
----

[[MapSingleClickEvent]]
=== MapSingleClickEvent

Одиночное событие щелчка по карте возникает через 250 мс, чтобы убедиться, что это не двойной щелчок.

[[MapDoubleClickEvent]]
=== MapDoubleClickEvent

Событие возникает, когда пользователь выполняет двойной щелчок на карте.

Ниже приведен пример обработки события двойного щелчка по карте.

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/events/EventsView.java[tags=geoMap;MapDoubleClickEvent]
----

[[MapMoveEndEvent]]
=== MapMoveEndEvent

Событие возникает после перемещения карты (например, после масштабирования, панорамирования или перетаскивания карты).

Вот пример того, как обработать событие перемещения карты.

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/events/EventsView.java[tags=notifications;MapMoveEndEvent]
----

[[MapZoomChangedEvent]]
=== MapZoomChangedEvent

Событие срабатывает при изменении разрешения экрана карты.

Вот пример, демонстрирующий, как обработать событие изменения масштаба карты.

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/events/EventsView.java[tags=notifications;MapZoomChangedEvent]
----

[[source-events]]
== События источников

[[SourceFeatureClickEvent]]
=== SourceFeatureClickEvent

Событие, которое возникает при щелчке на xref:maps:features-geometries.adoc[объекте]. Обратите внимание: если пользователь выполнит двойной щелчок, событие будет сработано дважды.

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/events/EventsView.java[tags=vectorSource;onInit;addSourceFeatureClickListener]
----

[[SourceFeatureSingleClickEvent]]
=== SourceFeatureSingleClickEvent

Событие одиночного щелчка по объекту возникает через 250 мс, чтобы убедиться, что это не двойной щелчок.

[[SourceFeatureDoubleClickEvent]]
=== SourceFeatureDoubleClickEvent

Событие возникает, когда пользователь выполняет двойной щелчок на объекте.

[[SourceFeatureSelectEvent]]
=== SourceFeatureSelectEvent

Событие срабатывает при выборе или отмене выбора объектов. Имейте в виду, что событие включает только те объекты, которые были только что выбраны или отменены. Например, если один объект уже выбран из двух, а затем выбирается второй объект, событие будет содержать только новый выбранный объект.

[source,java,indent=0]
----
include::example$maps-ex2/src/main/java/com/company/mapssample/view/layers/SelectModeView.java[tags=notifications;featureSelectEvent]
----

[[SourceFeatureDragStartEvent]]
=== SourceFeatureDragStartEvent

Событие возникает, когда пользователь начинает перетаскивать объект.

[source,java,indent=0]
----
include::example$maps-ex2/src/main/java/com/company/mapssample/view/layers/DragModeView.java[tags=notifications;featureDragStartEvent]
----

[[SourceFeatureDragEndEvent]]
=== SourceFeatureDragEndEvent

Событие возникает, когда пользователь заканчивает перетаскивание объекта.

[source,java,indent=0]
----
include::example$maps-ex2/src/main/java/com/company/mapssample/view/layers/DragModeView.java[tags=notifications;featureDragEndEvent]
----

[[SourceFeatureModifyStartEvent]]
=== SourceFeatureModifyStartEvent

Событие возникает при начале изменения объекта.

[source,java,indent=0]
----
include::example$maps-ex2/src/main/java/com/company/mapssample/view/layers/ModifyModeView.java[tags=notifications;featureModifyStartEvent]
----

[[SourceFeatureModifyEndEvent]]
=== SourceFeatureModifyEndEvent

Событие возникает при завершении изменения объекта.

[source,java,indent=0]
----
include::example$maps-ex2/src/main/java/com/company/mapssample/view/layers/ModifyModeView.java[tags=notifications;featureModifyEndEvent]
----

[[SourceFeatureDeleteEvent]]
=== SourceFeatureDeleteEvent

Событие возникает, когда объект удаляется из источника.

[source,java,indent=0]
----
include::example$maps-ex2/src/main/java/com/company/mapssample/view/layers/ModifyModeView.java[tags=notifications;featureDeleteEvent]
----

[[GeoObjectClickEvent]]
=== GeoObjectClickEvent

Событие, которое возникает при щелчке на геообъекте. Обратите внимание: если пользователь выполнит двойной щелчок, событие будет сработано дважды.

[source,java,indent=0]
----
include::example$/maps-ex1/src/main/java/com/company/onboarding/view/location/LocationDetailView.java[tags=dataVectorSource;notifications;onInit;addGeoObjectClickListener]
----

[[GeoObjectSingleClickEvent]]
=== GeoObjectSingleClickEvent

Событие одиночного щелчка по геообъекту возникает через 250 мс, чтобы убедиться, что это не двойной щелчок.

[[GeoObjectDoubleClickEvent]]
=== GeoObjectDoubleClickEvent

Событие возникает, когда пользователь выполняет двойной щелчок на геообъекте.

[[GeoObjectSelectEvent]]
=== GeoObjectSelectEvent

Событие выбора срабатывает, когда геообъекты выбираются или отменяются. Имейте в виду, что событие включает только что выбранные или отмененные геообъекты. Например, если один геообъект уже выбран из двух, а затем вы выбираете второй геообъект, событие будет содержать информацию только о втором, только что выбранном геообъекте.

[source,java,indent=0]
----
include::example$maps-ex2/src/main/java/com/company/mapssample/view/layers/SelectModeView.java[tags=notifications;selectEvent]
----

[[GeoObjectDragStartEvent]]
=== GeoObjectDragStartEvent

Событие возникает, когда пользователь начинает перетаскивать геообъект.

[source,java,indent=0]
----
include::example$maps-ex2/src/main/java/com/company/mapssample/view/layers/DragModeView.java[tags=notifications;dragStartEvent]
----

[[GeoObjectDragEndEvent]]
=== GeoObjectDragEndEvent

Событие возникает, когда пользователь заканчивает перетаскивание геообъекта.

[source,java,indent=0]
----
include::example$maps-ex2/src/main/java/com/company/mapssample/view/layers/DragModeView.java[tags=notifications;dragEndEvent]
----

[[GeoObjectModifyStartEvent]]
=== GeoObjectModifyStartEvent

Событие возникает при начале изменения геообъекта.

[source,java,indent=0]
----
include::example$maps-ex2/src/main/java/com/company/mapssample/view/layers/ModifyModeView.java[tags=notifications;modifyStartEvent]
----

[[GeoObjectModifyEndEvent]]
=== GeoObjectModifyEndEvent

Событие возникает при завершении изменения геообъекта.

[source,java,indent=0]
----
include::example$maps-ex2/src/main/java/com/company/mapssample/view/layers/ModifyModeView.java[tags=notifications;modifyEndEvent]
----

== События объектов

[[FeatureClickEvent]]
=== FeatureClickEvent

Событие, которое возникает при щелчке на объекте. Обратите внимание: если пользователь выполнит двойной щелчок, событие будет сработано дважды.

[[FeatureSingleClickEvent]]
=== FeatureSingleClickEvent

Событие возникает через 250 мс, чтобы убедиться, что это не двойной щелчок.

[[FeatureDoubleClickEvent]]
=== FeatureDoubleClickEvent

Событие возникает, когда пользователь выполняет двойной щелчок на объекте.