= 地图要素和几何图形

== 地图要素

要素是指表示地图上元素的基本构建块。要素可以包括点、线、面或其他能在地图上提供空间信息的几何图形。

//Each feature typically contains attributes or properties that describe the characteristics of the geographical entity it represents.

要素可以有样式，并支持点击交互。要素在创建动态和交互式地图方面发挥着核心作用，开发人员可以通过地图要素有效地表示和操作地理数据。

// , and used for various spatial operations and analyses

`GeoMap` 具有下列地图要素：

* <<marker-feature,MarkerFeature>>
* <<point-feature,PointFeature>>
* <<line-string-feature,LineStringFeature>>
* <<polygon-feature,PolygonFeature>>
* <<multi-point-feature,MultiPointFeature>>
* <<multi-line-string-feature,MultiLineStringFeature>>
* <<multi-polygon-feature,MultiPolygonFeature>>

[[marker-feature]]
=== MarkerFeature

标记要素表示使用预定义 <<point-geometry,PointGeometry>> 的一个标记元素。在地图组件中显示为一个标记图标。

下面的示例演示了如何在地图中创建并放置一个标记：

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/features/FeaturesView.java[tags=vectorSource;onInit;addMarker]
----

[[point-feature]]
=== PointFeature

点要素表示使用预定义 <<point-geometry,PointGeometry>> 的一个点。在地图组件中显示为一个默认样式的点。更多内容请参阅 https://openlayers.org/en/v8.2.0/apidoc/module-ol_Feature-Feature.html[要素文档^]。

下面的示例演示了如何在地图中创建并放置一个点：

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/features/FeaturesView.java[tags=vectorSource;onInit;addPoint]
----

[[line-string-feature]]
=== LineStringFeature

`LineStringFeature` 表示地图中的线性要素，一般是多段线。使用预定义的 <<line-string-geometry,LineStringGeometry>>。更多内容请参阅 https://openlayers.org/en/v8.2.0/apidoc/module-ol_Feature-Feature.html[要素文档^]。

下面的示例演示了如何在地图中创建并放置一条多段线：

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/features/FeaturesView.java[tags=vectorSource;GeometryFactory;onInit;addLineString]
----

[[polygon-feature]]
=== PolygonFeature

`PolygonFeature` 表示地图中的封闭几何图形，定义一个区域或地区。这个要素用一组互相连接的点组成一个封闭的图形，一般是多边形。使用预定义的 <<line-string-geometry,LineStringGeometry>>。更多内容请参阅 https://openlayers.org/en/v8.2.0/apidoc/module-ol_Feature-Feature.html[要素文档^]。

下面的示例演示了如何在地图中创建并放置一个多边形：

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/features/FeaturesView.java[tags=vectorSource;GeometryFactory;onInit;addPolygon]
----

[[multi-marker-feature]]
=== MultiMarkerFeature

多标记要素表示使用 <<multi-point-geometry,MultiPointGeometry>> 定义的的一组标记元素。在地图组件中展示一组标记。

下面的示例演示了如何在地图中创建并放置一个多标记：

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/features/FeaturesView.java[tags=vSource;GeometryFactory;onInit;addMultiMarker]
----

[[multi-point-feature]]
=== MultiPointFeature

多点要素表示使用 <<multi-point-geometry,MultiPointGeometry>> 定义的的一组点元素。在地图组件中展示一组默认样式的点。更多详情请参阅： https://openlayers.org/en/v8.2.0/apidoc/module-ol_Feature-Feature.html[Feature documentation^]。

下面的示例演示了如何在地图中创建并放置 `MultiPointFeature`：

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/features/FeaturesView.java[tags=vSource;GeometryFactory;onInit;addMultiPoint]
----

[[multi-line-string-feature]]
=== MultiLineStringFeature

`MultiLineStringFeature` 表示地图上的线段，由一组多段线构成。`MultiLineStringFeature` 使用预定义的 <<multi-line-string-geometry,MultiLineStringGeometry>>。更多详情请参阅： https://openlayers.org/en/v8.2.0/apidoc/module-ol_Feature-Feature.html[Feature documentation^]。

下面的示例演示了如何在地图中创建并放置 `MultiLineStringFeature` ：

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/features/FeaturesView.java[tags=vSource;GeometryFactory;onInit;addMultiLineString]
----

[[multi-polygon-feature]]
=== MultiPolygonFeature

`MultiPolygonFeature` 表示由一组多边形构成的元素。其中，每个多边形是由一组点定义的闭合图形，这些点通过预定义的 <<multi-polygon-geometry,MultiPolygonGeometry>> 实现。更多详情请参阅： https://openlayers.org/en/v8.2.0/apidoc/module-ol_Feature-Feature.html[Feature documentation^]。

下面的示例演示了如何在地图中创建并放置 `MultiPolygonFeature`：

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/features/FeaturesView.java[tags=vSource;GeometryFactory;onInit;addMultiPolygon]
----

== Geometries

[[point-geometry]]
=== PointGeometry

`PointGeometry` 是一个包含 JTS 库中 `org.locationtech.jts.geom.Point` 的对象。

[[line-string-geometry]]
=== LineStringGeometry

`LineStringGeometry` 是一个包含 JTS 库中 `org.locationtech.jts.geom.LineString` 的对象。

[[polygon-geometry]]
=== PolygonGeometry

`PolygonGeometry` 是一个包含 JTS 库中 `org.locationtech.jts.geom.Polygon` 的对象。

[[multi-point-geometry]]
=== MultiPointGeometry

`MultiPointGeometry` 是一个包含 JTS 库中 `org.locationtech.jts.geom.MultiPoint` 的对象。

[[multi-line-string-geometry]]
=== MultiLineStringGeometry

`MultiLineStringGeometry` 是一个包含 JTS 库中 `org.locationtech.jts.geom.MultiLineString` 的对象。

[[multi-polygon-geometry]]
=== MultiPolygonGeometry

`MultiPolygonGeometry` 是一个包含 JTS 库中 `org.locationtech.jts.geom.MultiPolygon` 的对象。
