= Объекты и геометрии

== Объекты

Объект (Feature) относится к базовому строительному блоку, который представляет некоторый элемент на карте. Объекты могут включать точки, линии, полигоны или другие геометрии, которые предоставляют пространственную информацию на карте.

//Each feature typically contains attributes or properties that describe the characteristics of the geographical entity it represents.

Объекты могут быть стилизованы, на них можно кликать для взаимодействия. Они играют центральную роль в создании динамических и интерактивных карт, позволяя разработчикам эффективно представлять и манипулировать географическими данными.

// , and used for various spatial operations and analyses

`GeoMap` поддерживает следующие объекты:

* <<marker-feature,MarkerFeature>>
* <<point-feature,PointFeature>>
* <<line-string-feature,LineStringFeature>>
* <<polygon-feature,PolygonFeature>>
* <<multi-point-feature,MultiPointFeature>>
* <<multi-line-string-feature,MultiLineStringFeature>>
* <<multi-polygon-feature,MultiPolygonFeature>>

[[marker-feature]]
=== MarkerFeature

Объект-маркер представляет элемент маркера с предопределенной <<point-geometry,PointGeometry>>. Он отображается значком маркера в компоненте карты.

Следующий пример демонстрирует, как создать и разместить маркер на карте:

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/features/FeaturesView.java[tags=vectorSource;onInit;addMarker]
----

[[point-feature]]
=== PointFeature

Точечный объект представляет точку с предопределенной <<point-geometry,PointGeometry>>. Он отображается как точка со стилем по умолчанию. Для получения более подробной информации смотрите https://openlayers.org/en/v8.2.0/apidoc/module-ol_Feature-Feature.html[документацию Feature^].

Следующий пример демонстрирует, как создать и разместить точку на карте:

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/features/FeaturesView.java[tags=vectorSource;onInit;addPoint]
----

[[line-string-feature]]
=== LineStringFeature

`LineStringFeature` представляет линейный объект на карте, обычно отображаемый как полилиния, соединяющая несколько точек. Объект-полилиния поставляется с предопределенной <<line-string-geometry,LineStringGeometry>>. Для получения более подробной информации смотрите https://openlayers.org/en/v8.2.0/apidoc/module-ol_Feature-Feature.html[документацию Feature^].

Следующий пример демонстрирует, как создать и разместить полилинию на карте:

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/features/FeaturesView.java[tags=vectorSource;GeometryFactory;onInit;addLineString]
----

[[polygon-feature]]
=== PolygonFeature

`PolygonFeature` представляет замкнутую геометрическую фигуру на карте, определяющую область или регион. Этот объект используется для отображения и работы с полигонами, которые определяются коллекцией взаимосвязанных точек, образующих замкнутый контур. Объект-полигон поставляется с предопределенной <<polygon-geometry,PolygonGeometry>>. Для получения более подробной информации смотрите https://openlayers.org/en/v8.2.0/apidoc/module-ol_Feature-Feature.html[документацию Feature^].

Следующий пример демонстрирует, как создать и разместить полигон на карте:

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/features/FeaturesView.java[tags=vectorSource;GeometryFactory;onInit;addPolygon]
----

[[multi-marker-feature]]
=== MultiMarkerFeature

Объект-мультимаркер представляет коллекцию элементов маркеров с предопределенной <<multi-point-geometry,MultiPointGeometry>>. Он отображается значками маркеров в компоненте карты.

Следующий пример демонстрирует, как создать и разместить `MultiMarkerFeature` на карте:

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/features/FeaturesView.java[tags=vSource;GeometryFactory;onInit;addMultiMarker]
----

[[multi-point-feature]]
=== MultiPointFeature

Объект-мультиточка представляет мультиточку с предопределенной <<multi-point-geometry,MultiPointGeometry>>. Он отображается как точки со стилем по умолчанию. Для получения более подробной информации смотрите https://openlayers.org/en/v8.2.0/apidoc/module-ol_Feature-Feature.html[документацию Feature^].

Следующий пример демонстрирует, как создать и разместить мультиточку на карте:

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/features/FeaturesView.java[tags=vSource;GeometryFactory;onInit;addMultiPoint]
----

[[multi-line-string-feature]]
=== MultiLineStringFeature

`MultiLineStringFeature` представляет линейные объекты на карте, обычно отображаемые как коллекция нескольких линейных строк. `MultiLineStringFeature` поставляется с предопределенной <<multi-line-string-geometry,MultiLineStringGeometry>>. Для получения более подробной информации смотрите https://openlayers.org/en/v8.2.0/apidoc/module-ol_Feature-Feature.html[документацию Feature^].

Следующий пример демонстрирует, как создать и разместить мультилинию на карте:

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/features/FeaturesView.java[tags=vSource;GeometryFactory;onInit;addMultiLineString]
----

[[multi-polygon-feature]]
=== MultiPolygonFeature

`MultiPolygonFeature` представляет геометрию, состоящую из нескольких сгруппированных вместе полигонов. Каждый полигон в `MultiPolygonFeature` состоит из замкнутой формы, определенной последовательностью точек, и поставляется с предопределенной <<multi-polygon-geometry,MultiPolygonGeometry>>. Для получения более подробной информации смотрите https://openlayers.org/en/v8.2.0/apidoc/module-ol_Feature-Feature.html[документацию Feature^].

Следующий пример демонстрирует, как создать и разместить `MultiPolygonFeature` на карте:

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/features/FeaturesView.java[tags=vSource;GeometryFactory;onInit;addMultiPolygon]
----

== Геометрии

[[point-geometry]]
=== PointGeometry

`PointGeometry` - это объект, содержащий `org.locationtech.jts.geom.Point` из библиотеки JTS.

[[line-string-geometry]]
=== LineStringGeometry

`LineStringGeometry` - это объект, содержащий `org.locationtech.jts.geom.LineString` из библиотеки JTS.

[[polygon-geometry]]
=== PolygonGeometry

`PolygonGeometry` - это объект, содержащий `org.locationtech.jts.geom.Polygon` из библиотеки JTS.

[[multi-point-geometry]]
=== MultiPointGeometry

`MultiPointGeometry` - это объект, содержащий `org.locationtech.jts.geom.MultiPoint` из библиотеки JTS.

[[multi-line-string-geometry]]
=== MultiLineStringGeometry

`MultiLineStringGeometry` - это объект, содержащий `org.locationtech.jts.geom.MultiLineString` из библиотеки JTS.

[[multi-polygon-geometry]]
=== MultiPolygonGeometry

`MultiPolygonGeometry` - это объект, содержащий `org.locationtech.jts.geom.MultiPolygon` из библиотеки JTS.