= Features and Geometries

== Features

A feature is a basic building block that represents an element on a map. Features can include points, lines, polygons, or other geometries that provide spatial information on the map.

//Each feature typically contains attributes or properties that describe the characteristics of the geographical entity it represents.

Features can be styled and clicked for interaction. They play a central role in creating dynamic and interactive maps by allowing developers to represent and manipulate geographic data efficiently.

// , and used for various spatial operations and analyses

`GeoMap` supports the following features:

* <<marker-feature,MarkerFeature>>
* <<point-feature,PointFeature>>
* <<line-string-feature,LineStringFeature>>
* <<polygon-feature,PolygonFeature>>
* <<multi-point-feature,MultiPointFeature>>
* <<multi-line-string-feature,MultiLineStringFeature>>
* <<multi-polygon-feature,MultiPolygonFeature>>

[[marker-feature]]
=== MarkerFeature

A marker feature represents a marker element with predefined <<point-geometry,PointGeometry>>. It is displayed with a marker icon in a map component.

The following example demonstrates how to create and place a marker on a map:

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/features/FeaturesView.java[tags=vectorSource;onInit;addMarker]
----

[[point-feature]]
=== PointFeature

Point feature represents a point with predefined <<point-geometry,PointGeometry>>. It is displayed as a point with default style. For more details see https://openlayers.org/en/v8.2.0/apidoc/module-ol_Feature-Feature.html[Feature documentation^].

The following example demonstrates how to create and place a point on a map:

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/features/FeaturesView.java[tags=vectorSource;onInit;addPoint]
----

[[line-string-feature]]
=== LineStringFeature

`LineStringFeature` represents a linear feature on a map, typically drawn as a polyline connecting multiple points. The polyline feature comes with a predefined <<line-string-geometry,LineStringGeometry>>. For more details see https://openlayers.org/en/v8.2.0/apidoc/module-ol_Feature-Feature.html[Feature documentation^].

The following example demonstrates how to create and place a polyline on a map:

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/features/FeaturesView.java[tags=vectorSource;GeometryFactory;onInit;addLineString]
----

[[polygon-feature]]
=== PolygonFeature

`PolygonFeature` represents a closed geometric shape on a map that defines an area or region. This feature is used to display and work with polygons, which are defined by a collection of interconnected points forming a closed loop. The polygon feature comes with a predefined <<polygon-geometry,PolygonGeometry>>. For more details see https://openlayers.org/en/v8.2.0/apidoc/module-ol_Feature-Feature.html[Feature documentation^].

The following example demonstrates how to create and place a polygon on a map:

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/features/FeaturesView.java[tags=vectorSource;GeometryFactory;onInit;addPolygon]
----

[[multi-marker-feature]]
=== MultiMarkerFeature

Multi marker feature represents a collection of marker elements with predefined <<multi-point-geometry,MultiPointGeometry>>. It is displayed with marker icons in a map component.

The following example demonstrates how to create and place `MultiMarkerFeature` on a map:

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/features/FeaturesView.java[tags=vSource;GeometryFactory;onInit;addMultiMarker]
----

[[multi-point-feature]]
=== MultiPointFeature

Multipoint feature represents a multipoint with predefined <<multi-point-geometry,MultiPointGeometry>>. It is displayed as points with default style. For more details see https://openlayers.org/en/v8.2.0/apidoc/module-ol_Feature-Feature.html[Feature documentation^].

The following example demonstrates how to create and place a multipoint on a map:

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/features/FeaturesView.java[tags=vSource;GeometryFactory;onInit;addMultiPoint]
----

[[multi-line-string-feature]]
=== MultiLineStringFeature

`MultiLineStringFeature` represents linear features on a map, typically drawn as a collection of multiple line strings. `MultiLineStringFeature` comes with a predefined <<multi-line-string-geometry,MultiLineStringGeometry>>. For more details see https://openlayers.org/en/v8.2.0/apidoc/module-ol_Feature-Feature.html[Feature documentation^].

The following example demonstrates how to create and place a multiline on a map:

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/features/FeaturesView.java[tags=vSource;GeometryFactory;onInit;addMultiLineString]
----

[[multi-polygon-feature]]
=== MultiPolygonFeature

`MultiPolygonFeature` represents a geometry consisting of multiple polygons grouped together. Each polygon within `MultiPolygonFeature` comprises a closed shape defined by a sequence of points, and comes with a predefined <<multi-polygon-geometry,MultiPolygonGeometry>>. For more details see https://openlayers.org/en/v8.2.0/apidoc/module-ol_Feature-Feature.html[Feature documentation^].

The following example demonstrates how to create and place `MultiPolygonFeature` on a map:

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/features/FeaturesView.java[tags=vSource;GeometryFactory;onInit;addMultiPolygon]
----

== Geometries

[[point-geometry]]
=== PointGeometry

`PointGeometry` is an object that contains `org.locationtech.jts.geom.Point` from the JTS library.

[[line-string-geometry]]
=== LineStringGeometry

`LineStringGeometry` is an object that contains `org.locationtech.jts.geom.LineString` from the JTS library.

[[polygon-geometry]]
=== PolygonGeometry

`PolygonGeometry` is an object that contains `org.locationtech.jts.geom.Polygon` from the JTS library.

[[multi-point-geometry]]
=== MultiPointGeometry

`MultiPointGeometry` is an object that contains `org.locationtech.jts.geom.MultiPoint` from the JTS library.

[[multi-line-string-geometry]]
=== MultiLineStringGeometry

`MultiLineStringGeometry` is an object that contains `org.locationtech.jts.geom.MultiLineString` from the JTS library.

[[multi-polygon-geometry]]
=== MultiPolygonGeometry

`MultiPolygonGeometry` is an object that contains `org.locationtech.jts.geom.MultiPolygon` from the JTS library.