= Начало работы с Maps
:page-aliases: maps:quick-start.adoc

Это руководство содержит инструкции по началу интеграции карт в ваше приложение.

Мы будем использовать приложение Onboarding в качестве отправной точки.

Если вы еще не создали это приложение, вы можете обратиться к разделу xref:tutorial:index.adoc[Руководство], который предлагает подробное пошаговое руководство по разработке приложения.

В противном случае загрузите полный исходный код приложения из репозитория GitHub https://github.com/jmix-framework/jmix-onboarding-2[jmix-framework/jmix-onboarding-2^]. Затем следуйте инструкциям в разделе xref:studio:project.adoc#opening-existing-project[Открытие существующего проекта], чтобы открыть его в Jmix Studio.

Добавьте дополнение Maps в соответствии с разделом xref:index.adoc#installation[установки].

Давайте рассмотрим модель данных приложения onboarding.

image::data-model-diagram.svg[align="center"]

Мы добавим новую сущность - `Location` (Местоположение). В приложении представлено два типа местоположений: офис и коворкинг. Когда менеджер по персоналу создает карточку пользователя, он выбирает базовое местоположение - офис, в котором пользователь должен работать.

* Пользователи должны иметь возможность просматривать все доступные местоположения, отмеченные маркерами на карте.
* Офисы и коворкинги должны быть отмечены разными маркерами.
* Пользователи должны иметь возможность изменять базовое местоположение, щелкая на маркер карты.