= 4. Set Up Interaction Between Views

The user ought to have the capability to modify and save the base location by clicking on the map marker. As of now, our application doesn't offer this functionality.

Go to the `LocationLookupView` view controller and create setter and getter methods to pass the location we want to display or save.

[source,java,indent=0]
----
include::example$/maps-ex1/src/main/java/com/company/onboarding/view/locationlookup/LocationLookupView.java[tags=location-param]
----

Navigate to the `UserDetailView` view controller and locate the `onLocationFieldSelect()` handler. Our goal is not only to open a dialog, but also to pass the previously saved location for the edited user. Additionally, we need to retrieve a result from the dialog once it has been closed. Let’s proceed with the necessary modifications to the handler:

[source,java,indent=0]
----
include::example$/maps-ex1/src/main/java/com/company/onboarding/view/user/UserDetailView.java[tags=locationField;onLocationFieldSelect]
----
<1> The `AfterCloseEvent` object contains `CloseAction` passed to the view’s `close()` method. We analyze the close action using the `closedWith()` method of the event object. Remember: in the previous section, we established a xref:maps:dispay-markers.adoc#select-action-handler[handler] for the `select` action.
<2> Passes the edited user's location to the setter of `LocationLookupView`.

Launch the application and make sure that the interaction between `UserDetailView` and `LocationLookupView` is correctly configured.