= 4. Настройка взаимодействия между экранами

Пользователь должен иметь возможность изменять и сохранять базовое местоположение, щелкая на маркере карты. На данный момент наше приложение не предоставляет эту функциональность.

Перейдите к контроллеру экрана `LocationLookupView` и создайте методы setter и getter для передачи местоположения, которое мы хотим отобразить или сохранить.

[source,java,indent=0]
----
include::example$/maps-ex1/src/main/java/com/company/onboarding/view/locationlookup/LocationLookupView.java[tags=location-param]
----

Перейдите к контроллеру экрана `UserDetailView` и найдите обработчик `onLocationFieldSelect()`. Наша цель - не только открыть диалог, но и передать ранее сохраненное местоположение для редактируемого пользователя. Кроме того, нам нужно получить результат из диалога после его закрытия. Давайте внесем необходимые изменения в обработчик:

[source,java,indent=0]
----
include::example$/maps-ex1/src/main/java/com/company/onboarding/view/user/UserDetailView.java[tags=locationField;onLocationFieldSelect]
----
<1> Объект `AfterCloseEvent` содержит `CloseAction`, переданный в метод `close()` экрана. Мы анализируем действие закрытия с помощью метода `closedWith()` объекта события. Помните: в предыдущем разделе мы установили xref:maps:dispay-markers.adoc#select-action-handler[обработчик] для действия `select`.
<2> Передает местоположение редактируемого пользователя в setter `LocationLookupView`.

Запустите приложение и убедитесь, что взаимодействие между `UserDetailView` и `LocationLookupView` настроено правильно.