= 图层和数据源

图层（Layer）是在地图上的一种数据组织方法。

图层可以是栅格层（raster）或矢量层（vector），栅格层由栅格图像（像素矩阵）组成，而矢量层由矢量几何图形组成。

[[tile-layer]]
== 瓦片层（TileLayer）

瓦片层（Tile Layer）的源需要能提供预渲染的地图瓦片，这些瓦片按缩放级别不同（在特定分辨率展示）提供不同的瓦片矩阵。

更多详情请参阅 https://openlayers.org/en/v8.2.0/apidoc/module-ol_layer_Tile-TileLayer.html[TileLayer 文档^]。

`TileLayer` 支持三种源：

* <<osm-source,OsmSource>>
* <<xyz-source,XyzSource>>
* <<wms-source,WmsSource>>

[[osm-source]]
=== OsmSource

这个源的瓦片数据是从 https://www.openstreetmap.org[OpenStreetMap^] 瓦片服务和 xref:maps:map-services.adoc#xyz-tiles[XYZ 瓦片] 服务加载。更多详情请参阅 https://openlayers.org/en/v8.2.0/apidoc/module-ol_source_OSM-OSM.html[OSM 文档^]。

下面的示例演示了如何展示 OpenStreetMap 瓦片层。

[source,xml,indent=0]
----
include::example$/maps-ex2/src/main/resources/com/company/mapssample/view/layers/layers-view.xml[tags=osmSource]
----

[[xyz-source]]
=== XyzSource

这个源的瓦片数据是在 URL 模板中定义一组 XYZ 格式的 URL。默认情况下，遵循 Google 矩阵的定义：x 0 和 y 0 位于左上角。`XyzSource` 可以加载 xref:maps:map-services.adoc#xyz-tiles[XYZ tile] 服务提供的瓦片。更多详情请参阅 https://openlayers.org/en/v8.2.0/apidoc/module-ol_source_XYZ-XYZ.html[XYZ 文档^]。

下面的示例演示了如何展示 Thunderforest 瓦片层。

[source,xml,indent=0]
----
include::example$/maps-ex2/src/main/resources/com/company/mapssample/view/layers/layers-view.xml[tags=xyzSource]
----

[[wms-source]]
=== WmsSource

这个源的瓦片数据是从 xref:maps:map-services.adoc#web-map-service[WMS]（Web Map Service）服务加载。更多详情请参阅 https://openlayers.org/en/v8.2.0/apidoc/module-ol_source_TileWMS-TileWMS.html[TileWMS 文档^]。

下面的示例演示了如何展示 `WmsSource` 瓦片层。

[source,xml,indent=0]
----
include::example$/maps-ex2/src/main/resources/com/company/mapssample/view/layers/layers-view.xml[tags=wmsSource]
----

[[image-layer]]
== 图像层（ImageLayer）

`ImageLayer` 用于处理静态图片或 WMS 图片。

//Layer with server-rendered images that are available for arbitrary extents and resolutions.

[[image-static-source]]
=== ImageStaticSource

这个源展示单一静态图片。更多详情请参阅 https://openlayers.org/en/v8.2.0/apidoc/module-ol_source_ImageStatic-Static.html[Static 文档^]。

这个示例展示使用 URL 的图片。取自 https://openlayers.org/en/latest/examples/static-image.html[OpenLayers -> Examples -> Static image^]：

[source,xml,indent=0]
----
include::example$/maps-ex2/src/main/resources/com/company/mapssample/view/layers/layers-view.xml[tags=imagestatic]
----

如需展示 classpath 中的图片，可以按照下面示例中的方法在 XML 定义：

[source,xml,indent=0]
----
include::example$/maps-ex2/src/main/resources/com/company/mapssample/view/layers/layers-view.xml[tags=imagestatic-classpath]
----

此外，在 Java 控制器中可以通过 `StreamResource` 实现：

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/layers/LayersView.java[tags=programmaticMap;onInit]
----

[[image-wms-source]]
=== ImageWmsSource

这个源从 xref:maps:map-services.adoc#web-map-service[WMS] 服务加载单一未命名图片。更多详情请参阅 https://openlayers.org/en/v8.2.0/apidoc/module-ol_source_ImageWMS-ImageWMS.html[ImageWMS 文档^]。

使用 `ImageWmsSource` 的示例取自 https://openlayers.org/en/latest/examples/wms-image.html[OpenLayers -> Examples -> Single Image WMS]：

[source,xml,indent=0]
----
include::example$/maps-ex2/src/main/resources/com/company/mapssample/view/layers/layers-view.xml[tags=imageWmsSource]
----

[[vector-layer]]
== 矢量层（VectorLayer）

矢量层用于处理几何图形。一个地图可以添加多个矢量层。

[[vector-source]]
=== VectorSource

这个源处理地图要素。更多详情请参阅 https://openlayers.org/en/v8.2.0/apidoc/module-ol_source_Vector-VectorSource.html[VectorSource 文档^]。

下面的示例演示了如何展示 `VectorSource` 矢量层。首先，在 XML 中定义一个地图：

[source,xml,indent=0]
----
include::example$/maps-ex2/src/main/resources/com/company/mapssample/view/layers/layers-view.xml[tags=vectorSource]
----

然后，打开视图控制器并在地图中添加标记：

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/layers/LayersView.java[tags=vectorSource;onInit;mapwithvector]
----
<1> 添加标记要素。

[[data-vector-source]]
=== DataVectorSource

`DataVectorSource` 支持通过 `dataContainer` 和 `property` 属性绑定 Jmix 数据容器。`property` 可以是属性名或者属性路径。

[source,xml,indent=0]
----
include::example$/maps-ex1/src/main/resources/com/company/onboarding/view/location/location-detail-view.xml[tags=geoMap]
----

[source,xml,indent=0]
----
<maps:vector id="vectorLayer">
    <maps:dataVectorSource dataContainer="ordersDc"
                           property="customer.address.point"/>
</maps:vector>
----
