= Слои и источники

Слой (Layer) - это способ организации данных на карте.

Слои могут быть растровыми или векторными. Растровые слои состоят из растровых изображений, которые представляют собой сетку пикселей, в то время как векторные слои состоят из векторных геометрий.

[[tile-layer]]
== TileLayer

Тайловый слой (`TileLayer`) - слой с источниками, которые предоставляют предварительно отрендеренные, разбитые на тайлы (плитки) изображения в сетках, организованных по уровням масштабирования для определенных разрешений.

Для получения более подробной информации см. https://openlayers.org/en/v8.2.0/apidoc/module-ol_layer_Tile-TileLayer.html[документацию TileLayer^].

`TileLayer` поддерживает три источника:

* <<osm-source,OsmSource>>
* <<xyz-source,XyzSource>>
* <<wms-source,WmsSource>>

[[osm-source]]
=== OsmSource

Источник для загрузки тайлов с сервера https://www.openstreetmap.org[OpenStreetMap^] и из сервисов xref:maps:map-services.adoc#xyz-tiles[XYZ tile]. Для получения более подробной информации смотрите https://openlayers.org/en/v8.2.0/apidoc/module-ol_source_OSM-OSM.html[документацию OSM^].

Следующий пример демонстрирует, как отобразить тайловый слой `OpenStreetMap`.

[source,xml,indent=0]
----
include::example$/maps-ex2/src/main/resources/com/company/mapssample/view/layers/layers-view.xml[tags=osmSource]
----

[[xyz-source]]
=== XyzSource

Источник для тайловых данных с URL-адресами в заданном формате XYZ, которые определены в шаблоне URL. По умолчанию используется широко распространенная сетка Google, где x 0 и y 0 находятся в левом верхнем углу. `XyzSource` может загружать тайлы из сервисов xref:maps:map-services.adoc#xyz-tiles[XYZ tile]. Для получения более подробной информации смотрите https://openlayers.org/en/v8.2.0/apidoc/module-ol_source_XYZ-XYZ.html[документацию XYZ^].

Следующий пример демонстрирует, как отобразить тайловый слой `Thunderforest`.

[source,xml,indent=0]
----
include::example$/maps-ex2/src/main/resources/com/company/mapssample/view/layers/layers-view.xml[tags=xyzSource]
----

[[wms-source]]
=== WmsSource

Источник для тайловых данных с xref:maps:map-services.adoc#web-map-service[WMS] (Web Map Service) серверов. Для получения более подробной информации смотрите https://openlayers.org/en/v8.2.0/apidoc/module-ol_source_TileWMS-TileWMS.html[документацию TileWMS^].

Следующий пример демонстрирует, как отобразить тайловый слой с `WmsSource`.

[source,xml,indent=0]
----
include::example$/maps-ex2/src/main/resources/com/company/mapssample/view/layers/layers-view.xml[tags=wmsSource]
----

[[image-layer]]
== ImageLayer

Растровый слой (`ImageLayer`) используется для работы со статическими изображениями или WMS-изображениями.

//Layer with server-rendered images that are available for arbitrary extents and resolutions.

[[image-static-source]]
=== ImageStaticSource

Источник для отображения одного статического изображения. Для получения более подробной информации смотрите https://openlayers.org/en/v8.2.0/apidoc/module-ol_source_ImageStatic-Static.html[документацию Static^].

Пример показа изображения по URL. Этот пример взят из https://openlayers.org/en/latest/examples/static-image.html[OpenLayers -> Examples -> Static image^].

[source,xml,indent=0]
----
include::example$/maps-ex2/src/main/resources/com/company/mapssample/view/layers/layers-view.xml[tags=imagestatic]
----

Чтобы отобразить изображение из classpath, определите XML таким же образом, как показано в примере выше:

[source,xml,indent=0]
----
include::example$/maps-ex2/src/main/resources/com/company/mapssample/view/layers/layers-view.xml[tags=imagestatic-classpath]
----

Дополнительно этого можно достичь в Java-контроллере с помощью `StreamResource`:

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/layers/LayersView.java[tags=programmaticSource;onInit;programmaticMap]
----

[[image-wms-source]]
=== ImageWmsSource

Источник для xref:maps:map-services.adoc#web-map-service[WMS] серверов, предоставляющих одиночные, не разбитые на тайлы изображения. Для получения более подробной информации смотрите https://openlayers.org/en/v8.2.0/apidoc/module-ol_source_ImageWMS-ImageWMS.html[документацию ImageWMS^].

Пример использования `ImageWmsSource` взят из https://openlayers.org/en/latest/examples/wms-image.html[OpenLayers -> Examples -> Single Image WMS]:

[source,xml,indent=0]
----
include::example$/maps-ex2/src/main/resources/com/company/mapssample/view/layers/layers-view.xml[tags=imageWmsSource]
----

[[vector-layer]]
== VectorLayer

Векторный слой (`VectorLayer`) используется для работы с геометриями. На карту можно добавить несколько векторных слоев.

[[vector-source]]
=== VectorSource

Источник для работы с объектами (features). Для получения более подробной информации смотрите https://openlayers.org/en/v8.2.0/apidoc/module-ol_source_Vector-VectorSource.html[документацию VectorSource^].

Следующий пример демонстрирует, как отобразить векторный слой с `VectorSource`. Сначала определите карту в XML-дескрипторе:

[source,xml,indent=0]
----
include::example$/maps-ex2/src/main/resources/com/company/mapssample/view/layers/layers-view.xml[tags=vectorSource]
----

Затем откройте контроллер экрана и добавьте созданный маркер на карту:

[source,java,indent=0]
----
include::example$/maps-ex2/src/main/java/com/company/mapssample/view/layers/LayersView.java[tags=vectorSource;onInit;mapwithvector]
----
<1> Добавляет объект-маркер в источник.

[[data-vector-source]]
=== DataVectorSource

`DataVectorSource` позволяет выполнять привязку данных к контейнерам данных Jmix через атрибуты `dataContainer` и `property`. Атрибут `property` может принимать как простое свойство, так и путь к свойству (property path).

[source,xml,indent=0]
----
include::example$/maps-ex1/src/main/resources/com/company/onboarding/view/location/location-detail-view.xml[tags=geoMap]
----

[source,xml,indent=0]
----
<maps:vector id="vectorLayer">
    <maps:dataVectorSource dataContainer="ordersDc"
                           property="customer.address.point"/>
</maps:vector>
----