= Сервисы карт

[[web-map-service]]
== Веб-сервис карт

Веб-сервис карт (WMS) - это стандарт http://www.opengeospatial.org/[OGC^] для предоставления картографических изображений по HTTP. Изображения карт обычно генерируются карт-сервером с использованием данных из ГИС-базы данных. Этот формат похож на тайлы карт, но является более общим и не так хорошо оптимизирован для использования в веб-приложениях.

WMS поддерживает ряд различных типов запросов, но основные операции это:

* *GetCapabilities* - операция, возвращающая XML-документ с описанием сервиса (поддерживаемые параметры, форматы изображений, доступные слои и т.д.).
* *GetMap* - операция, возвращающая изображение карты для указанной области и содержимого. Дополнение использует эту операцию для получения изображений из WMS.

Важно не путать концепцию слоя в дополнении со слоем в WMS. WMS предоставляет набор слоев, определенных в XML-документе *GetCapabilities*. Слой WMS в дополнении отображает результирующие изображения, предоставляемые WMS. Эти изображения строятся с использованием одного или нескольких слоев WMS.

Дополнение не работает с операцией *GetCapabilities*, поэтому информацию о доступных слоях в WMS можно узнать одним из следующих способов:

* Найти ее в XML-документе *GetCapabilities*. Его можно получить, отправив URL-запрос на сервер и получив ответ в виде XML-документа. URL-запрос выглядит так: `BASE_WMS_URL?request=GetCapabilities`.
* Использовать ГИС-программное обеспечение (например, https://qgis.org/en/site/[QGIS^]). http://www.qgistutorials.com/en/docs/working_with_wms.html[Смотрите^] руководство по работе с WMS в QGIS.

[[xyz-tiles]]
== XYZ тайлы

XYZ - это стандарт OpenStreetMap де-факто, также известный как https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames[Slippy Map Tilenames^], который определяет схему для тайлов, обслуживаемых через веб-сервер.

Эти тайлы доступны через URL, соответствующий определенному шаблону: `\http://.../\{z}/\{x}/\{y}.png`, где `z` - уровень масштабирования, а `x`,`y` идентифицируют тайл.

Например, шаблон URL тайлов https://www.openstreetmap.org/[OpenStreetMap^] такой: `\https://\{s}.tile.openstreetmap.org/\{z}/\{x}/\{y}.png`.

Полезные ссылки:

* https://wiki.openstreetmap.org/wiki/Tile_servers[Тайловые серверы^] на основе данных OpenStreetMap.
* https://leaflet-extras.github.io/leaflet-providers/preview/[Превью тайловых провайдеров^] - здесь можно найти и просмотреть различные сервисы XYZ тайлов. Некоторые из них бесплатны, в то время как другие требуют регистрации и могут иметь ограничение на количество бесплатных запросов тайлов. Обязательно проверяйте политики использования провайдеров перед их применением.
* https://docs.mapbox.com/api/maps/[Mapbox^] тайловый API.
* https://developer.here.com/documentation/map-tile/topics/quick-start-map-tile.html[HERE^] тайловый API.