= Map Services

[[web-map-service]]
== Web Map Service

Web Map Service (WMS) is an http://www.opengeospatial.org/[OGC] standard for serving map images over HTTP. Map images are usually generated by a map server using data from a GIS database. This format is similar to map tiles, but more general and not as well optimized for use in web applications.

WMS supports a number of different request types, but the main operations are:

* *GetCapabilities* — an operation that returns an XML document describing the service (supported parameters, image formats, available layers, etc.).
* *GetMap*  — an operation that returns a map image for a specified area and content. The add-on uses this operation to obtain images from WMS.

It's important not to confuse the concept of the add-on's layer with the layer in WMS. WMS provides a set of layers defined in the `GetCapabilities` XML document. The WMS Layer of the add-on displays the resulting images provided by WMS. These images are being built using one or more layers in WMS.

The add-on does not work with the *GetCapabilities* operation, so you can find information about the available layers in WMS in one of the following ways:

* Find it in the `GetCapabilities` XML document. You can obtain it by sending a URL request to the server and getting the response as an XML document. The URL request looks like this: `BASE_WMS_URL?request=GetCapabilities`.
* Use a GIS software (such as https://qgis.org/en/site/[QGIS]). http://www.qgistutorials.com/en/docs/working_with_wms.html[See] a tutorial on how to work with WMS in QGIS.

[[xyz-tiles]]
== XYZ Tiles

XYZ is a de facto OpenStreetMap standard, also known as https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames[Slippy Map Tilenames], defining a scheme for tiles that are served through a web server.

These tiles can be accessed via a URL following a certain pattern: `\http://.../\{z}/\{x}/\{y}.png`, where `z` is the zoom level, and `x`,`y` identify the tile.

For example, https://www.openstreetmap.org/[OpenStreetMap] tiles URL pattern is: `\https://\{s}.tile.openstreetmap.org/\{z}/\{x}/\{y}.png`.

Useful links:

* https://wiki.openstreetmap.org/wiki/Tile_servers[Tile servers] based on OpenStreetMap data.
* https://leaflet-extras.github.io/leaflet-providers/preview/[Tile providers preview] — here you can find and preview various XYZ tile services. Some of them are free, while others require registration and may have free tile requests limit. Be sure to check the providers usage policies before using them.
* https://docs.mapbox.com/api/maps/[Mapbox] tile API.
* https://developer.here.com/documentation/map-tile/topics/quick-start-map-tile.html[HERE] tile API.