= 地图服务

[[web-map-service]]
== 网络地图服务

网络地图服务（WMS）是一个 http://www.opengeospatial.org/[OGC^] 标准，通过 HTTP 提供地图图像。地图图像通常由地图服务器使用 GIS 数据库中的数据生成。这种格式类似于地图瓦片，但更通用，并且没有专门为在 Web 应用程序中使用做过优化。

WMS 支持多种不同的请求类型，但主要操作有：

* *GetCapabilities* — 返回描述服务的 XML 文档（包括支持的参数、图像格式、可用层等）的操作。
* *GetMap* — 返回指定区域和内容的地图图像的操作。此扩展组件使用此操作从 WMS 获取图像。

有一点很重要，不要将扩展组件中层的概念与 WMS 中的层混淆。WMS 提供了一组在 `GetCapabilities` XML 文档中定义的层。扩展组件的 WMS 层显示 WMS 提供的结果图像，是使用 WMS 中的一个或多个图层构建的。

该扩展组件不支持 *GetCapabilities* 操作，因此可以通过以下方式之一找到有关 WMS 中可用图层的信息：

* 在 `GetCapabilities` XML 文档中查找。可以通过向服务器发送 URL 请求并以 XML 文档格式解析响应获取此文档。URL 请求如下所示：`BASE_WMS_URL?request=GetCapabilities`。
* 使用 GIS 软件（例如 https://qgis.org/en/site/[QGIS^]）。请参阅关于如何在 QGIS 中使用 WMS 的 http://www.qgistutorials.com/en/docs/working_with_wms.html[教程^]。

[[xyz-tiles]]
== XYZ 瓦片

XYZ 是事实上的 OpenStreetMap 标准，也称为 https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames[Slippy Map Tilenames^]，定义通过 Web 服务器提供服务的瓦片结构。

这些瓦片可以通过遵循特定范式的 URL 访问：`\http://.../\{z}/\{x}/\{y}.png`，其中 `z` 是缩放级别，而 `x`、`y` 表示瓦片。

例如， https://www.openstreetmap.org/[OpenStreetMap^] 瓦片 URL 模式为：`\https://\{s}.tile.openstreetmap.org/\{z}/\{x}/\{y}.png`。

有用的链接：

* https://wiki.openstreetmap.org/wiki/Tile_servers[瓦片服务^]，基于 OpenStreetMap 的数据。
* https://leaflet-extras.github.io/leaflet-providers/preview/[瓦片供应商预览^] — 在这里可以找到并预览各种 XYZ 瓦片服务。其中一些是免费的，而另一些则需要注册并且可能有免费瓦片请求限制。请确保在使用之前检查供应商的使用政策。
* https://docs.mapbox.com/api/maps/[Mapbox] 瓦片 API。
* https://developer.here.com/documentation/map-tile/topics/quick-start-map-tile.html[HERE] 瓦片 API。
