= Reports Configuration

[[app_properties]]
== Application Properties

This section describes the application properties related to the Reports add-on in alphabetical order.

[[jmix.reports.client.background-report-processing-timeout-ms]]
=== jmix.reports.client.background-report-processing-timeout-ms

Defines the processing timeout in milliseconds for the report execution if the <<jmix.reports.client.use-background-report-processing,jmix.reports.client.use-background-report-processing>> is set to `true`.

Default value: `10000`.

[[jmix.reports.client.enable-tab-symbol-in-data-set-editor]]
=== jmix.reports.client.enable-tab-symbol-in-data-set-editor

Defines whether the TAB key should be handled as the `\t` symbol instead of focus navigation in Script fields of the report detail view.

Default value: `false`

[[jmix.reports.client.use-background-report-processing]]
=== jmix.reports.client.use-background-report-processing

Allows you to set the report execution as a background task. This property is used in order to add the cancel option.

Default value: `false`.

[[jmix.reports.curl-path]]
=== jmix.reports.curl-path

The Reports add-on uses the cURL tool to run external reports. The property value represents the path to the cURL tool.

Default value: `curl`.

[[jmix.reports.display-device-available]]
=== jmix.reports.display-device-available

`false` value allows running LibreOffice in the server operating system without a window interface.

Default value: `false`

[[jmix.reports.doc-formatter-timeout]]
=== jmix.reports.doc-formatter-timeout

Sets the LibreOffice timeout in seconds for converting DOCX/XLSX to HTML/PDF.

When the time is up, the user will receive an error message.

Default value: `20`

[[jmix.reports.formulas-post-processing-evaluation-enabled]]
=== jmix.reports.formulas-post-processing-evaluation-enabled

Controls whether formulas in XLSX reports are re-evaluated after the report document is formed.

When enabled (`true`), LibreOffice or other spreadsheet software will recalculate all formulas in the XLSX report, ensuring the most up-to-date values are displayed. This is particularly useful when formulas in the report aren't automatically calculated upon opening in certain spreadsheet applications.

The default value is `false`.

[[jmix.reports.history-cleanup-max-days]]
=== jmix.reports.history-cleanup-max-days

The scheduled task deletes all xref:exec-history.adoc[execution history] records older than the specified number of days. If the property value is 0, the scheduled task does not consider this property when deleting records.

See xref:exec-history.adoc#execution_history_cleanup[Cleanup the History] for details on setting up the scheduled task.

Default value: `730`

[[jmix.reports.history-cleanup-max-items-per-report]]
=== jmix.reports.history-cleanup-max-items-per-report

The scheduled task leaves no more than this number of xref:exec-history.adoc[execution history] entries for every report. It is not recommended to use a number greater than 1000 as the value of this property. If the property value is 0, the scheduled task does not consider this property when deleting records. It is useful for frequently run reports such as email templates, invoicing document templates, etc.

See xref:exec-history.adoc#execution_history_cleanup[Cleanup the History] for details on setting up the scheduled task.

Default value: `1000`.

[[jmix.reports.history-recording-enabled]]
=== jmix.reports.history-recording-enabled

Activates the xref:exec-history.adoc[report execution history] mechanism.

Default value: `false`.

[[jmix.reports.multilineStringsProcessingEnabled]]
=== jmix.reports.multilineStringsProcessingEnabled

Enables processing of multi-line strings in parameter values for DOCX report templates. When enabled (`true`), line break characters (`\n`, `\r\n`) present in parameter values are rendered as actual line breaks in the generated DOCX document. This functionality is only applied when using a xref:creation/templates.adoc#template_doc[DOCX template].

Default value: `false`.

[[jmix.reports.office-path]]
=== jmix.reports.office-path

Sets the path to LibreOffice.

Default value: `/`

[[jmix.reports.office-ports]]
=== jmix.reports.office-ports

Specifies the comma- or vertical bar-separated list of available ports for LibreOffice.

For example: `jmix.reports.office-ports = 8100|8101|8102|8103|8104|8105`.

Default value: `8100, 8101, 8102, 8103`.

[[jmix.reports.pdf-fonts-directory]]
=== jmix.reports.pdf-fonts-directory

Sets the fonts directory for converting reports from HTML to PDF.

For example: `jmix.reports.pdf-fonts-directory = C:/Windows/Fonts`.

[[jmix.reports.put-empty-row-if-no-data-selected]]
=== jmix.reports.put-empty-row-if-no-data-selected

Sets the mode when the bands which datasets have returned no records are still displayed once.

Default value: `true`

[[jmix.reports.save-output-documents-to-history]]
=== jmix.reports.save-output-documents-to-history

If set to true, report results files are saved to the xref:files:index.adoc[file store], if the <<jmix.reports.history-recording-enabled,jmix.reports.history-recording-enabled>> property is on. See xref:exec-history.adoc#history_output_documents[Output documents] for details.

Default value: `false`.

[[jmix.reports.use-office-for-document-conversion]]
=== jmix.reports.use-office-for-document-conversion

Turns on using LibreOffice to convert the report having DOCX template to HTML/PDF, which significantly increases the conversion accuracy.

Default value: `false`

[[jmix.reports.view-file-extensions]]
=== jmix.reports.view-file-extensions

Specifies the list of file extensions to be shown in the web browser tab instead of downloading them automatically.

Default value: `htm, html, jpg, png, jpeg, pdf`

[[libre_office]]
== Installing and Configuring LibreOffice

The Reports add-on uses the *LibreOffice* package to output reports in PDF and DOC xref:creation/templates.adoc#output_format_compliance[formats]. Below we provide instructions about how to install and configure it in the application server:

[[install-on-microsoft-windows]]
=== For Microsoft Windows

// *Installing and Configuring LibreOffice for Microsoft Windows*

* Download the application at http://www.libreoffice.org/download/download/[www.libreoffice.org^].
* Install the application.
* Configure the <<jmix.reports.office-path,jmix.reports.office-path>> application property and set it to the path to *LibreOffice*, for example:

[source, properties,indent=0]
----
jmix.reports.office-path = C:/Program Files (x86)/LibreOffice 5/program
----

[[install-on-ubuntu-server]]
=== On Ubuntu Server
// *Installing and Configuring LibreOffice on Ubuntu Server*

* Install the `libreoffice` package, for example, by running the following command:
+
[source, properties,indent=0]
----
$ sudo apt-get install libreoffice
----
    
* Configure the <<jmix.reports.office-path,jmix.reports.office-path>> application property and set it to the path to *LibreOffice*:
+
[source, properties,indent=0]
----
jmix.reports.office-path = /usr/lib/libreoffice/program
----

* If the server does not have window interface installed, LibreOffice will start with the error, `Caused by: java.awt.HeadlessException: No X11 DISPLAY variable was set, but this program performed an operation which requires it`, or will simply terminate without error messages. To resolve this issue, set the <<jmix.reports.display-device-available, jmix.reports.display-device-available>> application property:
+
[source, properties,indent=0]
----
jmix.reports.display-device-available = false
----

* You can run the following command to diagnose errors when starting LibreOffice:
+
[source, properties,indent=0]
----
$ strace -e trace=signal /usr/lib/libreoffice/programs/office.bin --headless --accept="socket,host=localhost,port=8100;urp" --nologo --nolockcheck
----

[TIP]
====
For Ubuntu users who installed tomcat using `apt`, it is necessary to copy `~/.config/libreoffice` to `$CATALINA_HOME`. For tomcat10, it is `/usr/share/tomcat10`.

After that, you should change the owner of this folder:

[source, properties,indent=0]
----
sudo mkdir /usr/share/tomcat10/.config
sudo cp -pr ~/.config/libreoffice /usr/share/tomcat10/.config/
sudo chown -R tomcat10.tomcat10 /usr/share/tomcat10/.config/
----
====

[[install-on-mac]]
=== For macOS
// *Installing and Configuring LibreOffice for macOS*

* Download the application at https://www.libreoffice.org/get-help/install-howto/macos/[www.libreoffice.org^].
* Install the application.
* In the <<jmix.reports.office-path, jmix.reports.office-path>> application property, specify the path to *LibreOffice.app*, for example:
+
[source, properties,indent=0]
----
jmix.reports.office-path = /Applications/LibreOffice.app/Contents/MacOS
----

[[formula-recalculation]]
=== LibreOffice Formulas Recalculation On Load

The LibreOffice Calc setting, found under *Tools > Options > LibreOffice Calc > Formula > Recalculation on File Load*, controls how LibreOffice handles formula recalculation when opening a spreadsheet file (like an XLSX report).

By default, LibreOffice might choose to not automatically recalculate formulas upon opening a file to improve load times, especially for large and complex spreadsheets. This can lead to situations where formulas display outdated results until the user manually triggers a recalculation (for example, by pressing `F9` or editing a cell).

Setting *Recalculation on File Load* to *Always recalculate* forces LibreOffice to recalculate all formulas every time the file is opened. This guarantees that the displayed values are always up-to-date but may increase the file's opening time, especially for large or computationally intensive spreadsheets. Therefore, this setting represents a trade-off between speed of opening and data accuracy. While it solves the problem of outdated formula results in most cases, it's worth considering the performance implications for very large files.