= Создание отчетов

Отчет в Jmix состоит из двух отдельных, но связанных элементов:

* _Шаблон отчета_ - файл в офисном формате (XLSX, DOCX), HTML или JRXML, который определяет визуальное представление отчета.
* _Определение отчета_ - программный артефакт, который определяет структуру и данные отчета, а также входные параметры, форматы выходных значений и параметры доступа. Определение отчета содержит ссылку на шаблон.

Отчеты могут создаваться пользователями в работающем приложении. В этом случае определение отчета создается с помощью xref:reports-ui.adoc[административного интерфейса отчетов]. Шаблон загружается через административный интерфейс в приложение и хранится в базе данных вместе с определением отчета:

.Создание отчета во время выполнения
image::create/create-runtime-1.svg[align="center", width="605"]

При создании отчетов во время разработки разработчик создает определение отчета в аннотированном Java-классе. Шаблон отчета обычно создается с помощью внешнего офисного приложения (LibreOffice, Microsoft Excel/Word) и затем сохраняется в ресурсах приложения:

.Создание отчета во время разработки
image::create/create-design-time-1.svg[align="center", width="468"]
// This section provides reference information about report definitions and templates, along with examples of solving typical problems encountered when creating various types of reports.