= Creating Reports

A report in Jmix consists of two separate but related elements:

* _Report Template_ -- a file in an office format (XLSX, DOCX), HTML or JRXML, that defines the visual representation of the report.
* _Report Definition_ -- a program artifact that defines the report structure and data, as well as input parameters, output value formats and access parameters. The report definition contains a reference to the template.

Reports can be created by users in the running application. In this case, the report definition is created using the xref:reports-ui.adoc[reports admin UI]. The template is uploaded through the admin UI to the application and stored in the database together with the report definition:

.Creating a report at runtime
image::create/create-runtime-1.svg[align="center", width="605"]

When creating reports at design time, the developer creates a report definition in an annotated Java class. The report template is usually created using an external office application (LibreOffice, Microsoft Excel/Word) and then saved in the application resources:

.Creating a report at design-time
image::create/create-design-time-1.svg[align="center", width="468"]


// This section provides reference information about report definitions and templates, along with examples of solving typical problems encountered when creating various types of reports.