= Reports

Дополнение Reports позволяет разработчикам и конечным пользователям создавать и генерировать различные отчеты, форматируя данные из приложения Jmix с помощью шаблонов, созданных в удобных офисных приложениях или HTML.

Дополнение предоставляет следующие возможности:

* Создание отчетов на этапе проектирования с использованием аннотированных Java-классов или во время выполнения через административный интерфейс или пошаговый мастер.
* Генерация отчетов в форматах DOCX, XLSX, HTML, CSV, PDF, произвольном текстовом формате или отображение таблицы внутри приложения.
* Создание расширенных отчетов XLSX с группировкой, агрегацией данных и кросс-таблицами.
* Использование диаграмм и формул в отчетах XLSX.
* Управление доступом к отчетам, использование REST API и история выполнения.

Обратитесь к руководству xref:reports-guide:index.adoc[] для получения практических примеров, демонстрирующих создание отчетов.

[[installation]]
== Установка

Для автоматической установки через Jmix Marketplace следуйте инструкциям в разделе xref:ROOT:add-ons.adoc#installation[Дополнения].

Для ручной установки добавьте следующие зависимости в ваш `build.gradle`:

[source,groovy,indent=0]
----
include::example$reports-onboarding/build.gradle[tags=dependencies]
----

Для доступа к отчетам через xref:reports:rest-api.adoc[REST API] добавьте также следующие зависимости:

[source,groovy,indent=0]
----
include::example$reports-onboarding/build.gradle[tags=rest-dependencies]
----

//Note that the `jmix-security-oauth2-starter` is used also by the xref:rest:index.adoc[] add-on, so it may already exist in your `build.gradle`.

[TIP]
====
Дополнение Reports использует пакет *LibreOffice* для вывода отчетов в форматах PDF и DOC. xref:configuration.adoc#libre_office[Установите] *LibreOffice* для поддержки вывода в PDF и DOC.
====

include::ROOT:single-menu-note.adoc[]
