= Reports

Дополнение Reports позволяет разработчикам и конечным пользователям создавать и генерировать различные отчеты, форматируя данные из приложения Jmix с помощью шаблонов, созданных в удобных офисных приложениях или HTML.

Дополнение предоставляет следующие возможности:

* Создание отчетов с использованием аннотированных Java-классов или во время выполнения с помощью комплексного административного интерфейса и пошагового мастера.
* Генерация отчетов в форматах DOCX, XLSX, HTML, CSV, и текстовом формате, а также конвертация вывода отчетов в PDF.
* Создание отчетов XLSX со сложной структурой, включая многоуровневую организацию, агрегацию данных и кросс-таблицы.
* Использование диаграмм и формул в отчетах XLSX.
* Права доступа к отчетам, REST API и история выполнения.

В этой главе представлена справочная информация по созданию и запуску отчетов.

Обратитесь к руководству xref:reports-guide:index.adoc[] для получения практических примеров, демонстрирующих создание отчетов.

[[installation]]
== Установка

Для автоматической установки через Jmix Marketplace следуйте инструкциям в разделе xref:ROOT:add-ons.adoc#installation[Дополнения].

Для ручной установки добавьте следующие зависимости в ваш `build.gradle`:

[source,groovy,indent=0]
----
include::example$reports-onboarding/build.gradle[tags=dependencies]
----

Для доступа к отчетам через xref:reports:rest-api.adoc[REST API] добавьте также следующие зависимости:

[source,groovy,indent=0]
----
include::example$reports-onboarding/build.gradle[tags=rest-dependencies]
----

//Note that the `jmix-security-oauth2-starter` is used also by the xref:rest:index.adoc[] add-on, so it may already exist in your `build.gradle`.

[TIP]
====
Дополнение Reports использует пакет *LibreOffice* для вывода отчетов в форматах PDF и DOC. xref:configuration.adoc#libre_office[Установите] *LibreOffice* для поддержки вывода в PDF и DOC.
====

include::ROOT:single-menu-note.adoc[]