= Reports

The Reports add-on allows developers and end users to design and generate various reports by formatting data from the Jmix application using templates created in user-friendly office applications or HTML.

The add-on provides the following features:

* Designing reports using annotated Java classes or at runtime using a comprehensive admin UI and a step-by-step wizard.
* Generating reports in DOCX, XLSX, HTML, CSV, and text formats, and converting report output to PDF.
* Creating XLSX reports with a complex structure, including multi-level organization, data aggregation, and cross-tab features.
* Using diagrams and formulas in XLSX reports.
* Report access rights, REST API, and execution history.

This chapter provides reference information about creating and running reports.

Refer to the xref:reports-guide:index.adoc[] guide for practical examples that demonstrate report design.

[[installation]]
== Installation

For automatic installation through Jmix Marketplace, follow instructions in the xref:ROOT:add-ons.adoc#installation[Add-ons] section.

For manual installation, add the following dependencies to your `build.gradle`:

[source,groovy,indent=0]
----
include::example$reports-onboarding/build.gradle[tags=dependencies]
----

To access reports through the xref:reports:rest-api.adoc[REST API], also add the following dependencies:

[source,groovy,indent=0]
----
include::example$reports-onboarding/build.gradle[tags=rest-dependencies]
----

//Note that the `jmix-security-oauth2-starter` is used also by the xref:rest:index.adoc[] add-on, so it may already exist in your `build.gradle`.

[TIP]
====
The Reports add-on uses the *LibreOffice* package to output reports in PDF and DOC formats. xref:configuration.adoc#libre_office[Install] *LibreOffice* to support PDF and DOC output.
====

include::ROOT:single-menu-note.adoc[]