= Импорт и экспорт отчетов

Дополнение Jmix Reports предоставляет функции для обработки экспорта и импорта определений отчетов непосредственно из пользовательского интерфейса и программно.

[[manually]]
== Вручную

Дополнение Reports позволяет вручную импортировать и экспортировать отчеты непосредственно из экрана *Reports* с помощью кнопок *Import* и *Export*. Для получения дополнительной информации смотрите xref:report-view.adoc#export-import[Экран списка отчетов].

[[report-import-export]]
== Использование ReportImportExport

Дополнение Jmix Reports предоставляет API `ReportImportExport`, который позволяет импортировать ZIP-файлы с экспортированными отчетами.

Рассмотрим пример автоматизированного развертывания отчетов в рамках проекта Jmix. Отчеты были вручную экспортированы и сохранены как ZIP-архивы в директорию ресурсов проекта.

[source,java,indent=0]
----
include::example$/library/src/main/java/com/company/library/app/DemoDataInitializer.java[tags=dataManager;resources;reportImportExport;REPORT_LOCATION;DemoDataInitializer;ApplicationStartedEvent;importReports;importReport]
----
<1> Бин `DemoDataInitializer` отвечает за запуск импорта отчетов при старте приложения.
<2> Этот метод автоматически вызывается при публикации события `ApplicationStartedEvent`. Мы поместим нашу логику инициализации сюда. `ApplicationStartedEvent` - это событие Spring, которое публикуется после полной инициализации приложения и его готовности обрабатывать запросы. Оно сигнализирует об успешном запуске вашего Jmix приложения.
<3> `DemoDataInitializer` использует сущность `InitFlags` для сохранения флага, который устанавливается в `true` после первоначального импорта. Этот флаг использует пессимистическую блокировку базы данных, чтобы избежать параллельного выполнения при запуске нескольких серверов в кластере. Более того, у вас есть гибкость в определении альтернативных условий для создания/обновления отчетов или даже запуска `ReportImportExport` с помощью ручной команды в пользовательском интерфейсе приложения.
<4> Бин `ReportImportExport` обрабатывает фактический импорт отчетов.