= Собственные шаблоны проектов

Studio поддерживает использование кастомного артефакта, содержащего шаблоны проектов. С его помощью можно предоставить собственные шаблоны для новых проектов, экранов UI и FlowUI.

Для указания координат собственного артефакта, нажмите *Settings* -> *Jmix Plugin Settings* и введите группу и имя артефакта в поле *Additional templates artifact*. Версия артефакта должна быть такой же, как версия Jmix BOM, используемая в шаблонах проектов данного артефакта.

Studio ищет стандартный (`io.jmix.templates.studio:jmix-studio-templates`) и кастомный артефакты с шаблонами в репозитории, выбранном в мастере *New Project*. Если оба артефакта найдены, Studio объединяет шаблоны, отдавая приоритет кастомному шаблону, если он находится в том же каталоге что и стандартный. Это позволяет переопределять стандартный шаблон путем предоставления кастомного в том же каталоге, например `content/project/application`.

Ниже приведена инструкция по сборке собственного артефакта шаблонов.

. Клонируйте репозиторий https://github.com/jmix-framework/jmix[https://github.com/jmix-framework/jmix^] и скопируйте его подкаталог `jmix-templates` в другое место на компьютере.

. Измените свойство `group` в `build.gradle`, например:
+
[source,groovy]
----
group = 'com.company.templates'
----

. Измените свойство `version` в `gradle.properties` на значение желаемой версии Jmix BOM, например:
+
[source,properties]
----
version = 1.5.0
----

. Модифицируйте существующие шаблоны или создайте собственные. Например, скопируйте каталог `content/project/application` в `my-application` и измените свойства `name` и `order` в его файле `template.json`:
+
[source,json]
----
{
  "version": 1,
  "name": "My Full-Stack Application",
  "order": 50,
  "addon": false,
----

. Соберите артефакт и опубликуйте в локальном репозитории Maven:
+
[source,shell]
----
./gradlew publishToMavenLocal
----

. Нажмите *Settings* -> *Jmix Plugin Settings* и введите `com.company.templates:jmix-studio-templates` в поле *Additional templates artifact*.

. Удалите кэш шаблонов из конфигурационного каталога IDE:
* Найдите конфигурационный каталог IDE по информации https://www.jetbrains.com/help/idea/directories-used-by-the-ide-to-store-settings-caches-plugins-and-logs.html#config-directory[IntelliJ IDEA docs^].
* Удалите все содержимое подкаталога `jmix/templates`.

. Создайте новый проект и отметьте флажок *Use local Maven repository*. В выпадающем списке *Jmix version* выберите версию кастомного артефакта.

. На следующей странице мастера создания проекта вы увидите объединенный список шаблонов, включающий ваш кастомный шаблон проекта.