= Using Studio

Jmix Studio IDE offers features to enhance your productivity when developing applications based on Jmix framework.

Jmix Studio is based on an open-source https://www.jetbrains.com/opensource/idea/[IntelliJ Platform^] and extends its functionality with the following specific features:

* Scaffolding of Gradle build scripts.
* Scaffolding of data model, database schema, and CRUD UI.
* WYSIWYG designer of screen layout.
* Developer-friendly features that boost the coding process: actions, intentions, inspections, references.
* Support for easy internationalization.
* Creating data model and UI screens for an existing (legacy) database.
* Hot (re)deploy.
* Easy migration to new versions of Jmix framework and add-ons.

IntelliJ Platform provides a strong foundation for the Jmix Studio. It contains many features that boost Jmix developer productivity, such as ergonomic user interface, smart completion, safe code refactorings, background inspections, built-in version control, and integration with Gradle. If you have not used IntelliJ IDEA before, we highly recommend visiting the https://www.jetbrains.com/idea/resources/[Learn & Support^] section of the IntelliJ IDEA website to get a quick tour of its basic features.
