= Генерация OpenAPI клиента

Studio предоставляет инструменты для упрощения интеграции Jmix-приложений с внешними REST-сервисами. Они позволяют:

* Сгенерировать клиентский код из OpenAPI-схемы внешнего сервиса.
* Сгенерировать сущности Jmix и мапперы для преобразования в классы импортированной OpenAPI-модели и обратно.
* Создавать сервисы уровня приложения, которые работают с сущностями Jmix, конвертируют их в классы внешней модели и вызывают импортированные классы эндпойнтов API.

В результате создается удобный уровень абстракции, состоящий из сущностей Jmix и сервисов Spring. Пользовательский интерфейс приложения и бизнес-логика могут взаимодействовать с внешними данными без прямого использования низкоуровневых классов модели и API, импортированных из OpenAPI-схемы.

.Интеграция с внешним REST-сервисом
image::openapi-client/openapi-client.drawio.svg[]

Чтобы начать импорт OpenAPI-схемы и генерацию клиентского кода, выберите в окне инструментов Jmix *New (+) -> Advanced -> OpenAPI Client*.

Подробные инструкции см. в руководстве xref:openapi-integration-guide:index.adoc[].

include::partial$subscription-note.adoc[]