= Creating Add-ons

In this section, we describe how to create custom add-ons and manage dependencies between them.

An add-on can be easily created using the *Add-On* template of the Studio project creation wizard. The resulting project will contain two source code modules: a functional module and a starter module.

By default, the functional module will contain dependencies on the Jmix data access and UI subsystems. You should create all functionality in this module.

The starter module contains Spring Boot auto-configuration for your add-on. To use the add-on in an application or in another add-on, you will add a dependency on the starter module artifact to the `build.gradle` file of the target project, for example:

[source,groovy]
----
dependencies {
    implementation 'com.company.sample:sample-starter:0.0.1'
----

The functional module will be included transitively through the starter.

TIP: See the xref:studio:composite-projects.adoc[] section for how to develop multiple add-ons and applications in a single IDE project.

[[hierarchy]]
== Hierarchy of Add-ons

In any Jmix application, all included xref:modularity:index.adoc#subsystems[core subsystems and add-ons] form a hierarchy of dependencies. The hierarchy is very important for some framework features.

For example, when the application starts, it can execute Liquibase changelogs for creating or updating the database. The changelogs from different subsystems must be executed in a certain order, because if entities of add-on A are referenced from add-on B, then tables of add-on A must be created before tables of add-on B.

If some base feature supports override, the hierarchy enables predictable end result of the overriding. For example, if add-ons A, B and C define a value of the same application property, and C depends on B which depends on A, then you can be sure that the application which uses all these add-ons will get the value from add-on C.

The application itself always depends on all included subsystems. Therefore, Liquibase changelogs of the application project are always executed last, and a property value defined in the application overrides values coming from any add-ons.

The application is placed at the bottom of the hierarchy automatically, because it can be uniquely identified by the presence of a class annotated with `@SpringBootApplication`. Dependencies between add-ons need an explicit declaration, which is described below.

[[jmix-module]]
== @JmixModule

In an add-on project, the functional module contains the main configuration class annotated with `@Configuration`, `@ComponentScan` and `@JmixModule`. The latter annotation indicates that the module should be included in the hierarchy of Jmix modules.

`@JmixModule` attributes:

* `id` - optional id of the module. Each module in the hierarchy must have a unique id. If this attribute is not set, the package name of the configuration class is used as the module id.
+
Usually, base packages of add-ons are unique, so the `id` attribute is not needed. But if your add-on contains tests, the test configuration class is located in the same base package as the main configuration. So you should provide a unique id for the test module, for example by adding the `.test` suffix to the package name:
+
[source,java,indent=0]
----
include::example$/base/base/src/test/java/com/company/sample/base/BaseTestConfiguration.java[tags=package;class]
----

* `dependsOn` - declares modules on which this module depends. The attribute should contain an array of configuration classes of the modules.
+
For example, if an add-on depends on Core, Data Access and UI subsystems, that is contains the following dependencies in `build.gradle`:
+
[source,groovy,indent=0]
----
include::example$/base/base/base.gradle[tags=dependencies]
----
+
then its `@JmixModule` annotation should declare dependencies to `EclipselinkConfiguration` and `FlowuiConfiguration` classes:
+
[source,java,indent=0]
----
include::example$/base/base/src/main/java/com/company/sample/base/BaseConfiguration.java[tags=jmix-module;class]
----
+
The dependency on the Core subsystem is added transitively. You can check it if you look at the definition of the `EclipselinkConfiguration` or the `FlowuiConfiguration` class.

When a Jmix application starts, it outputs to the log an INFO message from the `io.jmix.core.JmixModulesProcessor` logger with the result of topological sort of the hierarchy of modules. For example:

----
Using Jmix modules: [io.jmix.core, io.jmix.security, io.jmix.flowui,
    io.jmix.securityflowui, io.jmix.data, io.jmix.eclipselink,
    com.company.users, com.company.customers, com.company.products,
    io.jmix.datatools, io.jmix.gridexportflowui, io.jmix.datatoolsflowui,
    io.jmix.flowuidata, io.jmix.localfs, io.jmix.securitydata,
    com.company.sales]
----

TIP: Make sure that the application module is the last in the list, after all add-ons. If it's not, most probably the dependencies between your add-ons are defined incorrectly, so check their `@JmixModule(dependsOn)` contents.

[[properties]]
== Module Properties

An add-on can provide application properties in a property file. To do this, define properties in a file located in the base package of the module, for example:

.src/main/resources/com/company/sample/base/module.properties
[source,properties,indent=0]
----
include::example$/base/base/src/main/resources/com/company/sample/base/module.properties[]
----

Then specify the path to the file in the `@PropertySource` annotation of the main configuration class:

[source,java,indent=0]
----
include::example$/base/base/src/main/java/com/company/sample/base/BaseConfiguration.java[tags=package;property-source;class]
----

IMPORTANT: The `@PropertySource` annotation must have the `name` attribute set to the module id (which is normally equal to the base package name).

You may notice that in the example above the add-on defines the `jmix.ui.menu-config`, which is usually also defined in the application. So why the application value does not just override the value of the add-on? In fact it does: if you get the value of `jmix.ui.menu-config` from Spring's `Environment` in the application, you'll get only the value defined in the application. But using the xref:extension.adoc#modules-api[JmixModules] bean, you can get values of a particular property from all modules used in the application. For example:

[source,java,indent=0]
----
include::example$/ext/src/test/java/com/company/sample/ext/ExtApplicationTests.java[tags=module-prop]
----

This approach is widely used in the framework for aggregating configuration defined in add-ons, like xref:flow-ui:menu-config.adoc[UI menu], shared xref:data-access:fetching.adoc#fetch-plan[fetch plans], and others.
