= Extending Functionality

Functionality of framework subsystems and add-ons can be extended and modified by the application or by other add-ons located lower in the xref:creating-add-ons.adoc#hierarchy[hierarchy].

For declaratively created elements, such as data model entities and XML layout of UI views, Jmix offers its own extension mechanism. Business logic defined by Spring beans can be extended using standard Java and Spring features.

[[data-model]]
== Extending Data Model

Let's consider an example of extending the data model of an add-on.

Suppose we have the following entities defined in the `base` add-on:

image::extension-diagram.svg[align="center"]

Their source code:

[source,java,indent=0]
----
include::example$/base/base/src/main/java/com/company/sample/base/entity/Department.java[tags=entity]
----

[source,java,indent=0]
----
include::example$/base/base/src/main/java/com/company/sample/base/entity/Employee.java[tags=entity]
----

In the `ext` application which uses the `base` add-on, we need to add the `description` and `manager` attributes to the `Department` entity. Obviously, we cannot modify the source code of the add-on, so we need to define another entity in the application and make other entities reference it instead of `Department`:

image::extension-diagram-2.svg[align="center"]

The extended entity source code:

[source,java,indent=0]
----
include::example$/ext/src/main/java/com/company/sample/ext/entity/ExtDepartment.java[tags=entity]
----
<1> The `@ReplaceEntity` annotation indicates that this entity must completely replace the parent entity, specified in the annotation value. This annotation is added by Studio if you select the *Replace parent* checkbox in the entity designer.
<2> A standard inheritance of JPA entities. In this case, the base class doesn't specify the JPA inheritance strategy, so the extension attributes will be stored in the same `BASE_DEPARTMENT` table.
<3> The attributes added in the extension.

After introducing the `ExtDepartment` entity annotated with `@ReplaceEntity` in the application project, it will be returned everywhere in data access code instead of the `Department` entity. For example, you can safely cast references to the `ExtDepartment` class:

[source,java,indent=0]
----
include::example$/ext/src/test/java/com/company/sample/ext/ExtApplicationTests.java[tags=ext-ref]
----

Also, the `ExtDepartment` entity meta-class will be returned by the xref:data-model:metadata.adoc[metadata API] for both `ExtDepartment` and `Department` Java classes. The original entity meta-class can be obtained using the `ExtendedEntities` bean.

[[ui]]
== Extending UI

If you replace an entity of an add-on by an extended version, most probably you will also need to override UI views of this entity to display the extended attributes. Below we consider an example of overriding the list view of the `Department` entity replaced by `ExtDepartment` as described in the <<data-model,previous section>>.

To extend and override a view provided by an add-on, select *Override an existing view* template in the Studio view creation wizard. Studio will create new XML descriptor and controller files. The XML descriptor will contain the `extends` attribute referring to the base view descriptor:

[source,xml,indent=0]
----
include::example$/ext/src/main/resources/com/company/sample/ext/view/department/ext-department-list-view.xml[tags=extends]
----

After that, you can add components to display the extended attributes:

[source,xml,indent=0]
----
include::example$/ext/src/main/resources/com/company/sample/ext/view/department/ext-department-list-view.xml[tags=extends;extends1]
----

You don't have to repeat all elements and attributes of the base view, only the changed part is required. The resulting XML will be merged from the base and extended descriptors - see more about it <<descriptor-extension,below>>.

In our case, one of the extended attributes (`manager`) is a reference to another entity. This reference will be loaded on demand due to the automatic xref:data-access:fetching.adoc#lazy-loading[lazy loading], but you may want to include the reference in the xref:data-access:fetching.adoc#fetch-plan[fetch plan] of the view to avoid the possible "N+1 queries" problem:

[source,xml,indent=0]
----
include::example$/ext/src/main/resources/com/company/sample/ext/view/department/ext-department-list-view.xml[tags=extends;extends1;extends2]
----

The controller of the extended view will be inherited from the base view class:

[source,java,indent=0]
----
include::example$/ext/src/main/java/com/company/sample/ext/view/department/ExtDepartmentListView.java[tags=extend]
----

[IMPORTANT]
====
Note that the `@ViewController` annotation has the same value as in the base view. This is important because we actually need to _override_ the base view, meaning that everywhere in the system the extended view will be used instead of the base one, as is done for replaced entities.
====

You can override public and protected methods of the base controller to extend the view logic if needed.

[CAUTION]
====
When extending or overriding a view that uses `MessageBundle` in its parent controller, you must ensure the child view's `messageGroup` matches the parent's value.

If the `messageGroup` differs, the framework attempts to load messages using the child view's group, which will fail because the messages are defined in the parent's bundle.

For example:

[source,java,indent=0]
----
include::example$/ext/src/main/java/com/company/sample/ext/view/extpessimisticlocklist/ExtPessimisticLockListView.java[tags=extend]
----
====

[[descriptor-extension]]
=== Rules of XML Descriptor Extension

Extension of XML descriptors doesn't take into account the semantics of the view and works purely on the XML level. It merges two XML files according to the following rules:

. If the extending descriptor has a certain element, the corresponding element will be searched for in the parent descriptor using the following algorithm:

.. If the overriding element has the `id` attribute, the corresponding element with the same `id` will be searched for. Some elements are analyzed also for other attributes that serve as unique identifiers instead of `id`:

... For `button` element: `action` attribute.
... For `column` element: `property` and `key` attributes.
... For `property` element: `name` attribute.

.. If the search is successful, the found element is overridden.

.. Otherwise, the framework determines how many elements with the provided path and name are contained in the parent descriptor. If there is only one element, it is overridden.

.. If the search yields no result and there is either zero or more than one element with the given path and name in the parent descriptor, a new element is added.

. The text for the overridden or added element is copied from the extending element.

. All attributes from the extending element are copied to the overridden or added element. If attribute names match, the value is taken from the extending element.

. By default, the new element is added to the end of the list of adjacent elements. In order to add a new element to the beginning or at an arbitrary index, do the following:

.. Define an additional namespace in the extending descriptor: `xmlns:ext="http://jmix.io/schema/flowui/view-ext"`.

.. Add the `ext:index` attribute with a desired index, for example: `ext:index="0"` to the extending element.

[[beans]]
== Overriding Spring Beans

All Jmix subsystems use Spring beans by their type and never by bean name. Therefore, beans can be overridden just by providing alternative implementations with the same or extended type. We recommend following this convention in your own add-ons and applications.

To override a Spring bean defined in an add-on, create its subclass (or implement the same interface) and declare a bean of this new type in a Java configuration, adding the `@Primary` annotation to the new bean.

For example, suppose you have the following bean in the `base` add-on:

[source,java,indent=0]
----
include::example$/base/base/src/main/java/com/company/sample/base/app/DepartmentService.java[tags=class]
----

You can override it in an application as follows:

. Create its subclass in the application project:
+
[source,java,indent=0]
----
include::example$/ext/src/main/java/com/company/sample/ext/app/ExtDepartmentService.java[tags=class]
----

. Define a bean with the `@Primary` annotation in the main application class or in any `@Configuration` class:
+
[source,java,indent=0]
----
include::example$/ext/src/main/java/com/company/sample/ext/ExtApplication.java[tags=extension]
----

After that, Spring container will always return `ExtDepartmentService` instead of `DepartmentService`, so any call to `sayHello()` method even from the `base` add-on will print both "Hello from base" and "Hello from ext" messages. Of course, you are free not to call `super()` in your overriding methods and hence completely replace the inherited behavior.

In a rare situation when you need to override a bean which already has a subclass marked as `@Primary`, you can use the xref:ROOT:app-properties.adoc#jmix.core.exclude-beans[jmix.core.exclude-beans] application property to remove other primary beans from the container.

[[modules-api]]
== Modules API

The  `JmixModules` bean allows you to get information about modules used in your application: the list of all modules, the last module in the list (which is normally the application), a module descriptor by module id. The `getPropertyValues()` method returns the list of values defined for a property by each module.

The `JmixModulesAwareBeanSelector` bean is designed for selecting an effective implementation of some interface from a given list. It returns a bean belonging to the lowest module in the hierarchy. For example, if you know that multiple add-ons define their own implementations of the `AmountCalculator` interface, and you want to use the one defined in the lowest module of the hierarchy, you can do it as follows:

[source,java,indent=0]
----
include::example$/ext/src/test/java/com/company/sample/ext/ExtApplicationTests.java[tags=bean-selector]
----