= Поддержка параметров URL-запроса

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/calendar-url-query-parameters" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Фасет xref:flow-ui:facets/urlQueryParameters.adoc[] поддерживает параметры URL-запроса для компонента `FullCalendar`. Вы можете связать два свойства с состоянием URL:

* xref:full-calendar-component.adoc#calendar-display-modes[Режим отображения календаря]. Это позволяет управлять тем, какой вид (например, день, неделя, месяц) отображается в календаре.
* *Дата для навигации*. Это позволяет указать начальную дату, которая должна отображаться в календаре.

== Базовое использование

Для привязки параметров URL-запроса к компоненту `FullCalendar` определите фасет `urlQueryParameters` и включите вложенный элемент `calendar:calendarParameters` для связи с существующим календарем по его идентификатору:

[source,xml,indent=0]
----
include::example$fullcalendar-ex2/src/main/resources/com/company/fullcalendarsample/view/demos/url-query-parameters-view.xml[tags=url-query-parameters-calendar1]
----

Это отобразит текущий режим отображения и дату в URL, например:

`++http://localhost:8080/url-query-parameters-view?calendarDisplayMode=dayGridMonth&calendarDate=2024-10-17++`

TIP: Вы можете просматривать и редактировать атрибуты фасета в Jmix Studio, используя панель инспектора *Jmix UI*.

== Атрибуты

Элемент `calendarParameters` имеет следующие атрибуты:

* `component`: Идентификатор компонента `FullCalendar`, к которому нужно подключиться.
* `calendarDisplayModeParam` (необязательно): Имя параметра запроса, используемого для представления режима отображения календаря.
* `calendarDateParam` (необязательно): Имя параметра запроса, используемого для представления даты навигации.