= API динамических атрибутов

[[model]]
== Модель

Динамические атрибуты реализуют модель Entity-Attribute-Value (Сущность-Атрибут-Значение).

image::dynattr-diagram.svg[align="center"]

* `Category` определяет категорию объектов и соответствующий набор динамических атрибутов. Каждая категория должна быть связана с конкретным типом сущности.
+
Например, рассмотрим сущность `Car` (Автомобиль). В этом случае мы можем создать две категории: `Truck` (Грузовик) и `Passenger` (Легковой). Категория `Truck` может включать атрибуты `Грузоподъемность` и `Тип кузова`, а категория `Passenger` - атрибуты `Количество мест` и `Детское кресло`.
+
* `CategoryAttribute` представляет динамический атрибут, связанный с конкретной категорией. Каждый атрибут определяет одно поле с определенным типом данных. Обязательное поле `code` содержит системный идентификатор атрибута, а поле `name` - понятное пользователю название атрибута. Поле `code` является техническим идентификатором и может содержать только латинские буквы, цифры и символ `_`. Первый символ должен быть строчной латинской буквой.

* `CategoryAttributeValue` означает значение динамического атрибута для конкретного экземпляра сущности. Эти значения хранятся в специальной таблице `SYS_ATTR_VALUE`. Каждая запись в таблице связана с конкретной сущностью через колонку `ENTITY_ID`.

Экземпляр сущности может обладать динамическими атрибутами из всех категорий, связанных с его типом сущности. Например, если вы создадите две категории для сущности `Car`, как описано выше, вы можете назначить любой динамический атрибут из обеих категорий экземпляру `Car`.

Если вы хотите категоризировать экземпляр сущности под одну категорию — например, автомобиль классифицируется как грузовик или легковой — сущность должна реализовывать интерфейс `Categorized`. Эта настройка гарантирует, что экземпляр сущности связан с конкретной категорией и обладает динамическими атрибутами исключительно из этой категории.

[[loading-and-saving]]
== Загрузка и сохранение

Загрузка и сохранение значений динамических атрибутов обрабатывается `DataManager`. Используйте один из этих методов, чтобы указать, что динамические атрибуты должны быть загружены для экземпляров сущностей:

* Метод `setHint(DynAttrQueryHints.LOAD_DYN_ATTR, true)` объекта `LoadContext`.
* Метод `hint(DynAttrQueryHints.LOAD_DYN_ATTR, true)` fluent API.

TIP: Если вы используете xref:data-access:data-repositories.adoc[репозитории данных], укажите аннотации `@QueryHints` и `@QueryHint` на методах репозитория. Смотрите пример в разделе xref:data-access:data-repositories.adoc#jmix-specific-parameters[Параметры специфичные для Jmix].

По умолчанию динамические атрибуты не загружаются. В то же время `DataManager` всегда сохраняет динамические атрибуты, содержащиеся в экземплярах сущностей, переданных в `save()`.

By default, dynamic attributes are not loaded. At the same time, `DataManager` always saves dynamic attributes contained in entity instances passed to `save()`.

Значения динамических атрибутов доступны через методы `getValue()` / `setValue()` класса `EntityValues`. Передайте код атрибута с префиксом `+` в эти методы, например:

[source,java,indent=0]
----
include::example$/dyn-attr-ex1/src/main/java/com/company/demo/view/car/CarListView.java[tags=get-value]
----

На практике прямой доступ к значениям атрибутов в коде приложения редко необходим. Любой динамический атрибут может автоматически отображаться в любом компоненте `DataGrid` или `FormLayout`, связанном с контейнером данных, содержащим сущность, ассоциированную с динамическим атрибутом. При настройке динамических атрибутов вы можете определить xref:dyn-attr:dynattr-managing.adoc#visibility[видимость атрибута] в рамках экранов и компонентов.

//TODO uncomment after fix
////
User permissions to access dynamic attributes can be set in the security role editor in the same way as for regular attributes. Dynamic attributes are displayed with the + prefix.
////
