= Dynamic Attributes

//include::ROOT:partial$outdated-ui-warning.adoc[]

Динамические атрибуты - это дополнительные свойства сущностей, которые расширяют модель данных без изменения схемы базы данных и перезапуска приложения. Эта функция позволяет определять новые атрибуты сущностей во время развертывания или при работе приложения в продакшене.

Динамические атрибуты хранятся в xref:data-model:data-stores.adoc#main[основном хранилище данных] в структуре https://en.wikipedia.org/wiki/Entity–attribute–value_model[Entity-Attribute-Value^]. Фреймворк автоматически загружает и сохраняет значения динамических атрибутов вместе с экземплярами сущностей.

Пользователи могут просматривать и редактировать динамические атрибуты в таблицах данных и формах существующих xref:flow-ui:views/views.adoc[экранов] приложения.

Jmix предоставляет пользовательский интерфейс для настройки динамических атрибутов. Администраторы могут определять названия, типы данных, критерии валидации и определять, в каких UI экранах и визуальных компонентах отображаются динамические атрибуты.

[[installation]]
== Установка

Для автоматической установки через Jmix Marketplace следуйте инструкциям в разделе xref:ROOT:add-ons.adoc#installation[Дополнения].

Для ручной установки добавьте следующие зависимости в ваш `build.gradle`:

[source,groovy,indent=0]
----
include::example$/dyn-attr-ex1/build.gradle[tags=dependencies]
----

include::ROOT:single-menu-note.adoc[]