= Dynamic Attributes

//include::ROOT:partial$outdated-ui-warning.adoc[]

Dynamic attributes are extra entity properties that expand the data model without altering the database schema and restarting the application. This feature enables the definition of new entity attributes during deployment or while the application is running in production.

Dynamic attributes are stored in the xref:data-model:data-stores.adoc#main[main data store] in an https://en.wikipedia.org/wiki/Entity–attribute–value_model[Entity-Attribute-Value^] structure. The framework automatically loads and saves the values of dynamic attributes along with entity instances.

Users can view and edit dynamic attributes in the data grids and forms of the existing application xref:flow-ui:views/views.adoc[views].

Jmix provides UI for setting up dynamic attributes. Administrators can define names, data types, validation criteria, and determine which UI views and visual components display dynamic attributes.

[[installation]]
== Installation

For automatic installation through Jmix Marketplace, follow instructions in the xref:ROOT:add-ons.adoc#installation[Add-ons] section.

For manual installation, add the following dependencies to your `build.gradle`:

[source,groovy,indent=0]
----
include::example$/dyn-attr-ex1/build.gradle[tags=dependencies]
----

include::ROOT:single-menu-note.adoc[]