= Конфигурация

[[https]]
== Настройка HTTPS

Для авторизации настольных приложений на сервере должен быть включен HTTPS. Ниже приведены простые инструкции по настройке HTTPS в вашей среде разработки.

[[trusted-certificate]]
=== Создание доверенного сертификата

Доверенные сертификаты можно получить у провайдеров SSL-сертификатов или сгенерировать с помощью `certbot`. Но для целей разработки можно выпустить собственный корневой сертификат и подписать им сертификат сервера разработки. Для упрощения этой задачи мы рекомендуем использовать инструмент `mkcert`.

. Установите `mkcert`, следуя инструкциям в его репозитории: https://github.com/FiloSottile/mkcert[https://github.com/FiloSottile/mkcert^].

. Сгенерируйте и установите корневой сертификат:
+
[source]
----
mkcert -install
----

. Создайте сертификат для localhost:
+
[source]
----
mkcert -pkcs12 localhost 127.0.0.1 ::1
----
+
В текущей папке появится файл `localhost+2.p12`.

. Создайте файл хранилища ключей (keystore) с сертификатом для вашего проекта:
+
[source]
----
keytool -importkeystore -srckeystore localhost+2.p12 -srcstoretype pkcs12 -destkeystore localhost.jks
----
+
В качестве пароля исходного хранилища ключей введите `changeit`.
+
В текущей папке появится файл `localhost.jks`.

[[configuring-server]]
=== Настройка сервера

В этом разделе описано, как использовать сертификат, сгенерированный в предыдущем разделе, в вашем приложении, когда оно запускается из IDE или как исполняемый JAR.

. Создайте директорию `src/main/resources/<base-package>/keystore` и скопируйте в нее `localhost.jks`.

. Задайте следующие свойства в файле `application.properties`, заменив `<base-package>` и `<password>` на реальные значения:
+
[source,properties,indent=0]
----
# Enables HTTPS
server.ssl.enabled=true
# The format used for the keystore
server.ssl.key-store-type = JKS
# The path to the keystore containing the certificate
server.ssl.key-store = classpath:<base-package>/keystore/localhost.jks
# The password used to generate the keystore
server.ssl.key-store-password = <password>
# The alias mapped to the certificate
server.ssl.key-alias = localhost

# Changes the server's port
server.port = 8443
----
+
[NOTE]
====
Значение `<base-package>` в пути к хранилищу ключей (свойство `server.ssl.key-store`) должно быть указано как путь с разделителями в виде слэшей:
----
server.ssl.key-store = classpath:com/example/demo/keystore/localhost.jks
----
====
. Откройте главный класс приложения и измените метод `printApplicationUrl()`. После настройки HTTPS URL должен быть изменен на `https://`:
+
[source,java,indent=0]
----
import com.google.common.base.Strings;
import org.slf4j.LoggerFactory;
import org.springframework.boot.context.event.ApplicationStartedEvent;
import org.springframework.context.event.EventListener;

@EventListener
    public void printApplicationUrl(final ApplicationStartedEvent event) {
        LoggerFactory.getLogger(DemoApplication.class).info("Application started at "
                + "https://localhost:"
                + environment.getProperty("local.server.port")
                + Strings.nullToEmpty(environment.getProperty("server.servlet.context-path")));
    }
----

[[maintenance]]
== Задачи обслуживания

Дополнение WebDAV включает несколько задач обслуживания, описанных ниже. Чтобы запускать эти задачи регулярно, добавьте в проект дополнение Quartz, как описано в разделе xref:quartz:index.adoc#installation[Quartz / Установка].

[[expired-lock-cleaning-job]]
=== ExpiredLockCleaningJob

Эта задача удаляет просроченные объекты xref:webdav-documents.adoc#lock-unlock[блокировки]. По умолчанию она запускается каждые два часа.

Чтобы изменить расписание задачи, используйте свойство xref:webdav:webdav-properties.adoc#jmix.webdav.expired-lock-cleaning-cron[jmix.webdav.expired-lock-cleaning-cron].

[[webdav-document-versions-cleaning-job]]
=== WebdavDocumentVersionsCleaningJob

Эта задача удаляет экземпляры `WebdavDocumentVersion`, не связанные ни с одним документом. По умолчанию она запускается один раз в месяц.

Чтобы изменить расписание задачи, используйте свойство xref:webdav:webdav-properties.adoc#jmix.webdav.document-versions-cleaning-cron[jmix.webdav.document-versions-cleaning-cron].

[[security]]
== Настройка безопасности

Ограничения доступа к документам настраиваются с помощью xref:security:resource-roles.adoc[ресурсных] и xref:security:row-level-roles.adoc[ролей уровня строк].

[[predefined-roles]]
=== Предопределенные роли

Приложение Jmix с дополнением WebDAV включает две предопределенные ресурсные роли по умолчанию:

* *WebDAV: minimal access* — базовая роль WebDAV, необходимая всем пользователям, которым требуется функциональность WebDAV.
* *WebDAV: view document browser* — предоставляет доступ к экрану xref:webdav-documents.adoc[документов WebDAV].

// [[row-level-restrictions]]
// === Restricting Access to Documents
//
// Suppose that some group of users should be able to edit only the documents created by themselves. Below is an example of how to do it using row-level roles.
//
// //The following example shows how to restrict access to a particular group of users. Suppose that there is a row-level role called `Users`. It is required to configure this row-level role so that only document authors can edit documents and document versions.
//
// . Create a row-level role at runtime using UI screens available at *Administration → Row-level roles.*
// . Create a row-level xref:security:row-level-roles.adoc#predicate-policy[predicate policy] for the `UPDATE` action and `WebdavDocument` entity.
// . Define a Groovy script for the created policy:
// +
// [source,groovy,indent=0]
// ----
// import io.jmix.core.security.CurrentAuthentication
//
// def authBean = applicationContext.getBean(CurrentAuthentication)
//
// return {E}.createdBy.equals(authBean.user.username)
// ----
// . Assign the role to the users.
//
// The system will check whether the current user is a document author. If it is not the case, the user will not be allowed to edit a document, and the `Access denied` message will be displayed.
//
// The *OK* button intended to save document versions will be inactive. The document itself will be opened in read-only mode.
