= Возможности

Дополнение предоставляет сущность `WebdavDocument`, которую следует использовать в вашей модели данных для ссылки на файлы, доступные через WebDAV.

[[webdav-support-annotation]]
== Аннотация WebdavSupport

Аннотацию `@WebdavSupport` можно применять к полям типа `WebdavDocument`. С помощью этой аннотации можно отключить версионирование для конкретного поля, поскольку по умолчанию версионирование включено.

Например, рассмотрим следующий пример:

[source,java,indent=0]
----
@JmixEntity
@Entity
public class WebdavDocumentWrapper {

    @JoinColumn(name = "WEBDAV_DOCUMENT_ID")
    @OneToOne(fetch = FetchType.LAZY)
    private WebdavDocument webdavDocument;

    @JoinColumn(name = "DOC_WITHOUT_VERSION_ID")
    @WebdavSupport(versioning = false)
    @OneToOne(fetch = FetchType.LAZY)
    private WebdavDocument docWithoutVersion;

    // getters and setters
}
----

В этом примере у `docWithoutVersion` версионирование отключено, а у `webdavDocument` версионирование по умолчанию включено.

[[links]]
== Ссылки на документы

Дополнение генерирует ссылки на документы, которые можно опубликовать на веб-сайте или передать третьим лицам. Ссылка имеет следующий формат: `++https://<host>:<port>/webdav/link/82b62377-7fd1-b75e-47fc-9ef4b8d67360++`. При переходе по ссылке браузер пользователя запросит учетные данные для доступа к документу. После успешной авторизации документ откроется в соответствующем настольном приложении, если оно установлено на компьютере пользователя.
