= Начало работы с WebDAV

В этом самоучителе приведены инструкции по интеграции дополнения WebDAV в ваше приложение.

[[project-setup]]
== Настройка проекта

Мы разрабатываем приложение Onboarding — инструмент, который помогает новым сотрудникам пройти все необходимые шаги при начале работы на новой должности.

Мы будем использовать приложение Onboarding в качестве отправной точки.

. Если вы еще не создали это приложение, обратитесь к разделу xref:tutorial:index.adoc[Самоучитель], где приведено подробное, пошаговое руководство по разработке базового приложения.

. Otherwise, download the complete application source code from the https://github.com/jmix-framework/jmix-onboarding-2[jmix-framework/jmix-onboarding-2^] GitHub repository. Next, follow the instructions in the xref:studio:project.adoc#opening-existing-project[Opening Existing Project] section to open it in Jmix Studio.

. Добавьте дополнение WebDAV согласно разделу xref:index.adoc#installation[установка].

[[about-app]]
== О демонстрационном приложении

В этом самоучителе мы добавим в приложение Onboarding новую функциональность.

Онбординг предполагает обучение новых сотрудников, и важной его частью является знакомство с *базой знаний* компании.

Как правило, база знаний включает общекорпоративные стандарты и правила, операционные процедуры, а также процедуры, инструкции и лучшие практики для каждого отдела. Чтобы база знаний оставалась актуальной, важно отслеживать обновления и поддерживать совместную работу над документацией.

* Внутренняя система управления знаниями необходима для того, чтобы у сотрудников был доступ к актуальной информации.
* Такая система помогает отслеживать изменения данных и устанавливать контроль доступа для защиты конфиденциальной информации.
* Она также способствует совместной работе над документами, предотвращает ошибки данных при одновременном редактировании и ведет журнал изменений документов. Это позволяет пользователям обращаться к предыдущим версиям документов при необходимости.

[[data-model]]
=== Модель данных

Рассмотрим модель данных демонстрационного приложения onboarding.

image::data-model-diagram.svg[align="center"]

Мы добавим сущность `WebdavDocumentWrapper`:

image::data-model.svg[align="center"]

[[user-roles]]
=== Роли пользователей

Демонстрационное приложение поддерживает следующие роли пользователей:

* _Employees_ (сотрудники) — изучают документы в рамках своего отдела, но не редактируют их.
* _HR Managers_ (HR-менеджеры) — отвечают за актуальность информации в базе знаний: загружают документы, удаляют документы и редактируют содержимое документов.