= WebDAV

Основная цель дополнения WebDAV — обеспечить доступ к файлам, хранящимся в xref:files:file-storage.adoc[хранилище файлов], по протоколу https://en.wikipedia.org/wiki/WebDAV[WebDAV^]. Эта функциональность позволяет пользователям удобно открывать и редактировать файлы с помощью настольных приложений (таких как Word, Excel, LibreOffice и т. д.) без необходимости постоянно скачивать и загружать файлы в веб-приложение.

Кроме того, дополнение предлагает следующие дополнительные возможности:

* Контроль версий документов. Если для документа включено версионирование, то при каждом изменении документа на сервере создается новая версия.

* Настраиваемые политики разрешения конфликтов для поддержки совместного редактирования документов.

* Возможность управления правами доступа к документам.

* UI-компоненты для управления файлами и версиями документов.

* Интеграция с внешними системами с помощью статических ссылок для беспрепятственного доступа к файлам.

[[installation]]
== Установка

[NOTE]
====
Для этого дополнения требуется Enterprise https://www.jmix.ru/subscription-plans-and-prices/[подписка^]. Если у вас нет подписки, ознакомьтесь с разделом xref:ROOT:account-management.adoc#enterprise-trial[Пробная Enterprise-подписка], чтобы получить пробную версию.
====

Для автоматической установки через Jmix Marketplace следуйте инструкциям в разделе xref:ROOT:add-ons.adoc#installation[Дополнения].

Для ручной установки выполните следующие шаги.

. Настройте доступ к премиум-репозиторию.
+
include::ROOT:partial$premium-repo.adoc[]

. Добавьте зависимости в ваш `build.gradle`:
+
[source,groovy,indent=0]
----
implementation 'io.jmix.webdav:jmix-webdav-starter'
implementation 'io.jmix.webdav:jmix-webdav-rest-starter'
implementation 'io.jmix.webdav:jmix-webdav-flowui-starter'
----
// [source,groovy,indent=0]
// ----
// include::webdav:example$ex1/build.gradle[tags=dependencies]
// ----

include::ROOT:single-menu-note.adoc[]

[[https]]
== HTTPS и базовая авторизация

Настольные приложения используют базовую авторизацию для подключения к серверу по WebDAV, поэтому для вашего веб-приложения необходимо настроить HTTPS. См. раздел xref:configuration.adoc#https[Настройка HTTPS] для получения инструкций по настройке HTTPS на localhost в целях разработки.

[[requirements]]
== Требования к офисным приложениям

IMPORTANT: Из-за недавнего отключения базовой авторизации в приложениях Microsoft 365 (см. https://learn.microsoft.com/en-us/microsoft-365-apps/security/basic-authentication-prompts-blocked[^]) дополнение WebDAV не может работать с последними версиями Microsoft Office.

Минимальная версия Microsoft Office, необходимая для доступа к документам по протоколу WebDAV, — MS Office 2010 SP2. Для LibreOffice минимальная требуемая версия — 6.3.

Чтобы проверить установленные версии Microsoft Office и Service Pack (SP) на вашем компьютере, откройте MS Word и перейдите в раздел *Product Information* через *File → Help*. Для Service Pack 2 MS Office 2010 (и последующих версий) должен отображаться следующий номер: 14.0.7015.1000 (или выше). Чтобы обновить Service Pack, перейдите по этой https://www.microsoft.com/en-US/download/details.aspx?id=39667[ссылке^].
