= WebDAV

The main purpose of the WebDAV add-on is to facilitate access to files stored in the xref:files:file-storage.adoc[file storage] via the https://en.wikipedia.org/wiki/WebDAV[WebDAV protocol^]. This feature enables users to conveniently open and edit files using desktop applications (such as Word, Excel, LibreOffice, etc.) without the necessity of repeatedly downloading and uploading files to the web application.

Additionally, the add-on offers the following supplementary functionalities:

* Document version control. Enabling versioning for a document ensures that a new version is generated on the server each time the document is modified.

* Customizable conflict resolution policies to support collaborative document editing.

* Ability to manage document access permissions.

* UI components for managing files and document versions.

* Integration with external systems through static links for seamless file access.

[[installation]]
== Installation

[NOTE]
====
This add-on requires the Enterprise https://www.jmix.io/subscription-plans-and-prices/[subscription^]. If you don't have the subscription, see the xref:ROOT:account-management.adoc#enterprise-trial[Enterprise Trial] section for how to get a trial version.
====

For automatic installation through Jmix Marketplace, follow instructions in the xref:ROOT:add-ons.adoc#installation[Add-ons] section.

For manual installation, follow the steps below.

. Configure access to the premium repository.
+
include::ROOT:partial$premium-repo.adoc[]

. Add dependencies to your `build.gradle`:
+
[source,groovy,indent=0]
----
implementation 'io.jmix.webdav:jmix-webdav-starter'
implementation 'io.jmix.webdav:jmix-webdav-rest-starter'
implementation 'io.jmix.webdav:jmix-webdav-flowui-starter'
----
// [source,groovy,indent=0]
// ----
// include::webdav:example$ex1/build.gradle[tags=dependencies]
// ----

include::ROOT:single-menu-note.adoc[]

[[https]]
== HTTPS

Desktop applications use basic authentication for server connections via WebDAV, so you have to set up HTTPS for your web application. Refer to the xref:configuration.adoc#https[Configuring HTTPS] section for guidance on configuring HTTPS on localhost in development.

[[requirements]]
== Requirements

IMPORTANT: Due to recently disabled Basic authentication in Microsoft 365 applications (see https://learn.microsoft.com/en-us/microsoft-365-apps/security/basic-authentication-prompts-blocked[^]), the WebDAV add-on cannot work with the latest versions of Microsoft Office.

The minimum version of Microsoft Office needed to access documents via the WebDAV protocol is MS Office 2010 SP2. For LibreOffice, the minimum required version is 6.3.

To verify the installed versions of Microsoft Office and Service Pack (SP) on your computer, open MS Word and navigate to the *Product Information* section via *File → Help*. Service Pack 2 for MS Office 2010 (and subsequent versions) should display the following number: 14.0.7015.1000 (or higher). To update your Service Pack, click on this https://www.microsoft.com/en-US/download/details.aspx?id=39667[link^].