= WebDAV

WebDAV 扩展组件的主要功能是通过 https://en.wikipedia.org/wiki/WebDAV[WebDAV 协议^] 访问位于 xref:files:file-storage.adoc[文件存储] 的文件。支持用户使用本地桌面应用程序（Word，Excel，LibreOffice 等）方便地打开和编辑文件，而无需从 Web 应用下载和上传。

该组件还提供下列附加功能：

* 文档版本控制。每次更新文档时，都会在服务器创建文档的一个新版本。

* 可自定义的冲突解决策略，支持文档协作编辑。

* 可以控制文档的访问权限。

* 管理文件和版本的 UI 组件。

* 使用静态链接从外部系统无缝访问文件。

[[installation]]
== 安装

[NOTE]
====
此扩展组件需要企业版 https://www.jmix.cn/subscription-plans-and-prices/[订阅^]。如果没有企业版订阅，可以按照 xref:ROOT:account-management.adoc#enterprise-trial[企业版试用] 介绍的方法试用。
====

请按照 xref:ROOT:add-ons.adoc#installation[扩展组件] 章节的介绍通过 Jmix 市场自动安装。

手动安装步骤：

. 配置 premium 仓库的访问：
+
include::ROOT:partial$premium-repo.adoc[]

. 在 `build.gradle` 中添加依赖：
+
[source,groovy,indent=0]
----
implementation 'io.jmix.webdav:jmix-webdav-starter'
implementation 'io.jmix.webdav:jmix-webdav-rest-starter'
implementation 'io.jmix.webdav:jmix-webdav-flowui-starter'
----
// [source,groovy,indent=0]
// ----
// include::webdav:example$ex1/build.gradle[tags=dependencies]
// ----

include::ROOT:single-menu-note.adoc[]

[[https]]
== HTTPS

桌面 Office 应用程序通过 WebDAV 连接服务时使用基本认证方式，因此需要为 Web 应用程序配置 HTTPS。参阅 xref:configuration.adoc#https[配置 HTTPS] 章节，了解如何在 localhost 配置 HTTPS 用于开发测试。

[[requirements]]
== 要求

IMPORTANT: 由于 Microsoft 365 应用程序最近禁用了基本认证（参阅 https://learn.microsoft.com/en-us/microsoft-365-apps/security/basic-authentication-prompts-blocked[^]），WebDAV 无法兼容 Microsoft Office 的最新版本。

能通过 WebDAV 协议打开文档的最低版本 Microsoft Office 需要是 MS Office 2010 SP2。LibreOffice 要求的最低版本是 6.3。

如需检查 Microsoft Office 和 Service Pack（SP） 的版本，打开 MS Word，从 *File → Help* 菜单打开 *Product Information*。MS Office 2010 SP2（或以上版本）会显示 14.0.7015.1000（或更高版本号）。如需升级 Service Pack，请访问 https://www.microsoft.com/en-US/download/details.aspx?id=39667[微软文档^]。
