= Сервисы

[[webdav-documents-management-service]]
== WebdavDocumentsManagementService

Этот сервис предназначен для использования с `WebdavDocument`. Его методы позволяют выполнять следующие действия:

* Получать документ по идентификатору версии документа, идентификатору документа, URI документа или версии документа.
* Получать список документов из указанного документа или пути ресурса.
* Создавать или удалять блокировку документа с заданным периодом тайм-аута.
* Создавать, обновлять или удалять документ.
* Создавать, обновлять или удалять версии конкретного документа.

[[webdav-document-versions-management-service]]
== WebdavDocumentVersionsManagementService

Этот сервис используется для управления версиями документов и предоставляет следующие возможности:

* Получение первой версии документа.
* Получение последней версии документа.
* Получение конкретной версии документа
* Получение всех доступных версий документа
* Создание, обновление или удаление версий документов

[[webdav-raw-links-management-service]]
== WebdavRawLinksManagementService

Этот сервис используется для управления постоянными ссылками. Постоянные ссылки хранятся в базе данных как экземпляры сущности `WebdavLink`, указывающие на экземпляры сущностей `WebdavDocument` или `WebdavDocumentVersion`. Формат ссылок следующий: `\http://localhost:8080/app/webdav/link/\{linkIdentifier}`, где `linkIdentifier` соответствует идентификатору сущности `WebdavLink`.

Например, `\http://localhost:8080/app/webdav/link/7a53ce0e-1576-ad32-a131-4abcde6b1235`.

При переходе по ссылке генерируется и открывается временная ссылка. Каждая ссылка сопровождается контекстом, который содержит дополнительную информацию о том, как открыть сущность файла, на который указывает ссылка. По умолчанию ссылка создается с контекстом по умолчанию (пустым). Этот контекст зависит от типа сущности, хранящейся в ссылке. Если тип сущности — `WebdavDocument`, файл будет открыт в режиме полного доступа. Если тип сущности — `WebdavDocumentVersion`, файл будет открыт в режиме только для чтения. Строковое значение ссылки содержится в поле `url` класса `WebdavUrl`.

Методы сервиса предоставляют возможность создавать и удалять постоянные ссылки на документ с контекстом по умолчанию, только для чтения или с пользовательским контекстом.

[[webdav-url-management-service]]
== WebdavUrlManagementService

Этот сервис используется для получения временных ссылок. Такие ссылки содержат сведения о приложении для открытия, режиме доступа, имени файла и версии документа. Ссылка либо запускает приложение для файла, хранящегося в сущности `WebdavDocument`/`WebdavDocumentVersion`, либо инициирует скачивание. Например: `ms-word:ofv|u|http://localhost:8080/app/webdav/document/0e68df0e-8395-4d25-a230-3eb89e6b2674/example.docx`.

Строковое значение ссылки содержится в поле `url` класса `WebdavUrl`. Такие ссылки не хранятся в базе данных, а генерируются динамически.

NOTE: Рекомендуется использовать постоянные ссылки из `WebdavRawLinksManagementService`.

Сервис предоставляет следующие возможности:

- Получение ссылки на последнюю версию документа с полным доступом или в режиме только для чтения.
- Получение ссылки на конкретную версию документа с полным доступом или в режиме только для чтения.
- Получение сведений о внешнем приложении, используемом для открытия версии документа.
