= WebDAV 应用属性配置

[[jmix.webdav.applications]]
== jmix.webdav.applications

设置文档格式和打开此格式的外部应用程序的映射。对于每个外部应用程序，可以在 "extensions" 属性配置一组文件扩展名。

例如，下面的映射使用 Microsoft PowerPoint 打开 PPT 和 PPTX 文件：

[source,properties,indent=0]
----
"ms-powerpoint":{\
  "name":"Microsoft PowerPoint",\
  "protocols":{"writable":"ms-powerpoint:ofe%7Cu%7C","read_only":"ms-powerpoint:ofv%7Cu%7C"},\
  "extensions":["ppt","pptx"]\
  }
----

默认值：

[source,properties,indent=0]
----
{"ms-word":{"name":"Microsoft Word","protocols":{"writable":"ms-word:ofe%7Cu%7C",\
  "read_only":"ms-word:ofv%7Cu%7C"},"extensions":["docx","doc","rtf"]},\
  "ms-excel":{"name":"Microsoft Excel","protocols":{"writable":"ms-excel:ofe%7Cu%7C",\
  "read_only":"ms-excel:ofv%7Cu%7C"},"extensions":["xls","xlsx"]},\
  "ms-powerpoint":{"name":"Microsoft PowerPoint",\
  "protocols":{"writable":"ms-powerpoint:ofe%7Cu%7C","read_only":"ms-powerpoint:ofv%7Cu%7C"},\
  "extensions":["ppt","pptx"]}}
----

LibreOffice 配置示例：

[source,properties,indent=0]
----
jmix.webdav.applications = {"vnd.libreoffice.command":\
  {"name":"LibreOffice","protocols":\
  {"writable":"vnd.libreoffice.command:ofe|u|",\
  "read_only":"vnd.libreoffice.command:ofv|u|"},\
  "extensions":["odt", "ods", "odp", "doc", "docx", "xls", "xlsx", "ppt", "pptx"]}}
----

[[jmix.webdav.authentication-method]]
== jmix.webdav.authentication-method

设置认证类型。

默认值：`basic`。

尽管不推荐，但是仍然可以在该属性设置 `digest`，避免在服务器配置 HTTPS。此时，别忘了修改 <<jmix.webdav.url-prefix>> 属性，以便使用正确的服务协议和端口生成链接。另请注意，所有用户都必须在数据库中单独存储哈希密码。当更改用户的密码时，扩展组件会更新这些密码，因此必须在设置摘要认证后为每个用户执行此操作。

[[jmix.webdav.auto-generate-unique-resource-uri]]
== jmix.webdav.auto-generate-unique-resource-uri

如果该属性设置为 `false`，且新上传文档生成的 URI 已经分配给另一个文档时，会发生违反唯一性约束错误。

如果该属性设置为 `true`，且 URI 已经分配给另一个文档时，会自动生成 `\{id}.extension` 格式的新路径。

默认值：`true`。

[[jmix.webdav.document-versions-cleaning-cron]]
== jmix.webdav.document-versions-cleaning-cron

该属性支持以 http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html[cron^] 表达式修改 xref:webdav:configuration.adoc#webdav-document-versions-cleaning-job[WebdavDocumentVersionsCleaningJob] 的调度计划。

默认值：`0 0 0 1 * ? *`（每月一次）。

[[jmix.webdav.expired-lock-cleaning-cron]]
== jmix.webdav.expired-lock-cleaning-cron

该属性支持以 http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html[cron^] 表达式修改 xref:webdav:configuration.adoc#expired-lock-cleaning-job[ExpiredLockCleaningJob] 的调度计划。

默认值：`0 0 0/2 ? * *`（两小时一次）。

[[jmix.webdav.file-storage]]
== jmix.webdav.file-storage

定义一个用于存储 WebDAV 文件的 xref:files:file-storage.adoc[文件存储]。

默认使用 `FileStorageLocator.getDefault()` 返回的文件存储。

[[jmix.webdav.lock-timeout]]
== jmix.webdav.lock-timeout

定义文档 xref:webdav:webdav-documents.adoc#lock-unlock[锁定] 的默认间隔，单位为毫秒。

默认值：`600000`。

[[jmix.webdav.use-default-document-versions-cleaner-quartz-configuration]]
== jmix.webdav.use-default-document-versions-cleaner-quartz-configuration

该属性可以禁用 xref:webdav:configuration.adoc#webdav-document-versions-cleaning-job[WebdavDocumentVersionsCleaningJob] 任务创建和计划的默认配置。

默认值：`true`。

[[jmix.webdav.use-default-expired-lock-cleaner-quartz-configuration]]
== jmix.webdav.use-default-expired-lock-cleaner-quartz-configuration

该属性可以禁用 xref:webdav:configuration.adoc#expired-lock-cleaning-job[ExpiredLockCleaningJob] 任务创建和计划的默认配置。

默认值：`true`。

[[jmix.webdav.url-prefix]]
== jmix.webdav.url-prefix

定义一个 WebDAV 文档链接的前缀。

默认值：`\https://localhost:8443/webdav`。

值必须与应用程序 URL 的根路径一致，且带附加的 `/webdav` 路径。

[[jmix.webdav.versioning-enabled]]
== jmix.webdav.versioning-enabled

对所有不带 `@WebdavSupport` 注解的 `WebdavDocument` 类型属性启用版本功能。

默认值：`true`。
