= WebDAV Application Properties

[[jmix.webdav.applications]]
== jmix.webdav.applications

Maps document formats to external applications that should open these documents. You can configure a set of file extensions for each application in the "extensions" property.

For example, the following mapping makes the system open PPT and PPTX files with Microsoft PowerPoint:

[source,properties,indent=0]
----
"ms-powerpoint":{\
  "name":"Microsoft PowerPoint",\
  "protocols":{"writable":"ms-powerpoint:ofe%7Cu%7C","read_only":"ms-powerpoint:ofv%7Cu%7C"},\
  "extensions":["ppt","pptx"]\
  }
----

Default value:

[source,properties,indent=0]
----
{"ms-word":{"name":"Microsoft Word","protocols":{"writable":"ms-word:ofe%7Cu%7C",\
  "read_only":"ms-word:ofv%7Cu%7C"},"extensions":["docx","doc","rtf"]},\
  "ms-excel":{"name":"Microsoft Excel","protocols":{"writable":"ms-excel:ofe%7Cu%7C",\
  "read_only":"ms-excel:ofv%7Cu%7C"},"extensions":["xls","xlsx"]},\
  "ms-powerpoint":{"name":"Microsoft PowerPoint",\
  "protocols":{"writable":"ms-powerpoint:ofe%7Cu%7C","read_only":"ms-powerpoint:ofv%7Cu%7C"},\
  "extensions":["ppt","pptx"]}}
----

Example value for LibreOffice:

[source,properties,indent=0]
----
jmix.webdav.applications = {"vnd.libreoffice.command":\
  {"name":"LibreOffice","protocols":\
  {"writable":"vnd.libreoffice.command:ofe|u|",\
  "read_only":"vnd.libreoffice.command:ofv|u|"},\
  "extensions":["odt", "ods", "odp", "doc", "docx", "xls", "xlsx", "ppt", "pptx"]}}
----

[[jmix.webdav.authentication-method]]
== jmix.webdav.authentication-method

Defines the authentication type.

Default value: `basic`.

Although not recommended, you can set this property to `digest` and avoid setting up HTTPS on the server. In this case, remember to change the <<jmix.webdav.url-prefix>> property to generate links with the correct server protocol and port. Also, all users must have separately stored hashed passwords in the database. The add-on updates these passwords when you change a user's password, so you must do this for each user after setting up digest authentication.

[[jmix.webdav.auto-generate-unique-resource-uri]]
== jmix.webdav.auto-generate-unique-resource-uri

If this property is set to `false` and a newly uploaded document has the URI already assigned to another document, a unique constraint violation will occur.

If this property is set to `true` and the URI is already assigned to some document, a new path will be automatically generated with the `\{id}.extension` format.

Default value: `true`.

[[jmix.webdav.document-versions-cleaning-cron]]
== jmix.webdav.document-versions-cleaning-cron

This property allows you to change the schedule of xref:webdav:configuration.adoc#webdav-document-versions-cleaning-job[WebdavDocumentVersionsCleaningJob] as a http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html[cron^] expression if necessary.

The default value is `0 0 0 1 * ? *` (once a month).

[[jmix.webdav.expired-lock-cleaning-cron]]
== jmix.webdav.expired-lock-cleaning-cron

This property allows you to change the schedule of xref:webdav:configuration.adoc#expired-lock-cleaning-job[ExpiredLockCleaningJob] as a http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html[cron^] expression if necessary.

The default value is `0 0 0/2 ? * *` (every two hours).

[[jmix.webdav.file-storage]]
== jmix.webdav.file-storage

Defines a xref:files:file-storage.adoc[file storage] used to store WebDAV files.

By default, the file storage returned by `FileStorageLocator.getDefault()` is used.

[[jmix.webdav.lock-timeout]]
== jmix.webdav.lock-timeout

Defines the default interval in milliseconds for document xref:webdav:webdav-documents.adoc#lock-unlock[locking].

Default value: `600000`.

[[jmix.webdav.use-default-document-versions-cleaner-quartz-configuration]]
== jmix.webdav.use-default-document-versions-cleaner-quartz-configuration

This property allows you to disable the default configuration that creates and schedules the xref:webdav:configuration.adoc#webdav-document-versions-cleaning-job[WebdavDocumentVersionsCleaningJob] job.

Default value: `true`.

[[jmix.webdav.use-default-expired-lock-cleaner-quartz-configuration]]
== jmix.webdav.use-default-expired-lock-cleaner-quartz-configuration

This property allows you to disable the default configuration that creates and schedules the xref:webdav:configuration.adoc#expired-lock-cleaning-job[ExpiredLockCleaningJob] job.

Default value: `true`.

[[jmix.webdav.url-prefix]]
== jmix.webdav.url-prefix

Defines the prefix for a WebDAV document link.

Default value: `\https://localhost:8443/webdav`.

It must match the root URL of the application with the additional `/webdav` path.

[[jmix.webdav.versioning-enabled]]
== jmix.webdav.versioning-enabled

Enables versioning for all attributes of the `WebdavDocument` type without `@WebdavSupport` annotation.

Default value: `true`.