= Fragments
:page-aliases: screens/screen-fragment-events.adoc

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/fragments" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

A _fragment_ is a UI building block that can be used as a part of views and other fragments. It's a composite component with the following additional features:

* Ability to define the content in XML.
* The `fragment` XML element allows you to include fragments in views and other fragments declaratively.
* The fragment class (AKA controller) supports injection of Spring beans and fragment's UI components, as well as the use of annotated methods as handlers.
* The `ReadyEvent` is sent when a fragment is fully initialized.
* You can define xref:flow-ui:actions.adoc[actions] and xref:flow-ui:data-components.adoc[data components] (data containers and loaders) in the fragment's XML. Data components can be marked as `provided` to obtain them from the host view.
* Studio offers the xref:studio:view-wizard.adoc#creating-blank-fragment[Blank fragment] template to generate fragments, shows them in the Jmix tool window and allows you to use the xref:studio:view-designer.adoc[visual designer] the same as for views.

TIP: Fragments can be used to render items within certain UI components, such as xref:vc/components/virtualList.adoc[virtualList], or xref:vc/components/dataGrid.adoc[dataGrid] columns. This is achieved using a nested xref:flow-ui:vc/miscellaneous/renderers.adoc#fragment-renderer[fragmentRenderer] element. The `fragmentRenderer` element specifies a Java class that extends `io.jmix.flowui.fragmentrenderer.FragmentRenderer`. This class is responsible for taking a data item and rendering it within the fragment's template.

[[fragment-content]]
== Fragment Content

To create a fragment, create a class that extends `io.jmix.flowui.fragment.Fragment`. The fragment generic type defines the root component type of the fragment content. The same component must be specified in the XML descriptor as the root component inside the `content` element.

The `@FragmentDescriptor` annotation specifies a string value that is a path to an XML file which is used for the fragment initialization. If the value contains a file name only (and doesn't start with `/`), it is assumed that the file is located in the package of the fragment class.

Elements available in the XML descriptor:

* `content` - required element that contains the fragment layout (similar to the view `layout` element). Since the root component of a fragment can be any component, `content` has no attributes and doesn't represent any component.

* `actions` - optional fragment actions element (similar to the view `actions` element). If an action has a xref:keyboard-shortcuts.adoc[shortcut], it is bound to the root component of the fragment. That is, the shortcut can be triggered only if focus is within the fragment layout.

* `data` - optional fragment data element (similar to the view `data` element). A fragment can define its own data containers and loaders or get them by id from a host view or enclosing fragment as described in the xref:flow-ui:fragments/using-fragments.adoc#using-data-components[Using Data Components] section.

Example of a fragment XML:

[source,xml,indent=0]
.customer-list-fragment.xml
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/customer/customer-list-fragment.xml[tags=fragment-xml]
----

[[fragment-api]]
== Fragment API

* `getFragmentData()` - returns the `FragmentData` object defining methods for interacting with the fragment data components.

* `getFragmentActions()` - returns the `FragmentActions` object defining methods for interacting with fragment actions. Similar to `ViewActions`.

* `getParentController()` - returns a parent `FragmentOwner` object. Currently, it may be `View` or `Fragment`.

* `findInnerComponent()` / `getInnerComponent()` - return the inner component with the given id. These methods search among components added via an XML descriptor only.

Fragment inner components have fragment-specific hidden IDs instead of actual Vaadin component IDs. Jmix stores these IDs separately to avoid conflicts with components defined in host views or in multiple instances of the same fragment.

Because of this, use `FragmentUtils.getComponentId()` to obtain a component ID inside a fragment. Do not use methods that rely on actual component IDs, such as `UiComponentUtils`, for this purpose.

Use `findInnerComponent()` / `getInnerComponent()` to access fragment components by ID from the fragment controller. If you need to work with a component instance directly, `FragmentUtils.getComponentId()` returns its fragment-specific hidden ID.

[[fragment-events]]
== Fragment Events

* `ReadyEvent` - the event that is fired after the fragment and all its declaratively defined inner components are created and fully initialized. In this event listener, you can make the final configuration of the fragment and its inner components. For example:
+
.CustomerListFragment.java
[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/customer/CustomerListFragment.java[tags=imports;fragment-java]
----
<1> Triggers `load()` method of all loaders registered in the fragment, including the xref:fragments/using-fragments.adoc#provided-data-components[provided] ones.

[[fragment-autowiring]]
== Autowiring

Similar to views, fragments support injection of components defined in XML and invoking annotated handler methods:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/customer/CustomerListFragment2.java[tags=imports;class-declaration;autowire]
----
<1> Injects a UI component.
<2> Inject a data container.
<3> Subscribes to the fragment's `ReadyEvent`.
<4> Subscribes to a button's `ClickEvent`.
<5> Installs a load delegate.
<6> Supplies a data grid `Renderer`.

In addition to that, it's possible to subscribe to the host view events by defining `target = Target.HOST_CONTROLLER` in the `@Subscribe` annotation:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/customer/CustomerListFragment2.java[tags=host]
----