= Data Access Properties

[[jmix.data.number-id-cache-size]]
== jmix.data.number-id-cache-size

When an instance of an entity with an `Integer` or `Long` identifier annotated with xref:data-model:entities.adoc#jmix-generated-value[@JmixGeneratedValue] is created in memory via the `Metadata.create()` method, an identifier value is assigned to the entity right away. This value is obtained from the xref:features:sequences.adoc[] mechanism that fetches the next id from a database sequence. In order to reduce the number of database calls, the sequence’s increment is set by default to 100, which means that the framework obtains the range of ids on each invocation. So it "caches" this range and yields the ids without going for the next value to the database until the whole range is used.

The property defines the sequence’s increment and the corresponding size of the cached range in memory.

CAUTION: If you change the value of this property when there are already some entities in the database, recreate also all existing sequences with the new increment (which must be equal to `jmix.data.number-id-cache-size`) and the starting values corresponding to the maximum values of existing ids.

If you use the same sequence to create entities in a stored procedure, it is highly recommended to disable caching by setting the value of this property to `0` and recreating the sequence with increment `1`.

Default value: `100`

[[jmix.data.unique-constraint-violation-pattern]]
== jmix.data.unique-constraint-violation-pattern

A regular expression which is used by the mechanism of handling xref:flow-ui:exception-handlers.adoc#unique-constraint-violation-handler[unique constraint violations] to find out that the exception is caused by a database unique constraint violation. The constraint name will be obtained from the first non-empty group of the expression. For example:

[source, properties]
----
jmix.data.unique-constraint-violation-pattern = ERROR: duplicate key value violates unique constraint "(.+)"
----

This property allows you to recognize unique constraint violation errors for any DBMS version and locale.

[[jmix.data.use-entity-data-store-for-id-sequence]]
== jmix.data.use-entity-data-store-for-id-sequence

If the property is set to `true`, sequences for generating entity identifiers of `Integer` or `Long` type annotated with `@JmixGeneratedValue` are created in the data store the entity belongs to. Otherwise, they are created in the main data store.

Default value: `false`

[[jmix.data.use-read-only-transaction-for-load]]
== jmix.data.use-read-only-transaction-for-load

Indicates that all loading methods of xref:data-manager.adoc[DataManager] use read-only transactions.

Default value: `true`

[[jmix.eclipselink.disable-lazy-loading]]
== jmix.eclipselink.disable-lazy-loading

NOTE: This feature is currently experimental. It can be finalized or abandoned in a future release. If you encounter a problem when using this feature, please file an issue at https://github.com/jmix-framework/jmix/issues[GitHub^].

Turns off xref:data-access:fetching.adoc#lazy-loading[lazy loading] for the whole application. If this property is set to `true`, an `IllegalStateException` will be thrown when accessing an unfetched attribute.

Default value: `false`

[[jmix.eclipselink.query-cache-enabled]]
== jmix.eclipselink.query-cache-enabled

If the property is set to `false`, the xref:cache.adoc#query-cache[Query Cache] is completely disabled for all methods regardless of their parameters and annotations.

Default value: `true`
