= Entity Events

When you save and load entities using `DataManager`, the Jmix data access subsystem sends specific Spring application events. You can create event listeners to perform some additional actions with saved or loaded entity instances.

[[entity-changed-event]]
== Using EntityChangedEvent

`EntityChangedEvent` is sent by the framework when an entity instance is saved to the database. You can handle the event both inside the transaction and after its completion. In both cases, at the time of the event, the database already contains the changed data.

`EntityChangedEvent` contains change type (create, update or delete), the identifier of the changed entity, the information on what attributes were changed, and old values of changed attributes. For reference attributes, the old values contain identifiers of the referenced entities.

[[before-commit]]
=== Handling Changes Before Commit

To handle `EntityChangedEvent` in the current transaction, create a bean method annotated with `@EventListener`. The method will be called by the framework right after saving the entity to the database but before the transaction commit. In the listener method, you can make any changes to data, and they will be committed together with the initial changes. If an exception occurs, everything will be rolled back.

In the example below, we create a linked entity to register the change of an attribute. Both the changed `Customer` and the created `CustomerGradeChange` instances will be committed in the same transaction:

[source,java,indent=0]
----
include::example$/data-access-ex1/src/main/java/com/company/demo/listener/CustomerEventListener.java[tags=import-customer;import-customer-grade;import-customer-grade-change;import-data-manager;import-id;import-entity-changed-event;import-autowired;import-event-listener;import-component;listener-bean;data-manager;before-commit]
----
<1> Determining the change type.
<2> Checking if an attribute was actually changed.
<3> Getting the changed entity id.
<4> Obtaining an old value of the changed attribute.
<5> Loading the new state of the changed entity.

Let's look at another example. Here the `amount` attribute of the `Order` entity is updated whenever one of its `OrderLine` instances is created, updated or deleted:

[source,java,indent=0]
----
include::example$/data-access-ex1/src/main/java/com/company/demo/listener/OrderLineEventListener.java[tags=import-order;import-order-line;import-data-manager;import-id;import-entity-changed-event;import-autowired;import-event-listener;import-component;entity-changed]
----
<1> When the entity is deleted, we cannot load its instance anymore, so we use old values to get the reference to the enclosing `Order`.
<2> Use `getOldReference()` and `getOldCollection()` instead of `getOldValue()` for to-one and to-many reference attributes.

[[after-commit]]
=== Handling Changes After Commit

To handle `EntityChangedEvent` after the changes are saved to the database and the transaction is committed, create a bean method annotated with `@TransactionalEventListener`.

Note that exceptions that occur in an "after commit" event listener are not propagated to the calling code and are not logged. So it is recommended to wrap your code in a try-catch clause.

If you need to load or save any data in an "after commit" event listener, always start a new transaction.

The example below demonstrates exception handling and loading an entity with `DataManager` in a separate transaction:

[source,java,indent=0]
----
include::example$/data-access-ex1/src/main/java/com/company/demo/listener/CustomerEventListener.java[tags=import-customer;import-customer-grade;import-data-manager;import-entity-changed-event;import-logger;import-logger-factory;import-autowired;import-component;import-transactional;import-transactional-event-listener;listener-bean;logger;data-manager;after-commit]
----
<1> `Propagation.REQUIRES_NEW` is necessary here for starting the new transaction.

[[saving-loading-events]]
== Using EntitySavingEvent and EntityLoadingEvent

`EntitySavingEvent` is sent by the framework when an entity instance is about to be saved to the database. As opposed to <<entity-changed-event,EntityChangedEvent>>, which contains the entity id, `EntitySavingEvent` contains the entity instance itself. It allows you to change the instance state before it is saved in the database fields.

The event has the `isNewEntity()` method that returns true if the event is sent for a new instance that will be inserted to a database table.

An `EntitySavingEvent` listener can be used to initialize entity attributes before saving to the database. For example:

[source,java,indent=0]
----
include::example$/data-access-ex1/src/main/java/com/company/demo/listener/OrderEventListener.java[tags=import-order;import-entity-saving-event;import-event-listener;import-component;saving-event]
----

`EntityLoadingEvent` is sent by the framework when an entity instance is loaded from the database. You can use it for initializing non-persistent attributes from the persistent state.

[CAUTION]
====
You should access only local attributes of the entity that comes to an `EntitySavingEvent` or `EntityLoadingEvent` listener.

For references, the framework does not guarantee the presence of the referenced instances in `EntitySavingEvent` listener and cascading of events when references are loaded from an `EntityLoadingEvent` listener.
====

In the example below, `EntitySavingEvent` and `EntityLoadingEvent` listeners maintain an encrypted attribute:

[source,java,indent=0]
----
include::example$/data-access-ex1/src/main/java/com/company/demo/entity/Customer.java[tags=entity;encryption]
----

When the entity is saved, the sensitive content is encrypted and stored in the database. On loading, the content is decrypted and set back to the transient attribute to be accessible by users:

[source,java,indent=0]
----
include::example$/data-access-ex1/src/main/java/com/company/demo/listener/CustomerEventListener.java[tags=import-encryption-service;import-customer;import-entity-loading-event;import-entity-saving-event;import-autowired;import-event-listener;import-component;listener-bean;encryption]
----