= Работа с EntityManager

`EntityManager` – это стандартный интерфейс JPA для загрузки и сохранения сущностей. Он также может выполнять собственные SQL-запросы.

TIP: Мы рекомендуем использовать xref:data-manager.adoc[DataManager] для работы с сущностями и обращаться к `EntityManager` только если он вам действительно нужен.

Для получения информации о методах `EntityManager` обратитесь к документации API https://jakarta.ee/specifications/persistence/3.1/apidocs/jakarta.persistence/jakarta/persistence/entitymanager[jakarta.persistence.EntityManager^].

`EntityManager` можно использовать в приложениях Jmix для работы с xref:data-model:entities.adoc#jpa[сущностями JPA] в основном таким же образом, как и в любом приложении Spring. Однако Jmix предоставляет собственную реализацию стандартного интерфейса, которая имеет некоторые особенности.

[[obtaining-entity-manager]]
== Получение EntityManager

Экземпляр `EntityManager` можно инжектировать в любой бин Spring с помощью аннотации `@PersistenceContext`. Для использования экземпляра `EntityManager` у вас должна быть открытая xref:transactions.adoc[транзакция]. Например:

[source,java,indent=0]
----
include::example$/data-access-ex1/src/main/java/com/company/demo/bean/EntityManagerSampleService.java[tags=em-inject;em-persist]
----

Если вам нужно работать с сущностями из xref:data-model:data-stores.adoc#additional[дополнительного хранилища данных], получите экземпляр `EntityManager` для этого хранилища, указав имя хранилища данных в параметре `unitName` аннотации `@PersistenceContext`, например:

[source,java,indent=0]
----
include::example$/data-access-ex1/src/main/java/com/company/demo/bean/EntityManagerSampleService.java[tags=em-db1-inject;em-db1-persist]
----

NOTE: `EntityManager` нельзя инжектировать в контроллеры UI.

[[fetch-plans]]
== Использование фетч-планов

По умолчанию при использовании `EntityManager` для загрузки сущностей по id или запросу JPQL, он возвращает все локальные (непосредственные) атрибуты и жадно извлеченные ссылки по правилам спецификации JPA. Другие ссылки загружаются лениво в той же транзакции.

Вы можете использовать xref:fetching.adoc#fetch-plan[фетч-планы] для оптимизации загрузки необходимого графа объектов независимо от инструкции извлечения `FetchType.LAZY` в аннотациях атрибутов сущности. Фетч-план должен быть указан в свойствах. Например:

[source,java,indent=0]
----
include::example$/data-access-ex1/src/main/java/com/company/demo/bean/EntityManagerSampleService.java[tags=em-inject;em-find]
----

В приведенном выше примере будут загружены все локальные атрибуты сущности `Order` и связанной с ней `Customer`, даже если они не включены в план выборки явно. Если вы хотите загрузить только часть локальных атрибутов, создайте «частичный» фетч-план. Например:

[source,java,indent=0]
----
include::example$/data-access-ex1/src/main/java/com/company/demo/bean/EntityManagerSampleService.java[tags=em-load-partial]
----

[[soft-deletion]]
== Мягкое удаление

`EntityManager` поддерживает xref:data-model:soft-deletion.adoc[мягкое удаление]. Когда вы вызываете метод `remove()` для сущности с xref:data-model:entities.adoc#soft-delete-trait[чертой Soft Delete], он обновляет атрибуты `@DeletedDate` и `@DeletedBy` вместо удаления записи из базы данных.

Вы можете отключить мягкое удаление для конкретной транзакции, чтобы полностью удалить объекты с чертой Soft Delete и иметь возможность загружать экземпляры, помеченные как удаленные, указав свойство `PersistenceHints.`SOFT_DELETION`. Например:

[source,java,indent=0]
----
include::example$/data-access-ex1/src/main/java/com/company/demo/bean/EntityManagerSampleService.java[tags=em-hard-delete]
----

[[limitations]]
== Ограничения EntityManager

. События xref:data-access:entity-events.adoc#saving-loading-events[EntitySavingEvent и EntityLoadingEvent] не отправляются при сохранении и загрузке сущностей с `EntityManager`.

. xref:fetching.adoc#lazy-loading[Ленивая загрузка] ссылок вне транзакции, загружающей корневую сущность, не работает. Вы получите исключение "java.lang.IllegalStateException: Cannot get unfetched attribute ...'`', если получите доступ к такой ссылке.

. xref:data-model:entities.adoc#cross-data-store-ref[Ссылки между хранилищами данных] не поддерживаются.

. xref:security:authorization.adoc#data-access-checks[Проверки доступа к данным] пропускаются.

. Не поддерживаются следующие функции JPA: именованные запросы, `CriteriaBuilder`, `EntityGraph`, `EntityTransaction`.