= Data Access

When writing backend business logic, you need to load and store data model xref:data-model:entities.adoc[entities] in the database. This chapter describes different ways of working with entities using APIs provided by Jmix.

TIP: See also the xref:concepts:features.adoc#data-access[Key Features] section to learn about Jmix data access concepts.

The main interface for CRUD (Create, Read, Update, Delete) operations on entities is xref:data-manager.adoc[DataManager]. It allows you to load graphs of entities by ID or query, to save changed instances or remove them. You can use entity event listeners to perform actions on loading and saving of particular entities. `DataManager` maintains cross-datastore references for both JPA, DTO, and mixed entity graphs.

Most often, your application works with a single or multiple relational databases and you use JPA entities to map your database tables to Java classes. In this case, `DataManager` works through `JpaDataStore` based on https://www.eclipse.org/eclipselink[EclipseLink^] JPA provider. This data store implementation is integrated with xref:security:index.adoc[data access control], xref:audit:entity-log.adoc[entity log] and xref:dyn-attr:index.adoc[dynamic attributes]. It is available in your project if you have the following dependency in `build.gradle`:

[source,java,indent=0]
----
include::example$/data-access-ex1/build.gradle[tags=dependencies]
----

[NOTE]
====
When we talk about `DataManager` and its capabilities in this manual, we mean the most common case of working with JPA entities, if not explicitly stated otherwise.

See also the xref:rest-ds:index.adoc[] section for how to work with DTO entities mapped to a generic xref:rest:index.adoc[] of another Jmix application.
====

Another option for working with JPA entities is using JPA xref:entity-manager.adoc[EntityManager] directly. Some framework features are not compatible with the concept of "managed" entities, therefore `EntityManager` has some xref:entity-manager.adoc#limitations[limitations] compared to `DataManager`.

If you need to execute complex SQL queries, perform batch operations, or invoke stored procedures, consider using xref:jdbc.adoc[JDBC] wrappers provided by Spring.