= Доступ к данным

В процессе разработки бизнес-логики бэкэнда необходимо загружать и сохранять xref:data-model:entities.adoc[сущности] модели данных в базу данных. В этой главе описываются различные способы работы с сущностями с использованием API, которые предоставляются в Jmix.

TIP: См. также раздел xref:concepts:features.adoc#data-access[Ключевые возможности], в котором рассматриваются концепции доступа к данным в Jmix.

Основным интерфейсом для CRUD (Create, Read, Update, Delete) операций с сущностями является xref:data-manager.adoc[DataManager]. Он позволяет загружать графы сущностей по идентификатору или запросу, сохранять измененные экземпляры или удалять их. Вы можете использовать слушатели событий сущностей для выполнения действий по загрузке и сохранению определенных сущностей. `DataManager` поддерживает ссылки между сущностями из разных хранилищ данных как для JPA и DTO, так и для смешанных графов сущностей.

Чаще всего приложение работает с одной или несколькими реляционными базами данных, и для маппинга таблиц базы данных на классы Java используются сущности JPA. В этом случае `DataManager` работает через `JpaDataStore` на основе JPA провайдера https://www.eclipse.org/eclipselink[EclipseLink^]. Такая реализация хранилища данных интегрирована с xref:security:index.adoc[контролем доступа к данным], xref:audit:entity-log.adoc[журналом сущностей] и xref:dyn-attr:index.adoc[динамическими атрибутами]. Она доступна в вашем проекте, если у вас есть следующая зависимость в `build.gradle`:

[source,java,indent=0]
----
include::example$/data-access-ex1/build.gradle[tags=dependencies]
----

[NOTE]
====
Когда в данном руководстве говорится о `DataManager` и его возможностях, имеется в виду наиболее общий случай работы с сущностями JPA, если явно не указано иное.

См. также раздел xref:rest-ds:index.adoc[] для информации о том, как работать с DTO-сущностями, отображенными на универсальный xref:rest:index.adoc[] другого Jmix-приложения.
====

Другим вариантом работы с сущностями JPA является использование JPA xref:entity-manager.adoc[EntityManager] напрямую. Некоторые механизмы фреймворка несовместимы с концепцией "managed" сущностей, поэтому `EntityManager` имеет ряд xref:entity-manager.adoc#limitations[ограничений] по сравнению с `DataManager`.

Если вам нужно выполнять сложные SQL запросы, пакетные операции или вызывать хранимые процедуры, используйте классы-обертки xref:jdbc.adoc[JDBC], предоставляемые Spring.