= 数据访问

当编写后端业务逻辑时，需要从数据库读写数据模型 xref:data-model:entities.adoc[实体]。本章节介绍使用 Jmix 提供的 API 处理数据的不同方式。

TIP: 参阅 xref:concepts:features.adoc#data-access[主要功能] 部分了解 Jmix 数据访问的相关概念。

对实体进行 CRUD 操作的主要接口是 xref:data-manager.adoc[DataManager]。基本功能包括通过 ID 或查询语句加载实体关系图、保存实体和删除实体。可以用实体事件监听器在加载和保存特定实体时做一些额外的操作。`DataManager` 中也维护了跨数据库的实体引用，包括 JPA、DTO 和混合实体的实体关系图。

多数情况下，应用程序使用单一或多个关系型数据库，代码中使用 JPA 实体作为数据库表和 Java 类的映射。此时，`DataManager` 使用基于 https://www.eclipse.org/eclipselink[EclipseLink^] JPA provider 的 `JpaDataStore`。这个 data store 的实现集成了 xref:security:index.adoc[数据访问控制]、xref:audit:entity-log.adoc[实体日志] 和 xref:dyn-attr:index.adoc[动态属性]。如果使用了下面这个依赖，则项目中可以使用：

[source,java,indent=0]
----
include::example$/data-access-ex1/build.gradle[tags=dependencies]
----

[NOTE]
====
在此手册中，我们提到 `DataManager` 及其功能时，只要不是特殊说明，都是指使用 JPA 实体的最常见情况。

参阅 xref:rest-ds:index.adoc[] 部分了解如何使用映射至其他 Jmix 应用程序通用 xref:rest:index.adoc[] 的 DTO 实体。
====

处理 JPA 实体的另一个方法是直接使用 JPA xref:entity-manager.adoc[EntityManager]。某些框架功能与 “托管” 实体的概念不兼容，因此，与 `DataManager` 相比，`EntityManager` 有一些功能上的 xref:entity-manager.adoc#limitations[局限性]。

如果需要执行复杂的 SQL 查询、批处理操作或调用存储过程，可以考虑使用 Spring 提供的 xref:jdbc.adoc[JDBC] 包装器。
