= Notifications

Дополнение позволяет создавать и отправлять уведомления через различные каналы сообщений. Пользователи могут получать информационные сообщения, а также уведомления о системных событиях.

// as well as notifications from business processes.

[[installation]]
== Установка

[NOTE]
====
Для использования этого дополнения требуется корпоративная https://www.jmix.ru/subscription-plans-and-prices/[подписка^]. Если у вас нет подписки, ознакомьтесь с разделом xref:ROOT:account-management.adoc#enterprise-trial[Пробная Enterprise+BPM подписка], чтобы узнать, как получить пробную версию.
====

Для автоматической установки через Jmix Marketplace следуйте инструкциям в разделе xref:ROOT:add-ons.adoc#installation[Дополнения].

Для ручной установки выполните следующие шаги.

. Настройте доступ к премиум-репозиторию.
+
include::ROOT:partial$premium-repo.adoc[]

. Добавьте зависимости в ваш `build.gradle`:
+
[source,groovy,indent=0]
----
implementation 'io.jmix.notifications:jmix-notifications-starter'
implementation 'io.jmix.notifications:jmix-notifications-flowui-starter'
----
// [source,groovy,indent=0]
// ----
// include::example$ex1/build.gradle[tags=notifications-dep]
// ----

include::ROOT:single-menu-note.adoc[]