= Notifications

The add-on allows you to create and send notifications via various message channels. Users can receive informational messages as well as notifications about system events.

[[installation]]
== Installation

[NOTE]
====
This add-on requires the Enterprise https://www.jmix.io/subscription-plans-and-prices/[subscription^]. If you don't have the subscription, see the xref:ROOT:account-management.adoc#enterprise-trial[Enterprise Trial] section for how to get a trial version.
====

For automatic installation through Jmix Marketplace, follow the instructions in the xref:ROOT:add-ons.adoc#installation[Add-ons] section.

For manual installation, follow the steps below.

. Configure access to the premium repository.
+
include::ROOT:partial$premium-repo.adoc[]

. Add dependencies to your `build.gradle`:
+
[source,groovy,indent=0]
----
implementation 'io.jmix.notifications:jmix-notifications-starter'
implementation 'io.jmix.notifications:jmix-notifications-flowui-starter'
----
// [source,groovy,indent=0]
// ----
// include::example$ex1/build.gradle[tags=notifications-dep]
// ----

include::ROOT:single-menu-note.adoc[]