= Custom Action Types

You can create your own action types or override existing standard types in your project. These custom actions are then reusable across all application views, as illustrated in the examples below.

== BaseAction

You can create your own action class and then assign it to a component. Below is a minimal example that makes the button show “Hello” when clicked.

. Create an action class extending `BaseAction` and add the `@ActionType` annotation with the desired type name:
+
[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/actions/MyCustomAction.java[]
----
+
NOTE: If you want to override an existing action, register your new action class with the same type name in `@ActionType` annotation.
+
. Now you can use the action in view descriptors by specifying its type:
+
[source, xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/department/department-list-view.xml[tags=my-action]
----
+
. You can then assign it to a component:
+
[source, xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/department/department-list-view.xml[tags=action-button]
----

== ItemsTrackingAction

If you need an action, which becomes enabled when one or more table rows are selected, use `ItemTrackingAction`. For example, imagine that you need an action that would show the instance name of the currently selected entity in a `dataGrid`. Below are the steps to create the action.

. Create an action class and add the `@ActionType` annotation with the desired type name:
+
[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/actions/ShowSelectedAction.java[]
----
+
NOTE: If you want to override an existing action, register your new action class with the same type name in `@ActionType` annotation.
+
. Now you can use the action in view descriptors by specifying its type:
+
[source, xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/department/department-list-view.xml[tags=custom-action]
----