= Собственные типы действий

В проекте можно создать собственные типы действий или переопределить существующие стандартные типы.
Такие действия затем могут использоваться повторно во всех экранах приложения, как показано в примерах ниже.

== BaseAction

Можно создать собственный класс действия и привязать его к компоненту. Ниже минимальный пример, при котором кнопка покажет пользователю "Hello" при нажатии.

. Создайте класс действия, наследующий `BaseAction`, и добавьте аннотацию `@ActionType` с желаемым именем типа:
+
[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/actions/MyCustomAction.java[]
----
+
NOTE: Если вы хотите переопределить существующий тип действия, просто зарегистрируйте свое новое действие с таким же именем типа в аннотации `@ActionType`.
+
. Объявите действие в дескрипторе экрана, просто указав его тип:
+
[source, xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/department/department-list-view.xml[tags=my-action]
----
+
. Действие можно привязать к компоненту:
+
[source, xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/department/department-list-view.xml[tags=action-button]
----

== ItemsTrackingAction

Если требуется действие, которое становится доступным при выборе одной или нескольких строк в таблице, используйте `ItemTrackingAction`. Предположим, что вы хотите создать действие, которое бы показывало имя экземпляра текущей сущности, выбранной в `dataGrid`, и использовать это действие в различных экранах, указывая только его тип. Чтобы это сделать, необходимо выполнить следующие шаги:

. Создайте для действия отдельный класс с аннотацией `@ActionType`, в которой укажите желаемое имя типа:
+
[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/actions/ShowSelectedAction.java[]
----
+
NOTE: Если вы хотите переопределить существующий тип действия, просто зарегистрируйте свое новое действие с таким же именем типа в аннотации `@ActionType`.
+
. Теперь вы можете использовать действие в дескрипторах экрана, просто указывая его тип:
+
[source, xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/department/department-list-view.xml[tags=custom-action]
----