= Универсальный компонент в XML

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/generic-component-xml" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Элемент XML `component` позволяет вам создать любой UI-компонент, указав его полное имя класса (FQN). Свойства компонента определяются с помощью вложенных элементов `property`, аналогично настройке действия.

Например, вы можете определить компонент `Button` таким образом:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/customcomponent/genericcomponent/generic-component-view.xml[tags=button-component-xml]
----

Вот пример определения пользовательского компонента:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/customcomponent/genericcomponent/generic-component-view.xml[tags=test-component-xml]
----

[[property-configuration]]
== Конфигурация свойств

* Значение атрибута `name` преобразуется в имя метода-сеттера, например:

** `text` → `setText()`
** `dataLoader` → `setDataLoader()`

* Фреймворк ищет первый метод с соответствующим `name` и одним входным параметром для установки значения.
+
NOTE: Если несколько методов имеют одинаковое имя, нет гарантии, что для установки значения будет использован именно предполагаемый метод.

* Тип входного параметра найденного метода используется для преобразования строкового значения из атрибута `value` в фактическое значение.

* Атрибут `type` указывает, что строковое значение должно быть преобразовано одним из подключаемых бинов `PropertyParser`:
+
[cols="1,1,3", options="header"]
|===
| Тип | Парсер | Описание

| `ICON`
| `IconPropertyParser`
| Преобразует строку в экземпляр `Icon`

| `CONTAINER_REF`
| `DataContainerPropertyParser`
| Находит контейнер данных по `ID`

| `LOADER_REF`
| `DataLoaderPropertyParser`
| Находит загрузчик данных по `ID`
|===

[[property-parsers]]
== Парсеры свойств

Когда строковые значения не могут быть напрямую преобразованы с использованием типа параметра, преобразованием занимаются подключаемые бины `PropertyParser`.

В настоящее время существует три реализации:

* *IconPropertyParser*. Преобразует строки в экземпляры `Icon`.
** Если переданная строка содержит разделитель `:`, новый `Icon` создается с использованием значений _коллекции иконок_ и _имени иконки_.
** В противном случае строка трактуется как имя константы `VaadinIcon`.
+
Примеры:
** `"PLUS"` → иконка `VaadinIcon.PLUS`.
** `"myicons:custom"` → Иконка из пользовательской коллекции `"myicons"` с именем `"custom"`.

* *DataContainerPropertyParser*. Возвращает xref:flow-ui:data/data-containers.adoc[контейнер данных] с заданным `ID` из объекта `ViewData` соответствующего экрана.

* *DataLoaderPropertyParser*. Возвращает xref:flow-ui:data/data-loaders.adoc[загрузчик данных] с заданным `ID` из объекта `ViewData` соответствующего экрана.