= Действия

`Action` – это интерфейс, который абстрагирует действие (другими словами, некоторую функцию) от визуального компонента. Такая абстракция полезна, когда одно и то же действие может быть вызвано из разных визуальных компонентов (например, кнопкой и из контекстного меню таблицы). `Action` также определяет некоторые общие свойства, такие как заголовок, иконки сочетания клавиш, признаки доступности и видимости, и т.д.

== Creating Actions

Фреймворк предоставляет набор xref:actions/standard-actions.adoc[] для экранов, таблиц и компонентов выбора. Кроме того, можно создавать действия, используя один из трёх подходов:

* *xref:actions/declarative-actions.adoc[]:* объявив действие в XML и реализовав его обработчик.
* *xref:actions/custom-action-type.adoc[]:* создавая класс действия с возможностью переиспользовать его в экранах приложения.
* *xref:actions/programmatic-actions.adoc[]:* создав экземпляр действия в контроллере экрана.

== Компоненты, которые могут содержать действия

Действия могут быть определены для следующих компонентов:

* *Компоненты с одним действием* реализуют интерфейс `HasAction`. Например, xref:vc/components/button.adoc[]. Чтобы задать действие, используйте `HasAction.setAction()`.
* *Компоненты с несколькими действиями* реализуют интерфейс `HasActions`. Например: xref:vc/components/dataGrid.adoc[], xref:vc/components/entityComboBox.adoc[], xref:vc/components/entityPicker.adoc[]. Чтобы добавить действие, используйте `HasActions.addAction()`.
+
NOTE: Реализация `HasActions.addAction()` проверяет, наличие у компонента действия с таким же идентификатором. Если есть, то имеющееся действие будет заменено на новое переданное. Поэтому можно, например, декларировать стандартное действие в дескрипторе экрана, а затем в контроллере создать новое с переопределенными методами и добавить компоненту.

* *Экраны* сами по себе тоже могут содержать действия. Их можно определить в XML элементе `<actions>` или добавив программно через `getViewActions().addAction()`.