= Иконки

Этот раздел объясняет использование встроенных наборов иконок и добавление пользовательских значков. В Jmix вы можете располагать иконки в различных местах.

== Отдельные значки

Если иконка сама по себе несёт смысл, используйте специальный компонент (например, `icon`, `svgIcon` или `fontIcon`) и разместите его в необходимом месте на экране.

== Иконки в визуальных компонентах

Визуальным компонентам можно добавить иконки тремя декларативными способами:

* *Атрибуты:* Многие компоненты поддерживают добавление иконок через атрибуты; некоторые компоненты включают несколько таких атрибутов для разных слотов (например, `icon`, `uploadIcon`, `downloadButtonIcon`, `dropLabelIcon`). Это самый простой способ, но он не позволяет добавить пользовательские иконки.
* *Вложенные элементы:* Некоторые компоненты поддерживают вложенные элемента (например, `<icon>`, `<uploadIcon>`, `<dropdownIcon>`), которые позволяет использовать xref:icons/custom-icons.adoc[пользовательские иконки] — SVG, иконочные шрифты или изображения.
* *Префикс и суффикс:* У компонентов могут быть элементы xref:vc/miscellaneous/prefix-suffix.adoc[префикс и суффикс] которые могут содержать как стандартные, так и xref:icons/custom-icons.adoc[пользовательские].

Иконки также можно добавлять программно.

== Дополнительно

Другие части интерфейса, где часто используются иконки:

* xref:actions.adoc[]
* xref:menu-config.adoc[Главное меню] – заголовки секций и пункты меню