= Menu Configuration

`MenuConfig` is a special class that loads the main menu structure based on a file specified in the xref:flow-ui:ui-properties.adoc#jmix.ui.menu-config[jmix.ui.menu-config] property.

TIP: Use xref:studio:menu-designer.adoc[Studio menu designer] to define the menu structure.

When you create a new project in Studio, it generates the `menu.xml` file that defines the structure of the application main menu.

[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=menu-config;menu]
----

There are two xref:studio:menu-designer.adoc#menu-modes[modes] of loading files that define menu structure: composite (default) and single. Use the xref:flow-ui:ui-properties.adoc#jmix.ui.composite-menu[jmix.ui.composite-menu] property to switch these modes.

[[menu-attributes]]
== Menu Attributes
//todo: add Icons and Themes links
`menu` is a nested element of `menu-config`. It has the following attributes:

* `id` -- a unique identifier of the element.
* `title` -- a title of the `menu` element. If not set, the title is determined by the rule explained <<defining-menu-title,below>>.
* `description` -- a text description to be shown as tooltip on mouse hover. You can use localized messages from the xref:localization:message-bundles.adoc[message bundle].
* `icon` -- an icon of the `menu` element.
//See xref:ui:icons.adoc[Icons] for details.
* `classNames` -- defines a class name for the menu item.
//See xref:jmix:ui:themes.adoc[Themes] for details.
* `opened` -- defines whether the `menu` element is initially expanded. The default value is `false`.

For example:

[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=menu]
----

[[menu-elements]]
== Menu Elements

A `menu` element may contain child elements such as `items`, `separators`, and an `icon` (for a xref:icons/custom-icons.adoc[custom icon]).

[[item-attributes]]
== Item Attributes

`item` is a nested element of `menu`. For each item you can set attributes, <<item-properties,properties>>, <<route-parameters,route>> and <<url-query-parameters,query>> parameters.

The attributes are as follows:

* `id` -- a unique identifier of the element. If no `view` or `bean`, attribute is specified, the `id` is used to point to a view with this `id`. When the user clicks on the menu item, the corresponding view opens on the main screen.
// xref:ui:screens/root-screens.adoc#main-screen[main screen].
+
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=item-id]
----

* `title` -- a title of the `item` element. You can use localized messages from the xref:localization:message-bundles.adoc[message bundle]. If not set, the title will be determined by the rule explained <<defining-menu-title,below>>.
+
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=item-title]
----

* `description` -- a text description to be shown as tooltip on mouse hover. You can use localized messages from the xref:localization:message-bundles.adoc[message bundle].

* `view` -- a view identifier. It can be used to include one screen into the menu multiple times. When the user clicks on the menu item, the corresponding screen will be opened on the main screen.
+
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=item-view]
----
* `bean` -- a bean name. Must be used together with `beanMethod`. When the user clicks on the menu item, the specified method is invoked.
+
.menu.xml
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=item-bean]
----
+
.MenuBean.java
[source,java,indent=0]
----
include::example$onboarding/src/main/java/com/company/onboarding/app/MenuBean.java[tags=start;menu-bean;end]
----
+
You can pass parameters from the menu item to the bean method using the <<item-properties,properties>> nested element. For example:
+
.menu.xml
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=bean-method]
----
+
.MenuBean.java
[source,java,indent=0]
----
include::example$onboarding/src/main/java/com/company/onboarding/app/MenuBean.java[tags=start;method-with-params;end]
----

* `shortcutCombination` -- a xref:keyboard-shortcuts.adoc[keyboard shortcut] for this menu item. For example:
+
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=item-shortcut]
----
+
Shortcuts can also be configured in the `application.properties` file and then used in the `menu.xml` file in the following way:
+
.menu.xml
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=item-shortcut-prop]
----
+
.application.properties
[source,properties,indent=0]
----
include::example$onboarding/src/main/resources/application.properties[tags=menu-item-shortcut]
----
* `icon` -- an icon of the `item` element.
//See xref:ui:icons.adoc[Icons] for details.
* `className` -- defines a class name for the menu item.
//See xref:jmix:ui:themes.adoc[Themes] for details.

[[item-icons]]
== Item Icons
An `item` element can set a xref:icons/custom-icons.adoc[custom icon] within a nested `icon` element.

[[item-properties]]
== Item Properties

An `item` element can have properties to be passed to beans. The nested `properties` element is a container for such properties, which are defined in the `property` child elements. A `property` element can have the following attributes:

* `name` -- property name.
* `value` -- value to be set for this property.

[[route-parameters]]
== Route Parameters

An `item` element can declare route parameters inside its child `routeParameters` element.

The route that defines the URL path of a view can include a route parameter. One example of such a parameter would be the id of a specific entity instance passed to a xref:flow-ui:views/views.adoc#standard-detail-view[detail view]. The following menu item opens a detail view for a particular department:

.menu.xml
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=route-params]
----

[[url-query-parameters]]
== URL Query Parameters

An `item` element can declare one or multiple query parameters inside its child `urlQueryParameters` element.

.menu.xml
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=query-params]
----

//todo: add screen controller example handling query params

Query parameters are name-value pairs attached to the end of a URL after a question mark (`?`). Multiple query parameters are joined together into a query string with an ampersand (`&`). The example above will create a menu item pointing at the following URL:

----
https://example.com/cities?page=3&sort=desc
----

[[defining-menu-title]]
== Defining Menu Title

If the `title` attribute is not set, the title of a `menu` or `item` element is defined as a combination of the `menu-config` prefix and the element's `id`. The resulting string can be used as the key that defines a title in the xref:localization:message-bundles.adoc[message bundle]. For example:

.messages.properties
[source,properties,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/messages_en.properties[tags=title]
----

If menu item `id` is not set, to define a title for such menu item the `menu-config` prefix may be followed by the view name, or bean name and bean method name, separated by `#`, depending on which of these attributes are present.

