= 菜单配置

`MenuConfig` 是一个特殊的类，根据 xref:flow-ui:ui-properties.adoc#jmix.ui.menu-config[jmix.ui.menu-config] 应用程序属性加载主菜单结构。

TIP: 使用 xref:studio:menu-designer.adoc[Studio 菜单设计器] 定义菜单结构。

当使用 Studio 新建项目时，会生成包含应用程序主菜单结构的 `menu.xml` 文件。

[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=menu-config;menu]
----

有两种加载菜单结构定义文件的 xref:studio:menu-designer.adoc#menu-modes[模式]：composite（默认）和 single。使用 xref:flow-ui:ui-properties.adoc#jmix.ui.composite-menu[jmix.ui.composite-menu] 应用程序属性切换这两种模式。

[[menu-attributes]]
== menu 属性
//todo: add Icons and Themes links
`menu` 是 `menu-config` 的内部元素。具有下列属性：

* `id` - 元素的唯一标识符。
* `title` - `menu` 元素的标题。如果未设置，则会用 <<defining-menu-title,下面>> 介绍的规则确定标题。
* `description` - 鼠标悬停时展示的提示文字。可以使用 xref:localization:message-bundles.adoc[消息包] 中的本地化消息。
* `icon` - `menu` 元素的图标。
// 参阅 xref:ui:icons.adoc[图标] 章节了解详情。
* `classNames` - 定义菜单项的 CSS 类名。
// 参阅 xref:jmix:ui:themes.adoc[主题] 了解详情。
* `opened` - 定义 `menu` 元素是否默认展开。默认值为 `false`。

示例：

[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=menu]
----

[[menu-elements]]
== 菜单元素

`menu` 元素可以包含子元素，例如 `items`、`separators` 或 `icon`（用于 xref:icons/custom-icons.adoc[自定义图标]）。

[[item-attributes]]
== item 属性

`item` 是 `menu` 的内部元素。对于每个 `item`，可以设置这些属性（attributes）、<<item-properties,配置（properties）>>、<<route-parameters,（路由（route）>> 以及 <<url-query-parameters,查询参数（query parameters）>>。

有下列属性：

* `id` - 元素的唯一标识符。如果没有定义 `view`、`bean` 属性，则可以使用 `id` 指向同名视图。当用户点击时，会在主主界面打开相应的视图。
// xref:ui:screens/root-screens.adoc#main-screen[主界面]
+
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=item-id]
----

* `title` -- `item` 元素的标题。可以使用 xref:localization:message-bundles.adoc[消息包] 中的本地化小心。如果未设置，则会用 <<defining-menu-title,下面>> 介绍的规则确定标题。
+
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=item-title]
----

* `description` -- 鼠标悬停时展示的提示文字。可以使用 xref:localization:message-bundles.adoc[消息包] 中的本地化消息。

* `view` -- 视图标识符。可以用来在多个菜单打开同一界面。当用户点击时，会在主界面打开相应的视图。
+
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=item-view]
----
* `bean` --  bean 名称。必须与 `beanMethod` 一起使用。当用户点击时，执行指定的 bean 方法。
+
.menu.xml
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=item-bean]
----
+
.MenuBean.java
[source,java,indent=0]
----
include::example$onboarding/src/main/java/com/company/onboarding/app/MenuBean.java[tags=start;menu-bean;end]
----
+
使用 <<item-properties,properties>> 内部元素可以从菜单项传递参数至 bean 方法。示例：
+
.menu.xml
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=bean-method]
----
+
.MenuBean.java
[source,java,indent=0]
----
include::example$onboarding/src/main/java/com/company/onboarding/app/MenuBean.java[tags=start;method-with-params;end]
----

* `shortcutCombination` -- 菜单项的 xref:keyboard-shortcuts.adoc[键盘快捷键]。示例：
+
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=item-shortcut]
----
+
快捷键可以在 `application.properties` 文件配置，在 `menu.xml` 文件使用：
+
.menu.xml
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=item-shortcut-prop]
----
+
.application.properties
[source,properties,indent=0]
----
include::example$onboarding/src/main/resources/application.properties[tags=menu-item-shortcut]
----
* `icon` -- `item` 元素的图标。
//See xref:ui:icons.adoc[Icons] for details.
* `className` -- 定义菜单项的 CSS 类名。
//See xref:jmix:ui:themes.adoc[Themes] for details.

[[item-icons]]
== 菜单项图标
在 `item` 元素的内部 `icon` 元素中，可以设置一个 xref:icons/custom-icons.adoc[自定义图标]。

[[item-properties]]
== item 配置

`item` 元素可以用内部的 `properties` 元素配置传入 bean 的参数。`properties` 是一个容器元素，内部的 `property` 子元素用来定义具体的配置，可以设置：

* `name` -- 配置属性名称
* `value` -- 配置属性值。

[[route-parameters]]
== 路由参数

`item` 元素可以在子元素 `routeParameters` 中声明路由参数。

定义视图路由的 URL 路径可以包含路由参数。例如，传入 xref:flow-ui:views/views.adoc#standard-detail-view[详情视图] 的实体实例 id 就可以作为路由参数。下面例子中的菜单项打开特定部门的详情视图：

.menu.xml
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=route-params]
----

[[url-query-parameters]]
== URL 查询参数

`item` 元素还可以在子元素 `urlQueryParameters` 中定义一个或多个 URL 查询参数（query parameter）。

.menu.xml
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=query-params]
----

//todo: add screen controller example handling query params

查询参数是 URL 尾部问号（`?`）后的名值对。多个查询参数可以用 `&` 符号分隔。上面示例会创建一个菜单项打开下面的 URL：

----
https://example.com/cities?page=3&sort=desc
----

[[defining-menu-title]]
== 菜单标题

如果 `title` 属性未定义，则 `menu` 或 `item` 标题通过这种方式定义：以 `menu-config` 作为前缀，再加上元素的 `id`，中间以 “.” 分隔。形成的字符串作为 xref:localization:message-bundles.adoc[消息包] 的键值。示例：

.messages.properties
[source,properties,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/messages_en.properties[tags=title]
----

如果菜单项的 `id` 未设置，为了给这种菜单项定义标题，会在 `menu-config` 之后添加视图名称或 bean 名称及方法，以 `#` 分隔。
