= Конфигурация меню

`MenuConfig` - это особый класс, который загружает структуру главного меню на основе файла, указанного в свойстве xref:flow-ui:ui-properties.adoc#jmix.ui.menu-config[jmix.ui.menu-config].

TIP: Используйте xref:studio:menu-designer.adoc[Дизайнер меню Studio], чтобы определить структуру меню.

При создании нового проекта в Studio, генерируется файл `menu.xml`, который определяет структуру главного меню приложения.

[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=menu-config;menu]
----

Существует два xref:studio:menu-designer.adoc#menu-modes[режима] загрузки файлов, определяющих структуру меню: составной (по умолчанию) и одиночный. Используйте свойство xref:flow-ui:ui-properties.adoc#jmix.ui.composite-menu[jmix.ui.composite-menu], чтобы переключать эти режимы.

[[menu-attributes]]
== Атрибуты меню
//todo: add Icons and Themes links
`menu` - это вложенный элемент `menu-config`. Он имеет следующие атрибуты:

* `id` - уникальный идентификатор элемента.
* `title` - заголовок элемента `menu`. Если не указан, заголовок определяется по правилу, объясненному <<defining-menu-title,ниже>>.
* `description` - текстовое описание, отображаемое во всплывающей подсказке при наведении мыши. Вы можете использовать локализованные сообщения из xref:localization:message-bundles.adoc[пакета сообщений].
* `icon` - значок элемента `menu`.
//См. xref:ui:icons.adoc[Значки] для подробностей.
* `classNames` - определяет имя класса для элемента меню.
//См. xref:jmix:ui:themes.adoc[Темы] для подробностей.
* `opened` - определяет, будет ли элемент `menu` изначально развернут. Значение по умолчанию - `false`.

Например:

[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=menu]
----

[[menu-elements]]
== Элементы меню

Элемент `menu` может содержать дочерние элементы: `items`, `separators` и `icon` (для добавления xref:icons/custom-icons.adoc[пользовательской иконки]).

[[item-attributes]]
== Атрибуты элемента
`item` - это вложенный элемент `menu`. Для каждого элемента можно установить атрибуты, <<item-properties,свойства>>, параметры <<route-parameters,маршрута>> и параметры <<url-query-parameters,запроса>>.

Атрибуты следующие:

* `id` - уникальный идентификатор элемента. Если не указаны атрибуты `view` или `bean`, идентификатор используется для указания на представление с этим `id`. Когда пользователь нажимает на элемент меню, соответствующее представление открывается на главном экране.
// xref:ui:screens/root-screens.adoc#main-screen[главный экран].
+
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=item-id]
----

* `title` - заголовок элемента `item`. Вы можете использовать локализованные сообщения из xref:localization:message-bundles.adoc[пакета сообщений]. Если не указан, заголовок будет определен по правилу, объясненному <<defining-menu-title,ниже>>.
+
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=item-title]
----

* `description` - текстовое описание, отображаемое во всплывающей подсказке при наведении мыши. Вы можете использовать локализованные сообщения из xref:localization:message-bundles.adoc[пакета сообщений].

* `view` - идентификатор экрана. Он может использоваться для включения одного экрана в меню несколько раз. Когда пользователь нажимает на элемент меню, открывается соответствующий экран на главном экране.
+
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=item-view]
----
* `bean` - имя бина. Должно использоваться вместе с `beanMethod`. Когда пользователь нажимает на элемент меню, вызывается указанный метод.
+
.menu.xml
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=item-bean]
----
+
.MenuBean.java
[source,java,indent=0]
----
include::example$onboarding/src/main/java/com/company/onboarding/app/MenuBean.java[tags=start;menu-bean;end]
----
+
Вы можете передавать параметры из элемента меню в метод бина, используя вложенный элемент <<item-properties,properties>>. Например:
+
.menu.xml
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=bean-method]
----
+
.MenuBean.java
[source,java,indent=0]
----
include::example$onboarding/src/main/java/com/company/onboarding/app/MenuBean.java[tags=start;method-with-params;end]
----

* `shortcutCombination` - xref:keyboard-shortcuts.adoc[горячая клавиша] для этого элемента меню. Возможные модификаторы - `ALT`, `CTRL`, `SHIFT` - разделяются символом "-". Например:
+
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=item-shortcut]
----
+
Горячие клавиши также можно настроить в файле `application.properties`, а затем использовать в файле `menu.xml` следующим образом:
+
.menu.xml
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=item-shortcut-prop]
----
+
.application.properties
[source,properties,indent=0]
----
include::example$onboarding/src/main/resources/application.properties[tags=menu-item-shortcut]
----
* `icon` - значок элемента `item`.
//См. xref:ui:icons.adoc[Значки] для подробностей.
* `className` - определяет имя класса для элемента меню.
//См. xref:jmix:ui:themes.adoc[Темы] для подробностей.

[[item-icons]]
== Иконка для пункта меню
Элемент `item` может задавать xref:icons/custom-icons.adoc[пользовательскую иконку] внутри вложенного элемента `icon`.

[[item-properties]]
== Свойства элемента меню
Элемент `item` может иметь свойства, которые передаются бинам. Вложенный элемент `properties` является контейнером для таких свойств, которые определены в дочерних элементах `property`. Элемент `property` может иметь следующие атрибуты:

* `name` - имя свойства.
* `value` - значение, которое нужно установить для этого свойства.

[[route-parameters]]
== Параметры маршрута
Элемент `item` может объявлять параметры маршрута внутри своего дочернего элемента `routeParameters`.

Маршрут, который определяет URL-путь к экрану, может включать параметр маршрута. Один из примеров такого параметра - это идентификатор конкретного экземпляра сущности, передаваемый в xref:flow-ui:views/views.adoc#standard-detail-view[экран деталей]. Следующий элемент меню открывает экран деталей для определенного отдела:

.menu.xml
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=route-params]
----

[[url-query-parameters]]
== Параметры запроса URL
Элемент `item` может объявлять один или несколько параметров запроса внутри своего дочернего элемента `urlQueryParameters`.

.menu.xml
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/menu.xml[tags=query-params]
----

//todo: add screen controller example handling query params

Параметры запроса представляют собой пары имя-значение, прикрепленные к концу URL после вопросительного знака (`?`). Несколько параметров запроса объединяются в строку запроса с использованием амперсанда (`&`). Приведенный выше пример создаст элемент меню, указывающий на следующий URL:

----
https://example.com/cities?page=3&sort=desc
----

[[defining-menu-title]]
== Определение заголовка меню
Если атрибут `title` не задан, заголовок элемента `menu` или `item` определяется как комбинация префикса `menu-config` и идентификатора элемента. Получившаяся строка может использоваться как ключ, который определяет заголовок в xref:localization:message-bundles.adoc[пакете сообщений]. Например:

.messages.properties
[source,properties,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/messages_en.properties[tags=title]
----

Если `id` для пункта меню не указан, для задания ему заголовка в пакете сообщений за префиксом `menu-config` может следовать имя экрана или имя бина и имя метода бина, разделенные символом `#`, в зависимости от наличия соответствующих атрибутов.