= UI Properties
:page-aliases: app-properties.adoc

[[common]]
== Common

[[jmix.ui.composite-menu]]
=== jmix.ui.composite-menu

Specifies whether the menu is built with menu items from installed xref:jmix:ROOT:add-ons.adoc[add-ons].

When set to `true`, the menu will include both the items from `menu.xml` of the application and the items from `menu.xml` of each installed add-on that has such file.

When set to `false`, the menu will only include those items that you add to the application's `menu.xml`.

Studio xref:studio:menu-designer.adoc[] helps managing the menu structure for both modes.

Default value: `true`.

[[jmix.ui.default-max-fetch-size]]
=== jmix.ui.default-max-fetch-size

Specifies the default maximum number of entity instances that can be loaded to the UI layer.

Default value: `10000`

See also <<jmix.ui.entity-max-fetch-size,jmix.ui.entity-max-fetch-size>>.

[[jmix.ui.default-page-size]]
=== jmix.ui.default-page-size

Specifies the default number of items on the page for the xref:flow-ui:vc/components/simplePagination.adoc[simplePagination] component.

Default value: `50`

See also <<jmix.ui.entity-page-size,jmix.ui.entity-page-size>>.

[[jmix.ui.default-view-id]]
=== jmix.ui.default-view-id

Defines a view to be opened after login inside the xref:flow-ui:views/views.adoc#standard-main-view[main view]. For example:

[source,properties]
----
jmix.ui.default-view-id = User.list
----

See also <<jmix.ui.main-view-id,jmix.ui.main-view-id>>.

[[jmix.ui.entity-max-fetch-size]]
=== jmix.ui.entity-max-fetch-size

Specifies the default maximum number of entity instances that can be loaded to the UI layer for a particular entity.

The following example configures the maximum fetch size for two entities. For all other entities the value from <<jmix.ui.default-max-fetch-size,jmix.ui.default-max-fetch-size>> is used.

[source,properties]
----
jmix.ui.entity-max-fetch-size.Product = 500
jmix.ui.entity-max-fetch-size.Customer = 1000
----

[[jmix.ui.entity-page-size]]
=== jmix.ui.entity-page-size

Specifies the default page size for the xref:flow-ui:vc/components/simplePagination.adoc[simplePagination] components for a particular entity.

The following example configures the page size for two entities. For all other entities the default value from <<jmix.ui.default-page-size,jmix.ui.default-page-size>> is used.

[source,properties]
----
jmix.ui.entity-page-size.Product = 100
jmix.ui.entity-page-size.Customer = 500
----

[[jmix.ui.exception-dialog-modal]]
=== jmix.ui.exception-dialog-modal

This application property controls whether the xref:exception-handlers.adoc#customizing-default-handler[ExceptionDialog] in Jmix applications should be displayed as a modal window.

When enabled, `ExceptionDialog` will act as a modal window, preventing interaction with other parts of the application until the dialog is closed.

When disabled, `ExceptionDialog` will act as a non-modal window, allowing users to continue interacting with other parts of the application while the dialog is open.

Default value: `true`.

See also xref:flow-ui:exception-handlers.adoc[Exception Handlers].

[[jmix.ui.file-downloader-cache-max-age-sec]]
=== jmix.ui.file-downloader-cache-max-age-sec

Sets the maximum time (in seconds) that a downloaded file is considered fresh by the browser's cache. This property is particularly useful for ensuring that the built-in PDF viewer in Google Chrome displays the most recent version of a file.

The property sets the `max-age` directive in the Cache-Control HTTP response header. See the https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Cache-Control#response_directives[MDN documentation^] for details.

Default value: `3600`.

See also xref:files:downloading-files.adoc#downloader[Using Downloader].

[[jmix.ui.main-view-id]]
=== jmix.ui.main-view-id

The identifier of a view to be used as the xref:flow-ui:views/views.adoc#standard-main-view[main page] of the application.

Default value: `main`.

See also <<jmix.ui.default-view-id,jmix.ui.default-view-id>>.

[[jmix.ui.menu-config]]
=== jmix.ui.menu-config

Specifies the path to the `menu.xml` file. The file is loaded using the `Resources` interface, so it can be located in classpath or in the configuration directory.

For example:

[source,properties]
----
jmix.ui.menu-config = com/company/onboarding/menu.xml
----

[[jmix.ui.login-view-id]]
=== jmix.ui.login-view-id

The identifier of a view to be used as the login page of the application.

Default value: `login`.

[[jmix.ui.save-exported-byte-array-data-threshold-bytes]]
=== jmix.ui.save-exported-byte-array-data-threshold-bytes

Specifies the threshold, in bytes, on which downloaded through `ByteArrayDownloadDataProvider` byte arrays will be saved to temporary files to prevent HTTP session memory leaks.

Default value: `102400`

[[jmix.ui.use-session-fixation-protection]]
=== jmix.ui.use-session-fixation-protection

Specifies whether the session is reinitialized after login to protect against session fixation attacks.

Default value: `true`

[[jmix.ui.view-file-extensions]]
=== jmix.ui.view-file-extensions

For the `Downloader` bean, specifies the list of file extensions to be shown in the web browser tab instead of downloading them automatically.

Default value: `jpg, png, jpeg, pdf`

[[jmix.ui.view.close-shortcut]]
=== jmix.ui.view.close-shortcut

Defines the xref:keyboard-shortcuts.adoc[keyboard shortcut] that is used to close the current view.

[[jmix.ui.view.save-shortcut]]
=== jmix.ui.view.save-shortcut

Defines the xref:keyboard-shortcuts.adoc[keyboard shortcut] that is used to save changes.

[[jmix.ui.view.create-action-adds-first]]
=== jmix.ui.view.create-action-adds-first

Specifies whether an entity created in the dialog window is added to the beginning of the list instead of to the end.

Default value: `true`

[[jmix.ui.view.reload-unfetched-attributes-from-lookup-views]]
=== jmix.ui.view.reload-unfetched-attributes-from-lookup-views

Specifies whether `LookupBuilder` will reload an entity after it is selected from lookup window if the selected entity doesn't contain all required entity attributes.

Default value: `true`

[[jmix.ui.view.use-save-confirmation]]
=== jmix.ui.view.use-save-confirmation

Determines what options are shown in the confirmation dialog when closing an entity detail view with unsaved changes in `DataContext`. Depending on this property, the entity detail view invokes either xref:views/view-validation.adoc#showSaveConfirmationDialog[showSaveConfirmationDialog()] or xref:views/view-validation.adoc#showUnsavedChangesDialog[showUnsavedChangesDialog()] methods of the `ViewValidation` bean.

If set to `true`, the dialog contains three options: *Save*, *Don’t save*, *Cancel*.

If set to `false`, the dialog contains only two options: *Yes* to close without saving, and *No* to stay and continue editing.

Default value: `true`.

[[jmix.ui.view.prevent-browser-tab-closing]]
=== jmix.ui.view.prevent-browser-tab-closing

Specifies whether a confirmation dialog is shown if a user attempts to close a browser tab, and the corresponding property of the view is also set to `true` using the xref:views/views.adoc#prevent-browser-tab-closing[setPreventBrowserTabClosing] method.

Default value: `false`.

[[jmix.ui.view.validation-notification-duration]]
=== jmix.ui.view.validation-notification-duration

Defines the duration, in milliseconds, to show the view validation error notifications.

Default value: `3000`

[[jmix.ui.view.validation-notification-position]]
=== jmix.ui.view.validation-notification-position

Sets the validation notifications position on the page. Possible values: `TOP_STRETCH`, `TOP_START`, `TOP_CENTER`, `TOP_END`, `MIDDLE`, `BOTTOM_START`, `BOTTOM_CENTER`, `BOTTOM_END`, `BOTTOM_STRETCH`.

Default value: `BOTTOM_END`

[[jmix.ui.view.validation-notification-type]]
=== jmix.ui.view.validation-notification-type

Specifies standard view validation error notifications variant. Accepts one of the `Notifications.Type` enum values: `DEFAULT`, `ERROR`, `SUCCESS`, `SYSTEM`, `WARNING`.

Default value: `DEFAULT`

[[jmix.ui.navigation.use-crockford-uuid-encoder]]
=== jmix.ui.navigation.use-crockford-uuid-encoder

Specifies whether https://www.crockford.com/base32.html[Base32 Crockford Encoding^]  is used for encoding/decoding of UUID URL parameters.

Default value: `false`

[[jmix.ui.ui-test-mode]]
=== jmix.ui.ui-test-mode

Enables generating special test ids to use with the Masquerade testing library. To learn more, please see xref:testing:masquerade.adoc[Masquerade].

[[components]]
== Components

[[jmix.ui.component.checkbox-required-state-initialization-enabled]]
=== jmix.ui.component.checkbox-required-state-initialization-enabled

This property controls the behavior of xref:vc/components/checkbox.adoc[checkbox] and xref:vc/components/switch.adoc[switch] bound to a mandatory boolean attribute with `@NotNull` validation.

* If `true`, `checkbox`/`switch` must be checked to pass validation.

* If `false`, `checkbox`/`switch` can remain unchecked without causing validation errors. This allows it to represent either a `true` or `false` value as needed.

Default value: `true`

[[jmix.ui.component.default-notification-duration]]
=== jmix.ui.component.default-notification-duration

Specifies the duration, in milliseconds, for which a notification is displayed.

Default value: `3000`

[[jmix.ui.component.default-notification-position]]
=== jmix.ui.component.default-notification-position

Specifies the default notification position on the page. Possible values: `TOP_STRETCH`, `TOP_START`, `TOP_CENTER`, `TOP_END`, `MIDDLE`, `BOTTOM_START`, `BOTTOM_CENTER`, `BOTTOM_END`, `BOTTOM_STRETCH`.

Default value: `MIDDLE`

[[jmix.ui.component.default-trim-enabled]]
=== jmix.ui.component.default-trim-enabled

Specifies the default value for the xref:vc/components/textField.adoc#trimEnabled[trimEnabled] attribute of the `textField` and `textArea` components.

Default value: `true`

[[jmix.ui.component.entity-field-actions]]
=== jmix.ui.component.entity-field-actions

Defines actions to be added to the selection component for the specified entity within generation strategy mechanisms as xref:vc/components/genericFilter.adoc[genericFilter] parameters or editable xref:vc/components/dataGrid.adoc[dataGrid] cells.

For example, to use `entity_lookup`, `entity_open`, and `entity_clear` actions in components selecting the `User` entity, set the property as follows:

[source,properties]
----
jmix.ui.component.entity-field-actions.User = entity_lookup, entity_open, entity_clear
----

[[jmix.ui.component.entity-field-fqn]]
=== jmix.ui.component.entity-field-fqn

Defines the component to be used for selecting the specified entity within generation strategy mechanisms as xref:vc/components/genericFilter.adoc[genericFilter] parameters or editable xref:vc/components/dataGrid.adoc[dataGrid] cells.

Specify the fully qualified class name (FQN) as the property value. For example, to use xref:vc/components/entityComboBox.adoc[entityComboBox] for selecting the `User` entity, set the property as follows:

[source,properties]
----
jmix.ui.component.entity-field-fqn.User = io.jmix.flowui.component.combobox.EntityComboBox
----

By default, generic mechanisms use the xref:vc/components/entityPicker.adoc[entityPicker] component.

The fully qualified class name (FQN) of `entityPicker` is `io.jmix.flowui.component.valuepicker.EntityPicker`.

[[jmix.ui.component.filter-apply-shortcut]]
=== jmix.ui.component.filter-apply-shortcut

Defines the xref:keyboard-shortcuts.adoc[keyboard shortcut] that is used to apply current filtering conditions in a xref:vc/components/genericFilter.adoc[genericFilter] component in case they are not <<jmix.ui.component.filter-auto-apply, automatically applied>>.

For example, you can disable auto-apply for all filters and provide a shortcut to apply them manually:

[source,properties]
----
jmix.ui.component.filter-auto-apply = false
jmix.ui.component.filter-apply-shortcut = ALT-ENTER
----

This property can be overridden for a particular xref:vc/components/genericFilter.adoc[] component using its `applyShortcut` XML attribute.

[[jmix.ui.component.filter-auto-apply]]
=== jmix.ui.component.filter-auto-apply

When set to `true`, configures xref:vc/components/genericFilter.adoc[] components to work in the immediate mode when every change of parameters automatically reloads data.

When set to `false`, reload occurs only after the *Refresh* button is clicked.

This property can be overridden for a particular xref:vc/components/genericFilter.adoc[] component using its `autoApply` XML attribute.

Default value: `true`

[[jmix.ui.component.filter-configuration-unique-names-enabled]]
=== jmix.ui.component.filter-configuration-unique-names-enabled

When set to `true` enforces unique names for filter configurations created at runtime. At the same time, allows a xref:vc/components/genericFilter.adoc#run-time-configuration[runtime configuration] and a xref:vc/components/genericFilter.adoc#design-time-configuration[design-time configuration] to share the same name without causing a conflict.

Note that configurations created at design time are marked with an asterisk (*) to distinguish them from runtime configurations.

Default value: `true`

[[jmix.ui.component.filter-properties-hierarchy-depth]]
=== jmix.ui.component.filter-properties-hierarchy-depth

Defines the properties hierarchy depth in the Add Condition editor in xref:vc/components/genericFilter.adoc[]. For example, if the depth value is 2, then you can select an entity attribute `contractor.city.country`, if the value is 3, then `contractor.city.country.name`, etc.

This property can be overridden for a particular xref:vc/components/genericFilter.adoc[] component using its `propertyHierarchyDepth` XML attribute.

Default value: `2`

[[jmix.ui.component.filter-show-configuration-id-field]]
=== jmix.ui.component.filter-show-configuration-id-field

Specifies whether the configuration id field is visible in the xref:vc/components/genericFilter.adoc[genericFilter's] configuration details dialog.

Default value: `false`


[[jmix.ui.component.grid-add-shortcut]]
=== jmix.ui.component.grid-add-shortcut

Defines the xref:keyboard-shortcuts.adoc[keyboard shortcut] that is used to execute xref:actions/list-actions.adoc#list_add[list_add] action.

[[jmix.ui.component.grid-create-shortcut]]
=== jmix.ui.component.grid-create-shortcut

Defines the xref:keyboard-shortcuts.adoc[keyboard shortcut] that is used to execute xref:actions/list-actions.adoc#list_create[list_create] action.

[[jmix.ui.component.grid-edit-shortcut]]
=== jmix.ui.component.grid-edit-shortcut

Defines the xref:keyboard-shortcuts.adoc[keyboard shortcut] that is used to execute xref:actions/list-actions.adoc#list_edit[list_edit] action.

Default value: `ENTER`

[[jmix.ui.component.grid-read-shortcut]]
=== jmix.ui.component.grid-read-shortcut

Defines the xref:keyboard-shortcuts.adoc[keyboard shortcut] that is used to execute xref:actions/list-actions.adoc#list_read[list_read] action.

Default value: `ENTER`

[[jmix.ui.component.grid-remove-shortcut]]
=== jmix.ui.component.grid-remove-shortcut

Defines the xref:keyboard-shortcuts.adoc[keyboard shortcut] that is used to execute xref:actions/list-actions.adoc#list_remove[list_remove] action.

[[jmix.ui.component.immediate-required-validation-enabled]]
=== jmix.ui.component.immediate-required-validation-enabled

By default, a required field is highlighted as soon as the view is opened and before the user enters any values.

If this property is set to false, the validation of required fields is performed only on saving the detail view.

Default value: `true`

[[jmix.ui.component.pagination-items-per-page-items]]
=== jmix.ui.component.pagination-items-per-page-items

Specifies the options for number of items per page in the xref:flow-ui:vc/components/simplePagination.adoc[simplePagination] component.

To configure a custom list of options for a concrete instance of simplePagination, use the xref:flow-ui:vc/components/simplePagination.adoc#itemsPerPageItems[itemsPerPageItems] XML attribute.

Default value: `[20, 50, 100, 500, 1000, 5000]`

[[jmix.ui.component.picker-clear-shortcut]]
=== jmix.ui.component.picker-clear-shortcut

Defines the xref:keyboard-shortcuts.adoc[keyboard shortcut] that is used to clear input of a picker component.

[[jmix.ui.component.picker-lookup-shortcut]]
=== jmix.ui.component.picker-lookup-shortcut

Defines the xref:keyboard-shortcuts.adoc[keyboard shortcut] that is used to open a lookup view for a picker component.

[[jmix.ui.component.picker-open-shortcut]]
=== jmix.ui.component.picker-open-shortcut

Defines the keyboard xref:keyboard-shortcuts.adoc[shortcut] that is used to open a detail view for the entity selected in a picker component.

[[jmix.ui.component.show-error-message-below-field]]
=== jmix.ui.component.show-error-message-below-field

Controls whether error messages are displayed directly below fields. The default value is `true`, meaning error messages appear beneath the corresponding field. Setting this property to `false` hides these inline messages; instead, a summary notification containing all errors appears when the user clicks *OK* (or a similar submit button).

Default value: `true`.

[[asynchronous-tasks]]
== Asynchronous Tasks

[[jmix.ui.async-task.default-timeout-sec]]
=== jmix.ui.async-task.default-timeout-sec

Default timeout of xref:flow-ui:async-tasks.adoc[asynchronous tasks] in seconds.

Default value: 300.

[[jmix.ui.async-task.executor-service.maximum-pool-size]]
=== jmix.ui.async-task.executor-service.maximum-pool-size

Maximum thread pool size of the executor service used in xref:async-tasks.adoc[asynchronous tasks].

Default value: 10.


[[background-tasks]]
== Background Tasks

[[jmix.ui.background-task.task-killing-latency]]
=== jmix.ui.background-task.task-killing-latency

Specifies the timeout after which xref:background-tasks.adoc[background tasks] that do not update their status are killed (task's timeout plus latency timeout). If the duration suffix (`ns`, `us`, `ms`, `s`, `m`, `h` and `d` for nanoseconds, microseconds, milliseconds, seconds, minutes, hours, and days, respectively) is not specified, seconds will be used.

Default value: `60`

[[jmix.ui.background-task.threads-count]]
=== jmix.ui.background-task.threads-count

Specifies the number of threads for executing xref:background-tasks.adoc[background tasks].

Default value: `10`

[[jmix.ui.background-task.timeout-expiration-check-interval]]
=== jmix.ui.background-task.timeout-expiration-check-interval

Specifies the interval at which the expiration of the xref:background-tasks.adoc[background task] is checked. If the duration suffix (`ns`, `us`, `ms`, `s`, `m`, `h` and `d` for nanoseconds, microseconds, milliseconds, seconds, minutes, hours, and days, respectively) is not specified, milliseconds will be used.

Default value: `5000`