= UI 配置
:page-aliases: app-properties.adoc

[[common]]
== 通用配置

[[jmix.ui.composite-menu]]
=== jmix.ui.composite-menu

配置应用程序的菜单是否包含所有已安装的 xref:jmix:ROOT:add-ons.adoc[扩展组件] 菜单。

当设置为 `true` 时，菜单会包含应用中 `menu.xml` 的内容，以及所有扩展组件中 `menu.xml` 的内容（如果有的话）。

而设置为 `false` 时，菜单仅包含应用程序的 `menu.xml`。

Studio xref:studio:menu-designer.adoc[] 可以帮助管理两种模式下的菜单结构。

默认值：`true`

[[jmix.ui.default-max-fetch-size]]
=== jmix.ui.default-max-fetch-size

配置可以加载至 UI 层实体实例的默认最大数量。

默认值：`10000`

参阅 <<jmix.ui.entity-max-fetch-size,jmix.ui.entity-max-fetch-size>>。

[[jmix.ui.default-page-size]]
=== jmix.ui.default-page-size

对于 xref:flow-ui:vc/components/simplePagination.adoc[simplePagination] 组件，配置显示在每页中的默认数据条数。

默认值：`50`

参阅 <<jmix.ui.entity-page-size,jmix.ui.entity-page-size>>。

[[jmix.ui.default-view-id]]
=== jmix.ui.default-view-id

定义一个视图，用于在登录后的 xref:flow-ui:views/views.adoc#standard-main-view[主视图] 中打开。示例：

[source,properties]
----
jmix.ui.default-view-id = User.list
----

参阅 <<jmix.ui.main-view-id,jmix.ui.main-view-id>>。

[[jmix.ui.entity-max-fetch-size]]
=== jmix.ui.entity-max-fetch-size

对于某个特定实体，配置可以加载至 UI 层实例的默认最大数量。

以下示例展示如何为两个实体配置不同的最大读取数。对其他未配置该属性的实体，按照 <<jmix.ui.default-max-fetch-size,jmix.ui.default-max-fetch-size>> 加载。

[source,properties]
----
jmix.ui.entity-max-fetch-size.Product = 500
jmix.ui.entity-max-fetch-size.Customer = 1000
----

[[jmix.ui.entity-page-size]]
=== jmix.ui.entity-page-size

对于特定实体的 xref:flow-ui:vc/components/simplePagination.adoc[simplePagination] 组件，配置显示在每页中的默认数据条数。

以下示例展示如何为两个实体配置不同的分页数量。对其他未配置该属性的实体，按照 <<jmix.ui.default-page-size,jmix.ui.default-page-size>> 加载。

[source,properties]
----
jmix.ui.entity-page-size.Product = 100
jmix.ui.entity-page-size.Customer = 500
----

[[jmix.ui.exception-dialog-modal]]
=== jmix.ui.exception-dialog-modal

这个应用程序属性控制是否在 Jmix 应用程序中使用模态窗显示 xref:exception-handlers.adoc#customizing-default-handler[ExceptionDialog]。

如果启用，则 `ExceptionDialog` 作为模态窗显示，用户只有先关闭该窗口才能与应用程序的其他部分交互。

如果禁用，则 `ExceptionDialog` 不作为模态窗显示，用户可以与应用程序的其他部分交互而无需关闭该窗口。

默认值：`true`。

参阅 xref:flow-ui:exception-handlers.adoc[异常处理]。

[[jmix.ui.file-downloader-cache-max-age-sec]]
=== jmix.ui.file-downloader-cache-max-age-sec

设置下载文件被浏览器缓存视为新文件的最大时间（以秒为单位）。此属性有助于确保 Google Chrome 内置 PDF 查看器显示文件的最新版本。

该属性设置 Cache-Control HTTP 响应头中的 `max-age` 指令。详细信息请参考 https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Cache-Control#response_directives[MDN 文档^]。

默认值：`3600`。

另参考 xref:files:downloading-files.adoc#downloader[使用下载器]。

[[jmix.ui.main-view-id]]
=== jmix.ui.main-view-id

配置应用程序 xref:flow-ui:views/views.adoc#standard-main-view[主页面] 的视图 ID。

默认值：`main`。

参阅 <<jmix.ui.default-view-id,jmix.ui.default-view-id>>。

[[jmix.ui.menu-config]]
=== jmix.ui.menu-config

配置 `menu.xml` 文件的路径。该文件通过 `Resources` 接口加载，因此可以位于 classpath 或者配置目录中。

示例：

[source,properties]
----
jmix.ui.menu-config = com/company/onboarding/menu.xml
----

[[jmix.ui.login-view-id]]
=== jmix.ui.login-view-id

配置应用程序登录页面的视图 ID。

默认值：`login`。

[[jmix.ui.save-exported-byte-array-data-threshold-bytes]]
=== jmix.ui.save-exported-byte-array-data-threshold-bytes

配置一个下载缓存的阈值，单位为字节。在通过 `ByteArrayDownloadDataProvider` 下载时，字节数组会保存在临时文件中，避免 HTTP 会话的内存泄露。

默认值：`102400`

[[jmix.ui.use-session-fixation-protection]]
=== jmix.ui.use-session-fixation-protection

配置是否在登录后重新初始化用户会话，以确保应用程序不会受到会话固定攻击。

默认值：`true`

[[jmix.ui.view-file-extensions]]
=== jmix.ui.view-file-extensions

对于 `Downloader` bean，配置哪些文件后缀类型可以直接展示在浏览器而不下载。

默认值：`jpg, png, jpeg, pdf`

[[jmix.ui.view.close-shortcut]]
=== jmix.ui.view.close-shortcut

定义关闭当前视图使用的 xref:keyboard-shortcuts.adoc[键盘快捷键]。

[[jmix.ui.view.save-shortcut]]
=== jmix.ui.view.save-shortcut

定义保存数据更改的 xref:keyboard-shortcuts.adoc[键盘快捷键]。

[[jmix.ui.view.create-action-adds-first]]
=== jmix.ui.view.create-action-adds-first

配置通过对话框创建的实体是否添加到列表的开头。

默认值：`true`

[[jmix.ui.view.reload-unfetched-attributes-from-lookup-views]]
=== jmix.ui.view.reload-unfetched-attributes-from-lookup-views

当从查找视图选择某个实体后，如果该实体不包含所需的全部实体属性，通过该配置指定 `LookupBuilder` 是否需要重新加载该实体。

默认值：`true`

[[jmix.ui.view.use-save-confirmation]]
=== jmix.ui.view.use-save-confirmation

当关闭对话框时，如果 `DataContext` 包含未保存的改动，通过该配置定义对话框显示的选项。根据该选项的配置，实体详情视图会调用 `ViewValidation` bean 的 xref:views/view-validation.adoc#showSaveConfirmationDialog[showSaveConfirmationDialog()] 或 xref:views/view-validation.adoc#showUnsavedChangesDialog[showUnsavedChangesDialog()] 方法。

如果设置为 `true`，对话框包含三个选项：*Save（保存）*、*Don’t save（不保存）*、*Cancel（取消）*。

如果设置为 `false`，对话框包含仅包含两个选项：*Yes（是）* 不保存数据并关闭窗口，以及 *No（否）*，可以继续编辑。

默认值：`true`。

[[jmix.ui.view.prevent-browser-tab-closing]]
=== jmix.ui.view.prevent-browser-tab-closing

当用户尝试关闭一个浏览器标签页时，设置是否显示一个确认窗口，需要对应的视图通过 xref:views/views.adoc#prevent-browser-tab-closing[setPreventBrowserTabClosing] 设置 `true`。

默认值：`false`。

[[jmix.ui.view.validation-notification-duration]]
=== jmix.ui.view.validation-notification-duration

定义视图中数据验证错误通知的显示时间，单位为毫秒。

默认值：`3000`

[[jmix.ui.view.validation-notification-position]]
=== jmix.ui.view.validation-notification-position

设置数据验证通知在页面中的位置。支持：`TOP_STRETCH`、`TOP_START`、`TOP_CENTER`、`TOP_END`、`MIDDLE`、`BOTTOM_START`、`BOTTOM_CENTER`、`BOTTOM_END`、`BOTTOM_STRETCH`。

默认值：`BOTTOM_END`

[[jmix.ui.view.validation-notification-type]]
=== jmix.ui.view.validation-notification-type

配置视图中标准的数据验证错误通知的类型。支持 `Notifications.Type` 的枚举值：`DEFAULT`、`ERROR`、`SUCCESS`、`SYSTEM`、`WARNING`。

默认值：`DEFAULT`

[[jmix.ui.navigation.use-crockford-uuid-encoder]]
=== jmix.ui.navigation.use-crockford-uuid-encoder

指定是否使用 https://www.crockford.com/base32.html[Base32 Crockford Encoding^]  对 UUID URL 参数进行加解密。

默认值：`false`

[[jmix.ui.ui-test-mode]]
=== jmix.ui.ui-test-mode

启用在 Masquerade 测试库中生成特殊测试 ID 的功能。具体请参阅 xref:testing:masquerade.adoc[Masquerade]。

[[components]]
== 组件配置

[[jmix.ui.component.checkbox-required-state-initialization-enabled]]
=== jmix.ui.component.checkbox-required-state-initialization-enabled

该属性控制当 xref:vc/components/checkbox.adoc[checkbox] 和 xref:vc/components/switch.adoc[switch] 绑定一个带 `@NotNull` 验证的必需布尔属性时的行为。

* 如果配置为 `true`，则 `checkbox`/`switch` 必需勾选以通过验证。

* 如果配置为 `false`，则 `checkbox`/`switch` 可以保留非选择状态而不会导致验证错误。这样可以表示所需的 `true` 或 `false` 值。

默认值：`true`

[[jmix.ui.component.default-notification-duration]]
=== jmix.ui.component.default-notification-duration

定义通知的显示时间，单位为毫秒。

默认值：`3000`

[[jmix.ui.component.default-notification-position]]
=== jmix.ui.component.default-notification-position

设置默认通知在页面中的位置。支持：`TOP_STRETCH`、`TOP_START`、`TOP_CENTER`、`TOP_END`、`MIDDLE`、`BOTTOM_START`、`BOTTOM_CENTER`、`BOTTOM_END`、`BOTTOM_STRETCH`。

默认值：`MIDDLE`

[[jmix.ui.component.default-trim-enabled]]
=== jmix.ui.component.default-trim-enabled

设置 `textField` 和 `textArea` 组件 xref:vc/components/textField.adoc#trimEnabled[trimEnabled] 属性的默认值。

默认值：`true`

[[jmix.ui.component.entity-field-actions]]
=== jmix.ui.component.entity-field-actions

定义特定实体选择组件中需要添加的操作，该组件用在 xref:vc/components/genericFilter.adoc[genericFilter] 的参数中，或可编辑的 xref:vc/components/dataGrid.adoc[dataGrid] 单元格中。

例如，如果需要在选择 `User` 实体的组件中使用 `entity_lookup`、`entity_open` 和 `entity_clear` 操作，可以按如下设置：

[source,properties]
----
jmix.ui.component.entity-field-actions.User = entity_lookup, entity_open, entity_clear
----

[[jmix.ui.component.entity-field-fqn]]
=== jmix.ui.component.entity-field-fqn

定义选择特定实体时使用的选择组件，该组件用在 xref:vc/components/genericFilter.adoc[genericFilter] 的参数中，或可编辑的 xref:vc/components/dataGrid.adoc[dataGrid] 单元格中。

属性值需要设置为类的全限定名称（FQN）。例如，如果需要为 `User` 实体使用 xref:vc/components/entityComboBox.adoc[entityComboBox] 组件，可以按如下设置：

[source,properties]
----
jmix.ui.component.entity-field-fqn.User = io.jmix.flowui.component.combobox.EntityComboBox
----

默认情况下，通用机制使用 xref:vc/components/entityPicker.adoc[entityPicker] 组件。

其全限定名称为 `io.jmix.flowui.component.valuepicker.EntityPicker`。

[[jmix.ui.component.filter-apply-shortcut]]
=== jmix.ui.component.filter-apply-shortcut

设置 xref:vc/components/genericFilter.adoc[genericFilter] 组件应用当前过滤条件的 xref:keyboard-shortcuts.adoc[快捷键]，可用在过滤器不是 <<jmix.ui.component.filter-auto-apply, 自动应用>> 时。

例如，可以禁用所有过滤器的自动应用而改用快捷键：

[source,properties]
----
jmix.ui.component.filter-auto-apply = false
jmix.ui.component.filter-apply-shortcut = ALT-ENTER
----

该全局配置可以通过特定 xref:vc/components/genericFilter.adoc[] 组件的 `applyShortcut` XML 属性覆盖。

[[jmix.ui.component.filter-auto-apply]]
=== jmix.ui.component.filter-auto-apply

当设置为 `true` 时，xref:vc/components/genericFilter.adoc[] 组件以“实时”模式工作，所有一旦过滤器参数有改动都会自动重新加载数据。

当设置为 `false` 时，需要点击 *Refresh（刷新）* 按钮才会重新加载数据。

该配置可以在 xref:vc/components/genericFilter.adoc[] 组件实例的级别通过配置实例的 `autoApply` XML 属性进行覆盖。

默认值：`true`

[[jmix.ui.component.filter-configuration-unique-names-enabled]]
=== jmix.ui.component.filter-configuration-unique-names-enabled

当设置为 `true` 时，会强制要求运行时的过滤器配置名称唯一。同时，支持 xref:vc/components/genericFilter.adoc#run-time-configuration[运行时配置] 和 xref:vc/components/genericFilter.adoc#design-time-configuration[设计时配置] 具有相同的名称而不会出现冲突。

注意，设计时的配置会带有一个 `*` 号标记，以便于运行时配置做区分。

默认值：`true`

[[jmix.ui.component.filter-properties-hierarchy-depth]]
=== jmix.ui.component.filter-properties-hierarchy-depth

定义 xref:vc/components/genericFilter.adoc[] 组件中添加条件时显示的实体属性层级深度。例如，如果该值设置为 2，那么可以选择 `contractor.city.country`，如果设置为 3，可以选择 `contractor.city.country.name`。

该属性可以在特定 xref:vc/components/genericFilter.adoc[] 组件级别通过组件的 `propertyHierarchyDepth` XML 属性进行覆盖。

默认值：`2`

[[jmix.ui.component.filter-show-configuration-id-field]]
=== jmix.ui.component.filter-show-configuration-id-field

配置是否在 xref:vc/components/genericFilter.adoc[过滤器] 的配置详情对话框中显示配置id字段。

默认值：`false`


[[jmix.ui.component.grid-add-shortcut]]
=== jmix.ui.component.grid-add-shortcut

定义执行 xref:actions/list-actions.adoc#list_add[list_add] 操作的 xref:keyboard-shortcuts.adoc[键盘快捷键]。

[[jmix.ui.component.grid-create-shortcut]]
=== jmix.ui.component.grid-create-shortcut

定义执行 xref:actions/list-actions.adoc#list_create[list_create] 操作的 xref:keyboard-shortcuts.adoc[键盘快捷键]。

[[jmix.ui.component.grid-edit-shortcut]]
=== jmix.ui.component.grid-edit-shortcut

定义执行 xref:actions/list-actions.adoc#list_edit[list_edit] 操作的 xref:keyboard-shortcuts.adoc[键盘快捷键]。

默认值：`ENTER`

[[jmix.ui.component.grid-read-shortcut]]
=== jmix.ui.component.grid-read-shortcut

定义执行 xref:actions/list-actions.adoc#list_read[list_read] 操作的 xref:keyboard-shortcuts.adoc[键盘快捷键]。

默认值：`ENTER`

[[jmix.ui.component.grid-remove-shortcut]]
=== jmix.ui.component.grid-remove-shortcut

定义执行 xref:actions/list-actions.adoc#list_remove[list_remove] 操作的 xref:keyboard-shortcuts.adoc[键盘快捷键]。

[[jmix.ui.component.immediate-required-validation-enabled]]
=== jmix.ui.component.immediate-required-validation-enabled

默认情况下，必填字段在视图打开时就高亮显示，不会等待用户输入。

如果该属性设置为 false，对必填字段的验证仅在视图保存时进行。

默认值：`true`

[[jmix.ui.component.pagination-items-per-page-items]]
=== jmix.ui.component.pagination-items-per-page-items

配置 xref:flow-ui:vc/components/simplePagination.adoc[simplePagination] 组件中展示的“每页显示行数”选项。

如需为某个 simplePagination 的具体实例配置自定义的选项列表，请使用 xref:flow-ui:vc/components/simplePagination.adoc#itemsPerPageItems[itemsPerPageItems] XML 属性。

默认值：`[20, 50, 100, 500, 1000, 5000]`

[[jmix.ui.component.picker-clear-shortcut]]
=== jmix.ui.component.picker-clear-shortcut

定义清空选择器组件输入内容的 xref:keyboard-shortcuts.adoc[键盘快捷键]。

[[jmix.ui.component.picker-lookup-shortcut]]
=== jmix.ui.component.picker-lookup-shortcut

定义选择器组件中打开选择视图的 xref:keyboard-shortcuts.adoc[键盘快捷键]。

[[jmix.ui.component.picker-open-shortcut]]
=== jmix.ui.component.picker-open-shortcut

定义选择器组件中打开已选实体详情视图的 xref:keyboard-shortcuts.adoc[键盘快捷键]。

[[jmix.ui.component.show-error-message-below-field]]
=== jmix.ui.component.show-error-message-below-field

控制是否直接在字段下方显示错误消息。默认值为 `true`，即错误消息在对应的组件下方显示。将此属性设置为 `false` 会隐藏这些内联消息；相反，当用户单击 *OK*（或类似的提交按钮）时，会显示包含所有错误的摘要通知。

默认值：`true`。

[[asynchronous-tasks]]
== 异步任务

[[jmix.ui.async-task.default-timeout-sec]]
=== jmix.ui.async-task.default-timeout-sec

xref:flow-ui:async-tasks.adoc[异步任务] 的默认超时时限，单位为秒。

默认值：300。

[[jmix.ui.async-task.executor-service.maximum-pool-size]]
=== jmix.ui.async-task.executor-service.maximum-pool-size

xref:async-tasks.adoc[异步任务] 中 executor service 线程池的大小。

默认值：10。


[[background-tasks]]
== 后台任务

[[jmix.ui.background-task.task-killing-latency]]
=== jmix.ui.background-task.task-killing-latency

定义 xref:background-tasks.adoc[后台任务] 不更新状态时的超时时限。如果达到任务本身的超时时限加上该参数配置的时限，则尝试终止任务。如果没有指定时间后缀（`ns`、`us`、`ms`、`s`、`m`、`h` 和 `d`），默认单位为 **秒**。

默认值：`60`

[[jmix.ui.background-task.threads-count]]
=== jmix.ui.background-task.threads-count

配置执行 xref:background-tasks.adoc[后台任务] 的线程数。

默认值：`10`

[[jmix.ui.background-task.timeout-expiration-check-interval]]
=== jmix.ui.background-task.timeout-expiration-check-interval

配置检查 xref:background-tasks.adoc[后台任务] 是否超时的间隔。如果没有指定时间后缀（`ns`、`us`、`ms`、`s`、`m`、`h` 和 `d`），默认单位为 **毫秒**。

默认值：`5000`
