= Свойства UI
:page-aliases: app-properties.adoc

[[common]]
== Общие

[[jmix.ui.composite-menu]]
=== jmix.ui.composite-menu

Определяет, строится ли меню с элементами меню из установленных xref:jmix:ROOT:add-ons.adoc[дополнений].

При установке в `true` в меню будут включены как элементы из `menu.xml` приложения, так и элементы из `menu.xml` каждого установленного дополнения, содержащего такой файл.

При установке в `false` в меню будут включены только те элементы, которые добавлены в `menu.xml` приложения.

Используйте xref:studio:menu-designer.adoc[] Studio для управления структурой меню в обоих режимах.

Значение по умолчанию: `true`.

[[jmix.ui.default-max-fetch-size]]
=== jmix.ui.default-max-fetch-size

Определяет для всех сущностей максимальное количество экземпляров, которые могут быть загружены на уровень UI.

Значение по умолчанию: `10000`

См. также <<jmix.ui.entity-max-fetch-size,jmix.ui.entity-max-fetch-size>>.

[[jmix.ui.default-page-size]]
=== jmix.ui.default-page-size

Определяет для всех сущностей количество элементов на странице по умолчанию для компонента xref:flow-ui:vc/components/simplePagination.adoc[simplePagination].

Значение по умолчанию: `50`

См. также <<jmix.ui.entity-page-size,jmix.ui.entity-page-size>>.

[[jmix.ui.default-view-id]]
=== jmix.ui.default-view-id

Задает экран, который будет открыт после входа в систему внутри xref:flow-ui:views/views.adoc#standard-main-view[главного экрана]. Например:

[source,properties]
----
jmix.ui.default-view-id = User.list
----

См. также <<jmix.ui.main-view-id,jmix.ui.main-view-id>>.

[[jmix.ui.entity-max-fetch-size]]
=== jmix.ui.entity-max-fetch-size

Определяет для конкретной сущности максимальное количество экземпляров, которые могут быть загружены на уровень UI.

В следующем примере настраивается максимальный размер выборки для двух сущностей. Для всех остальных сущностей используется значение из <<jmix.ui.default-max-fetch-size,jmix.ui.default-max-fetch-size>>.

[source,properties]
----
jmix.ui.entity-max-fetch-size.Product = 500
jmix.ui.entity-max-fetch-size.Customer = 1000
----

[[jmix.ui.entity-page-size]]
=== jmix.ui.entity-page-size

Определяет для конкретной сущности размер страницы по умолчанию для компонента xref:flow-ui:vc/components/simplePagination.adoc[simplePagination].

В следующем примере настраивается размер страницы для двух сущностей. Для всех остальных сущностей используется значение по умолчанию из <<jmix.ui.default-page-size,jmix.ui.default-page-size>>.

[source,properties]
----
jmix.ui.entity-page-size.Product = 100
jmix.ui.entity-page-size.Customer = 500
----

[[jmix.ui.exception-dialog-modal]]
=== jmix.ui.exception-dialog-modal

Это свойство приложения определяет, должен ли xref:exception-handlers.adoc#customizing-default-handler[ExceptionDialog] отображаться как модальное окно в Jmix-приложениях.

Если свойство включено, `ExceptionDialog` будет вести себя как модальное окно, блокируя взаимодействие с другими частями приложения, пока диалог не будет закрыт.

Если свойство выключено, `ExceptionDialog` будет вести себя как немодальное окно, позволяя пользователям продолжать взаимодействовать с другими частями приложения, пока диалог открыт.

Значение по умолчанию: `true`.

Смотрите также xref:flow-ui:exception-handlers.adoc[Обработчики исключений].

[[jmix.ui.file-downloader-cache-max-age-sec]]
=== jmix.ui.file-downloader-cache-max-age-sec

Устанавливает максимальное время (в секундах), в течение которого загруженный файл считается актуальным для кэша браузера. Это свойство особенно полезно для обеспечения отображения самой последней версии файла во встроенном средстве просмотра PDF в Google Chrome.

Свойство устанавливает директиву `max-age` в HTTP-заголовке ответа Cache-Control. Подробности смотрите в https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Cache-Control#response_directives[документации MDN^].

Значение по умолчанию: `3600`.

Смотрите также xref:files:downloading-files.adoc#downloader[Использование Downloader].

[[jmix.ui.main-view-id]]
=== jmix.ui.main-view-id

Идентификатор экрана, который будет использоваться в качестве xref:flow-ui:views/views.adoc#standard-main-view[главной страницы] приложения.

Значение по умолчанию: `main`.

См. также <<jmix.ui.default-view-id,jmix.ui.default-view-id>>.

[[jmix.ui.menu-config]]
=== jmix.ui.menu-config

Определяет путь к файлу `menu.xml`. Файл загружается с использованием интерфейса `Resources`, поэтому он может находиться в classpath или в xref:ROOT:app-properties.adoc#jmix.core.conf-dir[каталоге конфигурации].

Например:

[source,properties]
----
jmix.ui.menu-config = com/company/onboarding/menu.xml
----

[[jmix.ui.login-view-id]]
=== jmix.ui.login-view-id

Идентификатор экрана, который будет использоваться в качестве страницы входа в приложение.

Значение по умолчанию: `login`.

[[jmix.ui.save-exported-byte-array-data-threshold-bytes]]
=== jmix.ui.save-exported-byte-array-data-threshold-bytes

Определяет порог, в байтах, на котором байтовые массивы, загруженные через `ByteArrayDownloadDataProvider`, будут сохранены во временные файлы для предотвращения утечек памяти HTTP-сессии.

Значение по умолчанию: `102400`

[[jmix.iu.use-session-fixation-protection]]
=== jmix.ui.use-session-fixation-protection

Определяет, будет ли сессия переинициализирована после входа, чтобы защититься от атак фиксации сессии.

Значение по умолчанию: `true`

[[jmix.ui.view-file-extensions]]
=== jmix.ui.view-file-extensions

Для бина `Downloader` определяет список расширений файлов, которые будут отображаться во вкладке веб-браузера вместо автоматической загрузки.

Значение по умолчанию: `jpg, png, jpeg, pdf`

[[jmix.ui.view.close-shortcut]]
=== jmix.ui.view.close-shortcut

Определяет xref:keyboard-shortcuts.adoc[клавишу быстрого доступа], которая используется для закрытия текущего экрана.

[[jmix.ui.view.save-shortcut]]
=== jmix.ui.view.save-shortcut

Определяет xref:keyboard-shortcuts.adoc[клавишу быстрого доступа], которая используется для сохранения изменений.

[[jmix.ui.view.create-action-adds-first]]
=== jmix.ui.view.create-action-adds-first

Определяет, будет ли созданная в диалоговом окне сущность добавлена в начало списка, а не в конец.

Значение по умолчанию: `true`

[[jmix.ui.view.reload-unfetched-attributes-from-lookup-views]]
=== jmix.ui.view.reload-unfetched-attributes-from-lookup-views

Определяет, будет ли `LookupBuilder` перезагружать сущность после выбора ее из окна поиска, если выбранная сущность не содержит все необходимые атрибуты сущности.

Значение по умолчанию: `true`

[[jmix.ui.view.use-save-confirmation]]
=== jmix.ui.view.use-save-confirmation

Определяет, какие варианты отображаются в диалоговом окне при закрытии экрана с несохраненными изменениями в `DataContext`. В зависимости от этого свойства, экран деталей сущности вызывает либо метод xref:views/view-validation.adoc#showSaveConfirmationDialog[showSaveConfirmationDialog()], либо xref:views/view-validation.adoc#showUnsavedChangesDialog[showUnsavedChangesDialog()] бина `ViewValidation`.

Если установлено значение `true`, диалоговое окно содержит три варианта: *Save*, *Don’t save*, *Cancel*.

Если установлено значение `false`, диалоговое окно содержит только два варианта: *Yes* - закрыть без сохранения и *No* - остаться и продолжить редактирование.

Значение по умолчанию: `true`.

[[jmix.ui.view.prevent-browser-tab-closing]]
=== jmix.ui.view.prevent-browser-tab-closing

Specifies whether a confirmation dialog is shown if a user attempts to close a browser tab, and the corresponding property of the view is also set to `true` using the xref:views/views.adoc#prevent-browser-tab-closing[setPreventBrowserTabClosing] method.

Default value: `false`.

[[jmix.ui.view.validation-notification-duration]]
=== jmix.ui.view.validation-notification-duration

Определяет продолжительность (в миллисекундах) отображения уведомлений об ошибках валидации экрана.

Значение по умолчанию: `3000`

[[jmix.ui.view.validation-notification-position]]
=== jmix.ui.view.validation-notification-position

Устанавливает позицию уведомлений о валидации на странице. Возможные значения: `TOP_STRETCH`, `TOP_START`, `TOP_CENTER`, `TOP_END`, `MIDDLE`, `BOTTOM_START`, `BOTTOM_CENTER`, `BOTTOM_END`, `BOTTOM_STRETCH`.

Значение по умолчанию: `BOTTOM_END`

[[jmix.ui.view.validation-notification-type]]
=== jmix.ui.view.validation-notification-type

Определяет вариант стандартных уведомлений об ошибках валидации экрана. Принимает одно из значений перечисления `Notifications.Type`: `DEFAULT`, `ERROR`, `SUCCESS`, `SYSTEM`, `WARNING`.

Значение по умолчанию: `DEFAULT`

[[jmix.ui.navigation.use-crockford-uuid-encoder]]
=== jmix.ui.navigation.use-crockford-uuid-encoder

Определяет, используется ли https://www.crockford.com/base32.html[Base32 Crockford Encoding^] для кодирования/декодирования UUID-параметров URL.

Значение по умолчанию: `false`

[[jmix.ui.ui-test-mode]]
=== jmix.ui.ui-test-mode

Включает генерацию специальных тестовых идентификаторов для использования с библиотекой тестирования Masquerade. Чтобы узнать больше, посетите раздел xref:testing:masquerade.adoc[].

[[components]]
== Компоненты

[[jmix.ui.component.checkbox-required-state-initialization-enabled]]
=== jmix.ui.component.checkbox-required-state-initialization-enabled

Это свойство управляет поведением компонентов xref:vc/components/checkbox.adoc[checkbox] и xref:vc/components/switch.adoc[switch], связанных с обязательным булевым атрибутом с валидацией `@NotNull`.

* Если выбрано `true`, то `checkbox`/`switch` должен быть отмечен, чтобы пройти валидацию.

* Если выбрано `false`, `checkbox`/`switch` может быть неотмеченным без возникновения ошибок валидации. Это позволяет ему представлять значения `true` или `false` по необходимости.

Значение по умолчанию: `true`

[[jmix.ui.component.default-notification-duration]]
=== jmix.ui.component.default-notification-duration

Определяет продолжительность отображения уведомления, в миллисекундах.

Значение по умолчанию: `3000`

[[jmix.ui.component.default-notification-position]]
=== jmix.ui.component.default-notification-position

Определяет позицию уведомления по умолчанию на странице. Возможные значения: `TOP_STRETCH`, `TOP_START`, `TOP_CENTER`, `TOP_END`, `MIDDLE`, `BOTTOM_START`, `BOTTOM_CENTER`, `BOTTOM_END`, `BOTTOM_STRETCH`.

Значение по умолчанию: `MIDDLE`

[[jmix.ui.component.default-trim-enabled]]
=== jmix.ui.component.default-trim-enabled

Указывает значение по умолчанию для атрибута xref:vc/components/textField.adoc#trimEnabled[trimEnabled] компонентов `textField` и `textArea`.

Значение по умолчанию: `true`

[[jmix.ui.component.entity-field-actions]]
=== jmix.ui.component.entity-field-actions

Определяет действия, которые необходимо добавить в компонент выбора для указанной сущности в механизмах стратегии генерации, таких как параметры xref:vc/components/genericFilter.adoc[genericFilter] или редактируемые ячейки xref:vc/components/dataGrid.adoc[dataGrid].

Например, чтобы использовать действия `entity_lookup`, `entity_open` и `entity_clear` в компонентах, выбирающих сущность `User`, задайте свойство следующим образом:

[source,properties]
----
jmix.ui.component.entity-field-actions.User = entity_lookup, entity_open, entity_clear
----

[[jmix.ui.component.entity-field-fqn]]
=== jmix.ui.component.entity-field-fqn

Определяет компонент, используемый для выбора указанной сущности в механизмах стратегии генерации, таких как параметры xref:vc/components/genericFilter.adoc[genericFilter] или редактируемые ячейки xref:vc/components/dataGrid.adoc[dataGrid].

Укажите полное имя класса (FQN) в качестве значения свойства. Например, чтобы использовать xref:vc/components/entityComboBox.adoc[entityComboBox] для выбора сущности `User`, задайте свойство следующим образом:

[source,properties]
----
jmix.ui.component.entity-field-fqn.User = io.jmix.flowui.component.combobox.EntityComboBox
----

По умолчанию, общие механизмы используют компонент xref:vc/components/entityPicker.adoc[entityPicker].

Полное имя класса (FQN) для `entityPicker` - `io.jmix.flowui.component.valuepicker.EntityPicker`.

[[jmix.ui.component.filter-apply-shortcut]]
=== jmix.ui.component.filter-apply-shortcut

Определяет xref:keyboard-shortcuts.adoc[клавишу быстрого доступа] для применения условий в компоненте xref:vc/components/genericFilter.adoc[genericFilter] в том случае если они не <<jmix.ui.component.filter-auto-apply, применяются автоматически>>.

Например, можно отключить автоматическое применение условий в фильтрах и указать сочетание клавиш для применения их вручную:

[source,properties]
----
jmix.ui.component.filter-auto-apply = false
jmix.ui.component.filter-apply-shortcut = ALT-ENTER
----

Это свойство может быть переопределено для конкретного компонента xref:vc/components/genericFilter.adoc[] с использованием его XML-атрибута `applyShortcut`.

[[jmix.ui.component.filter-auto-apply]]
=== jmix.ui.component.filter-auto-apply

При установке в `true` настраивает компоненты xref:vc/components/genericFilter.adoc[] на работу в режиме немедленного выполнения, при котором каждое изменение параметров автоматически перезагружает данные.

При установке в `false` перезагрузка происходит только после нажатия кнопки *Refresh*.

Это свойство может быть переопределено для конкретного компонента xref:vc/components/genericFilter.adoc[] с использованием его XML-атрибута `autoApply`.

Значение по умолчанию: `true`

[[jmix.ui.component.filter-configuration-unique-names-enabled]]
=== jmix.ui.component.filter-configuration-unique-names-enabled

При установке в `true` проверяет уникальность имен для конфигураций фильтра созданных во время выполнения программы. В то же время позволяет задать одинаковые имена для xref:vc/components/genericFilter.adoc#run-time-configuration[конфигурации времени выполнения] и xref:vc/components/genericFilter.adoc#design-time-configuration[конфигурации созданной на этапе разработки].

Обратите внимание, что конфигурации, созданные во время разработки, помечены звездочкой (*) для отличия их от конфигураций времени выполнения.

Значение по умолчанию: `true`

[[jmix.ui.component.filter-properties-hierarchy-depth]]
=== jmix.ui.component.filter-properties-hierarchy-depth

Определяет глубину иерархии свойств в редакторе "Добавить условие" в xref:vc/components/genericFilter.adoc[]. Например, если глубина равна 2, то можно выбирать атрибут сущности `contractor.city.country`, если значение равно 3, то `contractor.city.country.name` и так далее.

Это свойство может быть переопределено для конкретного компонента xref:vc/components/genericFilter.adoc[] с использованием его XML-атрибута `propertyHierarchyDepth`.

Значение по умолчанию: `2`

[[jmix.ui.component.filter-show-configuration-id-field]]
=== jmix.ui.component.filter-show-configuration-id-field

Определяет, будет ли видно поле идентификатора конфигурации в диалоге сведений о конфигурации xref:vc/components/genericFilter.adoc[genericFilter].

Значение по умолчанию: `false`

[[jmix.ui.component.grid-add-shortcut]]
=== jmix.ui.component.grid-add-shortcut

Определяет xref:keyboard-shortcuts.adoc[клавишу быстрого доступа], которая используется для выполнения действия xref:actions/list-actions.adoc#list_add[list_add].

[[jmix.ui.component.grid-create-shortcut]]
=== jmix.ui.component.grid-create-shortcut

Определяет xref:keyboard-shortcuts.adoc[клавишу быстрого доступа], которая используется для выполнения действия xref:actions/list-actions.adoc#list_create[list_create].

[[jmix.ui.component.grid-edit-shortcut]]
=== jmix.ui.component.grid-edit-shortcut

Определяет xref:keyboard-shortcuts.adoc[клавишу быстрого доступа], которая используется для выполнения действия xref:actions/list-actions.adoc#list_edit[list_edit].

Значение по умолчанию: `ENTER`

[[jmix.ui.component.grid-read-shortcut]]
=== jmix.ui.component.grid-read-shortcut

Определяет xref:keyboard-shortcuts.adoc[клавишу быстрого доступа], которая используется для выполнения действия xref:actions/list-actions.adoc#list_read[list_read].

Значение по умолчанию: `ENTER`

[[jmix.ui.component.grid-remove-shortcut]]
=== jmix.ui.component.grid-remove-shortcut

Определяет xref:keyboard-shortcuts.adoc[клавишу быстрого доступа], которая используется для выполнения действия xref:actions/list-actions.adoc#list_remove[list_remove].

[[jmix.ui.component.immediate-required-validation-enabled]]
=== jmix.ui.component.immediate-required-validation-enabled

По умолчанию обязательное поле выделяется сразу после открытия экрана и до того, как пользователь введет какие-либо значения.

Если это свойство установлено в значение false, проверка обязательных полей выполняется только при сохранении экрана деталей.

Значение по умолчанию: `true`

[[jmix.ui.component.pagination-items-per-page-items]]
=== jmix.ui.component.pagination-items-per-page-items

Определяет варианты числа элементов на странице в компоненте xref:flow-ui:vc/components/simplePagination.adoc[simplePagination].

Для настройки пользовательского списка вариантов для конкретного экземпляра simplePagination используйте атрибут XML xref:flow-ui:vc/components/simplePagination.adoc#itemsPerPageItems[itemsPerPageItems].

Значение по умолчанию: `[20, 50, 100, 500, 1000, 5000]`

[[jmix.ui.component.picker-clear-shortcut]]
=== jmix.ui.component.picker-clear-shortcut

Определяет xref:keyboard-shortcuts.adoc[клавишу быстрого доступа], которая используется для очистки ввода компонента выбора.

[[jmix.ui.component.picker-lookup-shortcut]]
=== jmix.ui.component.picker-lookup-shortcut

Определяет xref:keyboard-shortcuts.adoc[клавишу быстрого доступа], которая используется для открытия экрана поиска для компонента выбора.

[[jmix.ui.component.picker-open-shortcut]]
=== jmix.ui.component.picker-open-shortcut

Определяет xref:keyboard-shortcuts.adoc[клавишу быстрого доступа], которая используется для открытия экрана деталей для выбранной сущности в компоненте выбора.

[[jmix.ui.component.show-error-message-below-field]]
=== jmix.ui.component.show-error-message-below-field

Управляет отображением сообщений об ошибках непосредственно под полями. Значение по умолчанию - `true`, то есть сообщения об ошибках отображаются под соответствующими полями. Установка этого свойства в `false` скрывает эти встроенные сообщения; вместо них появляется уведомление, содержащее все ошибки, когда пользователь нажимает кнопку *OK* (или аналогичную кнопку отправки).

Значение по умолчанию: `true`.

[[asynchronous-tasks]]
== Асинхронные задачи

[[jmix.ui.async-task.default-timeout-sec]]
=== jmix.ui.async-task.default-timeout-sec

Значение по умолчанию для таймаута xref:flow-ui:async-tasks.adoc[асинхронных задач] в секундах.

Значение по умолчанию: 300.

[[jmix.ui.async-task.executor-service.maximum-pool-size]]
=== jmix.ui.async-task.executor-service.maximum-pool-size

Максимальный размер пула потоков `ExecutorService`, используемого в xref:async-tasks.adoc[асинхронных задачах].

Значение по умолчанию: 10.

[[background-tasks]]
== Фоновые задачи

[[jmix.ui.background-task.task-killing-latency]]
=== jmix.ui.background-task.task-killing-latency

Определяет время ожидания после которого xref:background-tasks.adoc[фоновые задачи], которые не обновляют свой статус, завершаются (время выполнения задачи плюс время задержки). Если суффикс длительности (`ns`, `us`, `ms`, `s`, `m`, `h` и `d` для наносекунд, микросекунд, миллисекунд, секунд, минут, часов и дней соответственно) не указан, будут использоваться секунды.

Значение по умолчанию: `60`

[[jmix.ui.background-task.threads-count]]
=== jmix.ui.background-task.threads-count

Определяет количество потоков для исполнения xref:background-tasks.adoc[фоновых задач].

Значение по умолчанию: `10`

[[jmix.ui.background-task.timeout-expiration-check-interval]]
=== jmix.ui.background-task.timeout-expiration-check-interval

Определяет интервал проверки срока действия xref:background-tasks.adoc[фоновых задач]. Если суффикс длительности (`ns`, `us`, `ms`, `s`, `m`, `h` и `d` для наносекунд, микросекунд, миллисекунд, секунд, минут, часов и дней соответственно) не указан, будут использоваться миллисекунды.

Значение по умолчанию: `5000`