= View Annotations
:page-aliases: screens/annotations.adoc

Annotations on view classes provide information about the views to the framework. Some annotations are applicable to any type of view, some of them can be used only on entity list or detail views.

[[common-annotations]]
== Common Annotations

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/myonboarding/MyOnboardingView.java[tags=annotations]
----

* `@ViewController` annotation indicates that the class is a view. The value of the annotation is the view id which can be used to refer to the view from the xref:menu-config.adoc[main menu] or when opening the view programmatically.

* `@ViewDescriptor` annotation connects the view class to the XML descriptor. The value of the annotation specifies the path to the descriptor file. If the value contains a file name only, it is assumed that the file is located in the same package as the view class. Otherwise, the path should start with `/` and contain the full path to the descriptor from the source root, for example `/com/company/demo/view/some-entity-list-view.xml`.

* `@com.vaadin.flow.router.Route` defines a URL path for navigation to this view. As long as the view should be opened inside the main view, the `layout` attribute specifies the main view class.

* `@DialogMode` annotation defines parameters of the dialog window when the view is opened as a dialog.

* `@com.vaadin.flow.server.auth.AnonymousAllowed` makes the view available without authentication. By default, only the login view is available to the anonymous (not authenticated) session.
+
TIP: See the https://github.com/jmix-framework/jmix-samples-2/tree/main/user-registration[User Registration^] sample project for how the `@AnonymousAllowed` annotation is used in a view for self-registration of users.

[[list-view-annotations]]
== List View Annotations

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/department/DepartmentListView.java[tags=annotations]
----

[[lookup-component]]
* `@LookupComponent` annotation specifies an id of a UI component to be used for getting a value returned from the lookup.

* `@PrimaryLookupView` annotation indicates that this view is the default lookup view for the specified entity. The annotation has greater priority than the `\{entity_name}.lookup` / `\{entity_name}.list` xref:views/opening-views.adoc#view-inference-conventions[name convention].

[[detail-view-annotations]]
== Detail View Annotations

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/department/DepartmentDetailView.java[tags=annotations]
----

[[edited-entity-container]]
* `@EditedEntityContainer` annotation specifies a data container that contains the edited entity.

* `@PrimaryDetailView` annotation indicates that this view is the default detail view for the specified entity. The annotation has greater priority than the `\{entity_name}.detail` xref:views/opening-views.adoc#view-inference-conventions[name convention].