= 视图注解
:page-aliases: screens/annotations.adoc

视图类上的注解用来为框架提供视图的相关信息。有些注解可用于任何类型的视图，有些只能用于实体列表或详情视图。

[[common-annotations]]
== 通用注解

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/myonboarding/MyOnboardingView.java[tags=annotations]
----

* `@ViewController` 注解表示该类是一个视图类。注解的值是视图 id，在 xref:menu-config.adoc[主菜单] 或通过编程打开时，需要使用视图 id。

* `@ViewDescriptor` 注解将视图类与 XML 描述进行关联。注解的值指定 XML 文件的路径。如果值仅包含文件名，则表示该描述文件位于与视图类相同的包中。否则，文件路径需要以 `/` 开头，包含自代码根目录开始的全路径，例如 `/com/company/demo/view/some-entity-list-view.xml`。

* `@com.vaadin.flow.router.Route` 定义导航至该视图的 URL 路径。如果视图需要在主视图内打开，`layout` 属性需要指定为主视图类。

* `@DialogMode` 注解定义当视图以对话框形式打开时的对话框窗口参数。

* `@com.vaadin.flow.server.auth.AnonymousAllowed` 可以将视图设置为允许匿名访问。默认仅登录页支持匿名会话。
+
TIP: 参考 https://github.com/jmix-framework/jmix-samples-2/tree/main/user-registration[用户注册^] 示例项目，了解如何在视图中使用 `@AnonymousAllowed` 注解以支持用户自注册。

[[list-view-annotations]]
== 列表视图注解

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/department/DepartmentListView.java[tags=annotations]
----

[[lookup-component]]
* `@LookupComponent` 注解指定一个 UI 组件的 id，从指定的该组件中获取每次查找的值。

* `@PrimaryLookupView` 注解表示该视图是用于查找指定实体的默认查找视图。该注解的优先级高于 `\{entity_name}.lookup` / `\{entity_name}.list` 这样的 xref:views/opening-views.adoc#view-inference-conventions[命名规范]。

[[detail-view-annotations]]
== 详情视图注解

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/department/DepartmentDetailView.java[tags=annotations]
----

[[edited-entity-container]]
* `@EditedEntityContainer` 注解指定包含编辑实体的数据容器。

* `@PrimaryDetailView` 注解表示该视图是用于指定实体的默认详情视图。该注解的优先级高于 `\{entity_name}.detail` 这样的 xref:views/opening-views.adoc#view-inference-conventions[命名规范]。
