= 视图验证
:page-aliases: screens/validation.adoc

[[validation-steps]]
== 验证步骤

在详情视图执行 `closeWithSave()` 和 `save()` xref:views/view-methods.adoc#methods-of-standard-detail[方法] 保存数据之前，会按以下顺序验证数据：

. 视图调用 <<validateUiComponents,下文所述>> `ViewValidation` bean 的 `validateUiComponents()` 方法。

. 如果第一步没有错误，视图会发送 xref:views/view-events.adoc#validation-event[ValidationEvent] 事件，可以在视图控制器中处理该事件以进行额外的验证。

[[view-validation-bean]]
== ViewValidation Bean

`ViewValidation` bean 包含验证 UI 组件、显示验证错误和未保存数据对话框的方法。由框架和扩展组件的视图和对话框使用。开发者也可以在应用程序视图中使用。

下面我们介绍 `ViewValidation` bean 中的一些主要方法。

[[validateUiComponents]]
=== validateUiComponents

`validateUiComponents()` 方法可以使用页面组件集合或组件容器作为参数。该方法会对所有实现了 `SupportsValidation` 接口的组件进行验证，并返回 `ValidationErrors` 对象，其中包含验证错误信息。

详情视图在调用 `closeWithSave()` 和 `save()` 时会调用该方法。

也可以在响应用户操作时调用，示例：

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/validation/SampleView.java[tags=validateUiComponents]
----

[[showValidationErrors]]
=== showValidationErrors

`showValidationErrors()` 方法可以展示一个带有验证错误消息的通知。参考上面的示例。

通知的标题是通过 `validationFail.title` 键值定义的。可以在项目的消息包中通过这个键值定义自己需要的标题。示例：

.messages_en.properties
[source,properties]
----
validationFail.title = Validation failed
----

[[showSaveConfirmationDialog]]
=== showSaveConfirmationDialog

`showSaveConfirmationDialog()` 方法展示是否保存页面改动的一个确认对话框。在 xref:ui-properties.adoc#jmix.ui.view.use-save-confirmation[jmix.ui.view.use-save-confirmation] 配置为 `true` 时（默认配置），xref:views/views.adoc#standard-detail-view[实体详情视图] 会在检测到用户关闭页面而未保存数据时使用该方法。

该对话框使用下列消息键值：

* `dialogs.closeUnsaved.title` - 对话框标题
* `dialogs.saveUnsaved.message` - 消息内容
* `dialogs.closeUnsaved.save` - "save" 按钮的文本
* `dialogs.closeUnsaved.discard` - "discard" 按钮的文本

可以在项目的消息包中通过这些键值定义自己需要的内容。示例：

.messages_zh_CN.properties
[source,properties]
----
dialogs.closeUnsaved.title = 您有改动还没有保存
dialogs.saveUnsaved.message = 需要保存吗？
dialogs.closeUnsaved.save = 保存
dialogs.closeUnsaved.discard = 不需要
----

[[showUnsavedChangesDialog]]
=== showUnsavedChangesDialog

`showSaveConfirmationDialog()` 方法展示是否放弃页面改动的一个确认对话框。在 xref:ui-properties.adoc#jmix.ui.view.use-save-confirmation[jmix.ui.view.use-save-confirmation] 配置为 `false` 时，xref:views/views.adoc#standard-detail-view[实体详情视图] 会在检测到用户关闭页面而未保存数据时使用该方法。

该对话框使用下列消息键值：

* `dialogs.closeUnsaved.title` - 对话框标题
* `dialogs.closeUnsaved.message` - 消息内容

可以在项目的消息包中通过这些键值定义自己需要的内容。示例：

.messages_zh_CN.properties
[source,properties]
----
dialogs.closeUnsaved.title = 您有改动还没有保存
dialogs.closeUnsaved.message = 确认丢弃数据？
----
