= PivotTable Onboarding

The PivotTable can be very useful for analyzing data. Let's see an example of how we can use the component for this purpose. Suppose we want to analyze a tips dataset and determine whether spending in a restaurant differs between smokers and non-smokers.

== Create TipInfo entity
Based on the data in the CSV file, create an entity.

[source,java,indent=0]
----
include::../examples/pivottable-onboarding/src/main/java/com/company/pivottableonboarding/entity/TipInfo.java[tags=onboarding-tip-info]
----

== Export data

Next, load the tips dataset into the application in any way. For example, you can add a `liquibase` changelog that loads data from `tips.csv`.
[source,xml,indent=0]
----
include::../examples/pivottable-onboarding/src/main/resources/com/company/pivottableonboarding/liquibase/changelog/2024/10/21-02-init-tip-info-data.xml[tags=onboarding-tip-info-data-changelog]
----

== Create UI
Create a blank view.
Specify the data container.
[source,xml,indent=0]
----
include::../examples/pivottable-onboarding/src/main/resources/com/company/pivottableonboarding/view/tipsanalyse/tips-analyse-view.xml[tags=onboarding-tip-info-dc]
----

Add the PivotTable add-on through Marketplace or manually.


Press Add Component and select PivotTable.
Add `dataContainer` and configure properties.
[source,xml,indent=0]
----
include::../examples/pivottable-onboarding/src/main/resources/com/company/pivottableonboarding/view/tipsanalyse/tips-analyse-view.xml[tags=onboarding-pivot-table]
----

== Analyse
Now you can run the application and analyze the data.
We do not set any predefined rows, columns, aggregations, or renderers.
So, the component shows all unused properties.

Move `Smoker` to the rows section and `Day` to the columns section.
Click `Day` and choose `Saturday` and `Sunday`.
Select `Average` aggregation. Then select `Tips` and then `Total bill` in `Aggregation Property`. You can see that `smokers` leave about the same tips as `non-smokers` (`3.08` vs `3.14`), but spend about 10% more on average (`22.16` vs `20.13`).



