= Using ShowPivotTableAction

`ShowPivotTableAction` is a special action that allows you to export data from components that extend `ListDataComponent`, such as xref:flow-ui:vc/components/dataGrid.adoc[DataGrid] and xref:flow-ui:vc/components/treeDataGrid.adoc[TreeDataGrid], to a Pivot Table.

The simplest way to use this action is to define it within your `dataGrid` and then associate it with a button.

[source,xml,indent=0]
----
include::../examples/pivottable-ex1/src/main/resources/com/company/ex1/view/pivottableshowaction/pivottable-show-action-view.xml[tags=data-grid-action,button-action]
----

You can also create the action programmatically within your view controller and use it with a button.

[source,java,indent=0]
----
include::../examples/pivottable-ex1/src/main/java/com/company/ex1/view/pivottableshowaction/PivottableShowActionView.java[tags=manual-set-action]
----

`ShowPivotTableAction` has two modes for exporting data:

* *All rows*: Exports all rows in the `DataGrid` or `TreeDataGrid`.
* *Selected rows*: Exports only the selected rows in the `DataGrid` or `TreeDataGrid`.

If no rows are selected, all rows will be exported by default without confirmation.

A pivot table in xref:pivottable-component.adoc#ui-mode[UI Mode] will be displayed in a new tab. By default, all attributes included in the component's data container view will be shown, except for:

* Attributes of type `Collection`.
* Attributes of type `byte[]` (byte array).
* `UUID` attributes.
* Attributes annotated with xref:data-model:entities.adoc#system-level[@SystemLevel].

To exclude certain attributes or include only a specific subset, use the `PivotTableViewBuilder` Spring bean. This bean provides a fluent API for configuring the pivot table component in the opened view.

To implement custom configuration, handle the `ActionPerformedEvent`.

[source,java,indent=0]
----
include::../examples/pivottable-ex1/src/main/java/com/company/ex1/view/pivottableshowaction/PivottableShowActionView.java[tags=custom-action]
----
<1> The `withIncludedProperties()` method only considers the properties you explicitly include, ignoring all others. To exclude specific properties, use the `withExcludedProperties()` method.
<2> All other methods starting with `"with"` can be used to configure Pivot Table options. These include methods like `withHiddenFromAggregations()`, `withHiddenFromDragDrop()`, `withAggregationProperties()`, and more.

You can export the displayed Pivot Table data to Excel (if the current renderer is supported). A corresponding button is displayed by default in the opened tab for this purpose.