= Экспорт в XLS

// ++++
// <div class="jmix-ui-live-demo-container">
//     <a href="https://demo.jmix.ru/ui-samples/sample/pivot-table-export" class="live-demo-btn" target="_blank">ДЕМО</a>
// </div>
// ++++

Бин `PivotTableExporter` предоставляет API для скачивания сводной таблицы с агрегированными данными в формате XLS (Excel).

Чтобы использовать `PivotTableExporter`, необходимо создать экземпляр бина в вашем контроллере экрана. Необходимо передать следующие параметры:

• `PivotTable`: Ссылка на компонент `pivotTable`, из которого вы хотите экспортировать данные.
• `PivotTableExcelExporter`: Экземпляр класса `PivotTableExcelExporter`, отвечающего за обработку процесса экспорта в Excel.

Вот пример того, как использовать `PivotTableExporter` в вашем контроллере экрана:

[source,java,indent=0]
----
include::../examples/pivottable-ex1/src/main/java/com/company/ex1/view/pivottableexport/PivottableExportView.java[tags=onInit;export]
----

NOTE: Функция экспорта в настоящее время поддерживает следующие типы xref:pivot-table:pivottable-component.adoc#using-renderers[рендереров]: `TABLE`, `TABLE_BAR_CHART`, `HEATMAP`, `COL_HEATMAP` и `ROW_HEATMAP`. Важно отметить, что цвета ячеек не экспортируются.

Метод `exportTableToXls()` предоставляет способ скачивания данных таблицы в виде файла XLS (Excel). Обычно он запускается по клику на кнопку в вашем пользовательском интерфейсе. Например:

[source,java,indent=0]
----
include::../examples/pivottable-ex1/src/main/java/com/company/ex1/view/pivottableexport/PivottableExportView.java[tags=run-export]
----

CAUTION: Формат XLS имеет ограничение в 65 536 строк. Если сводная таблица содержит более 65 536 строк, контент будет усечен на последней строке, и вы увидите предупреждающее сообщение об этом.