= Exporting to XLS

// ++++
// <div class="jmix-ui-live-demo-container">
//     <a href="https://demo.jmix.io/ui-samples/sample/pivot-table-export" class="live-demo-btn" target="_blank">LIVE DEMO</a>
// </div>
// ++++

The `PivotTableExporter` bean provides an API for downloading a pivot table with aggregated data in the XLS (Excel) format.

To use the `PivotTableExporter`, you need to create an instance of the bean in your view controller. You need to pass the following parameters:

• `PivotTable`: A reference to the `pivotTable` component from which you want to export data.
• `PivotTableExcelExporter`: An instance of the `PivotTableExcelExporter` class, responsible for handling the Excel export process.

Here's an example of how to use the `PivotTableExporter` in your view controller:

[source,java,indent=0]
----
include::../examples/pivottable-ex1/src/main/java/com/company/ex1/view/pivottableexport/PivottableExportView.java[tags=onInit;export]
----

NOTE: The export functionality currently supports the following xref:pivot-table:pivottable-component.adoc#using-renderers[renderer] types: `TABLE`, `TABLE_BAR_CHART`, `HEATMAP`, `COL_HEATMAP`, and `ROW_HEATMAP`. Note that cell colors are not exported.

The `exportTableToXls()` method provides a way to download the table data as an XLS (Excel) file. This is typically triggered by a button click in your UI. For example:

[source,java,indent=0]
----
include::../examples/pivottable-ex1/src/main/java/com/company/ex1/view/pivottableexport/PivottableExportView.java[tags=run-export]
----

CAUTION: The XLS format has a limitation of 65536 rows. If the Pivot Table contains more than 65536 rows, the content will be truncated at the last row, and you will see a warning message indicating this.