= Process

Process is a structured flow of activities or tasks that serve a particular business goal.
In BPMN, a process is a central element that encompasses all associated elements, thereby illustrating the entire workflow and interactions within the business context.

== Graphical Notation

A process does not have a visual representation. It can be wrapped into a xref:bpmn/bpmn-pools-lanes.adoc#pools[pool] to make the model clearer, but using pools isn't mandatory.

== XML Representation

In the XML, the process is represented by `process` element.

[source,xml]
----
  <process id="new-process" name="New process" isExecutable="true" >
    . . .
  </process>
----

// Additionally, the process may have `processType`, `isClosed`, and `definitionalCollaborationRef` attributes that are ignored in Jmix BPM.

[[properties]]
== Properties

Just like the elements which make up a process, the process itself has a number of properties. You can view and edit process properties in the Modeler when no element is selected.

[cols="1,6", grid=rows, frame=none]
|===
|*Property*
|*Description*
|Process id
|The *process id* identifies the process when it is deployed. In runtime, it is called *process key*.
|Name
|The name of the process. The maximal length is 255 characters.
|Candidate groups
|A group of users permitted to start the process. If the user belongs to the group, they will see this process definition in the xref:menu-views/start-process-view.adoc[Start process] view.
|Candidate users
|Individual users permitted to start the process. If the user is among candidates, they will see this process definition in the xref:menu-views/start-process-view.adoc[Start process] view.
|Event listeners
|See xref:listeners.adoc#execution-listeners[listeners].
|Signal definitions [[signal-definition]]
a|To create a signal definition, set its *Id*, *Name*, and *Scope*:

* `Global` signals are sent throughout the entire process engine. This means if one process instance triggers a signal event, other process instances can respond to it. This is useful for communication between different processes.
* `Process instance` signals only function within their own process instance. They can help synchronize tasks that are mutually exclusive.

You can configure a xref:bpmn/bpmn-events.adoc#signal-events[signal event] element to reference a definition.
|Message definitions
|To create a message definition, set its id and name. This message can be used in xref:bpmn/bpmn-events.adoc#message-events[Message event] elements.
|Error definitions
|To create an error definition, set its id and name. Besides, you may set Error code. This error can be used in xref:bpmn/bpmn-events.adoc#error-events[Error event] elements.
|Documentation
|A description and additional information about the process.
|===
