= Свойства Email

[[spring-boot-mail-properties]]
== Свойства Spring Boot Mail

Используйте {spring-boot-doc}/appendix/application-properties/index.html#appendix.application-properties.mail[свойства Spring Boot для почты^], чтобы определить основные параметры отправки писем, такие как протокол, хост, порт и другие.

Например:

[source, properties,indent=0]
----
include::example$/email-ex1/src/main/resources/application.properties[tags=spring-boot-properties]
----

Также вы можете указать свойства `JavaMail` в формате `spring.mail.properties.*`. Например, свойство `mail.smtp.auth` можно задать следующим образом:

[source, properties,indent=0]
----
include::example$/email-ex1/src/main/resources/application.properties[tags=java-mail-properties]
----

[[email-properties]]
== Свойства Jmix Email

Свойства Jmix email позволяют настроить функциональность, описанную в разделе xref:api.adoc[].

[[jmix.email.from-address]]
=== jmix.email.from-address

Определяет адрес отправителя по умолчанию. Используется, если атрибут `EmailInfo.from` не указан.

Значение по умолчанию: `DoNotReply@localhost`

[[jmix.email.scheduled-sending-delay-call-count]]
=== jmix.email.scheduled-sending-delay-call-count

Свойство используется при асинхронной отправке писем для пропуска первых нескольких вызовов `Emailer.processQueuedEmails()` после запуска сервера, чтобы снизить нагрузку во время инициализации приложения. Отправка писем начнется со следующего вызова.

Значение по умолчанию: `2`

[[jmix.email.message-queue-capacity]]
=== jmix.email.message-queue-capacity

Свойство используется для асинхронной отправки, максимальное количество сообщений, читаемых из очереди и отправляемых за один вызов `Emailer.processQueuedEmails()`.

Значение по умолчанию: `100`

[[jmix.email.default-sending-attempts-limit]]
=== jmix.email.default-sending-attempts-limit

Свойство используется для асинхронной отправки, количество попыток отправить письмо по умолчанию. Используется, если параметр `attemptsCount` не указан при вызове `Emailer.sendEmailAsync()`.

Значение по умолчанию: `10`

[[jmix.email.sending-timeout-sec]]
=== jmix.email.sending-timeout-sec

Определяет максимально ожидаемое время в секундах, необходимое для отправки письма на SMTP-сервер. Используется для асинхронной отправки для оптимизации выборки объектов `SendingMessage` из базы данных.

Значение по умолчанию: `240`

[[jmix.email.admin-address]]
=== jmix.email.admin-address

Определяет адрес, на который отправляются все сообщения, если включено свойство <<jmix.email.send-all-to-admin,jmix.email.send-all-to-admin>>.

Значение по умолчанию: `admin@localhost`

[[jmix.email.send-all-to-admin]]
=== jmix.email.send-all-to-admin

Указывает, что все сообщения должны отправляться на адрес <<jmix.email.admin-address,jmix.email.admin-address>>, независимо от указанного адреса получателя. Рекомендуется использовать этот параметр во время разработки и отладки системы.

Значение по умолчанию: `false`

[[jmix.email.use-file-storage]]
=== jmix.email.use-file-storage

При включении текст тела письма и вложения будут храниться в файловом хранилище, а не в BLOB-столбцах базы данных. Следует использовать, если приложение хранит много писем и/или вложений к письмам.

Значение по умолчанию: `false`

[[jmix.email.async-sending-username]]
=== jmix.email.async-sending-username

Определяет логин системного пользователя, используемого кодом асинхронной отправки писем для возможности сохранения информации в базе данных. Рекомендуется создать отдельного пользователя (например, `emailer`) без пароля, чтобы под его именем было невозможно войти через пользовательский интерфейс. Это также удобно для поиска сообщений, связанных с отправкой писем, в логе сервера.

Значение по умолчанию: `admin`

[[jmix.email.use-default-quartz-configuration]]
=== jmix.email.use-default-quartz-configuration

Определяет, используется ли <<sending-default-quartz-configuration,конфигурация Quartz по умолчанию>> для отправки писем.

Значение по умолчанию: `true`

[[jmix.email.email-sending-cron]]
=== jmix.email.email-sending-cron

Определяет CRON-выражение, которое используется по умолчанию в конфигурации планирования Quartz для отправки писем.

Значение по умолчанию: `0 * * * * ?` (каждую минуту).

[[jmix.email.use-default-email-cleaning-quartz-configuration]]
=== jmix.email.use-default-email-cleaning-quartz-configuration

Определяет, используется ли <<cleaning-default-quartz-configuration,конфигурация Quartz по умолчанию>> для очистки писем.

Значение по умолчанию: `false`

[[jmix.email.email-cleaning-cron]]
=== jmix.email.email-cleaning-cron

Определяет CRON-выражение, которое используется по умолчанию в конфигурации планирования Quartz для очистки писем.

Значение по умолчанию: `0 0 0 * * ?` (в начале каждого дня)

[[jmix.email.max-age-of-important-messages]]
=== jmix.email.max-age-of-important-messages

Определяет максимальный возраст (в днях) важных сообщений, после которого они должны быть удалены. Значение ноль (`0`) означает, что сообщения не будут удаляться.

Значение по умолчанию: `0`

[[jmix.email.max-age-of-non-important-messages]]
=== jmix.email.max-age-of-non-important-messages

Определяет максимальный возраст (в днях) сообщений, после которого они должны быть удалены. Значение ноль (`0`) означает, что сообщения не будут удаляться.

Значение по умолчанию: `0`

[[jmix.email.clean-file-storage]]
=== jmix.email.clean-file-storage

Определяет, должна ли выполняться очистка файлового хранилища во время работы планировщика очистки.

Значение по умолчанию: `false`

[[jmix.email.oauth2.enabled]]
=== jmix.email.oauth2.enabled

Если `true`, включает использование авторизации на основе токена OAuth 2.0 для подключения к почтовому серверу.

[[jmix.email.oauth2.provider]]
=== jmix.email.oauth2.provider

Определяет провайдера OAuth для почты.

[[jmix.email.oauth2.client-id]]
=== jmix.email.oauth2.client-id

Определяет идентификатор клиента OAuth (client id).

[[jmix.email.oauth2.secret]]
=== jmix.email.oauth2.secret

Определяет секрет клиента OAuth (client secret).

[[jmix.email.oauth2.tenant-id]]
=== jmix.email.oauth2.tenant-id

Определяет идентификатор тенанта OAuth (tenant id).

[[jmix.email.oauth2.refresh-token]]
=== jmix.email.oauth2.refresh-token

Определяет токен обновления OAuth (refresh token).

[[email-sending-scheduler]]
== Планировщик отправки писем

При вызове метода `Emailer.sendEmailAsync()` письмо не отправляется, а ставится в очередь в базе данных. Для отправки писем из очереди необходимо вызвать метод `Emailer.processQueuedEmails()`.

Вы можете использовать планировщик заданий Quartz для периодической обработки очереди писем, как описано ниже.

[[sending-default-quartz-configuration]]
=== Конфигурация Quartz по умолчанию

Дополнение Email Sending предоставляет конфигурацию задачи Quartz по умолчанию для обработки очереди отправки писем. Чтобы использовать ее, выполните следующие действия:

. Включите дополнение Quartz в свой проект, как описано в разделе xref:quartz:index.adoc#installation[Quartz / Установка].

. При необходимости измените CRON-выражение, используя свойство <<jmix.email.email-sending-cron,jmix.email.email-sending-cron>>:
+
[source, properties,indent=0]
----
include::example$/email-ex1/src/main/resources/application.properties[tags=email-sending-cron]
----

[[sending-custom-quartz-configuration]]
=== Пользовательская конфигурация Quartz

Если вы хотите использовать пользовательскую конфигурацию задачи Quartz, выполните следующие действия:

. Включите дополнение Quartz в свой проект, как описано в разделе xref:quartz:index.adoc#installation[Quartz / Установка].

. Установите значение свойства приложения <<jmix.email.use-default-quartz-configuration>> в `false`:
+
[source, properties,indent=0]
----
jmix.email.use-default-quartz-configuration = false
----

. Создайте класс задачи:
+
[source,java,indent=0]
----
include::example$/email-ex1/src/main/java/com/company/emailex1/service/MyCustomEmailSendingJob.java[tags=quartz]
----

. В работающем приложении откройте экран *Quartz -> Quartz jobs* и настройте задачу для класса `MyCustomEmailSendingJob`.

. Альтернативно, если вы хотите настроить задачу отправки писем на этапе разработки, добавьте следующие бины в основной класс приложения:
+
[source,java,indent=0]
----
include::example$/email-ex1/src/main/java/com/company/emailex1/EmailEx1Application.java[tags=quartz]
----
<1> Начните построение определения задачи с помощью класса `org.quartz.JobBuilder`.
<2> Создайте экземпляр `org.quartz.JobDetail`.
<3> Начните построение определения триггера с помощью класса `org.quartz.TriggerBuilder`.
<4> Свяжите этот триггер с ранее определенной задачей.
<5> Создайте экземпляр `org.quartz.Trigger`.

[[email-cleaning-scheduler]]
== Планировщик очистки писем

Дополнение имеет встроенную задачу Quartz для очистки, которая по умолчанию выключена. Вы можете использовать ее для периодической очистки сохраненных писем, как описано ниже.

Если вам нужно хранить некоторые письма дольше, используйте флаг `important` и установите максимальный возраст для важных и неважных писем. Вы можете установить этот флаг с помощью метода `setImportant()` у `EmailInfoBuilder`.

[[cleaning-default-quartz-configuration]]
=== Конфигурация Quartz по умолчанию

Чтобы использовать конфигурацию задачи Quartz по умолчанию для регулярной очистки писем, выполните следующие действия:

. Включите дополнение Quartz в свой проект, как описано в разделе xref:quartz:index.adoc#installation[Quartz / Установка].

. Установите значение свойства <<jmix.email.use-default-email-cleaning-quartz-configuration,jmix.email.use-default-email-cleaning-quartz-configuration>> в `true`:
+
[source, properties,indent=0]
----
jmix.email.use-default-email-cleaning-quartz-configuration=true
----

. При необходимости измените CRON-выражение, используя свойство <<jmix.email.email-cleaning-cron,jmix.email.email-cleaning-cron>>.
+
[source, properties,indent=0]
----
jmix.email.email-cleaning-cron=0 0 0 1/2 * ? 
----

. Установите возраст для важных и неважных писем, используя свойства <<jmix.email.max-age-of-important-messages,jmix.email.max-age-of-important-messages>> и <<jmix.email.max-age-of-non-important-messages,jmix.email.max-age-of-non-important-messages>>, например:
+
[source, properties,indent=0]
----
jmix.email.max-age-of-non-important-messages=5
jmix.email.max-age-of-important-messages=30
----

. Установите значение свойства <<jmix.email.clean-file-storage,jmix.email.clean-file-storage>> в `true`, если вы хотите удалять вложения.

[[cleaning-custom-quartz-configuration]]
=== Пользовательская конфигурация Quartz

Если вы хотите использовать пользовательскую конфигурацию задачи Quartz, выполните следующие действия:

. Включите дополнение Quartz в свой проект, как описано в разделе xref:quartz:index.adoc#installation[Quartz / Установка].

. Создайте класс задачи:
+
[source,java,indent=0]
----
include::example$/email-ex1/src/main/java/com/company/emailex1/service/MyCustomEmailCleaningJob.java[tags=quartz]
----

. В работающем приложении откройте экран *Quartz -> Quartz jobs* и настройте задачу для класса `MyCustomEmailCleaningJob`.

. Альтернативно, если вы хотите настроить задачу очистки писем на этапе разработки, добавьте следующие бины в основной класс приложения:
+
[source,java,indent=0]
----
include::example$/email-ex1/src/main/java/com/company/emailex1/EmailEx1Application.java[tags=quartz-clean]
----
<1> Начните построение определения задачи с помощью класса `org.quartz.JobBuilder`.
<2> Создайте экземпляр `org.quartz.JobDetail`.
<3> Начните построение определения триггера с помощью класса `org.quartz.TriggerBuilder`.
<4> Свяжите этот триггер с ранее определенной задачей.
<5> Создайте экземпляр `org.quartz.Trigger`.

. Установите возраст для важных и неважных писем, используя свойства <<jmix.email.max-age-of-important-messages,jmix.email.max-age-of-important-messages>> и <<jmix.email.max-age-of-non-important-messages,jmix.email.max-age-of-non-important-messages>>, например:
+
[source, properties,indent=0]
----
jmix.email.max-age-of-non-important-messages=5
jmix.email.max-age-of-important-messages=30
----

. Установите значение свойства <<jmix.email.clean-file-storage,jmix.email.clean-file-storage>> в `true`, если вы хотите удалять вложения.

[[file-storage-usage]]
== Использование файлового хранилища

Вы можете хранить текст тела письма и вложения в файловом хранилище вместо BLOB-столбцов в базе данных.

Чтобы использовать файловое хранилище:

. Убедитесь, что следующая строка присутствует в разделе `dependencies` вашего файла `build.gradle`:
+
[source,groovy,indent=0]
----
include::example$/email-ex1/build.gradle[tags=fs-dependency]
----
+
. Включите использование файлового хранилища. Установите в файле `application.properties`:
+
[source, properties,indent=0]
----
include::example$/email-ex1/src/main/resources/application.properties[tags=fs-enable]
----

По умолчанию локальное файловое хранилище находится в рабочем каталоге приложения по пути `${user.dir}/.jmix/work/filestorage`.