= Email Sending

Jmix provides the following email sending functionality:

* *Synchronous and asynchronous sending:* In synchronous mode the calling code waits until the message is sent to the SMTP server; in asynchronous mode the message is persisted to the database for later sending and control is returned immediately to the calling code.

* *Scheduled sending via xref:jmix:quartz:index.adoc[]:* Defer sends, create recurring messages, or align sending with specific time zones using Quartz jobs.

* *Reliable tracking:* Send timestamps and error details are saved in the database for both synchronous and asynchronous modes.

* *User interface:* A user interface to search and view sent emails, including full message content, attributes, sending status, and attempt count.

[[installation]]
== Installation

For automatic installation through Jmix Marketplace, follow instructions in the xref:ROOT:add-ons.adoc#installation[Add-ons] section.

For manual installation, add the following dependencies to your `build.gradle`:

[source,groovy,indent=0]
----
implementation 'io.jmix.email:jmix-email-starter'
implementation 'io.jmix.email:jmix-email-flowui-starter'
----

include::ROOT:single-menu-note.adoc[]