= Email Sending

Jmix предоставляет следующую функциональность для отправки электронных писем:

* *Синхронная и асинхронная отправка*: В синхронном режиме вызывающий код ожидает, пока сообщение будет отправлено на SMTP-сервер; в асинхронном режиме сообщение сохраняется в базу данных для последующей отправки, и управление немедленно возвращается вызывающему коду.

* *Планируемая отправка через xref:jmix:quartz:index.adoc[]*: Откладывайте отправку, создавайте повторяющиеся сообщения или согласовывайте отправку с определенными часовыми поясами с помощью задач Quartz.

* *Надежное отслеживание*: Временные метки отправки и сведения об ошибках сохраняются в базе данных как для синхронного, так и для асинхронного режимов.

* *Пользовательский интерфейс*: Пользовательский интерфейс для поиска и просмотра отправленных писем, включая полное содержимое сообщения, атрибуты, статус отправки и количество попыток.

[[installation]]
== Установка

Для автоматической установки через Jmix Marketplace следуйте инструкциям в разделе xref:ROOT:add-ons.adoc#installation[Дополнения].

Для ручной установки добавьте следующие зависимости в ваш `build.gradle`:

[source,groovy,indent=0]
----
implementation 'io.jmix.email:jmix-email-starter'
implementation 'io.jmix.email:jmix-email-flowui-starter'
----

include::ROOT:single-menu-note.adoc[]