= API бизнес-календаря

== BusinessCalendarRepository

`BusinessCalendarRepository` определяет удобные методы для получения бизнес-календарей, настроенных в системе.

* Метод `getBusinessCalendarByCode(String code)` возвращает бизнес-календарь с указанным кодом.
* Метод `getAllBusinessCalendars()` возвращает все бизнес-календари, настроенные в системе.

== BusinessCalendar

`BusinessCalendar` предоставляет методы для проверки, относится ли указанная дата и время к рабочим часам, а также для арифметических операций с датой и временем с учетом рабочих часов, определенных календарем:

* `getDayInfo(LocalDate date)` возвращает информацию о заданной дате, включая то, является ли она рабочим днем, и связанную с ним метку (*Mark*).
* `getDayInfo(LocalDateTime dateTime)` возвращает информацию о заданной дате и времени, включая то, является ли это рабочим временем, и связанную с ним метку (*Mark*).
* `isBusinessDay(LocalDate date)` проверяет, относится ли указанная дата к рабочим дням.
* `isBusinessTime(LocalDateTime dateTime)` проверяет, относится ли указанные дата и время к рабочему времени.
* `plus(LocalDate date, int daysToAdd)` возвращает копию указанной даты с добавлением указанного количества рабочих дней.
* `minus(LocalDate date, int daysToSubtract)` возвращает копию указанной даты с вычитанием указанного количества рабочих дней.
* `plus(LocalDateTime dateTime, int hoursToAdd)` возвращает копию указанных даты и времени с добавлением указанного количества рабочих часов.
* `minus(LocalDateTime dateTime, int hoursToSubtract)` возвращает копию указанных даты и времени с вычитанием указанного количества рабочих часов.
* `plus(LocalDateTime dateTime, Duration duration)` возвращает копию указанных даты и времени с добавлением указанной продолжительности в терминах рабочего времени.
* `minus(LocalDateTime dateTime, Duration duration)` возвращает копию указанных дата и времени с вычитанием указанной продолжительности в терминах рабочего времени.