= initialLayout

Компонент `initialLayout` - это контейнер, который отображается, когда в xref:flow-ui:views/view-classes.adoc#standard-main-view[главном экране] не открыто никаких экранов. Этот компонент может быть полезен, когда необходимо показать контент по умолчанию, такой как логотип или dashboard, до открытия других экранов.

* XML-элемент: `initialLayout`

== Основы

`initialLayout` является вложенным элементом компонента `appLayout`.

TIP: Чтобы добавить вложенный элемент `initialLayout` в Jmix Studio, выберите элемент `appLayout` в XML-дескрипторе главного экрана или на панели структуры *Jmix UI* и нажмите кнопку xref:studio:screen-designer.adoc#component-inspector-add-button[Add]->InitialLayout на панели инспектора *Jmix UI*.

Пример определения `initialLayout` в `main-view.xml`:

[source,xml,indent=0]
----
<mainView xmlns="http://jmix.io/schema/flowui/main-view"
          title="msg://MainView.title">
    <appLayout>
        <navigationBar .../>
        <drawerLayout .../>
        <initialLayout>
            <image id="urlImage"
                   resource="https://www.jmix.io/uploads/framework_image_9efadbc372.svg"
                   width="100%"
                   height="100%"/>
        </initialLayout>
    </appLayout>
</mainView>
----

При добавлении в XML корневой элемент `<initialLayout>` фактически является xref:vc/layouts/vbox.adoc[VerticalLayout].

Альтернативно, Java API `StandardMainView` может быть использовано для установки/получения начального контейнера:

* `getInitialLayout()` - возвращает корневой компонент начального контейнера.
* `setInitialLayout()` - устанавливает компонент, который будет начальным контейнером.

Компоненты внутри `initialLayout` могут быть инжектированы в `MainView`, например:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/main/MainView.java[tags=initialLayout;!init-onBoardingStatus;!get-menu-item;!new-menu-item]
----

== Атрибуты

xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignItems[alignItems] -
xref:vc/layouts/vbox.adoc#boxSizing[boxSizing] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/layouts/vbox.adoc#expand[expand] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/layouts/vbox.adoc#justifyContent[justifyContent] -
xref:vc/layouts/vbox.adoc#margin[margin] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/layouts/vbox.adoc#padding[padding] -
xref:vc/layouts/vbox.adoc#spacing[spacing] -
xref:vc/common-attributes.adoc#themeNames[themeNames] -
xref:vc/common-attributes.adoc#width[width]

[[handlers]]
== Обработчики

include::../handler-generation-tip.adoc[]

xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
xref:vc/layouts/vbox.adoc#ClickEvent[ClickEvent] -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent]