= Indexing Queue

Once you integrate the Search add-on into your application, it immediately begins xref:config-options.adoc#tracking-changes[monitoring changes] in your entities. This section details the process of configuring the automatic update of indexes with the latest data.

The change tracking mechanism stores a queue of actions that should be done for changed entity instances in the `SEARCH_INDEXING_QUEUE` database table. The `IndexingQueueManager` bean contains methods to process the queue and send changed data to Elasticsearch/OpenSearch.

NOTE: It's essential to establish regular processing of the indexing queue to ensure that search results reflect current data.

For scheduling periodic queue processing, you can utilize the Quartz Job Scheduler following the instructions provided.

[[default-quartz-configuration]]
== Default Quartz Configuration

The Search add-on comes with a pre-configured Quartz job for regularly processing the indexing queue. To enable this feature, follow these steps:

. Include the Quartz add-on in your project as described in the xref:quartz:index.adoc#installation[Quartz / Installation] section.

. Modify the CRON expression as needed. The default value is `0/5 * * * * ?` (every 5 seconds).
+
[source,properties,indent=0]
----
include::example$/search-ex1/src/main/resources/application.properties[tags=cron]
----

The default configuration creates and schedules a job with the `IndexingQueueProcessing` identity.

[[custom-quartz-configuration]]
== Custom Quartz Configuration

If you prefer to utilize a custom Quartz configuration, follow these steps:

. Include the Quartz add-on in your project as described in the xref:quartz:index.adoc#installation[Quartz / Installation] section.

. Within the `application.properties` file, include the following property to deactivate the default configuration:
+
[source,properties,indent=0]
----
include::example$/search-ex1/src/main/resources/application.properties[tags=not-default]
----

. Develop a custom job class that invokes `IndexingQueueManager.processNextBatch()`:
+
[source,java,indent=0]
----
include::example$/search-ex1/src/main/java/com/company/demo/service/MyCustomQueueProcessingJob.java[tags=custom-job]
----

. While the application is running, navigate to the *Quartz -> Quartz jobs* view to set up a job for the `MyCustomQueueProcessingJob` class.

. Alternatively, if you want to configure the job during development, register the following beans in the application:
+
[source,java,indent=0]
----
include::example$/search-ex1/src/main/java/com/company/demo/DemoApplication.java[tags=beans]
----

//Value of the property `jmix.search.indexingQueueProcessingCron` can be found in `io.jmix.search.SearchProperties` class.