= Очередь индексации

После интеграции дополнения Search в ваше приложение оно немедленно начинает xref:config-options.adoc#tracking-changes[отслеживать изменения] в ваших сущностях. В этом разделе подробно описывается процесс настройки автоматического обновления индексов актуальными данными.

Механизм отслеживания изменений сохраняет очередь действий, которые должны быть выполнены для измененных экземпляров сущностей, в таблице базы данных `SEARCH_INDEXING_QUEUE`. Бин `IndexingQueueManager` содержит методы для обработки очереди и отправки измененных данных в Elasticsearch/OpenSearch.

NOTE: Крайне важно настроить регулярную обработку очереди индексации, чтобы обеспечить отражение текущих данных в результатах поиска.

Для планирования периодической обработки очереди вы можете использовать Планировщик задач Quartz, следуя приведенным инструкциям.

[[default-quartz-configuration]]
== Конфигурация Quartz по умолчанию

Дополнение Search поставляется с предварительно настроенной задачей Quartz для регулярной обработки очереди индексации. Чтобы включить эту функцию, выполните следующие шаги:

. Включите дополнение Quartz в ваш проект, как описано в разделе xref:quartz:index.adoc#installation[Quartz / Установка].

. При необходимости измените выражение CRON. Значение по умолчанию - `0/5 * * * * ?` (каждые 5 секунд).
+
[source,properties,indent=0]
----
include::example$/search-ex1/src/main/resources/application.properties[tags=cron]
----

Конфигурация по умолчанию создает и планирует задание с идентификатором `IndexingQueueProcessing`.

[[custom-qurtz-configuration]]
== Пользовательская конфигурация Quartz

Если вы предпочитаете использовать пользовательскую конфигурацию Quartz, выполните следующие шаги:

. Включите дополнение Quartz в ваш проект, как описано в разделе xref:quartz:index.adoc#installation[Quartz / Установка].

. В файле `application.properties` включите следующее свойство, чтобы деактивировать конфигурацию по умолчанию:
+
[source,properties,indent=0]
----
include::example$/search-ex1/src/main/resources/application.properties[tags=not-default]
----

. Разработайте пользовательский класс задачи, который вызывает `IndexingQueueManager.processNextBatch()`:
+
[source,java,indent=0]
----
include::example$/search-ex1/src/main/java/com/company/demo/service/MyCustomQueueProcessingJob.java[tags=custom-job]
----

. Во время работы приложения перейдите в экран *Quartz -> Quartz jobs*, чтобы настроить задачу для класса `MyCustomQueueProcessingJob`.

. Альтернативно, если вы хотите настроить задачу во время разработки, зарегистрируйте следующие бины в приложении:
+
[source,java,indent=0]
----
include::example$/search-ex1/src/main/java/com/company/demo/DemoApplication.java[tags=beans]
----

//Value of the property `jmix.search.indexingQueueProcessingCron` can be found in `io.jmix.search.SearchProperties` class.