= Search

Дополнение Search предоставляет функциональность полнотекстового поиска для вашего приложения.
Оно позволяет настраивать индексацию сущностей и загруженных файлов, а также предоставляет API и UI-компоненты для поиска по индексированным данным. Результаты поиска фильтруются на основе прав xref:security:index.adoc[доступа к данным] текущего пользователя.

Дополнение использует https://www.elastic.co[Elasticsearch^] или https://opensearch.org[OpenSearch^] в качестве поисковой системы. Оно может работать только с одной из них одновременно.

Для получения дополнительной информации о внутренних механизмах поиска и индексации обратитесь к документации https://www.elastic.co/guide/en/elasticsearch/reference/current/documents-indices.html[Elasticsearch^] или https://opensearch.org/docs/latest[OpenSearch^].

[[installation]]
== Установка

Для автоматической установки через Jmix Marketplace следуйте инструкциям в разделе xref:ROOT:add-ons.adoc#installation[Дополнения].

По умолчанию дополнение будет установлено с поддержкой OpenSearch.

Если вы обновляете проект с предыдущей версии Jmix с установленным дополнением, оно сохранит поддержку Elasticsearch.

Для ручной установки добавьте следующие зависимости в ваш `build.gradle`:

[source,groovy,indent=0]
----
include::example$/search-ex1/build.gradle[tags=dependency]
----

Если вы хотите переключиться между Elasticsearch и OpenSearch, замените `jmix-search-opensearch-starter` на `jmix-search-elasticsearch-starter` или наоборот:

[source,groovy,indent=0]
----
include::example$/search-ex1/build.gradle[tags=dependency-elastic]
----

[[connecting-to-search-engine-service]]
== Подключение к сервису поисковой системы

Для подключения к сервису Elasticsearch/OpenSearch укажите следующие свойства в файле `application.properties`:

* `jmix.search.server.url` - полный URL сервиса.
* `jmix.search.server.login` - логин для базовой аутентификации.
* `jmix.search.server.password` - пароль пользователя, используемый для подключения к сервису.

[[version-compatibility]]
== Совместимость версий

Java API клиенты для Elasticsearch/OpenSearch имеют прямую совместимость с версией сервера.

Версия Elasticsearch Java API, используемая дополнением, определяется Spring Boot. См. версию `co.elastic.clients:elasticsearch-java` в {spring-boot-doc}/appendix/dependency-versions/coordinates.html[^].

Для OpenSearch дополнение использует Java API client v2.13.

NOTE: На платформе AWS необходимо использовать Amazon OpenSearch Service. Устаревший сервис Elasticsearch не поддерживается.

// In case you use a local service, you may not specify the properties above.

//[[using-amazon-web-services]]
//=== Using Amazon Web Services
//
//To connect to Elasticsearch deployed in AWS with IAM authentication, add the following properties to your `application.properties` file:
//
//* `jmix.search.elasticsearch.url` - a full URL of Elasticsearch service.
//* `jmix.search.elasticsearch.aws.region` - AWS region, for example, 'eu-central-1'.
//* `jmix.search.elasticsearch.aws.accessKey` - an access key of the target IAM user.
//* `jmix.search.elasticsearch.aws.secretKey` - a secret key of the target IAM user.
