= 搜索

搜索扩展组件为应用程序提供全文搜索的功能。
支持配置实体索引和已上传文件的索引，并提供对索引数据进行搜索的 API 和 UI 组件。搜索结果会根据当前用户的 xref:security:index.adoc[数据访问] 权限进行过滤。

该扩展组件使用 https://www.elastic.co[Elasticsearch（ES）^] 或 https://opensearch.org[OpenSearch^]作为搜索引擎。使用时请选择其中之一作为搜索引擎。

关于其内部原理和索引构建的更多信息请参阅 https://www.elastic.co/guide/en/elasticsearch/reference/current/documents-indices.html[Elasticsearch^] 或 https://opensearch.org/docs/latest[OpenSearch^] 文档。

[[installation]]
== 安装

按照 xref:ROOT:add-ons.adoc#installation[扩展组件] 章节的说明通过 Jmix 市场进行自动安装。

扩展组件默认安装后，将支持 OpenSearch 作为搜索引擎。

如果项目是从之前安装了扩展组件的 Jmix 版本升级而来，则会保留 Elasticsearch 作为搜索引擎。

手动安装，在 `build.gradle` 添加下列依赖：

[source,groovy,indent=0]
----
include::example$/search-ex1/build.gradle[tags=dependency]
----

如果需要切换搜索引擎，可以替换 `jmix-search-opensearch-starter` 或 `jmix-search-elasticsearch-starter`。

[source,groovy,indent=0]
----
include::example$/search-ex1/build.gradle[tags=dependency-elastic]
----

[[connecting-to-search-engine-service]]
== 连接搜索引擎服务

连接 Elasticsearch/OpenSearch 服务需要在 `application.properties` 文件中配置：

* `jmix.search.server.url` - 服务的完整 URL 地址。
* `jmix.search.server.login` - 用户名。
* `jmix.search.server.password` - 用户密码。

[[version-compatibility]]
== 版本兼容性

Elasticsearch/OpenSearch 的 Java API 客户端是向前兼容的。

扩展组件使用 Elasticsearch Java API 的版本由 Spring Boot 决定。参阅 {spring-boot-doc}/appendix/dependency-versions/coordinates.html[^] 中的 `co.elastic.clients:elasticsearch-java` 版本。

对于 OpenSearch，扩展组件使用 Java API 客户端 v2.10.3。

NOTE: 在 AWS 中，请使用 Amazon OpenSearch Service。不支持旧的 Elasticsearch service 服务。

// In case you use a local service, you may not specify the properties above.

//[[using-amazon-web-services]]
//=== 使用 AWS
//
//如需连接部署在 AWS 中使用 IAM 认证的 ES 服务，在 `application.properties` 文件中添加下列属性：
//
//* `jmix.search.elasticsearch.url` - ES 服务的完整 URL。
//* `jmix.search.elasticsearch.aws.region` - AWS 区域，例如，'eu-central-1'。
//* `jmix.search.elasticsearch.aws.accessKey` - IAM 用户的 access key。
//* `jmix.search.elasticsearch.aws.secretKey` - IAM 用户的 secret key。
