= Search

The Search add-on provides full-text search functionality for your application.
It allows you to configure indexing of entities and uploaded files, as well as providing API and UI components for searching the indexed data. The search results are filtered based on the xref:security:index.adoc[data access] permissions of the current user.

The add-on utilizes https://www.elastic.co[Elasticsearch^] or https://opensearch.org[OpenSearch^] as its search engine. It can work with only one of them at the same time.

For more information about the internal search and indexing mechanisms, please refer to the https://www.elastic.co/guide/en/elasticsearch/reference/current/documents-indices.html[Elasticsearch^] or https://opensearch.org/docs/latest[OpenSearch^] documentation.

[[installation]]
== Installation

For automatic installation through Jmix Marketplace, follow instructions in the xref:ROOT:add-ons.adoc#installation[Add-ons] section.

By default, the add-on will be installed with the OpenSearch support.

If you upgrade the project from the previous Jmix version with the installed add-on, it will keep the Elasticsearch support.

For manual installation, add the following dependencies to your `build.gradle`:

[source,groovy,indent=0]
----
include::example$/search-ex1/build.gradle[tags=dependency]
----

If you want to switch between Elasticsearch and OpenSearch, replace `jmix-search-opensearch-starter` with `jmix-search-elasticsearch-starter` or vice versa:

[source,groovy,indent=0]
----
include::example$/search-ex1/build.gradle[tags=dependency-elastic]
----

[[connecting-to-search-engine-service]]
== Connecting to Search Engine Service

To connect to the Elasticsearch/OpenSearch service, specify the following properties in the `application.properties` file:

* `jmix.search.server.url` - the complete URL of the service.
* `jmix.search.server.login` - the login for basic authentication.
* `jmix.search.server.password` - the user password used to connect to the service.

[[version-compatibility]]
== Version Compatibility

Java API clients for Elasticsearch/OpenSearch are forward-compatible with server versions.

The version of the Elasticsearch Java API used by the add-on is determined by the Spring Boot. See `co.elastic.clients:elasticsearch-java` version at {spring-boot-doc}/appendix/dependency-versions/coordinates.html[^].

With OpenSearch, the add-on uses Java API client v2.13.

NOTE: On AWS, use Amazon OpenSearch Service. The legacy Elasticsearch service is not supported.

// In case you use a local service, you may not specify the properties above.

//[[using-amazon-web-services]]
//=== Using Amazon Web Services
//
//To connect to Elasticsearch deployed in AWS with IAM authentication, add the following properties to your `application.properties` file:
//
//* `jmix.search.elasticsearch.url` - a full URL of Elasticsearch service.
//* `jmix.search.elasticsearch.aws.region` - AWS region, for example, 'eu-central-1'.
//* `jmix.search.elasticsearch.aws.accessKey` - an access key of the target IAM user.
//* `jmix.search.elasticsearch.aws.secretKey` - a secret key of the target IAM user.
