= 配置

[[jmix.search.changedEntitiesIndexingEnabled]]
== jmix.search.changed-entities-indexing-enabled

定义是否启用对 xref:config-options.adoc#tracking-changes[变更实体] 的自动索引。

默认值：`true`

[[jmix.search.defaultSearchStrategy]]
== jmix.search.default-search-strategy

默认 xref:search-in-ui.adoc#search-strategies[搜索策略] 的名称。

默认值：`anyTermAnyField`

[[jmix.search.enqueueIndexAllOnStartupIndexRecreationEnabled]]
== jmix.search.enqueue-index-all-on-startup-index-recreation-enabled

定义是否自动将启动时创建或重建索引的所有实体实例都添加至队列中。参考 xref:config-options.adoc#existing-data-indexing[已有数据索引]。

默认值：`true`

[[jmix.search.enqueueIndexAllOnStartupIndexRecreationEntities]]
== jmix.search.enqueue-index-all-on-startup-index-recreation-entities

定义在应用程序启动重建索引时需要自动添加到队列中的实体列表。空列表表示全部索引实体。参考 xref:config-options.adoc#existing-data-indexing[已有数据索引]。

默认值：无

[[jmix.search.enqueueingSessionProcessingCron]]
== jmix.search.enqueueing-session-processing-cron

默认队列会话（Enqueueing Session）处理 Quartz xref:indexing-queue.adoc#default-quartz-configuration[调度配置] 使用的 http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html[Cron 表达式^]。

默认值：`0/5 * * * * ?`

[[jmix.search.indexingQueueProcessingCron]]
== jmix.search.indexing-queue-processing-cron

默认索引队列（Indexing Queue）处理 Quartz xref:indexing-queue.adoc#default-quartz-configuration[调度配置] 使用的 http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html[Cron 表达式^]。

默认值：`0/5 * * * * ?`

[[jmix.search.indexSchemaManagementStrategy]]
== jmix.search.index-schema-management-strategy

索引结构的同步方式。参阅 xref:config-options.adoc#indexes-creation[索引创建] 了解细节。

默认值：`create-or-recreate`

[[jmix.search.maxPrefixLength]]
== jmix.search.max-prefix-length

定义 xref:search:index-definitions.adoc#extended-search["starts with"] 搜索策略的生成前缀的最大长度。

Edge N-gram 分析器为每个索引单词创建从 <<jmix.search.minPrefixLength,min-prefix-length>> 到此最大值的所有前缀。最大值设置的越大会：

* 提高较长前缀的搜索准确性。
* 由于存储更多前缀而增加索引大小。
* 降低通配符回退查询的性能。

默认值：`8`

[[jmix.search.maxSearchPageCount]]
== jmix.search.max-search-page-count

设置结果页面显示的最大数量。

默认值：`100`

[[jmix.search.minPrefixLength]]
== jmix.search.min-prefix-length

定义 xref:search:index-definitions.adoc#extended-search["starts with"] 搜索策略的生成前缀的最小长度。

Edge N-gram 分析器仅从此长度开始创建前缀。最小值设置的越小会：

* 支持匹配非常短的搜索词。
* 显著增加索引大小（生成更多前缀）。
* 可能因大量小前缀而影响性能。

默认值：`3`

[[jmix.search.processQueueBatchSize]]
== jmix.search.process-queue-batch-size

设置每组（batch）中能处理的队列项数量。

默认值：`100`

[[jmix.search.reindexEntityEnqueueBatchSize]]
== jmix.search.reindex-entity-enqueue-batch-size

设置在实体索引重建过程中每个队列组中实体的数量。

默认值：`100`

[[jmix.search.searchIndexNamePrefix]]
== jmix.search.search-index-name-prefix

索引名称前缀。索引名格式为 `<prefix><entity_name>`。参阅 xref:getting-started.adoc#configure-index-naming[配置索引名]。

默认值：`search_index_`

[[jmix.search.searchReloadEntitiesBatchSize]]
== jmix.search.search-reload-entities-batch-size

定义搜索完成后处理实体的每组（batch）中实体的数量，例如，当搜索接续需要按照行级策略做过滤时，或者当实体从搜索结果中使用 fetch plan 获取时。参阅 See xref:search-api.adoc#security-and-pagination[访问控制和分页]。

默认值：`100`

[[jmix.search.searchResultPageSize]]
== jmix.search.search-result-page-size

定义搜索结果每页展示对象的最大数量。

默认值：`100`

[[jmix.search.useDefaultEnqueueingSessionProcessingQuartzConfiguration]]
== jmix.search.use-default-enqueueing-session-processing-quartz-configuration

定义是否使用默认队列会话（Enqueueing Session）处理的 Quartz xref:indexing-queue.adoc#default-quartz-configuration[调度配置]。

默认值：`true`

[[jmix.search.useDefaultIndexingQueueProcessingQuartzConfiguration]]
== jmix.search.use-default-indexing-queue-processing-quartz-configuration

定义是否使用默认索引队列（Indexing Queue）处理的 Quartz xref:indexing-queue.adoc#default-quartz-configuration[调度配置]。

默认值：`true`

[[jmix.search.server.url]]
== jmix.search.server.url

定义 Elasticsearch/OpenSearch 服务的 URL。

默认值：`localhost:9200`

[[jmix.search.server.login]]
== jmix.search.server.login

定义用于基本认证的用户名。

默认值：无

[[jmix.search.server.password]]
== jmix.search.server.password

定义用于基本认证的用户密码。

默认值：无

[[jmix.search.server.bulkRequestRefreshPolicy]]
== jmix.search.server.bulk-request-refresh-policy

定义向搜索服务发送批量请求时所使用的刷新策略。

刷新机制可以让最近的改动能被搜索到。

* `false` - 批量请求不会触发刷新。
这个请求触发的变更会直到其他原因触发刷新后才能被搜索到，其他原因可以是显式地刷新操作或周期性的刷新（默认每秒一次）。
建议使用默认配置。除非必须同步看到改动。
* `true` - 刷新会在请求之后立即执行。
_这个模式必须在小心验证之后使用，因为有可能会引起性能问题。_
* `wait_for` - 请求不会触发刷新，但是会等待由其他因素触发的刷新。
刷新完成后才会发送请求结果。

默认值：`false`

[[jmix.search.server.ssl.certificateLocation]]
== jmix.search.server.ssl.certificate-location

定义连接搜索服务时需要使用的证书位置（如果需要的话）。

会使用 `io.jmix.core.Resources` 的规则查找提供的位置。

默认值：无

[[jmix.search.server.ssl.certificateAlias]]
== jmix.search.server.ssl.certificate-alias

定义存储在 Key Store 中证书的别名。

默认值：`es_client_ca`

[[jmix.search.server.ssl.certificateFactoryType]]
== jmix.search.server.ssl.certificate-factory-type

定义证书工厂（certificate factory）类型。

默认值：`X.509`

[[jmix.search.server.ssl.keyStoreType]]
== jmix.search.server.ssl.key-store-type

定义 key store 的类型。

默认值：`pkcs12`

[[jmix.search.wildcardPrefixQueryEnabled]]
== jmix.search.wildcard-prefix-query-enabled

当搜索词长度超过 <<jmix.search.maxPrefixLength,jmix.search.max-prefix-length>> 时，回退至通配符查询。

为 `true` 时，对大于最大前缀长度的词项执行通配符查询；当为 `false` 时，对此类词项不返回任何结果。

NOTE: 无论此设置如何，短于 <<jmix.search.minPrefixLength,jmix.search.min-prefix-length>> 的词项始终返回空结果。

默认值：`true`
