= Search Properties

[[jmix.search.changedEntitiesIndexingEnabled]]
== jmix.search.changed-entities-indexing-enabled

Defines whether automatic indexing of xref:config-options.adoc#tracking-changes[changed entities] is enabled.

Default value: `true`

[[jmix.search.defaultSearchStrategy]]
== jmix.search.default-search-strategy

Name of the default xref:search-in-ui.adoc#search-strategies[search strategy].

Default value: `anyTermAnyField`

[[jmix.search.enqueueIndexAllOnStartupIndexRecreationEnabled]]
== jmix.search.enqueue-index-all-on-startup-index-recreation-enabled

Defines whether all entity instances related to indexes created or recreated on startup should be enqueued automatically. See also xref:config-options.adoc#existing-data-indexing[Existing Data Indexing].

Default value: `true`

[[jmix.search.enqueueIndexAllOnStartupIndexRecreationEntities]]
== jmix.search.enqueue-index-all-on-startup-index-recreation-entities

Defines the list of entities that should be automatically enqueued on startup in case of index recreation. Empty list means all indexed entities. See also xref:config-options.adoc#existing-data-indexing[Existing Data Indexing].

Default value: none

[[jmix.search.enqueueingSessionProcessingCron]]
== jmix.search.enqueueing-session-processing-cron

http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html[Cron expression^] used by the default Enqueueing Session processing Quartz xref:indexing-queue.adoc#default-quartz-configuration[scheduling configuration].

Default value: `0/5 * * * * ?`

[[jmix.search.indexingQueueProcessingCron]]
== jmix.search.indexing-queue-processing-cron

http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html[Cron expression^] used by the default Indexing Queue processing Quartz xref:indexing-queue.adoc#default-quartz-configuration[scheduling configuration].

Default value: `0/5 * * * * ?`

[[jmix.search.indexSchemaManagementStrategy]]
== jmix.search.index-schema-management-strategy

The way of index schema synchronization. See xref:config-options.adoc#indexes-creation[Index Creation] for more details.

Default value: `create-or-recreate`

[[jmix.search.maxPrefixLength]]
== jmix.search.max-prefix-length

Defines the maximum length for generated prefix terms used in xref:search:index-definitions.adoc#extended-search["starts with"] search.

The edge N-gram analyzer creates prefixes from <<jmix.search.minPrefixLength,min-prefix-length>> to this maximum value for each indexed word. Longer maximum values:

* Improve search accuracy for longer prefixes.
* Increase index size due to more stored prefixes.
* Reduce performance of wildcard fallback queries.

Default value: `8`.

[[jmix.search.maxSearchPageCount]]
== jmix.search.max-search-page-count

Sets the maximum number of result pages.

Default value: `100`

[[jmix.search.minPrefixLength]]
== jmix.search.min-prefix-length

Defines the minimum length for generated prefix terms used in xref:search:index-definitions.adoc#extended-search["starts with"] search.

The edge N-gram analyzer only creates prefixes starting from this length. Shorter minimum values:

* Enable matching of very short search terms.
* Significantly increase index size (more prefixes generated).
* May impact performance due to numerous small prefixes.

Default value: `3`

[[jmix.search.processQueueBatchSize]]
== jmix.search.process-queue-batch-size

Sets the number of queue items processed in a single batch.

Default value: `100`

[[jmix.search.reindexEntityEnqueueBatchSize]]
== jmix.search.reindex-entity-enqueue-batch-size

Sets the number of entity instances enqueued in a single batch during the entity reindex process.

Default value: `100`

[[jmix.search.searchIndexNamePrefix]]
== jmix.search.search-index-name-prefix

Prefix for the search index name. Index naming template: `<prefix><entity_name>`. See xref:getting-started.adoc#configure-index-naming[Configure Index Naming].

Default value: `search_index_`

[[jmix.search.searchReloadEntitiesBatchSize]]
== jmix.search.search-reload-entities-batch-size

Defines the batch size for post-search entity processing, for example, when results are filtered after search due to the row-level security policies, or when entities are fetched from search results with their fetch plans. See xref:search-api.adoc#security-and-pagination[Access Control and Pagination].

Default value: `100`

[[jmix.search.searchResultPageSize]]
== jmix.search.search-result-page-size

Sets the maximum number of objects displayed on a single page of search results.

Default value: `100`

[[jmix.search.useDefaultEnqueueingSessionProcessingQuartzConfiguration]]
== jmix.search.use-default-enqueueing-session-processing-quartz-configuration

Defines whether the default Enqueueing Session processing Quartz  xref:indexing-queue.adoc#default-quartz-configuration[scheduling configuration] is used.

Default value: `true`

[[jmix.search.useDefaultIndexingQueueProcessingQuartzConfiguration]]
== jmix.search.use-default-indexing-queue-processing-quartz-configuration

Defines whether the default Indexing Queue processing Quartz  xref:indexing-queue.adoc#default-quartz-configuration[scheduling configuration] is used.

Default value: `true`

[[jmix.search.server.url]]
== jmix.search.server.url

Defines the URL of the Elasticsearch/OpenSearch service.

Default value: `localhost:9200`

[[jmix.search.server.login]]
== jmix.search.server.login

Defines login for basic authentication.

Default value: none

[[jmix.search.server.password]]
== jmix.search.server.password

Defines password for basic authentication.

Default value: none

[[jmix.search.server.bulkRequestRefreshPolicy]]
== jmix.search.server.bulk-request-refresh-policy

Defines refresh policy that should be used with bulk requests to search service.

Refresh makes recent changes available for searching.

* `false` - bulk request will not cause refresh.
Changes made by this request will be visible after refresh is performed via another cause: an explicit refresh operation or periodic refresh (by default, every second).
Recommended policy. Use other policies only if you must have the changes made by a request visible synchronously with the request.
* `true` - refresh will be performed immediately after request execution.
_This mode should be used only after careful verification because it can lead to performance issues._
* `wait_for` - request will not cause refresh but will wait for it to be performed via another cause.
Response will be sent back after refresh is done.

Default value: `false`

[[jmix.search.server.ssl.certificateLocation]]
== jmix.search.server.ssl.certificate-location

Defines location of certificate for connection to search service (if required).

Location is handled according to the rules of `io.jmix.core.Resources`.

Default value: none

[[jmix.search.server.ssl.certificateAlias]]
== jmix.search.server.ssl.certificate-alias

Defines the alias that will be used to store the certificate in the key store.

Default value: `es_client_ca`

[[jmix.search.server.ssl.certificateFactoryType]]
== jmix.search.server.ssl.certificate-factory-type

Defines type of certificate factory.

Default value: `X.509`

[[jmix.search.server.ssl.keyStoreType]]
== jmix.search.server.ssl.key-store-type

Defines type of key store.

Default value: `pkcs12`

[[jmix.search.wildcardPrefixQueryEnabled]]
== jmix.search.wildcard-prefix-query-enabled

Enables wildcard query fallback when the search term length exceeds <<jmix.search.maxPrefixLength,jmix.search.max-prefix-length>>.

When `true`, performs wildcard query for terms longer than max prefix length; when `false`, returns no results for such terms.

NOTE: Terms shorter than <<jmix.search.minPrefixLength,jmix.search.min-prefix-length>> always return empty results regardless of this setting.

Default value: `true`