= Application Settings

Это дополнение предоставляет простой API и пользовательский интерфейс для работы с изменяемыми значениями различных типов, хранящимися в базе данных. Эти значения обычно используются как параметры различного функционала приложения.

[[installation]]
== Установка

Для автоматической установки через Jmix Marketplace следуйте инструкциям в разделе xref:ROOT:add-ons.adoc#installation[Дополнения].

Для ручной установки добавьте следующие зависимости в ваш `build.gradle`:

[source,groovy,indent=0]
----
implementation("io.jmix.appsettings:jmix-appsettings-starter")
implementation("io.jmix.appsettings:jmix-appsettings-flowui-starter")
----

// todo flowui
// [source,groovy,indent=0]
// ----
// include::example$/ex1/build.gradle[tags=dependencies]
// ----

[[usage]]
== Использование

Чтобы определить некоторые настройки, создайте сущность, расширяющую класс `io.jmix.appsettings.entity.AppSettingsEntity`:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/appsettings/ex1/entity/CustomerSettings.java[tags=settings-entity]
----

После этого вы сможете устанавливать значения для атрибутов этой сущности с помощью экрана *Application settings*.

Для получения настроек в коде приложения используйте бин `AppSettings`, например:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/appsettings/ex1/screen/customer/CustomerEdit.java[tags=app-settings]
----