= Application Settings

This add-on provides a simple API and UI to work with mutable values of different types stored in database. These values are usually used as parameters of different functionality of the application.

[[installation]]
== Installation

For automatic installation through Jmix Marketplace, follow instructions in the xref:ROOT:add-ons.adoc#installation[Add-ons] section.

For manual installation, add the following dependencies to your `build.gradle`:

[source,groovy,indent=0]
----
implementation("io.jmix.appsettings:jmix-appsettings-starter")
implementation("io.jmix.appsettings:jmix-appsettings-flowui-starter")
----

include::ROOT:single-menu-note.adoc[]

// todo flowui
// [source,groovy,indent=0]
// ----
// include::example$/ex1/build.gradle[tags=dependencies]
// ----

[[usage]]
== Usage

To define some settings, create an entity extending the `io.jmix.appsettings.entity.AppSettingsEntity` class:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/appsettings/ex1/entity/CustomerSettings.java[tags=settings-entity]
----

After that, you will be able to set values for this entity attributes using the *Application settings* view.

To get settings in the application code, use the `AppSettings` bean, for example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/appsettings/ex1/screen/customer/CustomerEdit.java[tags=app-settings]
----
