= Свойства экспорта таблиц

[[jmix.gridexport.default-columns-to-export]]
== jmix.gridexport.default-columns-to-export

Определяет поведение выбора колонок по умолчанию для функциональности экспорта таблиц. Эта настройка определяет, какие колонки включаются в xref:grid-export:actions.adoc#columns-export[экспорт], когда не предоставлена другая, более специфичная конфигурация.

Возможные значения: `ALL_COLUMNS`, `VISIBLE_COLUMNS`.

Значение по умолчанию: `VISIBLE_COLUMNS`.

[[jmix.gridexport.default-export-modes]]
== jmix.gridexport.default-export-modes

Определяет набор опций по умолчанию для диалогового окна xref:actions.adoc[ExportAction].

Значение по умолчанию: `ALL_ROWS,CURRENT_PAGE,SELECTED_ROWS`.

[[jmix.gridexport.export-all-batch-size]]
== jmix.gridexport.export-all-batch-size

Определяет размер пакета при экспорте всех записей.

Значение по умолчанию: `1000`.

Например:

[source,properties]
----
jmix.gridexport.export-all-batch-size = 2000
----

[[jmix.gridexport.export-all-pagination-strategy]]
== jmix.gridexport.export-all-pagination-strategy

Определяет стратегию пагинации, используемую при xref:grid-export:actions.adoc#export-modes[экспорте] всех сущностей.

Возможные значения:

* `keyset`: Извлекает сущности на основе сортировки по первичному ключу. Следующая страница начинается после последней сущности предыдущей страницы.
* `limit-offset`: Извлекает сущности в том же порядке, в котором они хранятся. Использует два параметра: `offset` (начальный индекс записи) и `limit` (количество записей на странице).

Значение по умолчанию: `keyset`.

[[jmix.gridexport.excel.use-sxssf]]
== jmix.gridexport.excel.use-sxssf

Определяет, использовать ли потоковый POI SXSSF API для построения XLSX файлов.

Значение по умолчанию: `true`.