= 通用属性
:page-aliases: vcl/xml.adoc

[[allowedCharPattern]]
== allowedCharPattern

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field/#constraints" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置客户端侧用于检查用户输入格式的正则表达式。设置的模式内容必须是合法的 JavaScript 正则表达式，用以匹配单一字符，而非字符序列。

例如，如需允许用户输入数字和短横，可以使用 `"[0-9/]"` 模式。

[[alignItems]]
== alignItems

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/align-items" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

定义内部组件在交叉轴方向上的对齐方式。支持：

* START - 内部组件放置于交叉轴的开始位置。
* END - 内部组件放置于交叉轴的结束位置。
* CENTER - 内部组件放置于交叉轴的中间位置。
* STRETCH - *交叉轴方向未定义尺寸* 的内部组件拉伸至容器尺寸。
* BASELINE - 内部组件放置于容器的基线位置。仅对 `flex-direction: row` 有效。
* AUTO - 组件继承父容器的 <<alignItems,alignItems>> 值，若无父容器，则为 "stretch"。

参阅布局规则部分的 xref:vc/layout-rules.adoc#align-items[使用示例]。

[[alignSelf]]
== alignSelf

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/align-self" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

定义容器内单一组件本身在交叉轴方向上的对齐方式，覆盖容器的 <<alignItems, alignItems>> 属性。支持：

* START - 组件放置于交叉轴的开始位置。
* END - 组件放置于交叉轴的结束位置。
* CENTER - 组件放置于交叉轴的中间位置。
* STRETCH - *交叉轴方向未定义尺寸* 的组件拉伸至容器尺寸。
* BASELINE - 组件放置于容器的基线位置。仅对 `flex-direction: row` 有效。
* AUTO - 组件继承父容器的 <<alignItems,alignItems>> 值，若无父容器，则为 "stretch"。

参阅布局规则部分的 xref:vc/layout-rules.adoc#align-self[使用示例]。

[[ariaLabel]]
== ariaLabel

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

设置一个单独的用于辅助功能的隐形标签，比如用于屏幕阅读器。

[[ariaLabelledBy]]
== ariaLabelledBy

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

引用另一个组件，为可视化组件设置可访问的名称。优先于提供辅助名称的所有其他方法，包括 <<ariaLabel, ariaLabel>> 和组件的内部文本。

[[autocapitalize]]
== autocapitalize

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

设置 `autocapitalize` HTML 属性。定义是否自动将用户输入的文字转换成大写。

[[autocomplete]]
== autocomplete

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#autocomplete" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

设置 `autocomplete` HTML 属性。定义该组件的值是否可由浏览器自动填充。

[[autocorrect]]
== autocorrect

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#autocorrect" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

设置字段的 `autocorrect` HTML 属性。

NOTE: 仅支持 Safari。

[[autofocus]]
== autofocus

指定该组件在页面加载后即获得输入焦点。

属性值可以是 `true` 或 `false`。默认情况下，没有组件自动获得焦点。

[[classNames]]
== classNames

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins/#hasstyle-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

为组件添加 CSS 类名。

可用的 CSS 类名有以下几种来源：

* `com.vaadin.flow.theme.lumo.LumoUtility` 类及其内部类。
* `io.jmix.flowui.themes.JmixLumoUtility` 类。
* 任何带 `@ThemeUtilityClasses` 注解的自定义类。可以在自己的扩展组件或应用程序源代码中提供共享类名。

Jmix Studio 提供对输入 `classNames` 属性的增强支持，在 UI 组件属性中输入时，会显示 xref:studio:view-designer.adoc#classNames-editor[ClassNames 向导]。

[[clearButtonVisible]]
== clearButtonVisible

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field/#clear-button" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置是否显示控件的清除按钮。

[[clickShortcut]]
== clickShortcut

定义触发组件点击事件的 xref:keyboard-shortcuts.adoc[键盘快捷键]。组件必须有处理点击事件的相应方法，否则快捷键不会有任何效果。

[[colspan]]
== colspan

设置 xref:vc/layouts/formLayout.adoc[] 中组件能占据的列宽。

默认值：`1`。

[[css]]
== css

为 UI 组件提供声明式设置 CSS 属性的方法。

下面的示例中，通过 `css` 属性为 xref:flow-ui:vc/components/textField.adoc[textField] 组件提供了内嵌的样式，包括设置背景色、边框、内边距以及字体大小：

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/cssattr/css-attr-view.xml[tags=textField]
----

下面的示例中，通过 `css` 属性为 xref:flow-ui:vc/components/button.adoc[button] 组件提供了内嵌的样式

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/cssattr/css-attr-view.xml[tags=button]
----

[[dataContainer]]
== dataContainer

在视图 XML 描述的 `data` 部分设置一个数据容器。

当设置 `dataContainer` 为某个 xref:data/instance-container.adoc[] 时，需要同时设置 <<property>> 属性。

[[datatype]]
== datatype

设置组件内容的 xref:data-model:datatype.adoc[数据类型]。支持：

* `boolean`
* `byteArray`
* `char`
* `date`
* `dateTime`
* `decimal`
* `double`
* `fileRef`
* `int`
* `localDate`
* `localDateTime`
* `localTime`
* `long`
* `offsetDateTime`
* `offsetTime`
* `string`
* `time`
* `uri`
* `uuid`

当组件不关联实体属性时需要设置该参数。否则数据类型由实体属性类型决定。

[[dateFormat]]
== dateFormat

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/date-picker#date-format" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

为组件支持的日期值设置格式偏好。默认情况下，使用当前 locale 的日期格式。

[[enabled]]
== enabled

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/enabled-state" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

显式设置组件是否启用。

[[errorMessage]]
== errorMessage

设置组件的错误消息。

[[flexGrow]]
== flexGrow

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/flex-grow" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

设置此组件的 flex grow。设置为 `0` 时，组件宽度固定。

[[focusShortcut]]
== focusShortcut

定义组件获得焦点的 xref:keyboard-shortcuts.adoc[键盘快捷键]。

[[height]]
== height

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins/#hassize-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置组件的高度。

高度值需要使用浏览器支持的值，例如，`"100px"` 或 `"2.5em"`。

请参考布局规则的 xref:vc/layout-rules.adoc#component-sizes[用例]。

[[helperText]]
== helperText

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field#basic-features" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置组件的说明信息，例如，可以告诉用户该组件支持什么类型的值。

[[id]]
== id

组件的标识符。

推荐根据 Java 标识符规则创建组件标识符，使用驼峰命名法，例如：`userGrid`、`filterPanel`。任何组件都可以指定 `id` 属性，要求在同一视图内唯一。

[[invalid]]
== invalid

根据字段验证的结果设置字段的无效状态。

* 如果 `invalid=false` 无论验证结果如何，该字段有效。
* 如果 `invalid=true` 且验证通过时，该字段有效。

[[justifySelf]]
== justifySelf

控制组件在其网格单元格内沿内轴（行轴）的水平对齐方式。对应于 CSS 的 https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Properties/justify-self[justify-self^] 属性。

默认值为 `AUTO`。

适用于版本 2.7.2+ 的项目。

[[label]]
== label

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field#basic-features" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置组件的标签。

该属性的值可以是一个纯文本，或 xref:localization:message-bundles.adoc[消息包] 中的一个键值。如果是键值，需要以 `msg://` 开头。

[[maxHeight]]
== maxHeight

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/max-height" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins/#hassize-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置组件的 `max-height` CSS 属性。高度值需要使用浏览器支持的值，例如，`"100px"` 或 `"2.5em"`。

请参考布局规则的 xref:vc/layout-rules.adoc#component-sizes[用例]。

[[maxLength]]
== maxLength

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#maxlength" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field#constraints" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置字段型组件允许输入的最大字符数。

[[maxWidth]]
== maxWidth

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/max-width" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins/#hassize-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置组件的 `max-width` CSS 属性。宽度值需要使用浏览器支持的值，例如，`"100px"` 或 `"2.5em"`。

请参考布局规则的 xref:vc/layout-rules.adoc#component-sizes[用例]。

[[metaClass]]
== metaClass

为展示实体的组件设置一个实体类，例如 xref:vc/components/dataGrid.adoc[dataGrid] 或 xref:vc/components/entityComboBox.adoc[]。

如果组件不与某个 xref:data/data-containers.adoc[数据容器] 关联，则需要设置该属性。否则，实体类型由数据容器决定。

[[minHeight]]
== minHeight

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/min-height" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins/#hassize-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置组件的 `min-height` CSS 属性。高度值需要使用浏览器支持的值，例如，`"100px"` 或 `"2.5em"`。

请参考布局规则的 xref:vc/layout-rules.adoc#component-sizes[用例]。


[[minLength]]
== minLength

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#minlength" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field#constraints" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置字段型组件允许输入的最小字符数。

[[minWidth]]
== minWidth

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/min-width" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins/#hassize-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置组件的 `min-width` CSS 属性。宽度值需要使用浏览器支持的值，例如，`"100px"` 或 `"2.5em"`。

请参考布局规则的 xref:vc/layout-rules.adoc#component-sizes[用例]。

[[overlayClass]]
== overlayClass

设置在 overlay 元素上的 CSS 类名列表。

[[pattern]]
== pattern

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#pattern" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field/#pattern" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

客户端输入时，设置一个输入值需要符合的正则表达式。表达式必须是有效的 JavaScript 正则表达式，用于匹配整个值，而非部分值。

[[placeholder]]
== placeholder

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field/#placeholder" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

占位符。用来提示用户组件中可以输入什么内容。

[[property]]
== property

设置一个 xref:data-model:entities.adoc[实体] 属性的名称，可视化组件会显示或者编辑该属性值。

`property` 需要与 <<dataContainer,dataContainer>> 属性同时使用。

[[readOnly]]
== readOnly

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field#read-only-disabled" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置组件是否是只读模式。

[[required]]
== required

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field#constraints" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

表示该控件为必填项。

使用 xref:flow-ui:ui-properties.adoc#jmix.ui.component.immediate-required-validation-enabled[jmix.ui.component.immediate-required-validation-enabled] 应用程序属性控制必填字段的高亮时机。

[[requiredIndicatorVisible]]
== requiredIndicatorVisible

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field#constraints" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置是否显示必填指示符。

[[requiredMessage]]
== requiredMessage

与 <<required,required>> 属性同时使用。当组件没有值时，则展示该消息。

属性值可以是一个消息本身，或者 xref:localization:message-bundles.adoc[消息包] 中的键值，示例：`requiredMessage="msg://infoTextField.requiredMessage"`。

[[step]]
== step

自定义 xref:vc/components/timePicker.adoc[] 和 xref:vc/components/dateTimePicker.adoc[] 组件中选择时间的间隔（分钟）。默认值为 `60`。

[[tabIndex]]
== tabIndex

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

设置组件的 `tabindex` HTML 属性。该属性控制该元素是否可以获得焦点，以及通过键盘 Tab 键进行跳转时的位置：

* 负值（通常设置 `tabindex = -1`），表示组件可以获得焦点，但是不能通过键盘顺序导航访问到。
* 0，表示组件可以通过键盘顺序导航访问，但是访问顺序是按照 HTML 中 dom 的顺序定义。
* 正值，表示组件可以通过键盘顺序导航访问，并且按照该值定义的顺序进行访问。即，`tabindex = 4` 的组件会在 `tabindex = 5` 的组件之前，`tabindex = 3` 的组件之后。如果多个组件拥有相同的顺序值，则按照 HTML 中 dom 的顺序。

[[text]]
== text

设置组件的文本内容。

该属性的值可以是文本本身，或者是 xref:localization:message-bundles.adoc[消息包] 的一个键值。如果是消息包键值，则需要使用 `msg://` 前缀。

有两种方式设置键值：

* 短键值 - 此时会在当前视图的消息组中查找该键值。例如，`msg://infoField.caption`

* 包含消息组的全键值，例如，`msg://com.company.sample.view.user/infoField.caption`

[[themeNames]]
== themeNames

为组件添加一个主题。

[[title]]
== title

该属性的值会设置到网页的 https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title[title^] 和 https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label[aria-label^] HTML 属性。大多数组件将这个作为 tooltip 使用。

[[value]]
== value

设置组件的值。如果新值与 `getValue()` 的值不同，则触发值变更事件。如果值非法，则抛出 `IllegalArgumentException`。

[[valueChangeMode]]
== valueChangeMode

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/tools/collaboration/components/collaboration-binder/#eagerly-propagate-values" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

为组件设置值更改模式。该模式定义了值更改的发送频率：

* `EAGER` – 每次用户修改时（例如每个键盘输入）。
* `LAZY` – 用户停止输入超过超时时间后。
* `TIMEOUT` – 在输入过程中，每个超时间隔就发送一次。
* `ON_BLUR` – 当组件失去焦点时。
* `ON_CHANGE` – 当值通过更改操作提交时。

对于文本输入，默认情况下通常不会在每个键盘输入时发送更新。
使用 `EAGER` 支持即时验证、实时搜索等类似的响应式行为。
使用 <<valueChangeTimeout>> 配置 `LAZY` 和 `TIMEOUT`。

[[valueChangeTimeout]]
== valueChangeTimeout

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/tools/collaboration/components/collaboration-binder/#eagerly-propagate-values" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置 <<valueChangeMode>> 的超时时限。单位为毫秒。

该属性仅影响延迟模式（`LAZY`、`TIMEOUT`），在即时模式或基于操作的提交模式（`EAGER`、`ON_BLUR`、`ON_CHANGE`）中，会忽略该设置。

[[visible]]
== visible

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/basic-features/#visibility" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置组件的可见性。

[[weekNumbersVisible]]
== weekNumbersVisible
++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/date-picker#week-numbers" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置日历的弹窗中是否显示第几周的信息。仅当设置星期一为每周开始时有效。

[[whiteSpace]]
== whiteSpace

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/white-space" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

设置 `white-space` CSS 属性值。

默认值：`NORMAL`。

[[width]]
== width

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins/#hassize-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

设置组件宽度。宽度值需要使用浏览器支持的值，例如，`"100px"` 或 `"2.5em"`。

请参考布局规则的 xref:vc/layout-rules.adoc#component-sizes[用例]。
