= Common Attributes
:page-aliases: vcl/xml.adoc

[[allowedCharPattern]]
== allowedCharPattern

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field/#constraints" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Sets a regular expression for the user input to check to the client-side. The allowed char pattern must be a valid JavaScript Regular Expression that matches a single character, not the sequence of characters.

For example, to allow entering only numbers and slash character, use `"[0-9/]"` pattern.

[[alignItems]]
== alignItems

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/align-items" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

Defines how items are aligned on the cross axis. Possible values:

* START – items are placed at the start of the cross axis.
* END – items are placed at the end of the cross axis.
* CENTER – items are centered in the cross axis.
* STRETCH – items with *undefined size along the cross axis* are stretched to fit the container.
* BASELINE – items are positioned at the baseline of the container. Works for `flex-direction: row` only
* AUTO – the item inherits its parent container’s <<alignItems, alignItems>> value, or "stretch" if it has no parent container.

For xref:vc/layout-rules.adoc#align-items[usage examples] visit the Layout Rules section.

[[alignSelf]]
== alignSelf

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/align-self" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

Aligns individual items inside the container overriding <<alignItems, alignItems>> attribute. Possible values:

* START – item is placed at the start of the cross axis.
* END – item is placed at the end of the cross axis.
* CENTER – item is centered on the cross axis.
* STRETCH – item with *undefined size along the cross axis* is stretched to fit the container.
* BASELINE – item is positioned at the baseline of the container. Works for `flex-direction: row` only.
* AUTO – item inherits its parent container’s <<alignItems, alignItems>> value, or "stretch" if it has no parent container.

For xref:vc/layout-rules.adoc#align-self[usage examples] visit the Layout Rules section.

[[ariaLabel]]
== ariaLabel

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

Sets a separate, visually hidden label for accessibility technologies, such as screen readers.

[[ariaLabelledBy]]
== ariaLabelledBy

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

Refers to another component to set an accessible name for a visual component. Takes precedence over all other methods of providing an accessible name, including <<ariaLabel, ariaLabel>>, and the component's inner text.

[[autocapitalize]]
== autocapitalize

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

Sets the `autocapitalize` HTML attribute. It is used to define whether the text entered by the user should be automatically capitalized or not.

[[autocomplete]]
== autocomplete

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#autocomplete" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

Sets the `autocomplete` HTML attribute for indicating whether the value of this component can be automatically completed by the browser.

[[autocorrect]]
== autocorrect

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#autocorrect" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

Sets the `autocorrect` HTML attribute for the field.

NOTE: It is supported only in Safari.

[[autofocus]]
== autofocus

Specifies that the component should have input focus when the page loads.

Possible values are `true`, `false`. By default, all components are not focused.

[[classNames]]
== classNames

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins/#hasstyle-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Adds CSS class names to the component.

Available class names are obtained from the following sources:

* `com.vaadin.flow.theme.lumo.LumoUtility` class and its nested classes.
* `io.jmix.flowui.themes.JmixLumoUtility` class.
* Any custom class annotated with `@ThemeUtilityClasses`. You can provide shared class names in your own add-ons and in the application sources.

Jmix Studio provides enhanced support for entering `classNames` in UI component properties via the xref:studio:view-designer.adoc#classNames-editor[ClassNames Wizard].

[[clearButtonVisible]]
== clearButtonVisible

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field/#clear-button" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Sets the visibility of the button which clears the field.

[[clickShortcut]]
== clickShortcut

Defines the xref:keyboard-shortcuts.adoc[keyboard shortcut] to fire a click event associated with the component. The component must have an appropriate handler to process the click event, otherwise the key combination will not have any effect.

[[colspan]]
== colspan

Sets the number of columns that the component should occupy if it is placed in a xref:vc/layouts/formLayout.adoc[].

Default is `1`.

[[css]]
== css

Provides a declarative way to set CSS properties for UI components.

In this example, the `css` attribute is used to apply inline styles to the xref:flow-ui:vc/components/textField.adoc[textField] component, including setting the background color, border, padding, and font size:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/cssattr/css-attr-view.xml[tags=textField]
----

In the example below, the `css` attribute is used to provide inline CSS for the xref:flow-ui:vc/components/button.adoc[button] component.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/cssattr/css-attr-view.xml[tags=button]
----

[[dataContainer]]
== dataContainer

Sets a data container defined in the `data` section of the view XML descriptor.

If you set an xref:data/instance-container.adoc[] in the `dataContainer` attribute, you should also set the <<property>> attribute.

[[datatype]]
== datatype

Sets a xref:data-model:datatype.adoc[datatype] of the component's content. Possible values:

* `boolean`
* `byteArray`
* `char`
* `date`
* `dateTime`
* `decimal`
* `double`
* `fileRef`
* `int`
* `localDate`
* `localDateTime`
* `localTime`
* `long`
* `offsetDateTime`
* `offsetTime`
* `string`
* `time`
* `uri`
* `uuid`

Set this attribute if the component is not linked to an entity attribute. Otherwise, the data type is defined by the entity attribute type.

[[dateFormat]]
== dateFormat

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/date-picker#date-format" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Sets a preferred format for date values in the component. By default, the current locale date format is used.

[[enabled]]
== enabled

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/enabled-state" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Sets the component explicitly disabled or enabled.

[[errorMessage]]
== errorMessage

Sets an error message to the component.

[[flexGrow]]
== flexGrow

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/flex-grow" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

Sets the flex grow factor for this component. When set to `0`, the width is fixed.

[[focusShortcut]]
== focusShortcut

Defines the xref:keyboard-shortcuts.adoc[keyboard shortcut] that is used to place focus on this component.

[[height]]
== height

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins/#hassize-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Sets the height of the component.

The height should be in a format understood by the browser, for example, `"100px"` or `"2.5em"`.

For xref:vc/layout-rules.adoc#component-sizes[usage examples] visit the Layout Rules section.

[[helperText]]
== helperText

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field#basic-features" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Defines a text adjacent to the component. It can be used, for example, to inform users which values the component expects.

[[id]]
== id

An identifier of the component.

It is recommended to create identifiers according to the rules for Java identifiers and use camelСase, for example: `userGrid`, `filterPanel`. The `id` attribute can be specified for any component and should be unique within a view.

[[invalid]]
== invalid

Sets an invalid state to the field considering the result of the field validation.

* If `invalid=false`, the field is valid regardless of the validation result.
* If `invalid=true`, the field is valid only if the validation is passed successfully.

[[justifySelf]]
== justifySelf

Controls the horizontal alignment of a component within its grid cell along the inline (row) axis. This corresponds to the CSS https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Properties/justify-self[justify-self^] property.

Default value is `AUTO`.

Available for projects with version 2.7.2+.

[[label]]
== label

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field#basic-features" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Specifies the label of the component.

The attribute value can either be the text itself or a key in the xref:localization:message-bundles.adoc[message bundle]. In case of a key, the value should begin with the `msg://` prefix.

[[maxHeight]]
== maxHeight

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/max-height" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins/#hassize-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Sets the `max-height` CSS property of the component. The height should be in a format understood by the browser, for example, `"100px"` or `"2.5em"`.

For xref:vc/layout-rules.adoc#component-sizes[usage examples] visit the Layout Rules section.

[[maxLength]]
== maxLength

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#maxlength" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field#constraints" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Sets the maximum number of characters a field accepts.

[[maxWidth]]
== maxWidth

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/max-width" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins/#hassize-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Sets the `max-width` CSS property of the component. The width should be in a format understood by the browser, for example, `"100px"` or `"2.5em"`.

For xref:vc/layout-rules.adoc#component-sizes[usage examples] visit the Layout Rules section.

[[metaClass]]
== metaClass

Defines an entity class for components displaying entities, like xref:vc/components/dataGrid.adoc[dataGrid] or xref:vc/components/entityComboBox.adoc[].

Set this attribute if the component is not linked to a xref:data/data-containers.adoc[data container]. Otherwise, the entity type is defined by the data container.

[[minHeight]]
== minHeight

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/min-height" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins/#hassize-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Sets the `min-height` CSS property of the component. The height should be in a format understood by the browser, for example, `"100px"` or `"2.5em"`.

For xref:vc/layout-rules.adoc#component-sizes[usage examples] visit the Layout Rules section.


[[minLength]]
== minLength

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#minlength" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field#constraints" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Sets the minimum number of characters a field accepts.

[[minWidth]]
== minWidth

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/min-width" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins/#hassize-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Sets the `min-width` CSS property of the component. The width should be in a format understood by the browser, for example, `"100px"` or `"2.5em"`.

For xref:vc/layout-rules.adoc#component-sizes[usage examples] visit the Layout Rules section.

[[overlayClass]]
== overlayClass

Specifies a list of CSS class names to set on the overlay element.

[[pattern]]
== pattern

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#pattern" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field/#pattern" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Sets a regular expression for the value to check to the client-side. The pattern must be a valid JavaScript Regular Expression that matches the entire value, not just some subset.

[[placeholder]]
== placeholder

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field/#placeholder" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Defines a hint to the user of what can be entered in the component.

[[property]]
== property

Sets the name of an xref:data-model:entities.adoc[entity] attribute, which value will be displayed and edited by this visual component.

`property` is always used together with the <<dataContainer,dataContainer>> attribute.

[[readOnly]]
== readOnly

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field#read-only-disabled" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Specifies whether the component is in read-only mode.

[[required]]
== required

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field#constraints" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Indicates that this field requires a value.

Use the xref:flow-ui:ui-properties.adoc#jmix.ui.component.immediate-required-validation-enabled[jmix.ui.component.immediate-required-validation-enabled] application property to control when the required field is highlighted.

[[requiredIndicatorVisible]]
== requiredIndicatorVisible

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field#constraints" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Sets the required indicator visibility.

[[requiredMessage]]
== requiredMessage

Used together with the <<required,required>> attribute. Sets a message that will be displayed to a user when the component has no value.

The attribute can contain a message or a key from xref:localization:message-bundles.adoc[message bundle], for example: `requiredMessage="msg://infoTextField.requiredMessage"`

[[step]]
== step

Sets a custom time interval, in minutes, between values available for selection in the xref:vc/components/timePicker.adoc[] and xref:vc/components/dateTimePicker.adoc[] components. The default value is `60`.

[[tabIndex]]
== tabIndex

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

Sets the `tabindex` HTML attribute in the component. The attribute indicates if its element can be focused, and if/where it participates in sequential keyboard navigation:

* A negative value (usually `tabindex = -1` means that the component should be focusable, but should not be reachable via sequential keyboard navigation.
* `tabindex = 0` means that the component should be focusable in sequential keyboard navigation, but its order is defined by the document's source order.
* A positive value means the component should be focusable in sequential keyboard navigation, with its order defined by the value of the number. That is, `tabindex = 4` would be focused before `tabindex = 5`, but after `tabindex = 3`. If multiple components share the same positive `tabindex` value, their order relative to each other follows their position in the document source.

[[text]]
== text

Sets a text content of the component.

The attribute value can either be the text itself or a key in the xref:localization:message-bundles.adoc[message bundle]. In case of a key, the value should begin with the `msg://` prefix.

There are two ways of setting a key:

* A short key - in this case the message will be searched in the message group of the current view. For example: `msg://infoField.caption`

* Full key including message group, for example: `msg://com.company.sample.view.user/infoField.caption`

[[themeNames]]
== themeNames

Adds a theme to the component.

[[title]]
== title

The value of the attribute is set to the https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title[title^] and https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label[aria-label^] HTML attributes. Most components interpret it as a tooltip.

[[value]]
== value

Sets the value of the component. If the new value is not equal to `getValue()`, fires a value change event. May throw `IllegalArgumentException` if the value is not acceptable.

[[valueChangeMode]]
== valueChangeMode

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/tools/collaboration/components/collaboration-binder#eagerly-propagate-values" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Sets a value change mode for the component. The mode defines how often values changes are sent:

* `EAGER` – on every user change (for example, each keystroke).
* `LAZY` – after the user stops typing for the timeout period.
* `TIMEOUT` – repeatedly while typing, using the timeout interval.
* `ON_BLUR` – when the component loses focus.
* `ON_CHANGE` – when the value is committed by a change action.

For text inputs, updates are typically not sent on each keystroke by default.
Use `EAGER` for instant validation, live search, and similar reactive behavior.
Use <<valueChangeTimeout>> to configure `LAZY` and `TIMEOUT`.

[[valueChangeTimeout]]
== valueChangeTimeout

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/tools/collaboration/components/collaboration-binder#eagerly-propagate-values" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Sets the timeout (in milliseconds) used by <<valueChangeMode>>.

This attribute only affects delayed modes (`LAZY`, `TIMEOUT`) and is ignored by immediate or commit-based modes (`EAGER`, `ON_BLUR`, `ON_CHANGE`).

[[visible]]
== visible

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/basic-features/#visibility" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Sets visibility of the component.

[[weekNumbersVisible]]
== weekNumbersVisible
++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/date-picker#week-numbers" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Specifies whether week numbers are visible in the calendar overlay. This works only when the first day of week is set to Monday.

[[whiteSpace]]
== whiteSpace

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/white-space" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

Sets the `white-space` CSS property.

Default value is `NORMAL`.

[[width]]
== width

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins/#hassize-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Sets the width of the component. The width should be in a format understood by the browser, for example, `"100px"` or `"2.5em"`.

For xref:vc/layout-rules.adoc#component-sizes[usage examples] visit the Layout Rules section.
