= Общие атрибуты
:page-aliases: vcl/xml.adoc

[[allowedCharPattern]]
== allowedCharPattern

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field/#constraints" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Устанавливает регулярное выражение для ввода данных пользователя на стороне клиента. Оно должно быть допустимым регулярным выражением JavaScript, которое соответствует одному символу, а не последовательности символов.

Например, чтобы разрешить ввод только цифр и косой черты, используйте `"[0-9/]"` шаблон.

[[alignItems]]
== alignItems

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/align-items" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

Определяет расположение элементов относительно поперечной оси. Возможные значения:

* START – элементы размещаются в начале поперечной оси.
* END – элементы размещаются в конце поперечной оси.
* CENTER – элементы центрируются в поперечной оси.
* STRETCH – элементы с *неопределенным размером вдоль поперечной оси* растягиваются, чтобы соответствовать контейнеру.
* BASELINE – элементы размещаются на базовой линии контейнера. Работает только для `flex-direction: row`.
* AUTO – элемент наследует свойство <<alignItems,alignItems>> своего родительского контейнера или "stretch", если у него нет родительского контейнера.

Вы можете найти xref:vc/layout-rules.adoc#align-items[примеры использования] в разделе Правила Компоновки.

[[alignSelf]]
== alignSelf

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/align-self" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

Определяет расположение отдельных компонентов внутри контейнера переопределяя при этом значение атрибута <<alignItems, alignItems>>. Возможные значения:

* START – элемент размещается в начале поперечной оси.
* END – элемент размещается в конце поперечной оси.
* CENTER – элемент центрируется в поперечной оси.
* STRETCH – элемент с *неопределенным размером вдоль поперечной оси* растягивается, чтобы соответствовать контейнеру.
* BASELINE – элемент размещается на базовой линии контейнера. Работает только для `flex-direction: row`.
* AUTO – элемент наследует свойство <<alignItems,alignItems>> своего родительского контейнера или "stretch", если у него нет родительского контейнера.

Вы можете найти xref:vc/layout-rules.adoc#align-self[примеры использования] в разделе Правила Компоновки.

[[ariaLabel]]
== ariaLabel

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

Устанавливает отдельную, визуально скрытую метку для технологий обеспечения доступности, таких как программы чтения с экрана.

[[ariaLabelledBy]]
== ariaLabelledBy

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

Позволяет ссылаться на другой компонент, чтобы определить доступное имя используемое для технологий обеспечения доступности, таких как программы чтения с экрана. Данное свойство имеет приоритет над другими методами задания доступного имени, включая <<ariaLabel,ariaLabel>> и текст внутри компонента.

[[autocapitalize]]
== autocapitalize

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

Устанавливает HTML-атрибут `autocapitalize`. Он используется для задания автоматического перевода текста, вводимого пользователем, в верхний регистр.

[[autocomplete]]
== autocomplete

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#autocomplete" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

Устанавливает HTML-атрибут `autocomplete`, указывающий, может ли значение этого компонента автоматически заполняться браузером.

[[autocorrect]]
== autocorrect

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#autocorrect" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

Устанавливает для поля HTML-атрибут `autocorrect`.

NOTE: Данный атрибут поддерживается только в Safari.

[[autofocus]]
== autofocus

Указывает, что компонент должен иметь фокус ввода при загрузке страницы.

Возможные значения: `true`, `false`. По умолчанию все компоненты не в фокусе.

[[classNames]]
== classNames

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins/#hasstyle-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Добавляет компоненту имена классов CSS.

Доступные имена классов берутся из следующих источников:

* Класс `com.vaadin.flow.theme.lumo.LumoUtility` и его вложенные классы.
* Класс `io.jmix.flowui.themes.JmixLumoUtility`.
* Любые пользовательские классы, аннотированные `@ThemeUtilityClasses`. Вы можете предоставлять общие имена классов в своих собственных дополнениях и в исходном коде приложения.

Jmix Studio предоставляет расширенные возможности для ввода `classNames` в свойствах UI-компонентов с помощью xref:studio:view-designer.adoc#classNames-editor[ClassNames Wizard].

[[clearButtonVisible]]
== clearButtonVisible

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field/#clear-button" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Устанавливает видимость кнопки очистки поля.

[[clickShortcut]]
== clickShortcut

Defines the xref:keyboard-shortcuts.adoc[keyboard shortcut] to fire a click event associated with the component. The component must have an appropriate handler to process the click event, otherwise the key combination will not have any effect.

[[colspan]]
== colspan

Устанавливает количество столбцов, которые должен занимать компонент, если он расположен в xref:vc/layouts/formLayout.adoc[].

По умолчанию `1`.

[[css]]
== css

Позволяет декларативно указывать CSS-свойства для компонентов UI.

In this example, the `css` attribute is used to apply inline styles to the xref:flow-ui:vc/components/textField.adoc[textField] component, including setting the background color, border, padding, and font size:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/cssattr/css-attr-view.xml[tags=textField]
----

In the example below, the `css` attribute is used to provide inline CSS for the xref:flow-ui:vc/components/button.adoc[button] component.

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/component/cssattr/css-attr-view.xml[tags=button]
----

[[dataContainer]]
== dataContainer

Устанавливает контейнер данных, определенный в разделе `data` XML-дескриптора экрана.

При установке в `dataContainer` xref:data/instance-container.adoc[контейнера экземпляра], необходимо также установить атрибут <<property>>.

[[datatype]]
== datatype

Устанавливает xref:data-model:data-types.adoc[тип данных] содержимого компонента. Возможные значения:

* `boolean`
* `byteArray`
* `char`
* `date`
* `dateTime`
* `decimal`
* `double`
* `fileRef`
* `int`
* `localDate`
* `localDateTime`
* `localTime`
* `long`
* `offsetDateTime`
* `offsetTime`
* `string`
* `time`
* `uri`
* `uuid`

Данный атрибут необходимо установить если компонент не связан с каким-либо атрибутом сущности. В противном случае тип данных определяется типом атрибута сущности.

[[dateFormat]]
== dateFormat

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/date-picker#date-format" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Устанавливает предпочтительный формат для значений даты в компоненте. По умолчанию используется формат даты текущей локали.

[[enabled]]
== enabled

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/enabled-state" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Делает компонент явно отключенным или включенным.

[[errorMessage]]
== errorMessage

Устанавливает компоненту сообщение об ошибке.

[[flexGrow]]
== flexGrow

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/flex-grow" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

Sets the flex grow factor for this component. When set to `0`, the width is fixed.

[[focusShortcut]]
== focusShortcut

Defines the xref:keyboard-shortcuts.adoc[keyboard shortcut] that is used to place focus on this component.

[[height]]
== height

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins/#hassize-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Устанавливает высоту компонента.

Высота должна быть в формате, понятном браузеру, например, `"100px"` или `"2.5em"`.

Вы можете найти xref:vc/layout-rules.adoc#component-sizes[примеры использования] в разделе Правила Компоновки.

[[helperText]]
== helperText

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field#basic-features" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Задает текст рядом с полем. Его можно использовать, например, для информирования пользователей о том, какие значения ожидает компонент.

[[id]]
== id

Идентификатор компонента.

Рекомендуется создавать идентификаторы по правилам идентификаторов Java и использовать camelСase, например: `userGrid`, `filterPanel`. Атрибут `id` можно указать для любого компонента и он должен быть уникальным в пределах экрана.

[[invalid]]
== invalid

Устанавливает недопустимое состояние поля с учетом результата валидации.

* Если `invalid=false`, то поле отбражается в допустимом состоянии независимо от результата валидации.
* If `invalid=true`, то поле отбражается в допустимом состоянии только если валидация прошла успешно.

[[label]]
== label

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field#basic-features" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Устанавливает надпись для компонента.

Значением атрибута может быть либо сам текст, либо ключ в xref:localization:message-bundles.adoc[пакете сообщений]. В случае ключа значение должно начинаться с `msg:// `префикса.

[[maxHeight]]
== maxHeight

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/max-height" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins/#hassize-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Устанавливает CSS-свойство `max-height` компонента. Высота должна быть в формате, понятном браузеру, например, `"100px"` или `"2.5em"`.

Вы можете найти xref:vc/layout-rules.adoc#component-sizes[примеры использования] в разделе Правила Компоновки.

[[maxLength]]
== maxLength

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#maxlength" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field#constraints" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Устанавливает максимальное количество символов, которое принимает поле.

[[maxWidth]]
== maxWidth

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/max-width" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins/#hassize-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Устанавливает CSS-свойство `max-width` компонента. Ширина должна быть в формате, понятном браузеру, например, `"100px"` или `"2.5em"`.

Вы можете найти xref:vc/layout-rules.adoc#component-sizes[примеры использования] в разделе Правила Компоновки.

[[metaClass]]
== metaClass

Определяет класс сущности для компонентов, отображающих сущности, например, xref:vc/components/dataGrid.adoc[DataGrid] или xref:vc/components/entityComboBox.adoc[].

Установите этот атрибут, если компонент не связан с xref:data/data-containers.adoc[контейнером данных]. В противном случае класс сущности определяется контейнером данных.

[[minHeight]]
== minHeight

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/min-height" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins/#hassize-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Устанавливает CSS-свойство `min-height` компонента. Высота должна быть в формате, понятном браузеру, например, `"100px"` или `"2.5em"`.

Вы можете найти xref:vc/layout-rules.adoc#component-sizes[примеры использования] в разделе Правила Компоновки.

[[minLength]]
== minLength

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#minlength" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field#constraints" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Устанавливает минимальное количество символов, которое принимает поле.

[[minWidth]]
== minWidth

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/min-width" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins/#hassize-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Устанавливает CSS-свойство `min-width` компонента. Ширина должна быть в формате, понятном браузеру, например, `"100px"` или `"2.5em"`.

Вы можете найти xref:vc/layout-rules.adoc#component-sizes[примеры использования] в разделе Правила Компоновки.

[[overlayClass]]
== overlayClass

Specifies a list of CSS class names to set on the overlay element.

[[pattern]]
== pattern

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#pattern" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field/#pattern" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Устанавливает регулярное выражение для значения, проверяемое на стороне клиента. Шаблон должен представлять собой допустимое регулярное выражение JavaScript, соответствующее всему значению, а не только некоторому его подмножеству.

[[placeholder]]
== placeholder

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field/#placeholder" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Определяет подсказку пользователю о том, что можно ввести в компонент.

[[property]]
== property

Задает имя атрибута xref:data-model:entities.adoc[сущности] значение которого будет отображаться и редактироваться данным визуальным компонентом.

`property` всегда используется вместе с атрибутом <<dataContainer,dataContainer>>.

[[readOnly]]
== readOnly

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field#read-only-disabled" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Устанавливает компонент в режим только для чтения.

[[required]]
== required

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field#constraints" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Указывает, что для этого поля требуется значение.

Используйте свойство приложения xref:flow-ui:ui-properties.adoc#jmix.ui.component.immediate-required-validation-enabled[jmix.ui.component.immediate-required-validation-enabled], чтобы контролировать, когда обязательное поле выделяется.

[[requiredIndicatorVisible]]
== requiredIndicatorVisible

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/text-field#constraints" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Устанавливает видимым индикатор необходимости ввода значения.

[[requiredMessage]]
== requiredMessage

Используется вместе с атрибутом <<required,required>>. Устанавливает сообщение, которое будет отображаться пользователю, когда компонент не имеет значения.

Атрибут может содержать само сообщение или ключ из xref:localization:message-bundles.adoc[пакета сообщений], например: `requiredMessage="msg://infoTextField.requiredMessage"`

[[step]]
== step

Устанавливает интервал времени в минутах между значениями, доступными для выбора в компонентах xref:vc/components/timePicker.adoc[] и xref:vc/components/dateTimePicker.adoc[]. Значение по умолчанию `60`:

[[tabIndex]]
== tabIndex

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

Устанавливает HTML-атрибут `tabindex` в компоненте. Атрибут указывает, может ли его элемент быть сфокусирован и как он участвует в последовательной навигации с помощью клавиатуры:

* Отрицательное значение (обычно `tabindex = -1` означает, что компонент должен быть доступен для фокуса, но не должен быть достижим при последовательной навигации с помощью клавиатуры.
* `tabindex = `0` означает, что компонент должен быть доступен для фокусировки при последовательной навигации с помощью клавиатуры, но его порядок определяется исходным порядком документа.
* Положительное значение означает, что компонент должен быть доступен для фокусировки при последовательной навигации с помощью клавиатуры, а его порядок определяется значением атрибута. То есть `tabindex = 4` фокусируется до `tabindex = 5`, но после `tabindex = 3`. Если несколько компонентов имеют одно и то же положительное значение `tabindex`, их порядок относительно друг друга соответствует их положению в документе.

[[text]]
== text

Задает текстовое содержимое компонента.

Значением атрибута может быть либо сам текст, либо ключ в xref:localization:message-bundles.adoc[пакете сообщений]. В случае ключа значение должно начинаться с `msg://` префикса.

Есть два способа заданя ключа:

* Короткий ключ - в этом случае сообщение будет искаться в группе сообщений текущего экрана. Например: `msg://infoField.caption`.

* Полный ключ, включающий группу сообщений, например: `msg://com.company.sample.view.user/infoField.caption`.

[[themeNames]]
== themeNames

Добавляет компоненту тему.

[[title]]
== title

Значение атрибута устанавливается в HTML-атрибуты https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title[title^] и https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label[aria-label^]. Большинство компонентов интерпретируют его как всплывающую подсказку.

[[value]]
== value

Sets the value of the component. If the new value is not equal to `getValue()`, fires a value change event. May throw `IllegalArgumentException` if the value is not acceptable.

[[valueChangeMode]]
== valueChangeMode

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/tools/collaboration/components/collaboration-binder/#propagate-values-eagerly-in-text-fields" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Устанавливает новый режим изменения значения для компонента.

[[valueChangeTimeout]]
== valueChangeTimeout

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/tools/collaboration/components/collaboration-binder/#propagate-values-eagerly-in-text-fields" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Применяет тайм-аут изменения значения для данного <<valueChangeMode>>.

[[visible]]
== visible

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/basic-features/#visibility" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Устанавливает видимость компонента.

[[weekNumbersVisible]]
== weekNumbersVisible
++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/components/date-picker#week-numbers" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Указывает, отображаются ли номера недель в всплывающем календаре. Это работает только в том случае, если первый день недели установлен на понедельник.

[[whiteSpace]]
== whiteSpace

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/white-space" class="mdn-docs-btn" target="_blank">MDN</a>
</div>
++++

Устанавливает CSS-свойство `white-space`.

Значение по умолчанию `NORMAL`.

[[width]]
== width

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://vaadin.com/docs/latest/create-ui/creating-components/mixins/#hassize-interface" class="vaadin-docs-btn" target="_blank">Vaadin</a>
</div>
++++

Устанавливает ширину компонента. Ширина должна быть в формате, понятном браузеру, например, `"100px"` или `"2.5em"`.

Вы можете найти xref:vc/layout-rules.adoc#component-sizes[примеры использования] в разделе Правила Компоновки.