= What's New

This section covers new features of Jmix framework and Studio {page-component-display-version}, as well as some breaking changes to be aware of when upgrading from a previous version of the framework.

[[upgrade]]
== How To Upgrade

[IMPORTANT]
====
To create new projects with Jmix {page-component-display-version} or to upgrade an existing project, you need Studio {page-component-display-version} or later, so xref:studio:update.adoc[update] your Jmix Studio plugin first.

The minimal supported IntelliJ IDEA version is now {minimal-idea-version}.
====

See xref:studio:project.adoc#upgrading-project[Upgrading Project] section for how to upgrade your project using Studio. The automatic migration procedure makes the following changes in your project:

* Updates the version of Jmix BOM which in turn defines versions of all dependencies.
* Updates the version of Jmix Gradle plugin.

See also the full list of <<breaking-changes,breaking changes>> that can affect your project after the upgrade.

[[new-features]]
== New Features and Improvements

[[element-collections]]
=== Support for Element Collections

The Jmix data model now supports collections of basic types, `FileRef` objects or custom types. In JPA entities, these collection attributes are annotated with `@ElementCollection` and stored in separate database tables.

See the xref:data-model:entities.adoc#element-collections[Entities] section for how to define element collections and xref:data-access:data-manager.adoc#element-collections[Using DataManager] for how to use them in queries.

Element collection attributes are xref:data-access:fetching.adoc#lazy-loading[lazily loaded] by default and can be included in fetch plans when needed.

Element collection attributes can be used in the xref:flow-ui:vc/components/genericFilter.adoc[] component conditions and can be bound as values of xref:flow-ui:vc/components/multiValuePicker.adoc[], xref:flow-ui:vc/components/multiSelectComboBox.adoc[] and xref:flow-ui:vc/components/multiSelectComboBoxPicker.adoc[] components.

To create an element collection attribute in Studio, select `ELEMENT_COLLECTION` in the *Attribute type* dropdown of the *New Attribute* dialog.

See also https://github.com/jmix-framework/jmix/issues/1271[#1271^].

[[data-model-visualization]]
=== Data Model Visualization in Data Tools

The xref:data-tools:index.adoc[] add-on now includes a xref:data-tools:data-model.adoc[] view to show entities and their attributes in the running application. Additionally, the view lets you create a data model diagram (for all entities or a chosen subset) using a public or self-hosted PlantUML server.

[[dynamic-attributes-process-forms]]
=== Dynamic Attributes in Process Forms

Dynamic attributes can now be loaded and displayed in process forms based on Jmix views. You can enable this behavior with the `@ProcessVariableParam` annotation. See xref:bpm:bpmn/jmix-view-forms.adoc#loading-dynamic-attributes[Loading Dynamic Attributes] for details.

[[h2-database]]
=== Support for H2 Database (Experimental)

Added experimental support for the H2 database. You can now select *H2 File* or *H2 Server* in the *Database type* dropdown of the data store properties editor.

Add `spring.h2.console.enabled=true` application property to enable the web-based database console in development environment. The console will be available at `++http://localhost:8080/h2-console++`.

[[custom-update-services]]
=== Custom Update Services (Experimental)

The xref:rest:index.adoc[Generic REST API], xref:data-tools:entity-inspector.adoc[Entity Inspector] and xref:bpm:bpmn/jmix-entity-data-task.adoc[BPM Entity Data Task] now can delegate save and remove operations to a custom application service instead of calling the `DataManager` directly. It allows you to place your entity update logic in a service and be sure that it will be invoked from the generic functions of the framework. Previously you had to use xref:data-access:entity-events.adoc#entity-changed-event[EntityChangedEvent] listeners for this.

The following interfaces should be implemented by your custom service to be called by the framework:

[source,java]
----
public interface SaveDelegate<E> {

    /**
     * Called by generic framework mechanisms instead of {@code DataManager} when saving entities of type {@code E}.
     *
     * @param entity entity to save
     * @param saveContext the whole save context
     * @return saved entity
     */
    E save(E entity, SaveContext saveContext);
}

public interface RemoveDelegate<E> {
    /**
     * Called by generic framework mechanisms instead of {@code DataManager} when removing entities of type {@code E}.
     *
     * @param entity entity to remove
     */
    void remove(E entity);
}
----

[[breaking-changes]]
== Breaking Changes

[[facet-registration]]
=== Facet Registration and Loading Mechanism

The `FacetProvider` mechanism for facet registration is now deprecated and will be removed in a future version. Existing custom facets registered with `FacetProvider` continue to work due to backward compatibility. However, migration to the new `FacetRegistrationBuilder` API is strongly recommended. See xref:flow-ui:facets.adoc#custom[Custom Facets].

A breaking change affects standard Jmix facet overrides. If you previously overrode framework facets using the old mechanism, these overrides will no longer work after upgrading. Such custom implementations must be redefined using the new API:

[source,java,indent=0]
----
  @Configuration
  public class FacetConfiguration {

      @Bean
      public FacetRegistration extTimerFacet() {
          return FacetRegistrationBuilder.create(MyOverridenFacet.class)
                  .replaceFacet(OriginalFacet.class)
                  .build();
      }
  }
----

[[role-scopes-in-oidc-and-authorization-server]]
=== Role Scopes in OIDC and Authorization Server

Fixed handling of xref:security:resource-roles.adoc#role-scope[role scopes] in OpenID Connect add-on. You can use xref:oidc:index.adoc#jmix.oidc.filter-chain.force-ui-scope-enabled[jmix.oidc.filter-chain.force-ui-scope-enabled] and xref:oidc:index.adoc#jmix.oidc.filter-chain.force-api-scope-enabled[jmix.oidc.filter-chain.force-api-scope-enabled] application properties to revert to the previous behavior.

If you have used the `jmix.resource-server.force-api-security-scope.enabled` property in Jmix 2.7, replace it with the xref:authorization-server:configuration.adoc#jmix.authserver.filter-chain.force-api-scope-enabled[jmix.authserver.filter-chain.force-api-scope-enabled] property set to `false`.

See https://github.com/jmix-framework/jmix/pull/5094[#5094^] for more information.

[[changelog]]
== Changelog

* Resolved issues in Jmix Framework:

** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A2.8.0[2.8.0^]

* Resolved issues in Jmix Studio:

** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%202.8.0,-2.7.*%20Affected%20versions:%20-SNAPSHOT[2.8.0^]
