= What's New

This section covers new features of Jmix framework and Studio {page-component-display-version}, as well as some breaking changes to be aware of when upgrading from a previous version of the framework.

[[upgrade]]
== How To Upgrade

[IMPORTANT]
====
To create new projects with Jmix {page-component-display-version} or to upgrade an existing project, you need Studio {page-component-display-version} or later, so xref:studio:update.adoc[update] your Jmix Studio plugin first.

The minimal supported IntelliJ IDEA version is now {minimal-idea-version}.
====

See xref:studio:project.adoc#upgrading-project[Upgrading Project] section for how to upgrade your project using Studio. The automatic migration procedure makes the following changes in your project:

* Updates the version of Jmix BOM which in turn defines versions of all dependencies.
* Updates the version of Jmix Gradle plugin.

See also the full list of <<breaking-changes,breaking changes>> that can affect your project after the upgrade.

[[new-features]]
== New Features and Improvements

[[element-collections]]
=== Support for Element Collections

The Jmix data model now supports collections of basic types, `FileRef` objects or custom types. In JPA entities, these collection attributes are annotated with `@ElementCollection` and stored in separate database tables.

See the xref:data-model:entities.adoc#element-collections[Entities] section for how to define element collections and xref:data-access:data-manager.adoc#element-collections[Using DataManager] for how to use them in queries.

Element collection attributes are xref:data-access:fetching.adoc#lazy-loading[lazily loaded] by default and can be included in fetch plans when needed.

Element collection attributes can be used in the xref:flow-ui:vc/components/genericFilter.adoc[] component conditions and can be bound as values of xref:flow-ui:vc/components/multiValuePicker.adoc[], xref:flow-ui:vc/components/multiSelectComboBox.adoc[] and xref:flow-ui:vc/components/multiSelectComboBoxPicker.adoc[] components.

To create an element collection attribute in Studio, select `ELEMENT_COLLECTION` in the *Attribute type* dropdown of the *New Attribute* dialog.

See also https://github.com/jmix-framework/jmix/issues/1271[#1271^].

[[breaking-changes]]
== Breaking Changes


[[changelog]]
== Changelog

* Resolved issues in Jmix Framework:

** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A2.8.0[2.8.0^]

* Resolved issues in Jmix Studio:

** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%202.8.0,-2.7.*%20Affected%20versions:%20-SNAPSHOT[2.8.0^]
