= Что нового

В данном разделе приведена информация о новой функциональности и возможных несовместимых изменениях в фреймворке Jmix и Jmix Studio версии {page-component-display-version}. Примите их во внимание при обновлении с предыдущей версии фреймворка.

[IMPORTANT]
====
Для создания новых проектов в Jmix {page-component-display-version} или для апгрейда существующего проекта требуется Studio {page-component-display-version} или более поздней версии, поэтому в первую очередь xref:studio:update.adoc[обновите] плагин Jmix Studio.

Минимальная требуемая версия IntelliJ IDEA / OpenIDE - {minimal-idea-version}.
====

Раздел xref:studio:project.adoc#upgrading-project[Апгрейд проекта] содержит информацию о том, как обновить проект с помощью Studio. Процедура автоматической миграции вносит следующие изменения в ваш проект:

* Обновляет версию Jmix BOM, которая, в свою очередь, определяет версии всех зависимостей.
* Обновляет версию Jmix Gradle plugin.

См. полный список <<breaking-changes,критических изменений>>, которые могут затронуть ваш проект после обновления.

[[new-features]]
== Новая и улучшенная функциональность

[[element-collections]]
=== Поддержка коллекций элементов

Модель данных Jmix теперь поддерживает коллекции базовых типов, объектов `FileRef` или кастомных типов. В JPA-сущностях эти атрибуты-коллекции аннотируются с помощью `@ElementCollection` и хранятся в отдельных таблицах базы данных.

См. раздел xref:data-model:entities.adoc#element-collections[Сущности] о том, как определять коллекции элементов, и xref:data-access:data-manager.adoc#element-collections[Работа с DataManager] о том, как использовать их в запросах.

Атрибуты-коллекции элементов по умолчанию xref:data-access:fetching.adoc#lazy-loading[загружаются лениво] и могут быть включены в фетч-планы при необходимости.

Атрибуты-коллекции элементов могут использоваться в условиях компонента xref:flow-ui:vc/components/genericFilter.adoc[] и могут быть привязаны как значения компонентов xref:flow-ui:vc/components/multiValuePicker.adoc[], xref:flow-ui:vc/components/multiSelectComboBox.adoc[] и xref:flow-ui:vc/components/multiSelectComboBoxPicker.adoc[].

Чтобы создать атрибут-коллекцию элементов в Studio, выберите `ELEMENT_COLLECTION` в раскрывающемся списке *Attribute type* диалога *New Attribute*.

См. также https://github.com/jmix-framework/jmix/issues/1271[#1271^].

[[data-model-visualization]]
=== Визуализация модели данных в Data Tools

Дополнение xref:data-tools:index.adoc[] теперь включает экран xref:data-tools:data-model.adoc[] для просмотра сущностей и их атрибутов в запущенном приложении. Экран также позволяет создать диаграмму модели данных (для всех сущностей или лишь для выбранного набора), используя публичный или собственный сервер PlantUML.

[[dynamic-attributes-process-forms]]
=== Динамические атрибуты в формах процесса

Процессные формы на базе экранов Jmix поддерживают загрузку и отображение динамических атрибутов. Для этого используйте аннотацию `@ProcessVariableParam`. Подробнее см. в разделе xref:bpm:bpmn/jmix-view-forms.adoc#loading-dynamic-attributes[Загрузка динамических атрибутов].

[[h2-database]]
=== Поддержка H2 Database (Experimental)

Добавлена экспериментальная поддержка базы данных H2. Теперь вы можете выбрать *H2 File* или *H2 Server* в выпадающем списке *Database type* редактора свойств хранилища данных.

Во время разработки можно использовать свойство приложения `spring.h2.console.enabled=true` для включения веб-консоли базы данных. Консоль будет доступна по адресу `++http://localhost:8080/h2-console++`.

[[custom-update-services]]
=== Кастомные сервисы обновления (Experimental)

xref:rest:index.adoc[Универсальный REST API], xref:data-tools:entity-inspector.adoc[Инспектор сущностей] и xref:bpm:bpmn/jmix-entity-data-task.adoc[BPM Entity Data Task] теперь могут делегировать операции сохранения и удаления кастомному сервису приложения вместо прямого вызова `DataManager`. Это позволяет поместить логику обновления сущностей в сервис и быть уверенным, что она будет вызвана из общих функций фреймворка. Ранее для этого приходилось использовать слушатели xref:data-access:entity-events.adoc#entity-changed-event[EntityChangedEvent].

Для вызова фреймворком кастомный сервис должен реализовывать следующие интерфейсы:

[source,java]
----
public interface SaveDelegate<E> {

    /**
     * Called by generic framework mechanisms instead of {@code DataManager} when saving entities of type {@code E}.
     *
     * @param entity entity to save
     * @param saveContext the whole save context
     * @return saved entity
     */
    E save(E entity, SaveContext saveContext);
}

public interface RemoveDelegate<E> {
    /**
     * Called by generic framework mechanisms instead of {@code DataManager} when removing entities of type {@code E}.
     *
     * @param entity entity to remove
     */
    void remove(E entity);
}
----

[[breaking-changes]]
== Критические изменения

[[facet-registration]]
=== Facet Registration and Loading Mechanism

The `FacetProvider` mechanism for facet registration is now deprecated and will be removed in a future version. Existing custom facets registered with `FacetProvider` continue to work due to backward compatibility. However, migration to the new `FacetRegistrationBuilder` API is strongly recommended. See xref:flow-ui:facets.adoc#custom[Custom Facets].

A breaking change affects standard Jmix facet overrides. If you previously overrode framework facets using the old mechanism, these overrides will no longer work after upgrading. Such custom implementations must be redefined using the new API:

[source,java,indent=0]
----
  @Configuration
  public class FacetConfiguration {

      @Bean
      public FacetRegistration extTimerFacet() {
          return FacetRegistrationBuilder.create(MyOverridenFacet.class)
                  .replaceFacet(OriginalFacet.class)
                  .build();
      }
  }
----

[[changelog]]
== Список изменений

* Решенные проблемы в Jmix Framework:

** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A2.8.0[2.8.0^]

* Решенные проблемы в Jmix Studio:

** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%202.8.0,-2.7.*%20Affected%20versions:%20-SNAPSHOT[2.8.0^]
