= What's New

This section covers new features of Jmix framework and Studio {page-component-display-version}, as well as some breaking changes to be aware of when upgrading from a previous version of the framework.

[[upgrade]]
== How To Upgrade

[IMPORTANT]
====
To create new projects with Jmix {page-component-display-version} or to upgrade an existing project, you need Studio {page-component-display-version} or later, so xref:studio:update.adoc[update] your Jmix Studio plugin first.

The minimal supported IntelliJ IDEA version is now {minimal-idea-version}.
====

See xref:studio:project.adoc#upgrading-project[Upgrading Project] section for how to upgrade your project using Studio. The automatic migration procedure makes the following changes in your project:

* Updates the version of Jmix BOM which in turn defines versions of all dependencies.
* Updates the version of Jmix Gradle plugin.
* Adds default values to `editorActionsColumn` buttons without assigned values in all project views. See details <<editor-actions-column-buttons,below>>.
* Renames the `id` attribute of the `settings.component` element to `componentId` in all project views. See details <<settings-component-id,below>>.


See also the full list of <<breaking-changes,breaking changes>> that can affect your project after the upgrade.

[[updated-dependencies]]
== Updated Dependencies

The following major dependencies have been updated:

* Spring Boot https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.5-Release-Notes[3.5^].

* Vaadin https://github.com/vaadin/platform/releases/tag/24.7.0[24.7^].

[[new-features]]
== New Features and Improvements

=== Switch Component

The new xref:flow-ui:vc/components/switch.adoc[switch] component is used to represent a binary choice, allowing users to toggle between two states, such as `true`/`false`.

=== Autocompletion in CodeEditor

The `codeEditor` component now provides autocompletion for a specific language mode or using custom suggestion handlers.

See xref:flow-ui:vc/components/codeEditor.adoc#suggestion[codeEditor: Suggestion] for more information.

[[save-without-reload]]
=== DataManager.saveWithoutReload method

The new `DataManager.saveWithoutReload()` method improves performance when the saved instances are not immediately required for further processing. You can use it instead of the verbose `save(new SaveContext().saving(entities).setDiscardSaved(true))` operation.

See xref:data-access:data-manager.adoc#save[Using DataManager: Saving Entities] for more information.

[[rest-data-store-oidc-authentication]]
=== REST DataStore OIDC Authentication

The REST DataStore add-on now includes the `restds_RestOidcAuthenticator` bean that allows you to use an external authentication provider (for example Keycloak) when integrating applications.

See xref:rest-ds:index.adoc#external-authentication[REST DataStore: External Authentication] for more information.

[[breaking-changes]]
== Breaking Changes

[[node-20]]
=== Node.js v.20

Vaadin 24.7 requires Node.js 20+. If you are using a locally installed Node, upgrade it if needed.

[[editor-actions-column-buttons]]
=== Removed defaults of editorActionsColumn buttons

Previously, the nested buttons within the xref:flow-ui:vc/components/dataGrid.adoc#actions-column[editorActionsColumn] element had default values for certain attributes. Specifically, all buttons were assigned an `icon`, while both the `editButton` and `cancelButton` had a `text` attribute assigned.

This behavior was inconsistent and prevented from removing an icon or text from the button in an application project.

Now the buttons have no default values at all.

The Studio migration procedure scans all views in the project and automatically adds previous default values to the buttons that don't have explicit values.

See https://github.com/jmix-framework/jmix/issues/4493[#4493^] for more information.

[[settings-component-id]]
=== Renamed settings.component id attribute

The `id` attribute of `component` element in the xref:flow-ui:facets/settings.adoc[settings] facet has been renamed to `componentId` to not confuse with the commonly used `id` attribute. For example:

Jmix 2.5:
[source,xml]
----
<facets>
    <settings>
        <component id="genericFilter"/>
    </settings>
</facets>
----

Jmix 2.6+:
[source,xml]
----
<facets>
    <settings>
        <component componentId="genericFilter"/>
    </settings>
</facets>
----

The Studio migration procedure scans all views in the project and automatically renames this attribute.

See https://github.com/jmix-framework/jmix/issues/4412[#4412^] for more information.

[[dynamic-attributes-views]]
=== Changes in Dynamic Attributes Views

The xref:dyn-attr:index.adoc[Dynamic Attributes] management views were significantly redesigned. If you have overridden these views, adapt your code accordingly.

[[in-app-notification-list-view]]
=== Changes in in-app-notification-list-view.xml

In the `in-app-notification-list-view.xml` descriptor of the xref:notifications:index.adoc[] add-on, the `create` action has been removed from `inAppNotificationsDataGrid`. This action has been moved to the view's `actions` section and renamed to `createNotificationAction`.

If you have overridden this view, adapt your code accordingly.

[[changelog]]
== Changelog

* Resolved issues in Jmix Framework:

** https://github.com/jmix-framework/jmix/issues?q=is%3Aissue%20state%3Aclosed%20project%3Ajmix-framework%2F30%20reason%3Acompleted[2.6.0]

// ** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A2.6.0[2.6.0^]

* Resolved issues in Jmix Studio:

** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%202.6.0,-2.5.*%20Affected%20versions:%20-SNAPSHOT[2.6.0^]
