= Что нового

В данном разделе приведена информация о новой функциональности и возможных несовместимых изменениях в фреймворке Jmix и Jmix Studio версии {page-component-display-version}. Примите их во внимание при обновлении с предыдущей версии фреймворка.

[IMPORTANT]
====
Для создания новых проектов в Jmix {page-component-display-version} или для апгрейда существующего проекта требуется Studio {page-component-display-version} или более поздней версии, поэтому в первую очередь xref:studio:update.adoc[обновите] плагин Jmix Studio.

Минимальная требуемая версия IntelliJ IDEA - {minimal-idea-version}.
====

Раздел xref:studio:project.adoc#upgrading-project[Апгрейд проекта] содержит информацию о том, как обновить проект с помощью Studio. Процедура автоматической миграции вносит следующие изменения в ваш проект:

* Обновляет версию Jmix BOM, которая, в свою очередь, определяет версии всех зависимостей.
* Обновляет версию Jmix Gradle plugin.
* Сканирует все экраны в проекте и добавляет предыдущие значения по умолчанию атрибутам кнопок в `editorActionsColumn`, которые не имеют явных значений. Подробнее см. <<editor-actions-column-buttons,ниже>>.

См. полный список <<breaking-changes,критических изменений>>, которые могут затронуть ваш проект после обновления.

[[updated-dependencies]]
== Обновленные зависимости

Следующие основные зависимости были обновлены:

* Spring Boot https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.5-Release-Notes[3.5^].

* Vaadin https://github.com/vaadin/platform/releases/tag/24.7.0[24.7^].

[[new-features]]
== Новая и улучшенная функциональность

=== Компонент Switch

Новый компонент xref:flow-ui:vc/components/switch.adoc[switch] предназначен для представления бинарного выбора, позволяя пользователям переключаться между двумя состояниями (например, `true`/`false`).

[[breaking-changes]]
== Критические изменения

[[editor-actions-column-buttons]]
=== Removed defaults of editorActionsColumn buttons

Previously, the nested buttons within the xref:flow-ui:vc/components/dataGrid.adoc#actions-column[editorActionsColumn] element had default values for certain attributes. Specifically, all buttons were assigned an `icon`, while both the `editButton` and `cancelButton` had a `text` attribute assigned.

This behavior was inconsistent and prevented from removing an icon or text from the button in an application project.

Now the buttons have no default values at all.

The Studio migration procedure scans all views in the project and automatically adds previous default values to the buttons that don't have explicit values.

See https://github.com/jmix-framework/jmix/issues/4493[#4493^] for more information.

[[settings-component-id]]
=== Renamed settings.component id attribute

The `id` attribute of the `settings` -> `component` element has been renamed to `componentId` to not confuse with the commonly used `id` attribute. For example:

Jmix 2.5:
[source,xml]
----
<settings>
    <component id="genericFilter"/>
</settings>
----

Jmix 2.6+:
[source,xml]
----
<settings>
    <component componentId="genericFilter"/>
</settings>
----

The Studio migration procedure scans all views in the project and automatically renames this attribute.

See https://github.com/jmix-framework/jmix/issues/4412[#4412^] for more information.

[[changelog]]
== Список изменений

* Решенные проблемы в Jmix Framework:

** https://github.com/jmix-framework/jmix/issues?q=is%3Aissue%20state%3Aclosed%20project%3Ajmix-framework%2F30%20reason%3Acompleted[2.6.0]

// ** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A2.6.0[2.6.0^]

* Решенные проблемы в Jmix Studio:

** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%202.6.0,-2.5.*%20Affected%20versions:%20-SNAPSHOT[2.6.0^]
