= What's New

This section covers new features of Jmix framework and Studio {page-component-display-version}, as well as some breaking changes to be aware of when upgrading from a previous version of the framework.

[[upgrade]]
== How To Upgrade

[IMPORTANT]
====
To create new projects with Jmix {page-component-display-version} or to upgrade an existing project, you need Studio {page-component-display-version} or later, so xref:studio:update.adoc[update] your Jmix Studio plugin first.

The minimal supported IntelliJ IDEA version is now {minimal-idea-version}.
====

See xref:studio:project.adoc#upgrading-project[Upgrading Project] section for how to upgrade your project using Studio. The automatic migration procedure makes the following changes in your project:

* Updates the version of Jmix BOM which in turn defines versions of all dependencies.
* Updates the version of Jmix Gradle plugin.


See also the full list of <<breaking-changes,breaking changes>> that can affect your project after the upgrade.

[[updated-dependencies]]
== Updated Dependencies

The following major dependencies have been updated:

* Vaadin https://github.com/vaadin/platform/releases/tag/24.8.0[24.8^].

[[new-features]]
== New Features and Improvements

[[studio]]
=== Studio Improvements

[[rest-data-store]]
=== REST DataStore Improvements

[[breaking-changes]]
== Breaking Changes

[[changelog]]
== Changelog

* Resolved issues in Jmix Framework:

** https://github.com/jmix-framework/jmix/issues?q=is%3Aissue%20state%3Aclosed%20project%3Ajmix-framework%2F32%20reason%3Acompleted[2.7.0^]
// ** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A2.7.0[2.7.0^]

* Resolved issues in Jmix Studio:

** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%202.7.0,-2.6.*%20Affected%20versions:%20-SNAPSHOT[2.7.0^]
