= What's New

This section covers new features of Jmix framework and Studio {page-component-display-version}, as well as some breaking changes to be aware of when upgrading from a previous version of the framework.

[[upgrade]]
== How To Upgrade

[IMPORTANT]
====
To create new projects with Jmix {page-component-display-version} or to upgrade an existing project, you need Studio {page-component-display-version} or later, so xref:studio:update.adoc[update] your Jmix Studio plugin first.

The minimal supported IntelliJ IDEA version is now {minimal-idea-version}.
====

See xref:studio:project.adoc#upgrading-project[Upgrading Project] section for how to upgrade your project using Studio. The automatic migration procedure makes the following changes in your project:

* Updates the version of Jmix BOM which in turn defines versions of all dependencies.
* Updates the version of Jmix Gradle plugin.
* Updates the version of Gradle wrapper to 8.10.2 in `gradle/wrapper/gradle-wrapper.properties`.
* If the project includes the REST API add-on, adds the `jmix.resource-server.authenticated-url-patterns` property, see details <<protecting-generic-rest-endpoints,below>>.
* Replaces calls to `dateTimeParameter()`, `dateParameter()` and `timeParameter()` methods of input dialog builder with calls to `localDateTimeParameter()`, `localDateParameter()` and `localTimeParameter()`. See details <<input-dialog-date-parameters,below>>.
* Adds the Grid Export Actions add-on to the project if it includes the Data Tools add-on. See details <<grid-export-actions-add-on-dependency,below>>.
* Sets the xref:flow-ui:ui-properties.adoc#jmix.ui.component.default-trim-enabled[jmix.ui.component.default-trim-enabled] application property to `false`. See details <<trimming-in-text-fields,below>>.

See also the full list of <<breaking-changes,breaking changes>> that can affect your project after the upgrade.

[IMPORTANT]
====
If, after upgrading the project and starting the application, you encounter the following exception:

`com.vaadin.flow.server.ExecutionFailedException: Vite build exited with a non zero status`

remove the following files and directories from the project root: `node_modules`, `package.json`, `pnpm-lock.yaml`, `tsconfig.json`, `types.d.ts`, `vite.config.ts`, `vite.generated.ts`

Also, if you have Node.js installed globally, update it to the latest LTS version available on the website https://nodejs.org[^].
====

[[updated-dependencies]]
== Updated Dependencies

The following major dependencies have been updated:

* Spring Boot https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.3-Release-Notes[3.3^].

* Vaadin https://github.com/vaadin/platform/releases/tag/24.4.0[24.4^].

[[new-features]]
== New Features and Improvements

[[new-add-ons]]
=== New Add-ons

The following new add-ons are now available:

* The xref:calendar:index.adoc[] add-on provides a UI component that allows you to show data-bound events in a calendar with various views (day, week, month, etc.) and edit them by dragging and resizing.

* The xref:pivot-table:index.adoc[] add-on provides a UI component that enables turning a data set into a summary table and manipulating it using 2D drag-and-drop UI.

* The xref:kanban:index.adoc[] add-on provides a UI component that represents a Kanban board. It shows workflow at different stages of a project, using cards for tasks and columns for stages.

* The xref:uiconstraints:index.adoc[] add-on allows you to control the visibility and accessibility of UI components using declarative policies defined in resource roles.

* The xref:rest-ds:index.adoc[] add-on allows you to access external entities from a remote Jmix application through the standard `DataManager` interface in the same way as local JPA entities.

[[data-binding-for-html-components]]
=== Data Binding for HTML Components

The xref:flow-ui:vc/html.adoc[HTML components] like `div`, `span`, `h1`...`h5` and others can now be bound to your data model entities declaratively in XML using the `dataContainer` and `property` attributes.

In many cases this will save you from writing code to set values in these components programmatically in view controllers.

[[fragment-renderer]]
=== Fragment Renderer

Renderers for xref:flow-ui:vc/components/virtualList.adoc[], xref:flow-ui:vc/components/dataGrid.adoc[] and other components can now be defined by xref:flow-ui:fragments/fragments.adoc[fragments].

The new `fragmentRenderer` XML element should specify the fragment Java class, for example:

[source,xml]
----
<virtualList itemsContainer="usersDc">
    <fragmentRenderer class="com.company.onboarding.view.userfragment.UserFragment"/>
</virtualList>
----

An example of the fragment used as a renderer:

[source,xml]
----
<fragment xmlns="http://jmix.io/schema/flowui/fragment">
    <data>
        <instance id="userDc" class="com.company.onboarding.entity.User">
            <loader id="userDl"/>
        </instance>
    </data>
    <content>
            <formLayout id="form" dataContainer="userDc">
                <textField id="usernameField" property="username" readOnly="true"/>
                <textField id="firstNameField" property="firstName"/>
                <textField id="lastNameField" property="lastName"/>
                <textField id="emailField" property="email"/>
            </formLayout>
        </hbox>
    </content>
</fragment>
----

The fragment renderer class should extend the `FragmentRenderer` base class with type parameters indicating the root component and rendered entity, for example:

[source,java]
----
@FragmentDescriptor("user-fragment.xml")
@RendererItemContainer("userDc")
public class UserFragment extends FragmentRenderer<FormLayout, User> {
}
----

The `@RendererItemContainer` annotation is used to specify the data container that accepts the rendered entity.

See https://github.com/jmix-framework/jmix/pull/3699[#3699^] for more information.

[[asynchronous-tasks]]
=== Asynchronous Tasks

The new xref:flow-ui:async-tasks.adoc[UiAsyncTasks] bean allows you to execute an operation in a separate thread using the security context of the current user, and then update the UI with the result of that operation.

In comparison to xref:flow-ui:background-tasks.adoc[], this is a lightweight mechanism based on `CompletableFuture`.

[[trimming-in-text-fields]]
=== Trimming in Text Fields

The `textField` and `textArea` components now have the xref:flow-ui:vc/components/textField.adoc#trimEnabled[trimEnabled] attribute which controls whether the component trims spaces at the beginning and at the end of the entered string.

The xref:flow-ui:ui-properties.adoc#jmix.ui.component.default-trim-enabled[jmix.ui.component.default-trim-enabled] application property specifies the default value of this attribute for the whole application. In new projects, this property is `true`. The Studio migration procedure sets this property to `false` for existing projects to minimize changes in behavior.

[[switching-theme-variants]]
=== Switching Theme Variants

The new `ThemeUtils` class contains methods for switching theme variants at runtime. This allows you to easily switch between light and dark themes in your application.

See an example in the xref:flow-ui:themes/themes.adoc#changing-theme-variants-at-runtime[Changing Theme Variants at Runtime] section.

[[immediate-validation-of-required-fields]]
=== Immediate Validation of Required Fields

The new xref:flow-ui:ui-properties.adoc#jmix.ui.component.immediate-required-validation-enabled[jmix.ui.component.immediate-required-validation-enabled] application property allows you to disable validation of required fields on view opening.

[[grid-export-options]]
=== Grid Export Options

When using the xref:grid-export:index.adoc[] add-on, the set of export options can now be defined by a particular export action using its `setAvailableExportModes()` method and corresponding `availableExportModes` property in XML. The default set of options is defined by the xref:grid-export:properties.adoc#jmix.gridexport.default-export-modes[jmix.gridexport.default-export-modes] application property.

[[using-browser-time-zone]]
=== Using Browser Time Zone

If a time zone is not assigned to the user explicitly, it can be obtained from the web browser at login. This option is controlled by the `isAutoTimeZone()` method of the `HasTimeZone` interface implemented by the standard `User` entity scaffolded in projects.

In existing projects the behavior won't change, because this method returns `false` by default. In new projects `User` will be scaffolded with `isAutoTimeZone()` returning `true`.

[[advanced-endpoints-security-configuration]]
=== Advanced Endpoints Security Configuration

More options have been introduced for configuring endpoints security when using Authorization Server or OpenID Connect add-ons:

* `jmix.resource-server.authenticated-url-patterns` and `jmix.resource-server.anonymous-url-patterns` properties
* `AuthenticatedUrlPatternsProvider` and `AnonymousUrlPatternsProvider`
* `AuthenticatedRequestMatcherProvider` and `AnonymousRequestMatcherProvider`

See xref:security:custom-endpoints.adoc#token-based-authentication[Token Based Authentication] for more information.

The old `AuthorizedUrlsProvider` is deprecated, but still works, as well as `jmix.rest.authenticated-url-patterns` and `jmix.rest.anonymous-url-patterns` properties. It is recommended to move the configuration to the new interfaces or properties.

[[search-improvements]]
=== Search Improvements

The new `@ExtendedSearch` annotation can be added to an index definition interface to provide functionality of "Starts with" search. It instructs the Search add-on to create additional "virtual" subfields for each "real" field to store prepared prefix terms.

The xref:search:search-in-ui.adoc#search-field[searchField] component now allows users to open a *Search settings* window to set the search strategy, results size and, optionally, a set of entities to search only within these entities. If there are index definitions with `@ExtendedSearch` in the project, the list of strategies contains "Starts with".

`allTermsAnyField` and `allTermsSingleField` strategies have been deprecated.

[[rest-api-improvements]]
=== REST API Improvements

Generic xref:rest:index.adoc[REST API] now supports CRUD operations with DTO entities in the `/entities` endpoints. The search conditions provided to the `entities/:entityName/search` endpoint are converted to the `Condition` tree and passed to the `DataManager`. This allows you to request DTO entities that are in turn loaded from another REST API through the xref:rest-ds:index.adoc[].

The JSON search conditions can now include objects in property values, for example:

[source,json]
----
{
  "conditions": [
    {
      "property": "field1",
      "operator": "=",
      "value": {
        "_entityName": "Customer",
        "id": "00000000-0000-0000-0000-000000000001",
        "firstName": "John",
        "lastName": "Doe"
      }
    }
  ]
}
----

[[studio-component-inspector]]
=== Studio Component Inspector

The Jmix UI component inspector now groups the properties by categories: *General*, *Data Binding*, *Size*, *Position*, *Look & Feel*, *Other*. This new feature allows you to quickly locate the property you need without having to go through a long list.

Categories are displayed only in projects based on Jmix 2.4 and above.

Besides, the component inspector now provides better support for the `icon` property. You can click the "pencil" button in the value field to show a dialog with the list of available icons and select an icon from it.

[[studio-support-for-openapi]]
=== Studio Support for OpenAPI

Jmix Studio now provides advanced support for OpenAPI-based integration. These new features include configuration of the OpenAPI client generator in your project and automatic generation of DTO entities, mappers, and intermediate services, making it easier to integrate external REST APIs into Jmix applications.

For a practical example and step-by-step instructions on how to use these features, refer to the xref:openapi-integration-guide:index.adoc[] guide.

[[composite-project-template-for-monorepo]]
=== Composite Project Template for Monorepo

We've added a new template for a composite project that is intended to be hosted in a monorepo. It provides a simple structure where all subprojects are located inside the root aggregate project:

[source]
----
composite-project/
    subproject1/
        src/
        build.gradle
        settings.gradle
    subproject2/
        src/
        build.gradle
        settings.gradle
    build.gradle
    settings.gradle
    README.md
----

This project layout is recommended if you are not going to store subprojects in separate repositories.

[[deprecated-accepts-tenant-interface]]
=== Deprecated AcceptsTenant Interface

When using the xref:multitenancy:index.adoc[] add-on, the `User` entity does not have to implement the `io.jmix.multitenancy.core.AcceptsTenant` interface anymore. The `@TenantId` annotation on a tenant field is enough.

The `AcceptsTenant` interface has been deprecated and will be removed in a future major release.

[[breaking-changes]]
== Breaking Changes

[[build-problem-with-enablejmixdatarepositories]]
=== Build Problem With EnableJmixDataRepositories

When `@EnableJmixDataRepositories` is used on the main application class extending `AppShellConfigurator`, a clean build fails with the following message:

[source]
----
> Task :vaadinPrepareFrontend FAILED
Could not read com.vaadin.flow.theme.Theme annotation from class com.company.onboarding.OnboardingApplication.
java.lang.TypeNotPresentException: Type [unknown] not present
----

The problem is caused by https://github.com/vaadin/flow/issues/19616[vaadin/flow#19616^] and will be fixed in a future patch.

To work around the problem, move the `@EnableJmixDataRepositories` annotation to a separate `@Configuration` class in the same package, for example:

[source,java]
----
package com.company.onboarding;

import io.jmix.core.repository.EnableJmixDataRepositories;
import org.springframework.context.annotation.Configuration;

@EnableJmixDataRepositories
@Configuration
public class OnboardingConfiguration {
}
----

[[protecting-generic-rest-endpoints]]
=== Protecting Generic REST Endpoints

Due to improvements in endpoints security configuration (see <<advanced-endpoints-security-configuration,above>>), the following application property must be set to secure the Generic REST API endpoints:

[source,properties]
----
jmix.resource-server.authenticated-url-patterns = /rest/**
----

The Studio migration procedure adds it to `application.properties` automatically.

[[generic-rest-unauthorized-error]]
=== Generic REST Unauthorized Error

Previously, generic REST API returned HTTP 500 code if the request to a secured endpoint was performed without `Authorization` header. Now it correctly returns HTTP 401.

[[listmenu-styles]]
=== ListMenu Styles

xref:flow-ui:vc/components/listMenu.adoc[] component styles have been changed to fix the issue with focus ring:

- Changed margin and padding for the `ListMenu` itself.
- Increased `margin-inline-start` for list of sub menu.
- Changed paddings for `MenuBarItem`.

If you have defined your own styles for this component, you may need to adjust them.

See https://github.com/jmix-framework/jmix/issues/3589[#3589^] for more information.

[[input-dialog-date-parameters]]
=== Input Dialog Date Parameters

The `dateTimeParameter()`, `dateParameter()` and `timeParameter()` methods of the xref:flow-ui:dialogs.adoc#input-dialog[input dialog] builder have been fixed: now they create parameters of `java.util.Date`, `java.sql.Date` and `java.sql.Time` type respectively. Previously they wrongly created `LocalDateTime`, `LocalDate` and `LocalTime` parameters.

See https://github.com/jmix-framework/jmix/issues/3499[#3499^] for more information.

The Studio migration procedure automatically replaces calls to these methods with calls to `localDateTimeParameter()`, `localDateParameter()` and `localTimeParameter()` to keep compatibility with returning values.

[[grid-export-actions-add-on-dependency]]
=== Grid Export Actions Add-on Dependency

Previously, the xref:data-tools:index.adoc[] add-on contained transitive dependency to the xref:grid-export:index.adoc[] add-on. This dependency has been removed, so now export actions can be used only when the Grid Export Actions add-on is included explicitly.

The Studio migration procedure automatically adds the Grid Export Actions add-on to the project if it includes the Data Tools add-on.

[[changelog-generation-for-mariadb]]
=== Changelog Generation for MariaDB

Spring Boot 3.3 brings the dependency on Liquibase 4.27, which changed column type for `UUID` attributes from `char(36)` to `uuid`. This is incompatible with the current support for MySQL/MariaDB databases in Jmix and causes invalid conversion of `UUID` values.

If you are using MariaDB, downgrade Liquibase in your project by adding the following dependency to `build.gradle`:

[source,groovy]
----
implementation 'org.liquibase:liquibase-core:4.25.0!!'
----

See https://github.com/jmix-framework/jmix/issues/3888[#3888^] for more information.


[[changelog]]
== Changelog

* Resolved issues in Jmix Framework:

** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A2.4.5[2.4.5^]
** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A2.4.4[2.4.4^]
** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A2.4.3[2.4.3^]
** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A2.4.2[2.4.2^]
** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A2.4.1[2.4.1^]
** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A2.4.0[2.4.0^]

* Resolved issues in Jmix Studio:

** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%202.4.3[2.4.3^]
** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%202.4.2[2.4.2^]
** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%202.4.1[2.4.1^]
** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%202.4.0,-2.3.*%20Affected%20versions:%20-SNAPSHOT[2.4.0^]
