= Что нового

В данном разделе приведена информация о новой функциональности и возможных несовместимых изменениях в фреймворке Jmix и Jmix Studio версии {page-component-display-version}. Примите их во внимание при обновлении с предыдущей версии фреймворка.

[IMPORTANT]
====
Для создания новых проектов в Jmix {page-component-display-version} или для апгрейда существующего проекта требуется Studio {page-component-display-version} или более поздней версии, поэтому в первую очередь xref:studio:update.adoc[обновите] плагин Jmix Studio.

Минимальная требуемая версия IntelliJ IDEA - {minimal-idea-version}.
====

Раздел xref:studio:project.adoc#upgrading-project[Апгрейд проекта] содержит информацию о том, как обновить проект с помощью Studio. Процедура автоматической миграции вносит следующие изменения в ваш проект:

* Обновляет версию Jmix BOM, которая, в свою очередь, определяет версии всех зависимостей.
* Обновляет версию Jmix Gradle plugin.
* Обновляет версию Gradle wrapper до 8.10.2 в `gradle/wrapper/gradle-wrapper.properties`.
* Если проект включает дополнение REST API, добавляет свойство `jmix.resource-server.authenticated-url-patterns`, смотрите подробности <<protecting-generic-rest-endpoints, ниже>>.
* Заменяет вызовы методов `dateTimeParameter()`, `dateParameter()` и `timeParameter()` билдера диалогового окна ввода на вызовы `localDateTimeParameter()`, `localDateParameter()` и `localTimeParameter()`. См. подробности <<input-dialog-date-parameters, ниже>>.
* Добавляет дополнение Grid Export Actions в проект, если он включает дополнение Data Tools. См. подробности <<grid-export-actions-add-on-dependency, ниже>>.
* Устанавливает свойство приложения xref:flow-ui:ui-properties.adoc#jmix.ui.component.default-trim-enabled[jmix.ui.component.default-trim-enabled] в `false`. См. подробности <<trimming-in-text-fields, ниже>>.

См. полный список <<breaking-changes,опасных изменений>>, которые могут затронуть ваш проект после обновления.

[IMPORTANT]
====
Если после обновления проекта и запуска приложения вы столкнетесь со следующей исключительной ситуацией:

`com.vaadin.flow.server.ExecutionFailedException: Vite build exited with a non zero status`

удалите следующие файлы и каталоги из корня проекта: `node_modules`, `package.json`, `pnpm-lock.yaml`, `tsconfig.json`, `types.d.ts`, `vite.config.ts`, `vite.generated.ts`

Кроме того, если у вас глобально установлен Node.js, обновите его до последней LTS версии доступной на сайте https://nodejs.org[^].
====

[[updated-dependencies]]
== Обновленные зависимости

Следующие основные зависимости были обновлены:

* Spring Boot https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.3-Release-Notes[3.3^].

* Vaadin https://github.com/vaadin/platform/releases/tag/24.4.0[24.4^].

[[new-features]]
== Новая и улучшенная функциональность

[[new-add-ons]]
=== Новые дополнения

Доступны следующие новые дополнения:

* Дополнение xref:calendar:index.adoc[] предоставляет UI-компонент, который позволяет отображать привязанные к данным события в календаре с различным отображением (день, неделя, месяц и т. д.) и редактировать их с помощью перетаскивания и изменения размера.

* Дополнение xref:pivot-table:index.adoc[] предоставляет UI-компонент, который позволяет преобразовать набор данных в сводную таблицу и манипулировать ею с помощью 2D интерфейса перетаскивания.

* Дополнение xref:kanban:index.adoc[] представляет UI-компонент, который отображает Канбан-доску. Он показывает рабочий процесс на разных этапах проекта, используя карточки для задач и колонки для этапов.

* Дополнение xref:uiconstraints:index.adoc[] позволяет контролировать видимость и доступность UI-компонентов с использованием декларативных политик, определенных в ресурсных ролях.

* Дополнение xref:rest-ds:index.adoc[] позволяет получать доступ к внешним сущностям из удаленного Jmix-приложения через стандартный интерфейс `DataManager`, так же как к локальным JPA-сущностям.

[[data-binding-for-html-components]]
=== Привязка данных для HTML-компонентов

xref:flow-ui:vc/html.adoc[HTML-компоненты], такие как `div`, `span`, `h1`...`h5` и другие, теперь могут быть привязаны к сущностям модели данных декларативно в XML с использованием атрибутов `dataContainer` и `property`.

В большинстве случаев это избавляет от необходимости программно задавать значения в этих компонентах в контроллерах экрана.

[[fragment-renderer]]
=== Fragment Renderer

Рендереры для xref:flow-ui:vc/components/virtualList.adoc[], xref:flow-ui:vc/components/dataGrid.adoc[] и других компонентов теперь могут быть определены с помощью xref:flow-ui:fragments/fragments.adoc[фрагментов].

Новый XML-элемент `fragmentRenderer` должен указывать класс Java фрагмента, например:

[source,xml]
----
<virtualList itemsContainer="usersDc">
    <fragmentRenderer class="com.company.onboarding.view.userfragment.UserFragment"/>
</virtualList>
----

Пример фрагмента, используемого в качестве рендерера:

[source,xml]
----
<fragment xmlns="http://jmix.io/schema/flowui/fragment">
    <data>
        <instance id="userDc" class="com.company.onboarding.entity.User">
            <loader id="userDl"/>
        </instance>
    </data>
    <content>
            <formLayout id="form" dataContainer="userDc">
                <textField id="usernameField" property="username" readOnly="true"/>
                <textField id="firstNameField" property="firstName"/>
                <textField id="lastNameField" property="lastName"/>
                <textField id="emailField" property="email"/>
            </formLayout>
        </hbox>
    </content>
</fragment>
----

Класс рендерера фрагмента должен расширять базовый класс `FragmentRenderer` с параметрами типов, указывающими корневой компонент и отображаемую сущность, например:

[source,java]
----
@FragmentDescriptor("user-fragment.xml")
@RendererItemContainer("userDc")
public class UserFragment extends FragmentRenderer<FormLayout, User> {
}
----

Аннотация `@RendererItemContainer` используется для указания контейнера данных, принимающего отображаемую сущность.

Для получения более подробной информации см. https://github.com/jmix-framework/jmix/pull/3699[#3699^].

[[asynchronous-tasks]]
=== Асинхронные задачи

Новый бин xref:flow-ui:async-tasks.adoc[UiAsyncTasks] позволяет выполнять операцию в отдельном потоке, используя контекст безопасности текущего пользователя, а затем обновлять UI результатом этой операции.

В отличие от xref:flow-ui:background-tasks.adoc[], это легковесный механизм, основанный на `CompletableFuture`.

[[trimming-in-text-fields]]
=== Обрезка пробелов в текстовых полях

Компоненты `textField` и `textArea` теперь имеют атрибут xref:flow-ui:vc/components/textField.adoc#trimEnabled[trimEnabled], который контролирует, обрезает ли компонент пробелы в начале и в конце введенной строки.

Свойство приложения xref:flow-ui:ui-properties.adoc#jmix.ui.component.default-trim-enabled[jmix.ui.component.default-trim-enabled] задает значение этого атрибута по умолчанию для всего приложения. В новых проектах это свойство равно `true`. Процедура миграции в Studio устанавливает это свойство в `false` для существующих проектов, чтобы минимизировать изменения в поведении.

[[switching-theme-variants]]
=== Переключение вариантов тем

Новый класс `ThemeUtils` содержит методы для переключения вариантов тем во время выполнения. Это позволяет легко переключаться между светлой и темной темами в вашем приложении.

Пример можно найти в разделе xref:flow-ui:themes/themes.adoc#changing-theme-variants-at-runtime[Смена вариантов тем во время выполнения].

[[immediate-validation-of-required-fields]]
=== Немедленная валидация обязательных полей

Новое свойство приложения xref:flow-ui:ui-properties.adoc#jmix.ui.component.immediate-required-validation-enabled[jmix.ui.component.immediate-required-validation-enabled] позволяет отключить валидацию обязательных полей при открытии экрана.

[[grid-export-options]]
=== Настройки экспорта таблиц

При использовании дополнения xref:grid-export:index.adoc[] набор опций экспорта теперь может быть определен конкретным действием экспорта с использованием его метода `setAvailableExportModes()` и соответствующего свойства `availableExportModes` в XML. Набор опций по умолчанию определяется свойством приложения xref:grid-export:properties.adoc#jmix.gridexport.default-export-modes[jmix.gridexport.default-export-modes].

[[using-browser-time-zone]]
=== Использование часового пояса браузера

Если часовой пояс не задан пользователю явно, он может быть получена из веб-браузера при входе. Эта опция контролируется методом `isAutoTimeZone()` интерфейса `HasTimeZone`, реализованного стандартной сущностью `User`, сгенерированной в проектах.

В существующих проектах поведение не изменится, поскольку этот метод по умолчанию возвращает `false`. В новых проектах `User` будет сгенерирован с `isAutoTimeZone()`, возвращающим `true`.

[[advanced-endpoints-security-configuration]]
=== Расширенная настройка безопасности эндпойнтов

Добавлены дополнительные опции для настройки безопасности эндпойнтов при использовании дополнений Authorization Server или OpenID Connect:

* Свойства `jmix.resource-server.authenticated-url-patterns` и `jmix.resource-server.anonymous-url-patterns`
* `AuthenticatedUrlPatternsProvider` и `AnonymousUrlPatternsProvider`
* `AuthenticatedRequestMatcherProvider` и `AnonymousRequestMatcherProvider`

Дополнительную информацию можно найти в разделе xref:security:custom-endpoints.adoc#token-based-authentication[Аутентификация на основе токенов].

Старый `AuthorizedUrlsProvider` помечен как устаревший, но по-прежнему работает, как и свойства `jmix.rest.authenticated-url-patterns` и `jmix.rest.anonymous-url-patterns`. Рекомендуется перенести настройку на новые интерфейсы или свойства.

[[search-improvements]]
=== Улучшение поиска

Новая аннотация `@ExtendedSearch` может быть добавлена к интерфейсу определения индекса для предоставления функциональности поиска "Начинается с". Она инструктирует дополнение Search создать дополнительные "виртуальные" поля для каждого "реального" поля для хранения подготовленных префиксных терминов.

Компонент xref:search:search-in-ui.adoc#search-field[searchField] теперь позволяет пользователям открыть окно *Search settings*, чтобы задать стратегию поиска, размер результатов и, при необходимости, набор сущностей для поиска только в этих сущностях. Если в проекте есть определения индекса с `@ExtendedSearch`, список стратегий включает "Начинается с".

Стратегии `allTermsAnyField` и `allTermsSingleField` помечены как устаревшие.

[[rest-api-improvements]]
=== Улучшение REST API

Универсальный xref:rest:index.adoc[REST API] теперь поддерживает CRUD-операции с DTO-сущностями в эндпойнтах `/entities`. Условия поиска, предоставленные в эндпойнт `entities/:entityName/search`, преобразуются в дерево `Condition` и передаются в `DataManager`. Это позволяет запрашивать DTO-сущности, которые в свою очередь загружаются из другого REST API через xref:rest-ds:index.adoc[].

Условия поиска в формате JSON теперь могут включать объекты в значения свойств, например:

[source,json]
----
{
  "

conditions": [
    {
      "property": "field1",
      "operator": "=",
      "value": {
        "_entityName": "Customer",
        "id": "00000000-0000-0000-0000-000000000001",
        "firstName": "John",
        "lastName": "Doe"
      }
    }
  ]
}
----

[[studio-component-inspector]]
=== Инспектор компонентов Studio

Инспектор компонентов Jmix UI теперь группирует свойства по категориям: *General*, *Data Binding*, *Size*, *Position*, *Look & Feel*, *Other*. Эта новая функция позволяет быстро найти нужное свойство, не просматривая длинный список.

Категории отображаются только в проектах, основанных на Jmix 2.4 и выше.

Кроме того, инспектор компонентов теперь лучше поддерживает свойство `icon`. Можно нажать кнопку "карандаш" в поле значения, чтобы отобразить диалог с перечнем доступных иконок и выбрать из них.

[[studio-support-for-openapi]]
=== Поддержка OpenAPI в Studio

Jmix Studio теперь предоставляет расширенную поддержку интеграции приложений на основе OpenAPI. Эти новые функции включают настройку генератора OpenAPI-клиентов в вашем проекте и автоматическую генерацию DTO-сущностей, мапперов и промежуточных сервисов, что упрощает интеграцию внешних REST API в приложения Jmix.

Практический пример и пошаговая инструкция по использованию этих функций находятся в руководстве xref:openapi-integration-guide:index.adoc[].

[[composite-project-template-for-monorepo]]
=== Шаблон композитного проекта для моно-репозитория

Мы добавили новый шаблон для композитного проекта, который предназначен для размещения в моно-репозитории. Он предоставляет собой простую структуру, где все подпроекты находятся внутри корневого агрегатного проекта:

[source]
----
composite-project/
    subproject1/
        src/
        build.gradle
        settings.gradle
    subproject2/
        src/
        build.gradle
        settings.gradle
    build.gradle
    settings.gradle
    README.md
----

Этот шаблон проекта рекомендуется использовать, если вы не планируете хранить подпроекты в отдельных репозиториях.

[[deprecated-accepts-tenant-interface]]
=== Интерфейс AcceptsTenant объявлен устаревшим

При использовании дополнения xref:multitenancy:index.adoc[] сущность `User` больше не обязана реализовывать интерфейс `io.jmix.multitenancy.core.AcceptsTenant`. Аннотации `@TenantId` на поле `tenant` теперь достаточно.

Интерфейс `AcceptsTenant` объявлен устаревшим и будет удален в будущем мажорном релизе.

[[breaking-changes]]
== Опасные изменения

[[build-problem-with-enablejmixdatarepositories]]
=== Проблема со сборкой при использовании EnableJmixDataRepositories

Когда аннотация `@EnableJmixDataRepositories` используется в главном классе приложения, расширяющем `AppShellConfigurator`, сборка может завершаться с ошибкой, сопровождающейся следующим сообщением:

[source]
----
> Task :vaadinPrepareFrontend FAILED
Could not read com.vaadin.flow.theme.Theme annotation from class com.company.onboarding.OnboardingApplication.
java.lang.TypeNotPresentException: Type [unknown] not present
----

Проблема вызвана https://github.com/vaadin/flow/issues/19616[vaadin/flow#19616^] и будет исправлена в будущих обновлениях.

Чтобы обойти эту проблему, перенесите аннотацию `@EnableJmixDataRepositories` в отдельный класс с аннотацией `@Configuration` в том же пакете, например:

[source,java]
----
package com.company.onboarding;

import io.jmix.core.repository.EnableJmixDataRepositories;
import org.springframework.context.annotation.Configuration;

@EnableJmixDataRepositories
@Configuration
public class OnboardingConfiguration {
}
----

[[protecting-generic-rest-endpoints]]
=== Настройка безопасности эндпойнтов универсального REST

В связи с улучшением конфигурации безопасности эндпойнтов (см. <<advanced-endpoints-security-configuration,выше>>), для настройки защиты эндпойнтов универсального REST API необходимо задать следующее свойство приложения:

[source,properties]
----
jmix.resource-server.authenticated-url-patterns = /rest/**
----

Процедура миграции в Studio автоматически добавляет это свойство в `application.properties`.

[[generic-rest-unauthorized-error]]
=== Ошибка "Unauthorized" эндпойнтов универсального REST

Ранее универсальный REST API возвращал код HTTP 500, если запрос к защищенному эндпойнту выполнялся без заголовка `Authorization`. Теперь правильно возвращается HTTP 401.

[[listmenu-styles]]
=== Стили ListMenu

Стили компонента xref:flow-ui:vc/components/listMenu.adoc[] были изменены, чтобы исправить проблему с обрамлением при фокусировке:

- Изменены отступы и поля для самого `ListMenu`.
- Увеличен `margin-inline-start` для списка подменю.
- Изменены отступы для `MenuBarItem`.

Если вы определяли собственные стили для этого компонента, возможно, их потребуется скорректировать.

См. https://github.com/jmix-framework/jmix/issues/3589[#3589^] для получения дополнительной информации.

[[input-dialog-date-parameters]]
=== Параметры даты в диалоге ввода

Методы `dateTimeParameter()`, `dateParameter()` и `timeParameter()` конструктора xref:flow-ui:dialogs.adoc#input-dialog[диалога ввода] были исправлены: теперь они создают параметры типа `java.util.Date`, `java.sql.Date` и `java.sql.Time` соответственно. Ранее они неверно создавали параметры `LocalDateTime`, `LocalDate` и `LocalTime`.

См. https://github.com/jmix-framework/jmix/issues/3499[#3499^] для получения дополнительной информации.

Процедура миграции в Studio автоматически заменяет вызовы этих методов на вызовы `localDateTimeParameter()`, `localDateParameter()` и `localTimeParameter()`, чтобы сохранить совместимость с возвращаемыми значениями.

[[grid-export-actions-add-on-dependency]]
=== Зависимость на дополнение Grid Export Actions

Ранее дополнение xref:data-tools:index.adoc[] содержало транзитивную зависимость от дополнения xref:grid-export:index.adoc[]. Эта зависимость была удалена, поэтому теперь действия экспорта могут использоваться только в том случае, если дополнение Grid Export Actions включено явно.

Процедура миграции в Studio автоматически добавляет дополнение Grid Export Actions в проект, если он включает дополнение Data Tools.

[[changelog-generation-for-mariadb]]
=== Генерация файлов changelog для MariaDB

Spring Boot 3.3 привносит зависимость от Liquibase 4.27, в котором изменился тип столбца для атрибутов `UUID` с `char(36)` на `uuid`. Это изменение несовместимо с текущей поддержкой баз данных MySQL/MariaDB в Jmix и вызывает некорректное преобразование значений `UUID`.

Если вы используете MariaDB, понизьте версию Liquibase в вашем проекте, добавив следующую зависимость в `build.gradle`:

[source,groovy]
----
implementation 'org.liquibase:liquibase-core:4.25.0!!'
----

См. https://github.com/jmix-framework/jmix/issues/3888[#3888^] для получения дополнительной информации.


[[changelog]]
== Список изменений

* Решенные проблемы в Jmix Framework:

** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A2.4.5[2.4.5^]
** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A2.4.4[2.4.4^]
** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A2.4.3[2.4.3^]
** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A2.4.2[2.4.2^]
** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A2.4.1[2.4.1^]
** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A2.4.0[2.4.0^]

* Решенные проблемы в Jmix Studio:

** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%202.4.3[2.4.3^]
** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%202.4.2[2.4.2^]
** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%202.4.1[2.4.1^]
** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%202.4.0,-2.3.*%20Affected%20versions:%20-SNAPSHOT[2.4.0^]
