= Что нового

В данном разделе приведена информация о новой функциональности и возможных несовместимых изменениях в фреймворке Jmix и Jmix Studio версии {page-component-display-version}. Примите их во внимание при обновлении с предыдущей версии фреймворка.

[IMPORTANT]
====
Для создания новых проектов в Jmix {page-component-display-version} или для апгрейда существующего проекта требуется Studio {page-component-display-version} или более поздней версии, поэтому в первую очередь xref:studio:update.adoc[обновите] плагин Jmix Studio.

Минимальная требуемая версия IntelliJ IDEA / OpenIDE - {minimal-idea-version}.
====

Раздел xref:studio:project.adoc#upgrading-project[Апгрейд проекта] содержит информацию о том, как обновить проект с помощью Studio. Процедура автоматической миграции вносит следующие изменения в ваш проект:

* Обновляет версию Jmix BOM, которая, в свою очередь, определяет версии всех зависимостей.
* Обновляет версию Jmix Gradle plugin.

См. полный список <<breaking-changes,критических изменений>>, которые могут затронуть ваш проект после обновления.

[[new-features]]
== Новая и улучшенная функциональность

[[element-collections]]
=== Поддержка коллекций элементов

Модель данных Jmix теперь поддерживает коллекции базовых типов, объектов `FileRef` или кастомных типов. В JPA-сущностях эти атрибуты-коллекции аннотируются с помощью `@ElementCollection` и хранятся в отдельных таблицах базы данных.

См. раздел xref:data-model:entities.adoc#element-collections[Сущности] о том, как определять коллекции элементов, и xref:data-access:data-manager.adoc#element-collections[Работа с DataManager] о том, как использовать их в запросах.

Атрибуты-коллекции элементов по умолчанию xref:data-access:fetching.adoc#lazy-loading[загружаются лениво] и могут быть включены в фетч-планы при необходимости.

Атрибуты-коллекции элементов могут использоваться в условиях компонента xref:flow-ui:vc/components/genericFilter.adoc[] и могут быть привязаны как значения компонентов xref:flow-ui:vc/components/multiValuePicker.adoc[], xref:flow-ui:vc/components/multiSelectComboBox.adoc[] и xref:flow-ui:vc/components/multiSelectComboBoxPicker.adoc[].

Чтобы создать атрибут-коллекцию элементов в Studio, выберите `ELEMENT_COLLECTION` в раскрывающемся списке *Attribute type* диалога *New Attribute*.

См. также https://github.com/jmix-framework/jmix/issues/1271[#1271^].

[[dynamic-attributes-process-forms]]
=== Динамические атрибуты в формах процесса

Процессные формы на базе экранов Jmix поддерживают загрузку и отображение динамических атрибутов. Для этого используйте аннотацию `@ProcessVariableParam`. Подробнее см. в разделе xref:bpm:bpmn/jmix-view-forms.adoc#loading-dynamic-attributes[Loading Dynamic Attributes].

[[breaking-changes]]
== Критические изменения


[[changelog]]
== Список изменений

* Решенные проблемы в Jmix Framework:

** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A2.8.0[2.8.0^]

* Решенные проблемы в Jmix Studio:

** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%202.8.0,-2.7.*%20Affected%20versions:%20-SNAPSHOT[2.8.0^]
