= Что нового

В данном разделе приведена информация о новой функциональности и возможных несовместимых изменениях в фреймворке Jmix версии {page-component-display-version}. Примите их во внимание при обновлении с предыдущей версии фреймворка.

Для фреймворка {page-component-display-version} нет Studio с соответствующим номером версии. Вместо этого рекомендуется использовать последнюю доступную https://docs.jmix.ru/jmix/studio/install.html[Studio 2.x^].

NOTE: Для создания новых проектов рекомендуется использовать Jmix версии https://docs.jmix.ru/jmix/intro.html[2.x^].

[[upgrade]]
== Обновление

[IMPORTANT]
====
Для автоматического обновления проекта на Jmix {page-component-display-version} требуется Studio 2.5.2 или более поздней версии, поэтому в первую очередь xref:studio:update.adoc[обновите] плагин Jmix Studio.

Studio 2.5.2 требует IntelliJ IDEA или OpenIDE версии 2024.3 или выше.
====

Перейдите к разделу xref:studio:project.adoc#upgrading-project[Апгрейд проекта], чтобы узнать, как обновить проект с помощью Studio. Процедура автоматической миграции вносит следующие изменения в ваш проект:

* Обновляет версию Jmix BOM, которая, в свою очередь, определяет версии всех зависимостей.
* Обновляет версию Jmix Gradle plugin.
* Обновляет версию Gradle wrapper до 8.12.1 в `gradle/wrapper/gradle-wrapper.properties`.

[[updated-dependencies]]
== Обновленные зависимости

Обновлены следующие важные зависимости:

* Vaadin 8.14.4
* EclipseLink 2.7.15
* Embedded Tomcat 9.0.102

[[new-features]]
== Новая и улучшенная функциональность

[[reduced-build-time]]
=== Сокращение времени сборки

Процесс сборки теперь пропускает этап энхансинга сущностей, если они не изменялись с момента последней сборки, что значительно сокращает время сборки для проектов с большой моделью данных.

Например, если вы собрали проект, затем изменили контроллер экрана и снова запустили сборку, в консоли должно появиться сообщение: `Entities enhancing was skipped, because entity classes haven’t been changed since the last build`.

Чтобы отключить это поведение и энхансить все сущности при каждой компиляции, добавьте следующую конфигурацию в `build.gradle`:

[source]
----
jmix {
    entitiesEnhancing {
        skipUnmodifiedEntitiesEnhancing = false
    }
}
----

Подробнее см. https://github.com/jmix-framework/jmix/issues/4254[#4254^].

[[oauth2-tokens-table-cleanup]]
=== Очистка таблицы токенов OAuth2

В таблицы `oauth_access_token` и `oauth_refresh_token` добавлен столбец `expires_at`. Он заполняется датой истечения срока действия, взятой из данных токена при его создании.

Новый сервис `OAuth2ExpiredTokenCleaner` позволяет удалять просроченные access/refresh токены. Если вы хотите вызывать его регулярно, настройте задание Quartz.

Обратите внимание, что существующие записи не будут обновлены при миграции, и в столбце `expires_at` у них останутся значения `null`. Таким образом, `OAuth2ExpiredTokenCleaner` не удалит эти записи. Если нужно очистить старые записи, выполните соответствующий SQL-запрос вручную.

Подробнее см. https://github.com/jmix-framework/jmix/issues/4120[#4120^].

[[table-and-datagrid-columns]]
=== Колонки Table и DataGrid

Раньше, если имя любой колонки изменялось, все пользовательские настройки игнорировались для всего компонента. Теперь настройки колонок применяются для всех неизменённых колонок.

Подробнее см. https://github.com/jmix-framework/jmix/issues/3953[#3953^].

[[action-state-refresh]]
=== Обновление состояния действий

Теперь при открытии каждого экрана в `AfterShowEvent` состояние всех его действий обновляется в соответствии со списком `EnabledRule`.

Подробнее см. https://github.com/jmix-framework/jmix/issues/3907[#3907^].

[[default-dialog-mode-dimensions]]
=== Размеры диалогового режима по умолчанию

Высота и ширина `dialogMode` для генерируемых экранов теперь по умолчанию установлены в `AUTO`.

Подробнее см. https://github.com/jmix-framework/jmix/issues/3952[#3952^].

[[list-of-all-enumerations]]
=== Список всех перечислений

Теперь списки перечислений в UI включают также те перечисления, которые не используются в атрибутах сущностей.

Подробнее см. https://github.com/jmix-framework/jmix/issues/3930[#3930^].

[[breaking-changes]]
== Опасные изменения

Данный релиз не содержит опасных изменений.

[[changelog]]
== Список изменений

* Решенные проблемы в Jmix Framework:

** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A1.7.2[1.7.2^]
** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A1.7.1[1.7.1^]
** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A1.7.0[1.7.0^]
