= Что нового

В данном разделе приведена информация о новой функциональности и возможных несовместимых изменениях в фреймворке Jmix и Jmix Studio версии {page-component-display-version}. Примите их во внимание при обновлении с предыдущей версии фреймворка.

[IMPORTANT]
====
Для создания новых проектов в Jmix {page-component-display-version} или для апгрейда существующего проекта требуется Studio {page-component-display-version} или более поздней версии, поэтому в первую очередь xref:studio:update.adoc[обновите] плагин Jmix Studio.

Минимальная требуемая версия IntelliJ IDEA - {minimal-idea-version}.
====

Раздел xref:studio:project.adoc#upgrading-project[Апгрейд проекта] содержит информацию о том, как обновить проект с помощью Studio. Процедура автоматической миграции вносит следующие изменения в ваш проект:

* Обновляет версию Jmix BOM, которая, в свою очередь, определяет версии всех зависимостей.
* Обновляет версию Jmix Gradle plugin.
// * Обновляет версию Gradle wrapper до 8.12.1 в `gradle/wrapper/gradle-wrapper.properties`.

См. полный список <<breaking-changes,критических изменений>>, которые могут затронуть ваш проект после обновления.

[[updated-dependencies]]
== Обновленные зависимости

Следующие основные зависимости были обновлены:

// * Spring Boot https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.4-Release-Notes[3.4^].
//
// * Vaadin https://github.com/vaadin/platform/releases/tag/24.6.0[24.6^].

[[new-features]]
== Новая и улучшенная функциональность

=== Компонент Switch

Новый компонент xref:flow-ui:vc/components/switch.adoc[switch] предназначен для представления бинарного выбора, позволяя пользователям переключаться между двумя состояниями (например, `true`/`false`).

[[breaking-changes]]
== Критические изменения

[[changelog]]
== Список изменений

* Решенные проблемы в Jmix Framework:

// ** https://github.com/jmix-framework/jmix/issues?q=is%3Aclosed+milestone%3A2.5.0[2.5.0^]

* Решенные проблемы в Jmix Studio:

// ** https://youtrack.jmix.io/issues/JST?q=Fixed%20in%20builds:%202.5.0,-2.4.*%20Affected%20versions:%20-SNAPSHOT[2.5.0^]
