= Свойства Jmix UI
:page-aliases: backoffice-ui:app-properties.adoc

[[common]]
== Common

[[jmix.ui.app-window-mode]]
=== jmix.ui.app-window-mode

Determines an initial mode for the main application window – `TABBED` or `SINGLE`. In the `SINGLE` mode, when a screen opens with the `NEW_TAB` parameter, it completely replaces the current screen instead of opening a new tab.

Default value: `TABBED`.

[[jmix.ui.composite-menu]]
=== jmix.ui.composite-menu

When set to `true`, the framework will merge all the `menu.xml` definitions from all xref:jmix:ROOT:add-ons.adoc[add-ons] including your definitions in xref:ui:menu-config.adoc[menu.xml] and render the menu as a superset of all those items.

When set to `false`, your application `menu.xml` is the only menu that will be considered when rendering the menu.

Using `false` is a good idea when you completely control the menu entries that are rendered. It allows you to easily remove, change and reorder menu entries from, for example, the *Administration* menu.

The downside is that you have to copy all entries that you want to appear there. That is, the menu items inherited from the add-ons won't appear in the menu, so you need to add them manually.

Default value: `true`.

//[[jmix.ui.data-grid.default-column-max-width]]
//=== jmix.ui.data-grid.default-column-max-width
//
//Defines the maximum allowed pixel width of the xref:vcl/components/data-grid.adoc[DataGrid] column when it is set to expand. It can be overridden for a concrete column using the xref:vcl/components/data-grid.adoc#column-maximum-width[maximumWidth] XML attribute.
//
//Default value: `-1`. The value of `-1` means there is no limitations.
//
//[[jmix.ui.data-grid.default-column-min-width]]
//=== jmix.ui.data-grid.default-column-min-width
//
//Defines the minimum guaranteed pixel width of the xref:vcl/components/data-grid.adoc[DataGrid] column when it is set to expand. It can be overridden for a concrete column using the xref:vcl/components/data-grid.adoc#column-minimum-width[minimumWidth] XML attribute.
//
//Default value: `10`.

[[jmix.ui.default-max-fetch-size]]
=== jmix.ui.default-max-fetch-size

Defines the default maximum number of entity instances that can be loaded to the UI layer.

Default value: `10000`

See also <<jmix.ui.entity-max-fetch-size,jmix.ui.entity-max-fetch-size>>.

[[jmix.ui.default-page-size]]
=== jmix.ui.default-page-size

Defines the default page size for xref:ui:vcl/components/pagination.adoc[] and xref:ui:vcl/components/simple-pagination.adoc[] components.

Default value: `50`

See also <<jmix.ui.entity-page-size,jmix.ui.entity-max-page-size>>.

[[jmix.ui.default-screen-can-be-closed]]
=== jmix.ui.default-screen-can-be-closed

Defines whether the default screen can be closed by close button, *ESC* button or `TabSheet` context menu when `TABBED` <<jmix.ui.app-window-mode,work area mode>> is used.

Default value: `true`.

[[jmix.ui.default-screen-id]]
=== jmix.ui.default-screen-id

Defines a screen to be opened after login. This setting will be applied to all users.

For example:

[source,properties]
----
jmix.ui.default-screen-id = sample_Order.browse
----

[[jmix.ui.entity-max-fetch-size]]
=== jmix.ui.entity-max-fetch-size

Defines the default maximum number of entity instances that can be loaded to the UI layer for a particular entity.

The following example configures the maximum fetch size for two entities. For all other entities the value from <<jmix.ui.default-max-fetch-size,jmix.ui.default-max-fetch-size>> is used.

[source,properties]
----
jmix.ui.entity-max-fetch-size.Product = 500
jmix.ui.entity-max-fetch-size.Customer = 1000
----

[[jmix.ui.entity-page-size]]
=== jmix.ui.entity-page-size

Defines the default page size for xref:ui:vcl/components/pagination.adoc[] and xref:ui:vcl/components/simple-pagination.adoc[] components for a particular entity.

The following example configures the default page size for two entities. For all other entities the value from <<jmix.ui.default-page-size,jmix.ui.default-page-size>> is used.

[source,properties]
----
jmix.ui.entity-page-size.Product = 100
jmix.ui.entity-page-size.Customer = 500
----

[[jmix.ui.exception-dialog-modal]]
=== jmix.ui.exception-dialog-modal

Determines whether an xref:ui:dialogs.adoc#exception-dialog[Exception dialog] should be opened as modal by default.

Default value: `false`.


[[jmix.ui.icons-config]]
=== jmix.ui.icons-config

Defines the icon sets to be registered for the application.

For example:

[source,properties]
----
jmix.ui.icons-config=ui.ex1.icon.MyIcon \
ui.ex1.icon.FontAwesome5Icon \
ui.ex1.icon.NewIcon
----

The icons from the registered icon sets are displayed in the *ICON SET* tab of the xref:studio:screen-designer.adoc#icon-editor[Choose icon] dialog.

[[jmix.ui.main-screen-id]]
=== jmix.ui.main-screen-id

An identifier of a screen to be used as xref:ui:screens/root-screens.adoc#main-screen[main screen] of the application.

Default value: `MainScreen`.

[[jmix.ui.max-tab-count]]
=== jmix.ui.max-tab-count

Defines the maximum number of tabs that can be opened in the main application window. The value of 0 disables this limitation.

Default value: `20`.

[[jmix.ui.menu-config]]
=== jmix.ui.menu-config

Defines the path to the xref:ui:menu-config.adoc[menu.xml] file.
//TODO: добавить ссылку на Resources после выполнения https://github.com/jmix-framework/jmix-docs/issues/390
The file is loaded using the `Resources` interface, so it can be located in classpath or in the configuration directory.

For example:

[source,properties,indent=0]
----
include::example$/ex2/src/main/resources/application.properties[tags=menu-config]
----

[[jmix.ui.login-screen-id]]
=== jmix.ui.login-screen-id

An identifier of a screen to be used as xref:ui:screens/root-screens.adoc#login-screen[login screen] of the application.

Default value: `LoginScreen`.

[[jmix.ui.screen.close-shortcut]]
=== jmix.ui.screen.close-shortcut

Defines the keyboard shortcut that closes the current xref:ui:screens.adoc[screen].

Default value: `ESCAPE`.

[[jmix.ui.screen.use-save-confirmation]]
=== jmix.ui.screen.use-save-confirmation

Defines the layout of the dialog displayed when a user attempts to close a xref:ui:screens.adoc[screen] with unsaved changes in `DataContext`.

Value of `true` corresponds to a layout with three possible actions: "Save changes", "Don’t save", "Don’t close the screen".

The value of `false` corresponds to a form with two options: "Close the screen without saving changes", "Don’t close the screen".

Default value: `true`.

[[jmix.ui.show-bread-crumbs]]
=== jmix.ui.show-bread-crumbs

If set to false, the breadcrumbs panel which normally appears on top of the main window working area is hidden.

Default value: `true`.

[[jmix.ui.theme-config]]
=== jmix.ui.theme-config

Defines a `<theme-name>-theme.properties` file or files that store theme variables, such as default popup window dimensions and input field width.

Default value:
[source, code,indent=0]
----
io/jmix/ui/theme/helium-theme.properties \
io/jmix/ui/theme/halo-theme.properties \
io/jmix/ui/theme/hover-theme.properties
----

[[jmix.ui.theme.default-mode-to-use]]
=== jmix.ui.theme.default-mode-to-use

Defines the name of the xref:themes/custom_theme.adoc#helium-configuration[color preset] to be used if no other settings are available. Either cookie or user settings obtained from `UserSettingService` have precedence over this value.

[[jmix.ui.theme.default-size-to-use]]
=== jmix.ui.theme.default-size-to-use

Defines the name of the xref:themes/custom_theme.adoc#helium-configuration[theme size preset] to be used if no other settings are available. Either cookie or user settings obtained from `UserSettingService` have precedence over this value.

[[jmix.ui.theme.modes]]
=== jmix.ui.theme.modes

Defines the list of available xref:themes/custom_theme.adoc#helium-configuration[theme modes], that is, color presets. Default modes are `light` and `dark`.

Default value:

[source, code,indent=0]
----
jmix.ui.theme.modes = light, dark
----

[[jmix.ui.theme.sizes]]
=== jmix.ui.theme.sizes

Defines the list of available xref:themes/custom_theme.adoc#helium-configuration[theme size presets]. Default theme size presets are `small`, `medium`, `large`.

Default value:

[source, code,indent=0]
----
jmix.ui.theme.sizes = small, medium, large
----

[[jmix.ui.theme.name]]
=== jmix.ui.theme.name

Defines the name of the xref:themes.adoc[theme] used as default. See also <<jmix.ui.theme-config,jmix.ui.theme-config>>.

Default value: `helium`.

[[jmix.ui.url-handling-mode]]
=== jmix.ui.url-handling-mode

Defines how URL changes should be handled.

Possible values are the elements of the `UrlHandlingMode` enumeration:

* `NONE` - URL changes are not handled at all.
* `URL_ROUTES` - changes are handled by the xref:url-history-navigation.adoc[URL History and Navigation] feature.

Default value: `URL_ROUTES`.

[[jmix.ui.background-task-timeout-check-interval]]
=== jmix.ui.background-task-timeout-check-interval

Defines interval in ms for checking timeout of a xref:background-tasks.adoc[Background Task].

Default value: `5000`.

[[jmix.ui.background-task.threads-count]]
=== jmix.ui.background-task.threads-count

Defines number of a xref:background-tasks.adoc[Background Task] threads.

Default value: `10`.

[[jmix.ui.view-file-extensions]]
=== jmix.ui.view-file-extensions

For the xref:files:downloading-files.adoc#downloader[Downloader] bean, defines the list of file extensions to be shown in the web browser tab instead of downloading them automatically.

Default value: `htm,html,jpg,png,jpeg,pdf`.

[[components]]
== Components

[[jmix.ui.component.combo-box-page-length]]
=== jmix.ui.component.combo-box-page-length

Defines the default number of options on one page of the drop-down list in the xref:vcl/components/combo-box.adoc[ComboBox] and xref:vcl/components/entity-combo-box.adoc[EntityComboBox] components. It can be overridden for a concrete instance of the component using the xref:vcl/components/combo-box.adoc#paging[pageLength] XML attribute.

Default value: `10`.

[[jmix.ui.component.entity-field-actions]]
=== jmix.ui.component.entity-field-actions

Defines actions to be added to the selection component for the specified entity in generic mechanisms like xref:vcl/components/filter.adoc[] parameters or editable cells of xref:vcl/components/table.adoc[] and xref:vcl/components/data-grid.adoc[].

For example, to use xref:actions/standard-actions/entity-lookup-action.adoc[], xref:actions/standard-actions/entity-open-action.adoc[] and xref:actions/standard-actions/entity-clear-action.adoc[] in the components selecting the `uiex1_City` entity, set the property as follows:

[source,properties]
----
jmix.ui.component.entity-field-actions.uiex1_City = entity_lookup,entity_open,entity_clear
----

[[jmix.ui.component.entity-field-type]]
=== jmix.ui.component.entity-field-type

Defines the component to be used for selecting the specified entity in generic mechanisms like xref:vcl/components/filter.adoc[] parameters or editable cells of xref:vcl/components/table.adoc[] and xref:vcl/components/data-grid.adoc[]. This component should implement the `EntityPicker` interface.

Specify the component's XML name as a value of this property. For example, to use xref:vcl/components/entity-combo-box.adoc[EntityComboBox] for selecting the `uiex1_City` entity, set the property as follows:

[source,properties]
----
jmix.ui.component.entity-field-type.uiex1_City = entityComboBox
----

By default, generic mechanisms use the xref:vcl/components/entity-picker.adoc[EntityPicker] component.

[[jmix.ui.component.filter-auto-apply]]
=== jmix.ui.component.filter-auto-apply

When set to `true`, the xref:vcl/components/filter.adoc[Filter] component works in the immediate mode when every change of filter parameters automatically reloads data. When set to `false`, filter will be applied only after the *Refresh* button is clicked. This property can be overridden for a concrete instance of the `Filter` component using the xref:vcl/components/filter.adoc#filter-attribute-auto-apply[autoApply] XML attribute.

Default value: `true`.

[[jmix.ui.component.filter-columns-count]]
=== jmix.ui.component.filter-columns-count

Sets the default number of columns for placing conditions on the filter panel. It can be overridden for a concrete instance of the `Filter` component using the xref:vcl/components/filter.adoc#filter-attribute-columns-count[columnsCount] XML attribute.

Default value: `3`.

[[jmix.ui.component.filter-properties-hierarchy-depth]]
=== jmix.ui.component.filter-properties-hierarchy-depth

Defines the properties hierarchy depth in the xref:vcl/components/filter.adoc#add-condition[Add Condition] editor in filter. For example, if the depth value is 2, then you can select an entity attribute `contractor.city.country`, if the value is 3, then `contractor.city.country.name`, etc.

Default value: `2`.

[[jmix.ui.component.filter-show-configuration-id-field]]
=== jmix.ui.component.filter-show-configuration-id-field

Determines whether the *Configuration id* field should be visible in the xref:vcl/components/filter.adoc#run-time-configuration[Configuration editor] screen of the `Filter` component. By default, the *Configuration id* field is not shown, and the `configurationId` is generated depending on the `configurationName`.

Default value: `false`.

[[jmix.ui.component.html-sanitizer-enabled]]
=== jmix.ui.component.html-sanitizer-enabled

Determines whether the `HtmlSanitizer` bean should be used by the UI components implementing the `HasHtmlSanitizer` interface to prevent cross-site scripting (XSS) in HTML content. The sanitization can also be enabled or disabled by individual components using xref:vcl/xml.adoc#html-sanitizer-enabled[htmlSanitizerEnabled] attribute.

Default value: `true`.

[[jmix.ui.component.main-tab-sheet-mode]]
=== jmix.ui.component.main-tab-sheet-mode

If set to `MANAGED`, main window TabSheet doesn’t unload components from the tab when the user selects another tab.

Default value: `DEFAULT`.

[[jmix.ui.component.main-tab-sheet-next-tab-shortcut]]
=== jmix.ui.component.main-tab-sheet-next-tab-shortcut

Keyboard shortcut to switch to the next tab in the main window TabSheet.

Default value: `CTRL-SHIFT-PAGE_DOWN`.

[[jmix.ui.component.main-tab-sheet-previous-tab-shortcut]]
=== jmix.ui.component.main-tab-sheet-previous-tab-shortcut

Keyboard shortcut to switch to the previous tab in the main window TabSheet.

Default value: `CTRL-SHIFT-PAGE_UP`.

[[jmix.ui.component.pagination-items-per-page-options]]
=== jmix.ui.component.pagination-items-per-page-options

Defines the options for the drop-down list that can be used as a number of items per page for xref:vcl/components/pagination.adoc[Pagination]. To configure a custom list of options for a concrete instance of the `Pagination` component, use the xref:vcl/components/pagination.adoc#items-per-page-options[itemsPerPageOptions] XML attribute.

Default value: `20`, `50`, `100`, `500`, `1000`, `5000`.


[[jmix.ui.component.upload-field-max-upload-size-mb]]
=== jmix.ui.component.upload-field-max-upload-size-mb

Maximum file size (in megabytes) that can be uploaded using the xref:vcl/components/file-upload-field.adoc[FileUploadField], xref:vcl/components/file-multi-upload-field.adoc[FileMultiUploadField], xref:vcl/components/file-storage-upload-field.adoc[FileStorageUploadField]  components.

Default value: `20`.

