= image
:page-aliases: vcl/components/image.adoc

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/image-simple" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

`image` предназначен для отображения изображений из различных источников. Компонент может быть привязан к xref:vc/common-attributes.adoc#dataContainer[контейнеру данных] или настроен программно.

[cols="1h,6", grid=none]
|===
|XML-элемент
|`image`
|Java-класс
|`JmixImage`
|Атрибуты
|xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
<<alternateText, alternateText>> -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan]
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#property[property] -
<<resource, resource>> -
xref:vc/common-attributes.adoc#text[text] -
<<themeNames,themeNames>> -
xref:vc/common-attributes.adoc#title[title] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#whiteSpace[whiteSpace] -
xref:vc/common-attributes.adoc#width[width]
|Обработчики
|xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
<<ClickEvent, ClickEvent>> -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent]
|===

[[basics]]
== Основы

Изображение может быть представлено как атрибут сущности типа `FileRef` или `byte[]`. В примере ниже атрибут `picture` сущности `User` является ссылкой на файл в xref:files:file-storage.adoc[файловом хранилище]:

[source,java,indent=0]
----
include::example$onboarding/src/main/java/com/company/onboarding/entity/User.java[tags=user-entity;picture]
----

Для отображения изображения, предоставляемого этим атрибутом, укажите его в компоненте. Для этого задайте атрибуты xref:vc/common-attributes.adoc#dataContainer[dataContainer] и xref:vc/common-attributes.adoc#property[property].

[source, xml, indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/view/htmlcomponent/image/image-view.xml[tags=data;instance;facets;layout;fileRefImage]
----

[[resources]]
== Ресурсы

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.ru/ui-samples/sample/image-resources" class="live-demo-btn" target="_blank">ДЕМО</a>
</div>
++++

Кроме того, компонент `image` может отображать изображения из различных ресурсов. Вы можете задать тип ресурса декларативно с помощью вложенных XML-элементов, описанных ниже, или программно с помощью метода `setSrc()`.

[[static-resource]]
=== Статический ресурс

Изображение может быть предоставлено приложением статически.

По умолчанию статический контент загружается из каталогов `/static`, `/public`, `/resources` или `/META-INF/resources` в classpath (подробности смотрите в https://docs.spring.io/spring-boot/docs/current/reference/html/web.html#web.servlet.spring-mvc.static-content[документации Spring Boot^]). Чтобы сконфигурировать анонимный доступ к статическим ресурсам, см. раздел xref:security:custom-endpoints.adoc#static-public-resources[Безопасность: Статические публичные ресурсы].

* В XML:
+
Если ваше изображение находится
в `/src/main/resources/META-INF/resources`, например,  `/src/main/resources/META-INF/resources/icons/icon.png`, вы можете указать ресурс следующим образом:
+
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/view/htmlcomponent/image/image-view.xml[tags=static-resource]
----
+
* В Java:
+
[source,java,indent=0]
----
include::example$onboarding/src/main/java/com/company/onboarding/view/htmlcomponent/image/ImageResourcesView.java[tags=image-static]
----

[[url-resource]]
=== Ресурс URL

Аналогично, изображение может быть загружено из произвольного URL.

* В XML:
+
[source, xml, indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/view/htmlcomponent/image/image-view.xml[tags=url-resource]
----

* В Java:
+
[source,java,indent=0]
----
include::example$onboarding/src/main/java/com/company/onboarding/view/htmlcomponent/image/ImageResourcesView.java[tags=image-url]
----

// [[file-resource]]
// === FileResource

// [[file-storage-resource]]
// === FileStorageResource

[[stream-resource]]
=== Программный ресурс

Изображение может быть предоставлено через `DownloadHandler`.

Используйте фабричные методы `com.vaadin.flow.server.streams.DownloadHandler` для создания обработчика источника изображения.

Например, `DownloadHandler.forClassResource()` создает обработчик для изображения, расположенного в classpath приложения.

[source,java,indent=0]
----
include::example$onboarding/src/main/java/com/company/onboarding/view/htmlcomponent/image/ImageResourcesView.java[tags=image-stream]
----

// [[theme-resource]]
// === ThemeResource

== Атрибуты

В Jmix существует множество xref:vc/common-attributes.adoc[общих атрибутов], которые служат одной цели для всех компонентов.

Следующие атрибуты специфичны для `image`:

[cols="1h,5,1", grid=rows, frame=none]
|===
|*Название*
|*Описание*
|*Значение по умолчанию*
|[[alternateText]]alternateText
|Задает альтернативный текст для изображения на случай, если ресурс не задан или недоступен.
|-
|[[resource]]resource
|Указывает расположение изображения. Смотрите <<resources, ресурсы>>.
|-
|[[themeNames]]themeNames
|Добавляет тему к компоненту. Возможные значения: `fill`, `contain`, `cover`, `scale-down`.
|-
|===

[[handlers]]
== Обработчики

В Jmix существует множество xref:vc/common-handlers.adoc[общих обработчиков], которые настраиваются одинаково для всех компонентов.

Следующие обработчики специфичны для `image`:

include::../handler-generation-tip.adoc[]

[cols="1h,6", grid=rows, frame=none]
|===
|*Название*
|*Описание*
|[[ClickEvent]]ClickEvent
|`com.vaadin.flow.component.ClickEvent` возникает при клике на компонент. Этот обработчик должен указывать один из трех субъектов для определения количества кликов:

*click* – событие возникает при любом клике на компонент.

*singleClick* – событие возникает после таймаута, чтобы убедиться, что это не двойной клик.

*doubleClick* – событие возникает при двойном клике на компонент.
|===