= image
:page-aliases: vcl/components/image.adoc

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/image-simple" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

`image` is designed to display images from different sources. The component can be bound to a xref:vc/common-attributes.adoc#dataContainer[data container] or configured programmatically.

[cols="1h,6", grid=none]
|===
|XML Element
|`image`
|Java Class
|`JmixImage`
|Attributes
|xref:vc/common-attributes.adoc#id[id] -
xref:vc/common-attributes.adoc#alignSelf[alignSelf] -
<<alternateText, alternateText>> -
xref:vc/common-attributes.adoc#ariaLabel[ariaLabel] -
xref:vc/common-attributes.adoc#ariaLabelledBy[ariaLabelledBy] -
xref:vc/common-attributes.adoc#classNames[classNames] -
xref:vc/common-attributes.adoc#colspan[colspan]
xref:vc/common-attributes.adoc#css[css] -
xref:vc/common-attributes.adoc#dataContainer[dataContainer] -
xref:vc/common-attributes.adoc#enabled[enabled] -
xref:vc/common-attributes.adoc#height[height] -
xref:vc/common-attributes.adoc#maxHeight[maxHeight] -
xref:vc/common-attributes.adoc#maxWidth[maxWidth] -
xref:vc/common-attributes.adoc#minHeight[minHeight] -
xref:vc/common-attributes.adoc#minWidth[minWidth] -
xref:vc/common-attributes.adoc#property[property] -
<<resource, resource>> -
xref:vc/common-attributes.adoc#text[text] -
<<themeNames,themeNames>> -
xref:vc/common-attributes.adoc#title[title] -
xref:vc/common-attributes.adoc#visible[visible] -
xref:vc/common-attributes.adoc#whiteSpace[whiteSpace] -
xref:vc/common-attributes.adoc#width[width]
|Handlers
|xref:vc/common-handlers.adoc#AttachEvent[AttachEvent] -
<<ClickEvent, ClickEvent>> -
xref:vc/common-handlers.adoc#DetachEvent[DetachEvent]
|===

[[basics]]
== Basics

An image can be represented as an entity attribute of `FileRef` or `byte[]` type. In the example below, the `picture` attribute of the `User` entity is a reference to a file in xref:files:file-storage.adoc[file storage]:

[source,java,indent=0]
----
include::example$onboarding/src/main/java/com/company/onboarding/entity/User.java[tags=user-entity;picture]
----

To display the image provided by this attribute, specify it in the component. For that, specify the xref:vc/common-attributes.adoc#dataContainer[data container] and xref:vc/common-attributes.adoc#property[property] attributes.

[source, xml, indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/view/htmlcomponent/image/image-view.xml[tags=data;instance;facets;layout;fileRefImage]
----

[[resources]]
== Resources

++++
<div class="jmix-ui-live-demo-container">
    <a href="https://demo.jmix.io/ui-samples/sample/image-resources" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

Alternatively, the `image` component can display images from different resources. You can set the resource type declaratively using the nested XML elements described below, or programmatically using the `setSrc()` method.

[[static-resource]]
=== Static Resource

An image can be served statically by the application.

By default, static content is served from `/static`, `/public`, `/resources`, or `/META-INF/resources` directories of the classpath (see details in the https://docs.spring.io/spring-boot/docs/current/reference/html/web.html#web.servlet.spring-mvc.static-content[Spring Boot documentation^]). To configure anonymous access to static resources, see xref:security:custom-endpoints.adoc#static-public-resources[Security: Static Public Resources].

* In XML:
+
For example, if your image is located
under `/src/main/resources/META-INF/resources`, such as `/src/main/resources/META-INF/resources/icons/icon.png`, you can specify the resource as follows:
+
[source,xml,indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/view/htmlcomponent/image/image-view.xml[tags=static-resource]
----
+
* In Java:
+
[source,java,indent=0]
----
include::example$onboarding/src/main/java/com/company/onboarding/view/htmlcomponent/image/ImageResourcesView.java[tags=image-static]
----

[[url-resource]]
=== URL Resource

Similarly, an image can be loaded from an arbitrary URL.

* In XML:
+
[source, xml, indent=0]
----
include::example$onboarding/src/main/resources/com/company/onboarding/view/htmlcomponent/image/image-view.xml[tags=url-resource]
----

* In Java:
+
[source,java,indent=0]
----
include::example$onboarding/src/main/java/com/company/onboarding/view/htmlcomponent/image/ImageResourcesView.java[tags=image-url]
----

// [[file-resource]]
// === FileResource

// [[file-storage-resource]]
// === FileStorageResource

[[stream-resource]]
=== Programmatic Resource

An image can be provided by a `DownloadHandler`.

Use the `com.vaadin.flow.server.streams.DownloadHandler` factory methods to create a handler for the image source.

For example, `DownloadHandler.forClassResource()` creates a handler for an image located in the application classpath.

[source,java,indent=0]
----
include::example$onboarding/src/main/java/com/company/onboarding/view/htmlcomponent/image/ImageResourcesView.java[tags=image-stream]
----

// [[theme-resource]]
// === ThemeResource

== Attributes
xref:vc/common-attributes.adoc[Common attributes] serve the same purpose for all components.
The following attributes are specific to `span`:

[cols="1h,5,1", grid=rows, frame=none]
|===
|*Name*
|*Description*
|*Default*
|[[alternateText]]alternateText
|Sets an alternate text for an image in case the resource is not set or unavailable.
|-
|[[resource]]resource
|Specifies the location of the image. See <<resources, resources>>.
|-
|[[themeNames]]themeNames
|Adds a theme to the component. Possible values: `fill`, `contain`, `cover`, `scale-down`.
|-
|===

[[handlers]]
== Handlers

xref:vc/common-handlers.adoc[Common handlers] are configured in the same way for all components.
The following handlers are specific to `image`:

include::../handler-generation-tip.adoc[]

[cols="1h,6", grid=rows, frame=none]
|===
|*Name*
|*Description*
|[[ClickEvent]]ClickEvent
|The `com.vaadin.flow.component.ClickEvent` is fired when the component is clicked. This handler must specify one of the three subjects to detect the number of clicks:

*click* – fires the event whenever the component is clicked.

*singleClick* – fires the event after a timeout to ensure it is not a double click.

*doubleClick* – fires the event when the component is double-clicked.
|===