= Kubernetes Cluster

In this guide, we describe how to deploy a Jmix application to a Kubernetes cluster. We'll use the single-node Kubernetes cluster provided by https://minikube.sigs.k8s.io/[minikube^], which you can install on your development machine and test the deployment locally.

The guide focuses on what should be configured in the application in order to run on Kubernetes. You can complete the guide and prepare your application for such deployment without any previous knowledge of Kubernetes. However, to run real production deployments, you should be familiar with this technology.

For more information about working in a cluster, see the xref:features:cluster-communication.adoc[] section.

[[app-configuration]]
== Configure Your Application

[[build-image]]
=== Configure Image Building

The Spring Boot Gradle plugin provides the `bootBuildImage` task which builds your application and creates a Docker image with it. To specify the image name, add the following section to your `build.gradle` file:

[source,groovy,indent=0]
----
include::example$/ex1/build.gradle[tags=bootBuildImage]
----

[[hazelcast-configuration]]
=== Configure Hazelcast

Jmix framework modules use various caches: JPA entity and query caches, pessimistic locks, dynamic attributes configuration, etc. When running in a cluster, a Jmix application requires coordination of caches between cluster nodes.

All Jmix caches support coordination through https://docs.hazelcast.com/imdg/latest/index.html[Hazelcast^]. In this guide, we'll use Hazelcast in the embedded mode, together with the https://github.com/hazelcast/hazelcast-kubernetes[hazelcast-kubernetes^] plugin for auto-discovery in Kubernetes environment.

Follow the steps below to configure Hazelcast for coordination of caches in a Kubernetes cluster.

. Add the Hazelcast dependency to your `build.gradle`:
+
[source,groovy,indent=0]
----
include::example$/ex1/build.gradle[tags=dependencies]
----

. Specify Hazelcast as JCache provider by adding the following property to the `application.properties` file:
+
[source,properties,indent=0]
----
include::example$/ex1/src/main/resources/application.properties[tags=properties]
----

. Create `hazelcast.yaml` file in the `resources` root:
+
[source,yaml,indent=0]
----
include::example$/ex1/src/main/resources/hazelcast.yaml[]
----

The `hazelcast.network.join.kubernetes.service-name` property must point to the application service defined in the <<app-service-config,application service configuration file>>.

Notice that the `hazelcast.network.join.kubernetes.enabled` property is set to `false` in this file. It's done to be able to run your application locally without Kubernetes. The property is set to `true` when the application actually runs on Kubernetes, using the `HZ_NETWORK_JOIN_KUBERNETES_ENABLED` environment variable in the application service configuration file.

[[k8s-config]]
== Create Kubernetes Configuration Files

Create `k8s` folder in the project root and add the files listed below to it.

[[db-service-config]]
=== Database Service Configuration

This file defines the PostgreSQL database service named `sample-db-service`.

.k8s/db.yaml
[source,yaml,indent=0]
----
include::example$/ex1/k8s/db.yaml[]
----

[[app-service-config]]
=== Application Service Configuration

This file defines the application service named `sample-app-service`. It uses the `mycompany/sample-app` Docker <<build-image,image>> with our application.

.k8s/app.yaml
[source,yaml,indent=0]
----
include::example$/ex1/k8s/app.yaml[]
----

[[load-balancer-config]]
=== Load-balancer Configuration

The Jmix xref:flow-ui:index.adoc[] expects that all requests from a user come to the same server. In a cluster environment with multiple servers it requires a load-balancer with sticky sessions. Below is the configuration of NGINX Ingress Controller with https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#session-affinity[session affinity^].

.k8s/balancer.yaml
[source,yaml,indent=0]
----
include::example$/ex1/k8s/balancer.yaml[]
----

[[hazelcast-rbac-config]]
=== Hazelcast Access Control Configuration

.k8s/hazelcast-rbac.yaml
[source,yaml,indent=0]
----
include::example$/ex1/k8s/hazelcast-rbac.yaml[]
----

[[local-k8s]]
== Set up Local Kubernetes

. Make sure Docker is running on your machine. The below command displays the Docker version:
+
[source,shell script]
----
docker -v
----
+
If the command fails, see https://docs.docker.com/get-docker[Docker documentation^] for how to install and run Docker.

. Install Minikube as described in its https://minikube.sigs.k8s.io/docs/start[installation instructions^].

. Run Minikube:
+
[source,shell script]
----
minikube start --vm-driver=virtualbox
----

. Enable Ingress Controller:
+
[source,shell script]
----
minikube addons enable ingress
----

. Configure the Kubernetes command-line tool to use Minikube:
+
[source,shell script]
----
kubectl config use-context minikube
----

. To open the Kubernetes dashboard in the web browser, run in a separate terminal:
+
[source,shell script]
----
minikube dashboard
----

[[build-and-run-app]]
== Build and Run Application

. Build Docker image:
+
[source,shell script]
----
./gradlew -Pvaadin.productionMode=true bootBuildImage
----

. Load the image into Minikube:
+
[source,shell script]
----
minikube image load mycompany/sample-app:latest
----

. Apply Kubernetes <<k8s-config,configuration files>>:
+
[source,shell script]
----
kubectl apply -f ./k8s
----

. To increase the number of application instances, use the following command:
+
[source,shell script]
----
kubectl scale deployment sample-app --replicas=2
----

. Figure out the cluster IP address:
+
[source,shell script]
----
minikube ip
----
+
Use this address to open the application in the web browser, for example: `++http://192.168.99.100++`