= Пессимистическая блокировка

Пессимистическая блокировка может использоваться, когда существует высокая вероятность одновременного редактирования одного и того же экземпляра сущности. В таких случаях xref:data-model:entities.adoc#versioned-trait[оптимистическая блокировка], основанная на управлении версиями сущностей, приводит к слишком многим конфликтам.

Пессимистическая блокировка явно блокирует экземпляр сущности, когда он открывается на экране редактирования UI или в подробном представлении Flow UI. В результате только один пользователь может редактировать этот конкретный экземпляр сущности в данный момент времени.

Также механизм пессимистической блокировки Jmix также использоваться для управления одновременным выполнением произвольных процессов. Ключевым преимуществом является распределение блокировок, поскольку они реплицируются в кластере.

[[installation]]
== Установка

Для автоматической установки через маркетплейс Jmix обратитесь к инструкции в разделе xref:ROOT:add-ons.adoc#installation[Дополнения].

Чтобы установить дополнение вручную, добавьте следующие зависимости в ваш `build.gradle`:

[source,groovy,indent=0]
----
include::example$/pslock-ex1/build.gradle[tags=dependencies]
----

include::ROOT:single-menu-note.adoc[]

[[usage]]
== Использование

Чтобы включить пессимистическую блокировку для любой сущности, добавьте аннотацию `@PessimisticLock` к классу сущности, например:

[source,java,indent=0]
----
include::example$/pslock-ex1/src/main/java/com/company/demo/entity/Document.java[tags=pessimistic-lock]
----

Стандартный экран деталей сущности автоматически обрабатывает пессимистичное блокирование, переключаясь в режим "только для чтения", если сущность кем-то уже заблокирована.

Вы также можете заблокировать объект в своем коде, используя бин `LockManager`. Например:

[source,java,indent=0]
----
include::example$/pslock-ex1/src/main/java/com/company/demo/DocumentService.java[tags=lock]
----

См. Javadocs интерфейса `LockManager` для получения дополнительной информации.

[[lock-expiration]]
=== Истечение блокировок

Атрибут аннотации `timeoutSec` определяет время истечения срока действия блокировки в секундах. Значение по умолчанию – 300 секунд.

Для истечения срока действия автоматической блокировки требуется планировщик заданий Quartz. Его можно предоставить, включив в проект дополнение xref:quartz:index.adoc[Quartz].

Следующие свойства приложения управляют механизмом истечения срока блокировок:

* Установите `jmix.pslock.use-default-quartz-configuration` в `false`, чтобы отключить механизм истечения срока блокировок по умолчанию. Значение этого свойства по умолчанию – `true`.

* Используйте `jmix.pslock.expiration-cron`, чтобы задать выражение Cron для расписания истечения срока блокировок. Значение по умолчанию – `0 * * * * ?`, что означает "каждую минуту".

[[locks-admin-ui]]
=== Административный UI блокировок

Текущее состояние блокировок можно отслеживать с помощью экрана *Pessimistic Locking -> Locks*. Этот экран также позволяет разблокировать любую сущность.
