= Pessimistic Locking

Pessimistic locking can be used when there is a high probability of simultaneous editing of a single entity instance. In such cases the xref:data-model:entities.adoc#versioned-trait[optimistic locking], based on entity versioning, usually creates too many collisions.

Pessimistic locking explicitly locks an entity instance when it is opened in the UI detail view. As a result, only one user can edit this particular entity instance in a given moment.

The Jmix pessimistic locking mechanism can also be used to manage simultaneous execution of arbitrary processes. The locks are distributed, since they are replicated in the cluster.

[[installation]]
== Installation

For automatic installation through Jmix Marketplace, follow instructions in the xref:ROOT:add-ons.adoc#installation[Add-ons] section.

For manual installation, add the following dependencies to your `build.gradle`:

[source,groovy,indent=0]
----
include::example$/pslock-ex1/build.gradle[tags=dependencies]
----

include::ROOT:single-menu-note.adoc[]

[[usage]]
== Usage

To enable pessimistic locking for any entity, add the `@PessimisticLock` annotation to the entity class, for example:

[source,java,indent=0]
----
include::example$/pslock-ex1/src/main/java/com/company/demo/entity/Document.java[tags=pessimistic-lock]
----

The standard entity detail view automatically handles pessimistic locking by switching to read-only mode if the entity is locked by someone else.

You can also lock an entity in your own code using the `LockManager` bean. For example:

[source,java,indent=0]
----
include::example$/pslock-ex1/src/main/java/com/company/demo/DocumentService.java[tags=lock]
----

See the Javadocs of the `LockManager` interface for more information.

[[lock-expiration]]
=== Lock Expiration

The `timeoutSec` annotation attribute defines the lock expiration timeout in seconds. It is 300 sec by default.

The automatic lock expiration requires the Quartz job scheduler. You can provide it by including the xref:quartz:index.adoc[Quartz] add-on in your project.

The following application properties control the expiration mechanism:

* Set `jmix.pslock.use-default-quartz-configuration` to `false` if you want to disable the default expiration mechanism. This property is `true` by default.

* Use `jmix.pslock.expiration-cron` to set a Cron expression for the expiration schedule. This property has the `0 * * * * ?` value by default, which means "every minute".

[[locks-admin-ui]]
=== Locks Admin UI

The current state of locks can be tracked through the *Pessimistic Locking -> Locks* view. This view also allows unlocking any object.