= Data Loaders

Loaders are designed to load data to xref:flow-ui:data/data-containers.adoc[containers].

There are slightly different interfaces of loaders depending on containers they work with:

* `InstanceLoader` loads a single instance to `InstanceContainer` by an entity id or JPQL query.
* `CollectionLoader` loads a collection of entities to `CollectionContainer` by a JPQL query. You can specify paging, sorting and other optional parameters.
* `KeyValueCollectionLoader` loads a collection of `KeyValueEntity` instances to `KeyValueCollectionContainer`. In addition to `CollectionLoader` parameters, you can specify a data store name.

In view XML descriptors, all loaders are defined by the same `<loader>` element and the type of a loader is determined by what container it is enclosed in.

Loaders are optional because you can just load data using `DataManager` or your custom service and set it directly to containers, but they simplify this process in declaratively defined views.

Usually, a collection loader obtains a JPQL query from the view XML descriptor, creates `LoadContext` and invokes `DataManager` to load entities. So the typical XML descriptor looks like this:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/department/department-list-view.xml[tags=collection-container]
----

In an entity detail view, the loader XML element is usually empty, because the instance loader requires an entity identifier that is specified programmatically by the `StandardDetailView` base class:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/department/department-detail-view.xml[tags=instance-container]
----

If the loader does not have the `readOnly="true"` attribute in XML or if the xref:flow-ui:data/data-context.adoc[DataContext] is set for the loader programmatically, all loaded entities are automatically merged into the data context.

[[data-context-events]]
== Events and Handlers

This section describes the data loader lifecycle events that can be handled in view controllers.

include::events-handlers-generation-data-tip.adoc[]

[[load-delegate]]
=== loadDelegate

Loaders can delegate actual loading to a method of the view controller, where you can call a custom service instead of `DataManager` used by default. For example:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/department/DepartmentListView.java[tags=delegate]
----
<1> The `departmentsDlLoadDelegate()` method will be used by the `departmentsDl` loader to load the list of `Department` entities.
<2> The method accepts `LoadContext` that will be created by the loader based on its parameters: query, conditions (if any), etc.
<3> The loading is done via `DepartmentService.loadDepartments()` method which accepts the filtering conditions, sorting and pagination set to the loader by visual components of the view.

Apart from invoking a custom service, the load delegate allows you to perform any post-processing of the loaded entities.

If you declare custom data loading with a delegate, and you display the loaded data in the DataGrid with a pagination component, then you may also need to define the custom logic to count total number of rows. Take a look at the xref:vc/components/simplePagination.adoc#totalCountDelegate[totalCountDelegate] handler for the pagination component associated with the table.

[[load-from-repository-delegate]]
=== loadFromRepositoryDelegate

If you prefer xref:data-access:data-repositories.adoc[data repositories] for accessing the database, consider using the `loadFromRepositoryDelegate` instead of `loadDelegate` described <<load-delegate,above>>.

It accepts arguments suitable for calling a data repository directly:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/department/DepartmentListView3.java[tags=delegate]
----

[[pre-load-event]]
=== PreLoadEvent

This event is sent before loading entities.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/department/DepartmentListView.java[tags=pre-load]
----

You can prevent load using the `preventLoad()` method of the event.

[[post-load-event]]
=== PostLoadEvent

This event is sent after successful loading of entities, merging them into `DataContext` and setting to the container.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/department/DepartmentListView.java[tags=post-load]
----

[[query-conditions]]
== Query Conditions

Sometimes you need to modify a data loader query at runtime to filter the loaded data at the database level. The simplest way to provide filtering based on parameters entered by users is to connect the xref:flow-ui:vc/components/propertyFilter.adoc[] or xref:flow-ui:vc/components/genericFilter.adoc[] visual component to the data loader.

Instead of the universal filter or in addition to it, you can create a set of conditions for the loader query. A condition is a set of query fragments with parameters. These fragments are added to the resulting query text only when all parameters used in the fragments are set for the query.

TIP: Explore the https://demo.jmix.io/ui-samples/sample/custom-filter[Custom filter using declarative conditions^] online example to see query conditions in action.

Conditions are processed on the data store level, so they can contain fragments of different query languages supported by data stores. The framework provides out-of-the-box handling of conditions for JPQL.

Let’s consider creating a set of conditions for filtering the `Department` entity by its `name` and `hrManager` attributes.

Loader query conditions can be defined either declaratively in the `<condition>` XML element, or programmatically using the `setCondition()` method. Below is an example of configuring the conditions in descriptor:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/department/department-list-view-2.xml[tags=condition-data]
----
<1> Adds the JPQL conditions namespace.
<2> Defines the `condition` element inside the query.
<3> If you have more than one condition, add `and` or `or` element
<4> Defines a JPQL condition with optional `join` element and mandatory `where` element.

Suppose that the view has `nameFilterField` text field and `hrManagerFilterField` combo box for entering the condition parameters:

[source,xml,indent=0]
----
include::example$/onboarding/src/main/resources/com/company/onboarding/view/department/department-list-view-2.xml[tags=field]
----

In order to refresh the data when a user changes their values, add the following event listeners to the view controller:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/department/DepartmentListView2.java[tags=condition]
----

As mentioned above, a condition is included in the query only when its parameters are set. So the resulting query executed on the database will depend on what is entered in the UI components:

.Only nameFilterField has a value
[source,jpql,indent=0]
----
select e from Department e where e.name like :name
----

.Only hrManagerFilterField has a value
[source,jpql,indent=0]
----
select e from Department e where e.hrManager = :hrManager
----

.Both nameFilterField and hrManagerFilterField have values
[source,jpql,indent=0]
----
select e from Department e where (e.name like :name) and (e.hrManager = :hrManager)
----