= DataContext

`DataContext` is an interface for tracking changes in entities loaded to the UI layer. Tracked entities are marked as "dirty" on any modification of their attributes, and `DataContext` saves dirty entities when its `save()` method is invoked.

Within `DataContext`, an entity with the given identifier is represented by a single object instance, no matter where and how many times it is used in graphs of entities contained in this context.

In order to be tracked, an entity must be put into `DataContext` using its `merge()` method. If the context does not contain the entity with the same id, the context creates a new instance, copies the state of the passed instance to the new one and returns it. If the context already contains an instance with the same id, it copies the state of the passed instance to the existing one and returns the existing instance. This mechanism allows the context to always have only one instance of an entity with a particular identifier.

When you merge an entity, the whole object graph with the root in this entity will be merged. That is all referenced entities (including collections) will become tracked.

NOTE: The main rule of using the `merge()` method is to continue working with the returned instance and discarding the passed one. In most cases, the returned object instance will be different. The only exception is when you pass to `merge()` an instance that was earlier returned from another invocation of `merge()` or `find()` of the same context.

An example of merging an entity into `DataContext`:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/department/DepartmentListView2.java[tags=data-context]
----

A single instance of `DataContext` exists for a given view. It is created if there is `<data>` element in the view XML descriptor.

xref:data/data-loaders.adoc[Data loaders] defined in XML automatically merge loaded entities into the `DataContext` if they don't have the `readOnly="true"` attribute. By default, data loaders in xref:views/view-classes.adoc#standard-list-view[entity list views] scaffolded by Studio include this attribute, so if you need to track changes and save dirty entities in a list view, remove the `readOnly="true"` XML attribute for respective loaders.

CAUTION: If a referenced entity is not included in the xref:data-access:fetching.adoc#fetch-plan[fetch plan] of the view but loaded by xref:data-access:fetching.adoc#lazy-loading[lazy loading], it is not merged into the view's `DataContext` and hence not tracked for changes. Make sure all entities edited on the view are loaded eagerly by including references to them in the fetch plan.

[[obtaining-data-context]]
== Obtaining DataContext

. `DataContext` of a view can be obtained in its controller using injection:
+
[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/department/DepartmentListView2.java[tags=data-context-inject]
----
+
. If you have a reference to a view, you can get its `DataContext` using the `ViewControllerUtils` class:
+
[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/department/DepartmentListView2.java[tags=sample-method]
----

[[parent-data-context]]
== Parent DataContext

DataContext instances can form parent-child relationships. If a `DataContext` instance has parent context, it saves changed entities to the parent instead of saving them to the data store. This feature enables xref:concepts:features.adoc#editing-aggregates[editing aggregates] when detail entities are saved only together with the master entity. If an entity attribute is annotated with xref:data-model:entities.adoc#composition[@Composition], the framework automatically sets parent context in the attribute detail view, so the changed attribute entity will be saved to the data context of the master entity.

You can easily provide the same behavior for any entities and views.

If you open a detail view that should save data to the current view’s data context, use the `withParentDataContext()` method:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/department/DepartmentListView2.java[tags=department-edit]
----

For more examples of explicit usage of `DataContext`, refer to the xref:data-modeling-composition-guide:index.adoc[] guide.

[[data-context-events]]
== Events and Handlers

This section describes the `DataContext` lifecycle events that can be handled in view controllers.

include::events-handlers-generation-data-tip.adoc[]

[[save-delegate]]
=== SaveDelegate

By default, `DataContext` saves changed and removed entities using the xref:data-access:data-manager.adoc#save[DataManager.save(SaveContext)] method. The `saveDelegate` handler allows you to customize the logic of saving data, which is especially useful when working with xref:data-model:entities.adoc#dto[DTO entities]. For example, you can save the changed entities with a custom service:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/department/DepartmentListView2.java[tags=save-delegate]
----

The save delegate should return the set of saved instances. If it's impossible, return the original instances from `saveContext.getEntitiesToSave()` or just an empty set. Do not return removed instances. `DataContext` will merge back the returned instances so the view will continue working with the updated state.

See the xref:data/entities-in-ui.adoc[] section for more information on saving entities using custom services.

[[change-event]]
=== ChangeEvent

This event is sent when the context detects changes in a tracked entity, a new instance is merged or an entity is removed.

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/department/DepartmentListView2.java[tags=change-event]
----

[[pre-save-event]]
=== PreSaveEvent

This event is sent before saving changes.
In this event listener, you can add arbitrary entity instances to the saved collections returned by `getModifiedInstances()` and `getRemovedInstances()` methods, for example:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/department/DepartmentListView2.java[tags=pre-save-event]
----

You can also prevent the save using the `preventSave()` method of the event, for example:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/department/DepartmentListView2.java[tags=prevent-save]
----

[[post-save-event]]
=== PostSaveEvent

This event is sent after saving changes.
In this event listener, you can get the collection of saved entities returned from `DataManager` or a custom <<save-delegate,save delegate>>. These entities are already merged into the DataContext. For example:

[source,java,indent=0]
----
include::example$/onboarding/src/main/java/com/company/onboarding/view/department/DepartmentListView2.java[tags=post-save-event]
----
