[[permissions]]
= Роли и экраны

[[roles-views-tab]]
== Вкладка Роли и экраны

Вы можете определить права пользователей на доступ к отчету, а также доступность отчета в определенных экранах приложения на вкладке *Roles and views* в редакторе отчетов во время выполнения.

Если список *Resource roles* содержит хотя бы одну роль, отчет будет доступен только пользователям с этой ролью. Если роль не указана, отчет доступен всем.

[TIP]
====
Имейте в виду, что в экране списка отчетов (пункт меню *Reports->Reports)* все системные отчеты видны, поскольку этот экран считается административным.
====

Список *Views* позволяет указать, в каких экранах отчет будет доступен при вызове действий xref:run-report.adoc#run-report-action[RunReportAction], xref:run-report.adoc#run-list-entity-report-action[RunListEntityReportAction], xref:run-report.adoc#run-single-entity-report-action[RunSingleEntityReportAction] или xref:exec-history.adoc#execution_history_action[ShowExecutionReportHistoryAction]. Если экран не указан, отчет не будет доступен ни из одного экрана приложения.

[[available-for-roles]]
== Аннотация @AvailableForRoles

Аннотация `@AvailableForRoles` определяет, какие xref:security:resource-roles.adoc[ресурсные роли] могут запускать определенный отчет в конкретных экранах и действиях при создании отчета на этапе разработки (design time). Если эта аннотация отсутствует или список ролей пуст, ограничения на основе ролей не применяются, что позволяет любому пользователю запускать отчет.

Аннотация `@AvailableForRoles` имеет следующие атрибуты:

* `roleCodes` - коды ресурсных ролей, которые должны иметь доступ к отчету.
* `roleClasses` - интерфейсы определения ресурсных ролей (помеченные `@ResourceRole`), которые должны иметь доступ к отчету.

[[available-in-views]]
== Аннотация @AvailableInViews

Аннотация `@AvailableInViews` определяет, в каких экранах отчет будет доступен при использовании xref:run-report.adoc#run-actions[стандартных действий отчетов] (из пакета `io.jmix.reportsflowui.action`).

Аннотация `@AvailableInViews` имеет следующие атрибуты:

* `viewIds` - идентификаторы экранов, в которых отчет будет доступен через стандартные действия.
* `viewClasses` - классы контроллеров экранов, в которых отчет будет доступен через стандартные действия. Контроллер класса должен быть аннотирован `@ViewController`.