[[permissions]]
= Роли и экраны

Вы можете определить права пользователей на доступ к отчету, а также доступность отчета в определенных экранах приложения на вкладке *Roles and views* экрана деталей отчета.

Если список *Resource roles* содержит хотя бы одну роль, отчет будет доступен только пользователям с этой ролью. Если роль не указана, отчет доступен всем.

[TIP]
====
Имейте в виду, что в экране списка отчетов (пункт меню *Reports->Reports)* все системные отчеты видны, поскольку этот экран считается административным.
====

Список *Views* позволяет указать, в каких экранах отчет будет доступен при вызове действий xref:run-report.adoc#run-report-action[RunReportAction], xref:run-report.adoc#run-list-entity-report-action[RunListEntityReportAction], xref:run-report.adoc#run-single-entity-report-action[RunSingleEntityReportAction] или xref:exec-history.adoc#execution_history_action[ShowExecutionReportHistoryAction]. Если экран не указан, отчет не будет доступен ни из одного экрана приложения.