= Свойства REST

Свойства Jmix REST позволяют настраивать различные аспекты поведения конечных точек универсального REST.

[[entities-api-properties]]
== Entities API


[[jmix.rest.default-max-fetch-size]]
=== jmix.rest.default-max-fetch-size

Определяет максимальное количество экземпляров сущностей, возвращаемых API по умолчанию.

Значение по умолчанию: `10000`


[[jmix.rest.entity-max-fetch-size]]
=== jmix.rest.entity-max-fetch-size

Определяет максимальное количество экземпляров сущности, возвращаемых API для конкретной сущности по умолчанию.

В следующем примере настраивается значение `entityMaxFetchSize` для двух сущностей. Для всех остальных сущностей используется значение из <<jmix.rest.default-max-fetch-size>>.

[source,properties]
----
jmix.rest.entity-max-fetch-size.sample_Product = 500
jmix.rest.entity-max-fetch-size.sample_Customer = 1000
----

[[jmix.rest.inline-enabled-file-extensions]]
=== jmix.rest.inline-enabled-file-extensions

Список расширений файлов, которые могут быть xref:files-api.adoc#downloading-files[скачаны] с заголовком `Content-Disposition: inline`.

Значение по умолчанию: `jpg,png,jpeg,pdf`

[[jmix.rest.inline-fetch-plan-enabled]]
=== jmix.rest.inline-fetch-plan-enabled

При установке в `false` запрещает принимать xref:rest:entities-api/load-entities.adoc#inline-fetch-plans[встроенные фетч-планы] во всех REST-эндпойнтах.

Значение по умолчанию: `true`

[[jmix.rest.json-transformation-config]]
=== jmix.rest.json-transformation-config

Определяет файл, содержащий список конфигураций преобразований JSON, которые использует REST API, когда клиенту нужны данные в формате определенной версии модели данных.

Файл загружается с помощью интерфейса `Resources`, поэтому он может находиться в пути к классам или в каталоге конфигурации.

// TODO: [MD] link to configuration directory description once it is available in the docs

Значение по умолчанию: `none`

[[jmix.rest.max-upload-size]]
=== jmix.rest.max-upload-size

Определяет максимальный размер файла (в байтах), который можно загрузить с помощью REST API.

Файл загружается с помощью интерфейса `Resources`, поэтому он может находиться в пути к классам или в каталоге конфигурации.

Значение по умолчанию: `20971520` (20 Mb)

[[jmix.rest.optimistic-locking-enabled]]
=== jmix.rest.optimistic-locking-enabled

Включает оптимистическую блокировку сущностей, если атрибут версии указан в JSON.

Значение по умолчанию: `false`

[[jmix.rest.queries-config]]
=== jmix.rest.queries-config

Определяет файл, содержащий список запросов JPQL, доступных как часть xref:rest:entities-api/load-entities.adoc#load-list-jpql[Entities API].

[source,properties]
----
jmix.rest.queries-config = rest/sample/rest-queries.xml
----

Файл загружается с помощью интерфейса `Resources`, поэтому он может находиться в пути к классам или в каталоге конфигурации.

// TODO: [MD] link to configuration directory description once it is available in the docs

Значение по умолчанию: `none`

[[jmix.rest.services-config]]
=== jmix.rest.services-config

Определяет файл, содержащий список методов сервиса, предоставляемых через xref:rest:business-logic.adoc#services-api[Services API].

[source,properties]
----
jmix.rest.services-config = rest/sample/rest-services.xml
----

Файл загружается с помощью интерфейса `Resources`, поэтому он может находиться в пути к классам или в каталоге конфигурации.

// TODO: [MD] link to configuration directory description once it is available in the docs

Значение по умолчанию: `none`


[[jmix.rest.response-fetch-plan-enabled]]
=== jmix.rest.response-fetch-plan-enabled

Если установлено значение true, параметр `responseFetchPlan` с именем фетч-плана может передаваться в запросах на создание и обновление. В этом случае созданная/обновленная сущность перезагружается с указанным фетч-планом и возвращается как часть ответа JSON.

Если установлено значение false, ответ содержит JSON с минимальным представлением созданной/обновленной сущности.

Значение по умолчанию: `true`

[[paths]]
== Пути

[[jmix.rest.base-path]]
=== jmix.rest.base-path

Базовый путь всех REST-эндпойнтов.

Значение по умолчанию: `/rest`

[[jmix.rest.entities-path]]
=== jmix.rest.entities-path

Путь к эндпойнтам xref:entities-api.adoc[].

Значение по умолчанию: `/entities`

[[jmix.rest.docs-path]]
=== jmix.rest.docs-path

Путь к эндпойнтам xref:api-docs.adoc[].

Значение по умолчанию: `/docs`

[[jmix.rest.metadata-path]]
=== jmix.rest.metadata-path

Путь к эндпойнтам xref:metadata-api.adoc[].

Значение по умолчанию: `/metadata`

[[jmix.rest.files-path]]
=== jmix.rest.files-path

Путь к эндпойнтам xref:files-api.adoc[].

Значение по умолчанию: `/files`

[[jmix.rest.messages-path]]
=== jmix.rest.messages-path

Путь к эндпойнтам xref:messages-api.adoc[].

Значение по умолчанию: `/messages`

[[jmix.rest.permissions-path]]
=== jmix.rest.permissions-path

Путь к эндпойнту xref:user-session-api.adoc#permissions[Permissions].

Значение по умолчанию: `/permissions`

[[jmix.rest.queries-path]]
=== jmix.rest.queries-path

Путь к эндпойнту для xref:entities-api/load-entities.adoc#load-list-jpql[загрузки сущностей с помощью JPQL].

Значение по умолчанию: `/queries`

[[jmix.rest.services-path]]
=== jmix.rest.services-path

Путь к эндпойнтам xref:business-logic.adoc#services-api[Services API].

Значение по умолчанию: `/services`

[[jmix.rest.user-info-path]]
=== jmix.rest.user-info-path

Путь к эндпойнту xref:user-session-api.adoc#user-info[User Info].

Значение по умолчанию: `/userInfo`

[[jmix.rest.capabilities]]
=== jmix.rest.capabilities

Путь к эндпойнту xref:capabilities-api.adoc[].

Значение по умолчанию: `/capabilities`

[[security-properties]]
== Безопасность

См. раздел xref:security:custom-endpoints.adoc#application-properties[Безопасность: Кастомные эндпойнты] для получения информации о свойствах приложения, влияющих на эндпойнты REST.