= REST Properties

Jmix REST properties allow you to configure different aspects of the behavior of the generic REST endpoints.

[[entities-api-properties]]
== Entities API


[[jmix.rest.default-max-fetch-size]]
=== jmix.rest.default-max-fetch-size

Defines the default maximum amount of entity instances that are returned by the API.

Default value: `10000`


[[jmix.rest.entity-max-fetch-size]]
=== jmix.rest.entity-max-fetch-size

Defines the default maximum amount of entity instances that are returned by the API for a particular entity.

The following example configures the `entityMaxFetchSize` value for two entities. For all other entities the value from <<jmix.rest.default-max-fetch-size, jmix.rest.default-max-fetch-size>> is used.

[source,properties]
----
jmix.rest.entity-max-fetch-size.sample_Product = 500
jmix.rest.entity-max-fetch-size.sample_Customer = 1000
----

[[jmix.rest.inline-enabled-file-extensions]]
=== jmix.rest.inline-enabled-file-extensions

The list of file extensions that can be xref:files-api.adoc#downloading-files[downloaded] with `Content-Disposition: inline` header.

Default value: `jpg,png,jpeg,pdf`

[[jmix.rest.inline-fetch-plan-enabled]]
=== jmix.rest.inline-fetch-plan-enabled

If set to `false`, xref:rest:entities-api/load-entities.adoc#inline-fetch-plans[Inline Fetch Plans] are refused by all REST endpoints.

Default value: `true`

[[jmix.rest.json-transformation-config]]
=== jmix.rest.json-transformation-config

A property that defines a file containing a list of JSON transformation configurations used by the REST API when the client needs data in the format of a particular data model version.

The file is loaded using the Resources interface, so it can be located in the classpath or the configuration directory.

// TODO: [MD] link to configuration directory description once it is available in the docs

Default value: `none`

[[jmix.rest.max-upload-size]]
=== jmix.rest.max-upload-size

Maximum file size (in bytes) that can be uploaded with the REST API.

The file is loaded using the `Resources` interface, so it can be located in the classpath or the configuration directory.

Default value: `20971520` (20 Mb)

[[jmix.rest.optimistic-locking-enabled]]
=== jmix.rest.optimistic-locking-enabled

Enables optimistic locking of entities with optimistic locking if the version attribute is provided in JSON.

Default value: `false`

[[jmix.rest.queries-config]]
=== jmix.rest.queries-config

A property that defines a file containing a list of JPQL queries available as part of the xref:rest:entities-api/load-entities.adoc#load-list-jpql[Entities API].

[source,properties]
----
jmix.rest.queries-config = rest/sample/rest-queries.xml
----

The file is loaded using the Resources interface, so it can be located in the classpath or the configuration directory.

// TODO: [MD] link to configuration directory description once it is available in the docs

Default value: `none`

[[jmix.rest.services-config]]
=== jmix.rest.services-config

A property that defines a file containing a list of service methods that are exposed via the xref:rest:business-logic.adoc#services-api[Services API].

[source,properties]
----
jmix.rest.services-config = rest/sample/rest-services.xml
----

The file is loaded using the Resources interface, so it can be located in the classpath or the configuration directory.

// TODO: [MD] link to configuration directory description once it is available in the docs

Default value: `none`


[[jmix.rest.response-fetch-plan-enabled]]
=== jmix.rest.response-fetch-plan-enabled

If set to true, the `responseFetchPlan` parameter with the fetch plan name can be passed in the create and update requests. In this case, the created/updated entity is reloaded with the specified fetch plan and returned as part of the response JSON.

If set to false, the response contains JSON with a minimal representation of the created/updated entity.

Default value: `true`

[[paths]]
== Paths

[[jmix.rest.base-path]]
=== jmix.rest.base-path

Base path of all generic REST endpoints.

Default value: `/rest`

[[jmix.rest.entities-path]]
=== jmix.rest.entities-path

Path to the xref:entities-api.adoc[] endpoints.

Default value: `/entities`

[[jmix.rest.docs-path]]
=== jmix.rest.docs-path

Path to the xref:api-docs.adoc[] endpoints.

Default value: `/docs`

[[jmix.rest.metadata-path]]
=== jmix.rest.metadata-path

Path to the xref:metadata-api.adoc[] endpoints.

Default value: `/metadata`

[[jmix.rest.files-path]]
=== jmix.rest.files-path

Path to the xref:files-api.adoc[] endpoints.

Default value: `/files`

[[jmix.rest.messages-path]]
=== jmix.rest.messages-path

Path to the xref:messages-api.adoc[] endpoints.

Default value: `/messages`

[[jmix.rest.permissions-path]]
=== jmix.rest.permissions-path

Path to the xref:user-session-api.adoc#permissions[Permissions] endpoint.

Default value: `/permissions`

[[jmix.rest.queries-path]]
=== jmix.rest.queries-path

Path to the endpoint for xref:entities-api/load-entities.adoc#load-list-jpql[loading entities via JPQL].

Default value: `/queries`

[[jmix.rest.services-path]]
=== jmix.rest.services-path

Path to the xref:business-logic.adoc#services-api[Services API] endpoints.

Default value: `/services`

[[jmix.rest.user-info-path]]
=== jmix.rest.user-info-path

Path to the xref:user-session-api.adoc#user-info[User Info] endpoint.

Default value: `/userInfo`

[[jmix.rest.capabilities]]
=== jmix.rest.capabilities

Path to the xref:capabilities-api.adoc[] endpoints.

Default value: `/capabilities`

[[security-properties]]
== Security

See xref:security:custom-endpoints.adoc#application-properties[Security: Custom Endpoints] section for information on application properties affecting REST endpoints.