= Business Logic

When interacting with the REST API, it is often needed to have an application-level layer of business logic in place that represents the invocation point for the API. It can be used for orchestration, validation, or other tasks that should happen when the API client interacts with the system. The xref:rest:entities-api.adoc[Entities API] does not allow placing additional orchestration business logic when interacting with the API. Instead, the API client directly interacts with the xref:data-access:index.adoc[Data Access Layer] of Jmix.

For exposing business logic to the API client, Jmix provides two ways:

1. Services API
2. Custom controllers

In the next section, we will take a look at both options to understand what the difference between those approaches is.

[[services-api]]
== Services API

Let's look at the first approach to expose business logic to the API client: the Services API.

The Services API allows exposing an arbitrary Spring bean as an HTTP endpoint. In this case, Jmix will take care of HTTP interactions like providing HTTP response codes, performing error handling, etc.

In this overview you can see the interaction between the API client and the Jmix application when using the Services API:

image::business-logic-diagram.svg[align="center"]

[[exposing-a-service]]
=== Exposing a Service

To use a Spring bean as part of the Jmix Services API, it needs to meet one of the following conditions:

* *Annotation-based approach*: The Spring bean must be created using the `@RestService` annotation.
* *XML-based approach*: The Spring bean must be registered in the `rest-services.xml` configuration file.

Let's examine these two methods in more detail.

[[using-annotations]]
==== Using Annotations

Create the Spring bean and annotate it with the `@RestService` annotation.

[source,java]
----
import io.jmix.rest.annotation.RestMethod;
import io.jmix.rest.annotation.RestService;

import java.math.BigDecimal;

@RestService("sample_OrderService") //<1>
public class OrderService {

    @RestMethod // <2>
    public BigDecimal calculateTotalAmount(int orderId) {
        // ...
    }
}
----
<1> The `@RestService` annotation is used to mark a service class that should be accessible through a REST API.
<2> The `@RestMethod` annotation is used to configure the mapping between a service method and a specific REST endpoint. You can pass the `httpMethods` parameter, which accepts a list of possible HTTP methods for invoking services through the Generic REST API. By default, it includes `GET` and `POST`.

[[using-rest-services]]
==== Using rest-services.xml

Let's look at the first part with this example:

[source,java]
.CalculationServiceBean.java
----
import org.springframework.stereotype.Service;

@Component("sample_OrderService") //<1>
public class OrderService {

    public BigDecimal calculateTotalAmount(int orderId) {
        // ...
    }
}
----
<1> The `OrderServiceBean` is registered as the Spring `@Component` with the name `sample_OrderService`.

NOTE: If the service name is not specified explicitly in the annotation, it is assumed to be equal to the simple class name with the first letter in lowercase. In the example above, it would be `orderService`.

The second part is to mention all Service methods as API endpoints. This happens via an XML configuration file, normally called `rest-services.xml`. You need to create this new file in your Jmix application as part of `src/main/resources`. It lists all service methods with information about the parameters that you want to expose.

[source,xml]
.rest-services.xml
----
<?xml version="1.0" encoding="UTF-8"?>
<services xmlns="http://jmix.io/schema/rest/services">
    <service name="sample_OrderService"> // <1>
        <method name="calculateTotalAmount"> // <2>
            <param name="orderId"/> // <3>
        </method>
    </service>
</services>
----
<1> You register the Service by its Spring component name.
<2> Each method that you want to expose needs to be mentioned here.
<3> The parameter needs to be described by its name and optionally by its type.

After the file has been created, and the services have been defined, the last part is to register the `rest-services.xml` configuration in the `application.properties` of your Jmix application:

[source,properties]
.application.properties
----
jmix.rest.services-config = rest-services.xml
----

NOTE: The value of the `serviceConfig` is a reference to the file within the classpath. In this case, the file is located directly in the classpath root under `src/main/resources`. If you, for example, put the file in the `src/resources/com/example/rest-services.xml` package, the value would be: `com/example/rest-services.xml`.

[[using-the-services-api]]
=== Using the Services API

Once we have exposed the Service through the Services API, you can invoke it from an API client. This is possible by HTTP GET or HTTP POST.

[[invoke-a-service-via-get]]
==== Invoke a Service via GET

In the case of HTTP GET, you need to provide the method parameter values as URL query parameters:

[source, http request]
.Calculate Total Order Amount via HTTP GET
----
GET http://localhost:8080/rest
            /services
            /sample_OrderService
            /calculateTotalAmount?orderId=123
Authorization: Bearer {{access_token}}
----

[source, json]
.Response: 200 - OK
----
450.0
----

NOTE: When using GET for invoking a service through the Services API, the OAuth access token still needs to be provided by the HTTP Authorization header. It is not possible to append the access token as a URL query parameter.

A service method may return a result of a simple data type, an entity, an entity collection, or a serializable POJO. In our case, the service method returns an `int`, so the response body contains just a number.

[[invoke-a-service-via-post]]
==== Invoke a Service via POST

Alternatively, it is also possible to invoke the Service via HTTP POST. This is particularly useful when the Service method has one of the following parameter types:

* Entities
* Entity Collections
* Serializable POJOs

Suppose we added a new method to the OrderService created in the previous part:

[source,java]
.OrderServiceBean.java
----
@Component("sales_OrderService")
public class OrderService {

    public OrderValidationResult validateOrder(Order order, Date validationDate){
        OrderValidationResult result = new OrderValidationResult();
        result.setSuccess(false);
        result.setErrorMessage("Validation of order " + order.getNumber() + " failed. validationDate parameter is: " + validationDate);
        return result;
    }
}
----

With the following structure for the `OrderValidationResult` POJO as the result object:

[source,java]
.OrderValidationResult.java
----
import java.io.Serializable;

public class OrderValidationResult implements Serializable {

    private boolean success;

    private String errorMessage;

    public boolean isSuccess() {
        return success;
    }

    public void setSuccess(boolean success) {
        this.success = success;
    }

    public String getErrorMessage() {
        return errorMessage;
    }

    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }
}
----

The new method has an Order entity in the arguments list and returns a POJO. Before invoking the REST API, the new method must also be registered in the `rest-services.xml`. Once you expose the method, you can perform the API call:

[source, http request]
.Invoke Order Validation via HTTP POST
----
POST http://localhost:8080/rest/services/sales_OrderService/validateOrder

{
  "order" : {
    "number": "00050",
    "date" : "2016-01-01"
  },
  "validationDate": "2016-10-01"
}
----

The REST API method returns a serialized `OrderValidationResult` POJO:

[source, json]
.Response: 200 - OK
----
{
  "success": false,
  "errorMessage": "Validation of order 00050 failed. validationDate parameter is: 2016-10-01"
}
----

[[service-parameters]]
==== Service Parameter Formats

Parameter values must be passed in a format defined for the corresponding xref:data-model:datatype.adoc[datatype].

* If the parameter type is `java.util.Date`, then the value is handled by `DateTimeDatatype`. This datatype implementation uses the https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/format/DateTimeFormatter.html#ISO_DATE_TIME[ISO_DATE_TIME^] format where the date and time parts are separated with `T`, for example `2011-12-03T10:15:30`.
* Parameters of `java.sql.Date` type are handled by `DateDatatype` which uses https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/format/DateTimeFormatter.html#ISO_DATE[ISO_DATE^] format, for example `2011-12-03`.
* Parameters of `java.sql.Time` type are handled by `TimeDatatype` which uses https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/format/DateTimeFormatter.html#ISO_TIME[ISO_TIME^] format, for example `10:15:30`.

[[using-dto-parameters]]
==== Using DTOs as Request Parameters

When using a structured request object as a method parameter, the JSON request body must include the parameter name as the top-level key.

Example:

[source,java]
----
public Owner registerOwner(OwnerRegistration registration) {
    return dataManager.create(Owner.class);
}
----

With the following DTO definition:

[source,java]
----
public record OwnerRegistration(String firstName, String lastName) {}
----

The request must follow this structure:

[source,json]
----
{
  "registration": {
    "firstName": "John",
    "lastName": "Doe"
  }
}
----


[[recommended-dto-usage]]
[NOTE]
====
Instead of using POJOs as parameter objects, it is recommended to use xref:data-model:entities.adoc#dto[DTO Entities]. This provides several advantages like correct OpenAPI Schema Generation and better support for Bean Validation to validate the request parameters.
====

[[custom-controller]]
== Custom Controller

The second way of exposing business logic as an API is the ability to use custom HTTP controllers. The main difference is that in this case, it is also possible to influence the HTTP interactions (like status codes, security, etc.) on your own. Jmix uses the default mechanisms from Spring MVC for creating HTTP endpoints.

Use-cases for custom controllers could be:

* explicitly define HTTP status codes
* use other request & response content type than JSON
* set custom response headers (e.g. for caching)
* create custom error messages from exceptions

In these situations, the generic Services API might be not flexible enough to accomplish your goals. Therefore Jmix allows natively integrate Spring MVC controllers into a Jmix application.

[[creating-custom-controllers]]
=== Creating Custom Controllers

To create a Spring MVC controller, it is only required to create a Spring bean in the Jmix application annotated as a Spring MVC controller. Jmix itself does not have any further requirements over Spring MVC. Let's look at an example Controller:

[source,java]
.OrderController.java
----
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMapping;

@RestController // <1>
@RequestMapping("/orders")  // <2>
public class OrderController {
    // ...
}
----
<1> The custom controller is marked as `@RestController` to indicate to Spring that this bean contains HTTP endpoints.
<2> The request mapping defines the base path for this Controller.

Now that the Spring controller is registered, we can create a method exposing a particular HTTP endpoint with it:

[source,java]
.OrderController.java
----
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpHeaders;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;

@RestController
@RequestMapping("/orders")
public class OrderController {

    @GetMapping("/calculateTotalAmount") // <1>
    public ResponseEntity<OrderTotalAmount> calculateTotalAmount(
            @RequestParam int orderId  // <2>
    ) {

        BigDecimal totalAmount = orderService.calculateTotalAmount(orderId);

        return ResponseEntity // <3>
                .status(HttpStatus.OK)
                .header(HttpHeaders.CACHE_CONTROL, "max-age=31536000")
                .body(new OrderTotalAmount(totalAmount, orderId));

    }
}
----
<1> The method `calculateTotalAmount` is annotated with `@GetMapping` indicating that it is accessible via HTTP GET on the subpath `/calculateTotalAmount`.
<2> The parameter `orderId` is retrieved via URL query parameters.
<3> We can use Spring's `ResponseEntity` class to indicate a JSON response together with different HTTP aspects.

More detailed information on the various aspects of how to create Spring MVC controllers can be found in the Spring guide: https://spring.io/guides/gs/rest-service/[Building a RESTful Web Service] as well as the https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#mvc[reference documentation] for Spring MVC.

With that controller in place, Jmix can serve this HTTP endpoint. Let's have a look at how to interact with the controller:

[source, http request]
.Invoke Custom Orders Controller
----
GET http://localhost:8080/orders/calculateTotalAmount?orderId=123
----

The result contains the calculation result exposed as JSON as well as the defined HTTP headers:

[source, http request]
.Response: 200 - OK
----
HTTP/1.1 200
Cache-Control: max-age=31536000
Content-Type: application/json

{
  "orderId": 123,
  "totalAmount": 450.0
}
----

[[securing-custom-controllers]]
=== Securing Custom Controllers

To secure a custom controller via the same OAuth2 mechanism that the other parts of the Jmix REST APIs use, register the controller's URL pattern in the xref:authorization-server:protecting-resources.adoc#protecting-rest-api-endpoints[jmix.resource-server.authenticated-url-patterns] application property:

[source,properties]
.application.properties
----
jmix.resource-server.authenticated-url-patterns = /rest/**,/orders/**
----

Here, the `/orders/**` wildcard indicates to Jmix that all endpoints that start with `/orders/` should also use the OAuth2 mechanism.

NOTE: The value can contain a comma-separated list of https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/AntPathMatcher.html[Apache Ant style URL patterns].

Trying to invoke the Order Controller now without a valid OAuth2 token will result in an `HTTP 401 - Unauthorized`:

[source, http request]
.Response: 401 - Unauthorized
----
HTTP/1.1 401
WWW-Authenticate: Bearer realm="oauth2-resource", error="unauthorized", error_description="Full authentication is required to access this resource"

{
"error": "unauthorized",
"error_description": "Full authentication is required to access this resource"
}
----

Authenticated endpoints can rely on data access control provided by the Jmix xref:security:index.adoc[security] subsystem. If your controller uses xref:data-access:data-manager.adoc[DataManager] to load or save data, it will check rights of the authenticated user on xref:security:resource-roles.adoc#entity-policy[entity operations]. In the following example, the "Access denied" exception will be thrown if the user has no rights to read the `Order` entity:

[source,java,indent=0]
----
@RestController
@RequestMapping("/orders")
public class OrderController {

    @Autowired
    private DataManager dataManager;

    @GetMapping("/all")
    public List<Order> loadAll() {
        return dataManager.load(Order.class).all().list();
    }
----

If you want to limit access also to entity attributes, use the `EntitySerialization` bean for serializing entities returned from the endpoint. In the following example, only attributes, permitted by the xref:security:resource-roles.adoc#entity-attribute-policy[entity attribute policy] will be returned in JSON to the client:

[source,java,indent=0]
----
@RestController
@RequestMapping("/orders")
public class OrderController {

    @Autowired
    private DataManager dataManager;
    @Autowired
    private EntitySerialization entitySerialization;

    @GetMapping("/all")
    public String loadAll() {
        List<Order> orders = dataManager.load(Order.class).all().list();
        return entitySerialization.toJson(
                orders,
                null,
                EntitySerializationOption.DO_NOT_SERIALIZE_DENIED_PROPERTY
        );
    }
----
