= REST API

Jmix provides a generic REST API that allows you to work with data model entities and business services without writing REST controllers on the backend. It automatically exposes endpoints for the following functionality:

* CRUD operations on entities.
* Calling registered service methods.
* Execution of predefined JPQL queries.
* Uploading and downloading files.
* Returning information about the data model.
* Returning information about the current user and their permissions.

NOTE: You can explore the generic REST endpoints using the Swagger UI page at {rest-api-open-api}{page-component-display-version}[{rest-api-open-api}{page-component-display-version}^]

REST API uses the OAuth2 protocol for authentication and supports anonymous access. All REST API endpoints respect data access constraints imposed by
xref:security:index.adoc[security].

TIP: The xref:rest-ds:index.adoc[] add-on allows you to consume the generic REST API in another Jmix application for easy integration.

[[installation]]
== Installation

Generic REST API is shipped as an optional add-on. To install it automatically through Jmix Marketplace, follow instructions in the xref:ROOT:add-ons.adoc#installation[Add-ons] section.

For manual installation, add the following dependencies to your `build.gradle`:

[source,groovy,indent=0]
----
include::example$/rest-ex1/build.gradle[tags=dependencies]
----
