= Генерация последовательностей

Механизм генерации последовательностей позволяет получать уникальные числовые значения через единый API, независимо от типа СУБД.

Точкой входа в этот механизм является интерфейс `Sequences`, который может быть инжектирован в компонент или экран:

[source,java,indent=0]
----
include::example$/features-ex1/src/main/java/com/company/demo/view/document/DocumentDetailView.java[tags=sequences-inject]
----

После этого вы можете использовать метод `createNextValue()` для генерации следующего числа в последовательности, передаваемой в качестве параметра:

[source,java,indent=0]
----
include::example$/features-ex1/src/main/java/com/company/demo/view/document/DocumentDetailView.java[tags=sequences-simple]
----

Интерфейс `Sequences` предоставляет следующие методы:

* `createNextValue()` – возвращает следующее значение в последовательности. Механизм позволяет одновременно управлять несколькими последовательностями, идентифицируемыми произвольными строками. Имя последовательности, из которой нужно извлечь значение, передается в статическом методе `Sequence.withName()`.
+
Последовательности не требуют инициализации. Когда `createNextValue()` вызывается в первый раз, создается соответствующая последовательность и возвращается значение по умолчанию `1`.

* `setCurrentValue()` – устанавливает новое начальное значение для последовательности.
+
Существует незначительная разница в том, что `createNextValue()` возвращает в первый раз после вызова `setCurrentValue()` в различных базах данных:
+
** PostgreSQL возвращает заданное значение плюс инкремент.
** Другие базы данных возвращают само заданное значение.

* `deleteSequence()` – удаляет последовательность с указанным идентификатором.

Механизм генерации последовательностей реализован для всех xref:data-model:data-stores.adoc#supported-databases[поддерживаемых СУБД].

Параметрами последовательности также можно управлять непосредственно в базе данных по правилам конкретной СУБД.

CAUTION: Реализация интерфейса `Sequences` основана на последовательностях БД или полях автоматического увеличения и не гарантирует непрерывную последовательность без пробелов, гарантируется только уникальность значений. Пробелы могут возникать из-за ошибки или отката транзакции.

[[sequence-usage]]
== Пример использования последовательности

Каждый экземпляр `Sequence` характеризуется именем, хранилищем данных, начальным значением и шагом инкрементации. Для определения этих параметров при вызове методов, упомянутых выше, можно использовать сеттеры. Например:

[source,java,indent=0]
----
include::example$/features-ex1/src/main/java/com/company/demo/view/document/DocumentDetailView.java[tags=sequences-inject;sequences-use]
----
<1> Генерация нового значения последовательности `document_number`.
<2> Для использования интерфейсом `Sequence` указывается xref:data-model:data-stores.adoc#additional[дополнительное хранилище данных] по его названию. Иначе будет использоваться основное хранилище данных.
<3> Установка начального номера `document_number`. Иначе последовательность начинается с `1`.
<4> Определение шаг инкрементации последовательности. Иначе приращение равно `1`.
