= Выгрузка и отображение файлов

В этом разделе объясняется, как выгружать файлы на компьютер пользователя или отображать файлы в UI. Сведения о том, как получить файлы с сервера через REST API, см. в разделе xref:rest:files-api.adoc[Files API].

[[downloader]]
== Использование Downloader

Бин `Downloader` предназначен для выгрузки файлов на компьютер пользователя. Он имеет ряд методов `download()`, которые принимают различные параметры, определяющие выгружаемый контент.

Файл может быть либо выгружен, либо показан браузером в новой вкладке. Это зависит от типа файла и значения свойства xref:flow-ui:ui-properties.adoc#jmix.ui.view-file-extensions[jmix.ui.view-file-extensions]. Тип файла определяется параметром `DownloadFormat` или, если он не указан, расширением имени файла. Вы также можете принудительно отображать содержимое вместо его выгрузки независимо от типа, вызвав метод `setShowNewWindow(true)` бина `Downloader`.

[NOTE]
====
Чтобы управлять поведением кэширования в браузере для загружаемых файлов, вы можете использовать свойство приложения xref:flow-ui:ui-properties.adoc#jmix.ui.file-downloader-cache-max-age-sec[jmix.ui.file-downloader-cache-max-age-sec]. Установка его в значение `0` гарантирует, что браузер всегда будет запрашивать последнюю версию с сервера, что особенно полезно для динамически генерируемых файлов, таких как PDF.
====

[[download-from-storage]]
=== Выгрузка из файлового хранилища

Метод `download()` со значением `FileRef` позволяет выгрузить файл из файлового хранилища. Объект `FileRef` содержит всю необходимую информацию о файле, поэтому его можно просто передать в `Downloader`:

[source,java,indent=0]
----
include::example$/files-ex1/src/main/java/com/company/demo/view/attachment/AttachmentDetailView.java[tags=downloader;download-from-fs]
----

[[download-arbitrary]]
=== Выгрузка произвольных ресурсов

Метод `download()` может принимать байтовые массивы, что позволяет выгружать файлы или любой другой контент. Вы должны передать сам массив байтов, имя целевого файла и необязательный формат, например:

[source,java,indent=0]
----
include::example$/files-ex1/src/main/java/com/company/demo/view/attachment/AttachmentDetailView.java[tags=downloader;download-array]
----

Чтобы использовать формат, отсутствующий в константах `DownloadFormat`, создайте новый экземпляр `DownloadFormat` и передайте его методу `download()`, например:

[source,java,indent=0]
----
include::example$/files-ex1/src/main/java/com/company/demo/view/attachment/AttachmentDetailView.java[tags=downloader;download-format]
----

Метод `download()` также может принимать лямбду, которая возвращает `InputStream` для выгрузки содержимого этого потока. Например:

[source,java,indent=0]
----
include::example$/files-ex1/src/main/java/com/company/demo/view/attachment/AttachmentDetailView.java[tags=downloader;data-provider]
----

[[display-files]]
== Отображение файлов на экранах UI

Jmix предоставляет два компонента UI для встраивания контента в экраны пользовательского интерфейса:

* xref:flow-ui:vc/html-components/image.adoc[] позволяет отображать изображения из различных ресурсов с помощью HTML-элемента `<img>`. Этот компонент может быть декларативно привязан к атрибуту сущности для отображения изображений, хранящихся в виде массивов байтов в базе данных или в виде файлов в хранилище файлов.

* `iframe` позволяет вставлять контент внутрь HTML-элемента `<iframe>`. См. примеры в онлайн демо-приложении https://demo.jmix.ru/ui-samples/sample/iframe-pdf[UI Samples^].
