= Использование хранилища файлов

Хранилище файлов – это абстракция, обеспечивающая различные реализации того, как и где хранятся файлы, и предоставляющая единый https://github.com/jmix-framework/jmix/blob/master/jmix-core/core/src/main/java/io/jmix/core/FileStorage.java[интерфейс^] для доступа к файлам и создания ссылок на них из сущностей модели данных.

Jmix поставляется с двумя реализациями хранения файлов: <<local-fs,локальной>> и <<aws-fs,AWS>>. При создании нового проекта в Studio в него включена локальная реализация.

TIP: В файловом хранилище можно хранить файлы любого размера, поскольку передача файлов в хранилище и из него выполняется путем копирования небольших фрагментов данных между входными и выходными потоками, поэтому файлы никогда не загружаются в память полностью.

[[examples]]
== Примеры

[[ui-example]]
=== Работа с файлами в UI

В этом разделе приводится пример работы с файлами в файловом хранилище с использованием компонентов UI.

Во-первых, создайте в сущности атрибут типа `FileRef`, например:

[source,java,indent=0]
----
include::example$/files-ex1/src/main/java/com/company/demo/entity/Attachment.java[tags=files]
----

При запуске приложения Studio генерирует скрипт миграции базы данных для создания соответствующего столбца строкового типа, поскольку `FileRef` имеет строковое представление в формате URI.

Для загрузки файлов с экрана UI используйте компонент xref:flow-ui:vc/components/fileStorageUploadField.adoc[], привязанный к атрибуту сущности:

[source,xml,indent=0]
----
include::example$/files-ex1/src/main/resources/com/company/demo/view/attachment/attachment-detail-view.xml[tags=files]
----

Чтобы скачать прикрепленные файлы, добавьте в таблицу в экране списка колонку с компонентом:

[source,java,indent=0]
----
include::example$/files-ex1/src/main/java/com/company/demo/view/attachment/AttachmentListView.java[tags=files]
----
<1> Используйте бин xref:downloading-files.adoc#downloader[Downloader] для скачивания файлов.
<2> Метод `download()` принимает значение `FileRef` и извлекает файл из хранилища файлов, указанного в объекте `FileRef`. Имя и тип файла также закодированы в `FileRef`, поэтому веб-браузер правильно выбирает, загружать или отображать файл.

[[file-storage-example]]
=== Использование интерфейса FileStorage

В следующем примере показано, как работать напрямую с интерфейсом https://github.com/jmix-framework/jmix/blob/master/jmix-core/core/src/main/java/io/jmix/core/FileStorage.java[FileStorage^].

Первый метод сохраняет в файловом хранилище полученный из веб-службы файл. Второй метод загружает файл из хранилища и сохраняет его в локальной файловой системе.

Используется та же сущность `Attachment`, что и в предыдущем примере.

[source,java,indent=0]
----
include::example$/files-ex1/src/main/java/com/company/demo/view/attachment/AttachmentListView.java[tags=file-storage]
----
<1> `FileStorageLocator` позволяет работать с определенным хранилищем файлов, если вы определили в проекте <<multiple-fs,несколько хранилищ>>. Если у вас одно хранилище файлов (что является ситуацией по умолчанию), интерфейс `FileStorage` можно внедрить напрямую.
<2> Получение входного потока для веб-ресурса. Вместо класса `URLConnection` можно использовать `HttpClient`, или стороннюю библиотеку, такую как Apache HttpClient.
<3> Сохранение содержимого ресурса в хранилище файлов. Возвращаемый объект `FileRef` является ссылкой на файл в хранилище.
<4> Сохранение ссылки на атрибут сущности.
<5> Получение входного потока для загрузки файла из хранилища файлов.
<6> Сохранение файла в локальной файловой системе.

[[local-fs]]
== Локальное хранилище файлов

Реализация локального хранилища позволяет хранить файлы в локальной файловой системе сервера приложения или в любом сетевом хранилище (NAS).

Чтобы использовать локальное хранилище файлов в своем приложении, убедитесь, что файл `build.gradle` содержит следующую строку в разделе `dependencies`:

[source,groovy,indent=0]
----
include::example$/files-ex1/build.gradle[tags=dependencies]
----

Файлы хранятся в специальной структуре каталогов, которая поддерживается файловым хранилищем. По умолчанию корневым каталогом является `${user.dir}/.jmix/work/filestorage`, где `${user.dir}` является рабочим каталогом пользователя (где была запущена JVM). Его можно изменить, указав рабочий каталог в свойстве приложения xref:ROOT:app-properties.adoc#jmix.core.work-dir[jmix.core.work-dir], или нужный путь целиком в свойстве `jmix.localfs.storage-dir`, например:

[source,properties]
----
jmix.localfs.storage-dir = /opt/file-storage
----

Свойство `jmix.localfs.max-file-size` ограничивает максимальный размер загружаемых файлов. Его значение по умолчанию составляет `100MB`.

[[aws-fs]]
== Хранилище файлов AWS

Реализация хранилища файлов AWS позволяет хранить файлы в https://aws.amazon.com/s3[Amazon S3^].

Чтобы использовать в приложении хранилище файлов AWS, установите дополнение AWS File Storage из каталога, как описано в разделе xref:ROOT:add-ons.adoc[], или вручную добавьте следующую строку в раздел `dependencies` файла `build.gradle`:

[source,groovy,indent=0]
----
include::example$/files-ex1/build.gradle[tags=dependencies-aws]
----

Если вы планируете использовать только хранилище файлов AWS, удалите зависимость локального хранилища файлов из `build.gradle` (строку, содержащую `io.jmix.localfs:jmix-localfs-starter`). В противном случае см. <<multiple-fs,следующий раздел>> о том, как настроить несколько хранилищ файлов.

Определите свойства приложения:

[source,properties,indent=0]
----
include::example$/files-ex1/src/main/resources/application.properties[tags=aws-config]
----

The S3 bucket in the selected region must be created beforehand.

[[multiple-fs]]
== Использование нескольких хранилищ

Если вы хотите использовать в приложении несколько хранилищ файлов, укажите имя хранилища по умолчанию в свойстве приложения:

[source,properties]
----
include::example$/files-ex1/src/main/resources/application.properties[tags=default-fs]
----

Имя локального хранилища файлов – `fs`; имя хранилища файлов AWS – `s3`.

Чтобы использовать несколько хранилищ одного типа, определите дополнительные хранилища с уникальными именами. Например, чтобы определить дополнительное локальное хранилище файлов с корневым каталогом в `/var/tmp/myfs`, добавьте следующий код в основной класс приложения:

[source,java,indent=0]
----
include::example$/files-ex1/src/main/java/com/company/demo/DemoApplication.java[tags=multiple-fs]
----

Для программной работы с различными хранилищами используйте бин `FileStorageLocator`. Он позволяет получить файловое хранилище по его имени.

Компонент xref:flow-ui:vc/components/fileStorageUploadField.adoc[] имеет атрибут `fileStorage` для указания имени хранилища файлов. Если он не установлен, компонент использует файловое хранилище по умолчанию.