= Using File Storage

File Storage is an abstraction enabling different implementations of how and where the files are stored and providing a unified https://github.com/jmix-framework/jmix/blob/master/jmix-core/core/src/main/java/io/jmix/core/FileStorage.java[interface^] for accessing files and referring to them from the data model entities.

Jmix comes with two file storage implementations: <<local-fs,Local>> and <<aws-fs,AWS>>. When you create a new project in Studio, it includes the local implementation.

TIP: You can store files of any size in the file storage, because transferring files to and from the file storage is performed by copying small chunks of data between input and output streams, so files are never fully loaded into memory.

[[examples]]
== Examples

[[ui-example]]
=== Working with Files in UI

In this section, we will give an example of working with files in the file storage using the UI components.

Firstly, create an attribute of the `FileRef` type in your entity, for example:

[source,java,indent=0]
----
include::example$/files-ex1/src/main/java/com/company/demo/entity/Attachment.java[tags=files]
----

When you run the application, Studio generates a database migration script for creating a corresponding column of the string type, because `FileRef` has a string representation in the URI format.

For uploading files from a UI view, use the xref:flow-ui:vc/components/fileStorageUploadField.adoc[] component bound to the entity attribute:

[source,xml,indent=0]
----
include::example$/files-ex1/src/main/resources/com/company/demo/view/attachment/attachment-detail-view.xml[tags=files]
----

To download attached files, add a component column to the data grid in the list view:

[source,java,indent=0]
----
include::example$/files-ex1/src/main/java/com/company/demo/view/attachment/AttachmentListView.java[tags=files]
----
<1> Use the xref:downloading-files.adoc#downloader[Downloader] bean to download files.
<2> The `download()` method accepts the `FileRef` value and takes the file from the file storage specified in the `FileRef` object. The name and type of the file are also encoded in `FileRef`, so the web browser correctly chooses whether to download or display the file.

[[file-storage-example]]
=== Using FileStorage Interface

The following example shows how to work with the https://github.com/jmix-framework/jmix/blob/master/jmix-core/core/src/main/java/io/jmix/core/FileStorage.java[FileStorage^] interface directly.

The first method saves to file storage a file obtained from a web service. The second method loads a file from the file storage and saves it to the local file system.

The same `Attachment` entity is used as in the previous example.

[source,java,indent=0]
----
include::example$/files-ex1/src/main/java/com/company/demo/view/attachment/AttachmentListView.java[tags=file-storage]
----
<1> `FileStorageLocator` allows you to work with a particular file storage if you have defined <<multiple-fs,multiple file storages>> in your project. If you have a single file storage (which is a default situation), you can inject the `FileStorage` interface directly.
<2> Getting an input stream for the web resource. Instead of the `URLConnection` class, you may want to use `HttpClient`, or a third-party library like Apache HttpClient.
<3> Saving the resource content to the file storage. The returned `FileRef` object is a reference to the file in the file storage.
<4> Saving the reference to an entity attribute.
<5> Getting an input stream to load the file from the file storage.
<6> Saving the file to the local file system.

[[local-fs]]
== Local File Storage

The Local File Storage implementation allows you to store files on the local file system of the application server or on any network-attached storage (NAS).

To use Local File Storage in your application, make sure your `build.gradle` file contains the following line in the `dependencies` section:

[source,groovy,indent=0]
----
include::example$/files-ex1/build.gradle[tags=dependencies]
----

Files are stored in a special directory structure which is maintained by the file storage. By default, the root directory is `${user.dir}/.jmix/work/filestorage`, where `${user.dir}` is the user working directory (where JVM was started). You can change it by specifying a work directory in the xref:ROOT:app-properties.adoc#jmix.core.work-dir[jmix.core.work-dir] application property or a complete path in the `jmix.localfs.storage-dir` application property, for example:

[source,properties]
----
jmix.localfs.storage-dir = /opt/file-storage
----

The `jmix.localfs.max-file-size` property limits the maximum size of uploaded files. Its default value is `100MB`.

[[aws-fs]]
== AWS File Storage

The AWS File Storage implementation allows you to store files in https://aws.amazon.com/s3[Amazon S3^].

To use AWS File Storage in your application, install the AWS File Storage add-on from the marketplace as described in the xref:ROOT:add-ons.adoc[Add-ons] section, or manually add the following line to the `dependencies` section of your `build.gradle` file:

[source,groovy,indent=0]
----
include::example$/files-ex1/build.gradle[tags=dependencies-aws]
----

If you plan to use AWS File Storage only, remove the Local File Storage dependency from `build.gradle` (the line containing `io.jmix.localfs:jmix-localfs-starter`). Otherwise, see the <<multiple-fs,next section>> for how to configure multiple file storages.

Define application properties:

[source,properties,indent=0]
----
include::example$/files-ex1/src/main/resources/application.properties[tags=aws-config]
----

The S3 bucket in the selected region must be created beforehand.

[[multiple-fs]]
== Using Multiple File Storages

If you want to use more than one file storage in your application, specify a default one using its name in the application property:

[source,properties]
----
include::example$/files-ex1/src/main/resources/application.properties[tags=default-fs]
----

The Local File Storage name is `fs`, the AWS File Storage name is `s3`.

If you want to use multiple storages of the same type, define additional storages with unique names. For example, to define an additional Local File Storage with the root directory at `/var/tmp/myfs`, add the following code to the main application class:

[source,java,indent=0]
----
include::example$/files-ex1/src/main/java/com/company/demo/DemoApplication.java[tags=multiple-fs]
----

To work with different file storages programmatically, use the `FileStorageLocator` bean. It allows you to get a file storage by its name.

The xref:flow-ui:vc/components/fileStorageUploadField.adoc[] component has the `fileStorage` attribute to specify a file storage name. If it's not set, the component uses the default file storage.